### ISSUE TITLE
there are other actions After deleting a file —— issue #523, again 

### ISSUE THREAD

**Issue by linhongzhao321** [laravel/lumen-framework#1003]
- Lumen Version: 5.5.2
- PHP Version: 7.2.5
- Database Driver & Version:

### Description:
**sorry, My English is not fluent, please forgive me**

add `deleteFileAfterSend(true)` after `response()->download($tmpFile, $fileName)`
The following error occurred
```
lumen.ERROR: RuntimeException: SplFileInfo::getSize(): stat failed for /<project path>/storage/excels/43f569980da87e54.xlsx in /<project path>/vendor/symfony/http-foundation/BinaryFileResponse.php:200
Stack trace:
#0 /<project path>/vendor/symfony/http-foundation/BinaryFileResponse.php(200): SplFileInfo->getSize()
#1 /<project path>/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(433): Symfony\Component\HttpFoundation\BinaryFileResponse->prepare(Object(Illuminate\Http\Request))
#2 /<project path>/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(132): Laravel\Lumen\Application->prepareResponse(Object(Symfony\Component\HttpFoundation\BinaryFileResponse))
#3 /<project path>/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(116): Laravel\Lumen\Application->callTerminableMiddleware(Object(Symfony\Component\HttpFoundation\BinaryFileResponse))
#4 /<project path>/public/index.php(31): Laravel\Lumen\Application->run()
```

It's solved temporarily with method from [# issue 523](https://github.com/laravel/lumen-framework/issues/523)。
But, This problem might belong to Lumen. Because, Symfony's delete file with `unlink` in File `symfony/http-foundation/BinaryFileResponse.php(309)`. But, after `send()`, Lumen still calls method that it's need file-size. For details, see **line.116** and **line.433** in `laravel/lumen-framework/src/Concerns/RoutesRequests.php`.
 
### Steps To Reproduce:
1. create controller class
2. Add the following code
    ```
    return response()->download($tmpFile, $fileName)->deleteFileAfterSend(true);
    ```
3. request

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by tbanov** [comment]
Lumen Version: 6.3.4
PHP Version: 7.2.26

Same issue on latest lumen version. Please advise.

**Comment by madhurbhaiya** [comment]
Lumen Version: 9.0.2
PHP Version: 8.1.6

Same issue on the latest lumen and PHP version.
