### ISSUE TITLE
http response status code always return 200

### ISSUE THREAD

**Issue by zhengyuhe123** [laravel/lumen-framework#1007]
- Lumen Version: Lumen (6.2.0) (Laravel Components ^6.0)
- Laravel Version: #.#.#
- PHP Version: 7.3.11(windows)
- Database Driver & Version:

### Description:
I installed lumen by composer
 `global require "laravel/lumen-installer"`

add the code in reoutes/web.php file
`$router->get('/', function () use ($router) {
    return response()->json(['test' => 1], 500);
});`

I think http response status code will return 500 but always return 200
![image](https://user-images.githubusercontent.com/30775855/70525775-095d5a00-1b83-11ea-844e-89db31786e65.png)

I tested a nonexistent url http response still returns code 200
![image](https://user-images.githubusercontent.com/30775855/70525122-91dafb00-1b81-11ea-8846-8907a0385f51.png)

Please tell me how to set the http status code， thanks

### Steps To Reproduce:
edit code in routes/web.php 
`$router->get('/', function () use ($router) {
    return response()->json(['test' => 1], 500);
});`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by dericlima** [comment]
I had the same issue on my app (Lumen 6.4) and believe me or not the issue was a extra blank line at the top of my `app.php`.

```


<?php
require_once __DIR__.'/helpers.php';
require_once __DIR__.'/../vendor/autoload.php';
```
So I just removed it:

```
<?php
require_once __DIR__.'/helpers.php';
require_once __DIR__.'/../vendor/autoload.php';
```

And everything was working like a charm!!

**Comment by sharaf84** [comment]
@dericlima Thanks, in my case, the extra blank line was in the `routes/web.php`

**Comment by abdelaliabouelhassan** [comment]
@sharaf84  thank you,  I had the same issue I found that I have an extra space in the ` routes/web.php`
