### ISSUE TITLE
route doesn't work for encoded url

### ISSUE THREAD

**Issue by wutong** [laravel/lumen-framework#101]
the route doesn't work with encoded url,
like `%E9%A6%96%E9%A1%B5/%E9%A6%96%E9%A1%B5`
could you fix it ?

**Comment by lukasgeiter** [comment]
Please include at least the route declaration. And what does *"doesn't work"* mean? Do you get a 404?

**Comment by wutong** [comment]
@lukasgeiter 
in mycase
I set a route rule

```
$app->get('首页/首页', function()
{
    return 'hello';
}
```
when I type http://xxx.com/首页/首页
It match to `urlencode('首页') . '/' . urlencode('首页')`
not match to `首页/首页`

**Comment by wutong** [comment]
@lukasgeiter 
that's my problem,
could you help me?

BTW: when I use laravel it's works.

**Comment by wutong** [comment]
@lukasgeiter 
I found a solution at 
<https://github.com/nikic/FastRoute/issues/49>
<https://github.com/symfony/symfony/blob/9f855176454aee2065cbba5923288df9f1c7cf91/src/Symfony/Component/Routing/Matcher/UrlMatcher.php#L96>
I just rawdecode the pathinfo~
