### ISSUE TITLE
Relation is not removed when calling unsetRelation()

### ISSUE THREAD

**Issue by Froxz** [laravel/lumen-framework#1010]
- Lumen Version: 6.2.0
- Laravel Version: 6.8.0
- PHP Version: 7.3.4
- Database Driver & Version: pgsql

### Description:
`unsetRelation('relation')` is not removed when calling `pluck('relation')`

### Steps To Reproduce:
```php
$data = Model::with([
        'child', 'child.one', 'child.two'
])->get()
```
**Removes 'child.one' and 'child.two' but keeps child**
```php
$data->transform(function ($item, $key) {
	if($key == 1){ //remove the second item
              $item->unsetRelation('child'); //same behavior if we call $item->unsetRelations();  
        }
        return $item;
});

$output = $data->pluck('child');
```
After calling pluck if we had 2 items under `$data->child`, the first contains all 3 relations ( `child`, `child.one`, `child.two`), the second item contains only `child`. I guess if we call `unsetRelation` should not return it after `pluck` method?

If we call `dd($data)` after `transform` relation is not there.

**Comment by driesvints** [comment]
This is an Eloquent issue and it's best to report his on the laravel/framework repo. However, can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open an issue on the laravel/framework repo and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
