### ISSUE TITLE
Lumen's ->seeJson() for testing doesn't assert anything

### ISSUE THREAD

**Issue by HenkPoley** [laravel/lumen-framework#1017]
- Lumen Version: 6.x
- Laravel Version: 6.x
- PHP Version: 7.2
- Database Driver & Version:

### Description:
If you do as described here:
https://lumen.laravel.com/docs/6.x/testing#testing-json-apis

You will get: `This test did not perform any assertions`.

Maybe not the most productive thing within the PhpUnit system of assertions.

**Comment by driesvints** [comment]
I can run this test just fine with a proper assertion. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
