### ISSUE TITLE
Return typehint for app/Exception/Handler.php can never be satisfied

### ISSUE THREAD

**Issue by HenkPoley** [laravel/lumen-framework#1034]
- Lumen Version: 5.8.13 &  6.x
- Laravel Version: 5.8 & 6.x
- PHP Version: 7.1 & 7.3 (irrelevant)
- Database Driver & Version: irrelevant

### Description:
`vimeo/psalm` would complain about mismatching return typehint of app/Exception/Handler.php

Fix here: https://github.com/laravel/lumen-framework/pull/1033

### Steps To Reproduce:
On a Laravel Lumen install:

1. `composer require --dev vimeo/psalm`
2. `vendor/bin/psalm --init`
3. `vendor/bin/psalm`

A problem with the return type of your \app\Exceptions\Handler::render() would show up. Due to a specification bug in Laravel Lumen.

**Comment by GrahamCampbell** [comment]
Thanks for the report. I've left a note on your PR.

**Comment by HenkPoley** [comment]
👍 btw, It's good to also check the other stuff psalm notices.
