### ISSUE TITLE
Config value used for error handling

### ISSUE THREAD

**Issue by tiirex9** [laravel/lumen-framework#1036]
- Lumen Version: 6.3.4

### Description:
By default Lumen uses config('app.debug') to check if errors should be visible in the browser. (I. e. in src/Exceptions/Handler.php). Inside the config/app.php it uses env('APP_DEBUG') to check the Environment (or .env file). But since the config is not being loaded this always evaluates to false. 
You have to add `$app->configure('app');` in the bootstrap/app.php for this to work as described (but fairly hard to find and not really intuitive) in https://lumen.laravel.com/docs/6.x/configuration#accessing-configuration-values

But since Lumen does not load the config by default this check is always false, regardless of any value in the .env file. 

#672 implies that it is on purpose that the config is not loaded by default, but I think the framework should check the environment for APP_DEBUG, instead of the config value since there is no error output (and in my test not even output to the log.)

**Comment by driesvints** [comment]
This is indeed on purpose. Please load the config as described in the docs.

**Comment by tiirex9** [comment]
At least you should add to the documentation that APP_DEBUG has no effect until you load the config. And maybe add the `$app->configure(..)` as comment in the app.php.

It is really confusing that some variables for the framework in the .env file are introduced but completely ignored.

**Comment by driesvints** [comment]
It seems this indeed got broken because of a recent change. Thanks for reporting. We've sent in a PR that should fix that.
