### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by TCM-dev** [laravel/lumen-framework#1042]
I am trying to upgrade my lumen framework from 6.3 to 7.0
But it just won't let me do it, I tried many things but I just can't get a comprehensible error message.
- PHP Version: 7.2.19
- Database Driver & Version: mysql 5.6

### Description:
I change my version of lumen framework to 7.0 in composer.json, run composer update and get this error

`Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
`

**Comment by GrahamCampbell** [comment]
You probably need to change your minimum stability to dev. Lumen 7.0 has not been released yet.

**Comment by TCM-dev** [comment]
That was already the case.
I used the composer.json in the lumen github and it worked fine.
I think it was due to illuminate/redis being at "^6.0".
