### ISSUE TITLE
Parameter name bug

### ISSUE THREAD

**Issue by kousalik** [laravel/lumen-framework#1045]
Hi guys, just gave a quick go to the 7.X branch and very quickly foud a blocker on this line 

https://github.com/laravel/lumen-framework/blob/3d3a58e5eb604e86801074f26bfb63b0658d4ed1/src/Testing/Concerns/MakesHttpRequests.php#L422

```
    public function assertResponseStatus($code)
    {
        $this->response->assertStatus($status);
    }
```
variable $status doesn't exist in this scope. $code should be renamed to $status to be consistent with the rest of this class

**Comment by kousalik** [comment]
fixed in https://github.com/laravel/lumen-framework/pull/1044

**Comment by GrahamCampbell** [comment]
Thanks for the report. This is fixed in dev now. A new release will go out by Tuesday afternoon at the latest.
