### ISSUE TITLE
Giant SVG icons on debug screen

### ISSUE THREAD

**Issue by isteven** [laravel/lumen-framework#1048]
- Lumen Version: 7.0.0 
- Laravel Version: ?
- PHP Version: 7.4.3
- Database Driver & Version: MariaDB 10.4.11

### Description:
I'm new with Lumen & trying to follow a simple tutorial (https://blog.pusher.com/php-laravel-migration/), however every time I encountered an error, I saw this screen:

![image](https://user-images.githubusercontent.com/5432100/76704644-61bd6e00-6715-11ea-80e2-49f0a00e1372.png)

Somehow the buttons are rendered in giant size. The small text on the left are the debug messages.

As a result, I'm not able to properly read the debug messages.

Any help would be appreciated. Thank you.

### Steps To Reproduce:
N/A

**Comment by driesvints** [comment]
This doesn't seems to be Lumen related. There are no such buttons in Lumen.
