### ISSUE TITLE
Wrong variable name in MakesHttpRequest::assertResponseStatus

### ISSUE THREAD

**Issue by emmanix2002** [laravel/lumen-framework#1052]
- Lumen Version: 7.0.0
- PHP Version: 7.4.1

### Description:
A wrong variable name in used in the `assertResponseStatus` and when using it to assert the response status results in an error message `ErrorException : Undefined variable: status`.

**What it looks like**
```php
public function assertResponseStatus($code)
{
    $this->response->assertStatus($status);
}
```

**What it should be**
```php
public function assertResponseStatus($code)
{
    $this->response->assertStatus($code);
}
```

### Steps To Reproduce:
- Write a simple Http test
- Call the `$this->assertResponseStatus(200)` or any status.

There's already a fix for this on the `master` branch, see https://github.com/laravel/lumen-framework/blob/7.x/src/Testing/Concerns/MakesHttpRequests.php#L422

**Comment by emmanix2002** [comment]
I can still send in a PR if required.

**Comment by driesvints** [comment]
It's already fixed. We'll tag a new release today.

https://github.com/laravel/lumen-framework/commit/5d9b4d896788afe48902cced5e8285d53129dd3e
