### ISSUE TITLE
Lumen Routing with regex for files path

### ISSUE THREAD

**Issue by ranganathabrr** [laravel/lumen-framework#1056]
- Lumen Version: 6.0
- Laravel Version: 5.4
- PHP Version: 7.4
- Database Driver & Version:

### Description:
Hi 
I am trying to upload, retrive and delete files using Lumen API. Routes I added but i am getting Not Found Exception. 
Laravel Framework I used where clause in the routes.
Route::delete('units/{unit}/files/{path}', 'UnitsOtaUpdateController@deleteFile')->where('path', '.+');

### Steps To Reproduce:
$router->delete('units/{unit}/files/{path:^(.+)\/([^/]+)$}', 'UnitsOtaUpdateController@deleteFile');

could you please help me to fix this issue.
Thanks in advance
![Screenshot from 2020-03-23 12-17-15](https://user-images.githubusercontent.com/11206388/77291628-abedb300-6d04-11ea-9d83-4ccb926f2da1.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by vitalijalbu** [comment]
hi, i also want to add image.png to url route, it's possible? how can i set regex to route?
