### ISSUE TITLE
Lumen Config Files

### ISSUE THREAD

**Issue by sebastiaanluca** [laravel/lumen-framework#107]
>Lumen will use your copy of the configuration file if you copy and paste one of the files into a config directory within your project root.

Doesn't seem to be the case. `project/config/app.php` exists, but it's not present when doing `config()` or `config('app.key')`. Only when I register the configuration file with `$app->configure('app');` does it successfully load.

Weird thing is, `database.php` _does_ seem to load.

**Comment by yadakhov** [comment]
http://lumen.laravel.com/docs/configuration

>Unlike Laravel, Lumen only uses a single .env configuration file which can be used to configure the various aspects of the framework. 

So there is no configs.  Everything is used for .env.

**Comment by GrahamCampbell** [comment]
> So there is no configs. Everything is used for .env.

What? That's not true at all.

**Comment by sebastiaanluca** [comment]
@GrahamCampbell So Lumen should use my config/app.php instead of the default, right? Same for config/database.php, …

**Comment by ctrlaltdylan** [comment]
Bumping this thread. Even with `$app->configure('any-config-file-in-config-directory');` the application is not aware of any configuration.

`config()->all();` return null.

**Comment by sebastiaanluca** [comment]
@ctrlaltdylan Where exactly did you place that line in your application's flow? I've put mine in the boot method of a loaded service provider and it seems to work, even with custom configuration files (as long as they are in `root/config`, not `app/config`). At the end of the Lumen app file should work too.

**Comment by ctrlaltdylan** [comment]
I placed the configuration file in the application root:

`/config/app.php`

Contents of `/config/app.php`:
```
<?php

return [
    'test' => 'this config should work',
];

In the `/bootstrap/app.php`:

```
$app->configure('app');
```

To test:
```
config('app.test');
```

But only receiving `null`. Even with config's I know are working, like `/config/database.php` and `/config/cache.php`.

**Comment by sebastiaanluca** [comment]
@ctrlaltdylan

- What version of Lumen are you using? I'm using 5.2.
- Did you put `config('app.test');` in a route/controller to test? Has to be __after__ returning `$app` in your `/bootstrap/app.php` file.
- `$app->configure('app');` should be just before `return $app;`.

**Comment by ctrlaltdylan** [comment]
@sebastiaanluca 

Upgrading to 5.2 did the trick. Thank you.

**Comment by prawnsalad** [comment]
I'm using 5.2 here, have `$app->configure('test');` directly after `$app` is created in app.php, but using `config('test')` in a controller returns null. What am I missing?

config/test.php contains `<?php return ['foo' => 'bar'];`

**Comment by rulatir** [comment]
So if I want to use e.g. Xethron/migrations-generator then I need full Laravel because Xethron/migrations-generator instructions tell me to put something into app/config.php and that file just isn't there?

**Comment by dsposito** [comment]
I had this same issue. `config('app');` returned null even though I had copied the framework app config into `/config/app.php`.

Adding this line anywhere in `/bootstrap/app.php` worked for me: `$app->configure('app');`. My guess is that Lumen does not load the config files by default for performance reasons.

**Comment by lingfengchencn** [comment]
I followed https://iwader.co.uk/post/tymon-jwt-auth-with-lumen-5-2
but i faild....
because we need  Uncomment  ：
` $app->register(App\Providers\AppServiceProvider::class);`
in bootstrap/app.php

**Comment by aftabnaveed** [comment]
I'm using lumen 5.4, have` $app->configure('test')` in my bootstrap/app.php right after application initialisation, but when I try config('test.key') it returns null.

**Comment by DarkGhostHunter** [comment]
Same here, until I wondered under my code that there was a new Instance of my application to get some aliases just to test something.


```php 
class ApplicationFix extends Application {
    public function getAliases() {
        return $this->aliases;
    }
}

$form = new ApplicationFix;
$form = $form->getAliases();

dd(config()); // NULL
```

You should check your code and see if there is anything that generates or extends another instance of your app, as ```config()``` will load the last instance.

**Comment by libasoles** [comment]
I'm running version 5.4

This is not making config available in routes when I put it in bootstrap/app.php 

`$app->configure('app');`

However it works if I place it in my routes file (web.api)

Weird, but actually dumping it in bootstrap will show the config, but dumping it again in the routes file displays null:
 
`dd(config());`

(and of course, I'm setting that just before `return $app;`)

**Comment by fgilio** [comment]
It's working flawlessly in Lumen 5.4 👍🏻

**Comment by vrkansagara** [comment]
@DavidStrada Just little improvement in your code.

replace `grab it's content config('app.value')` with `grab it's content config('filename')`

and get config file as `$file = config('filename')` in your code. it's working with `Laravel Framework Lumen (5.5.1) (Laravel Components 5.5.*)`

**Comment by TheGeekyM** [comment]
collect(scandir(__DIR__ . '/../config'))->each(function ($item) use ($app) {
    $app->configure(basename($item, '.php'));
});

**Comment by ruchisheth** [comment]
#solution

https://medium.com/@mamreezaa/create-custom-config-and-use-in-lumen-120eb4d3278

point no 7.
