### ISSUE TITLE
php artisan migrate --env=testing not working 

### ISSUE THREAD

**Issue by sadaimudiNaadhar** [laravel/lumen-framework#1070]
- Lumen Version: 5.6
- Laravel Version: #.#.#
- PHP Version: 7.2
- Database Driver & Version: SQLite 3

### Steps To Reproduce:

1/ cp .env .env.testing
2/ Set` APP_ENV=testing`
3/ Run  php artisan migrate --env=testing

It's still picking from existing .env

Seems below functionality is missing as in laravel
```
     /**
     * Detect if a custom environment file matching the APP_ENV exists.
     *
     * @param  \Illuminate\Contracts\Foundation\Application  $app
     * @return void
     */
   protected function checkForSpecificEnvironmentFile($app)
    {
        if ($app->runningInConsole() && ($input = new ArgvInput)->hasParameterOption('--env')) {
            if ($this->setEnvironmentFilePath(
                $app, $app->environmentFile().'.'.$input->getParameterOption('--env')
            )) {
                return;
            }
        }

        if (! env('APP_ENV')) {
            return;
        }

        $this->setEnvironmentFilePath(
            $app, $app->environmentFile().'.'.env('APP_ENV')
        );
    }

```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by lukaskj** [comment]
As "--env=xxx" will not be supported (see #1055) I managed to get this working this way:

File: `bootstrap\app.php`
```php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

$envFileName = ".env";
if (php_sapi_name() == 'cli') {
   $input = new \Symfony\Component\Console\Input\ArgvInput();
   $envParameterOption = $input->getParameterOption('--env');
   if ($input->hasParameterOption('--env') && file_exists(__DIR__ . '/../' . $envFileName . '.' . $envParameterOption)) {
      $envFileName .= '.' . $envParameterOption;
   }
}

(new Laravel\Lumen\Bootstrap\LoadEnvironmentVariables(
   dirname(__DIR__), $envFileName
))->bootstrap();


```

**Comment by hhx999** [comment]
> * Lumen Version: 5.6
> 
>     * Laravel Version: #.#.#
> 
>     * PHP Version: 7.2
> 
>     * Database Driver & Version: SQLite 3
> 
> 
> ### Description:
> ### Steps To Reproduce:
> 
> 1/ cp .env .env.testing 2/ Set` APP_ENV=testing` 3/ Run php artisan migrate --env=testing
> 
> It's still picking from existing .env
> 
> Seems below functionality is missing as in laravel
> 
> ```
>      /**
>      * Detect if a custom environment file matching the APP_ENV exists.
>      *
>      * @param  \Illuminate\Contracts\Foundation\Application  $app
>      * @return void
>      */
>    protected function checkForSpecificEnvironmentFile($app)
>     {
>         if ($app->runningInConsole() && ($input = new ArgvInput)->hasParameterOption('--env')) {
>             if ($this->setEnvironmentFilePath(
>                 $app, $app->environmentFile().'.'.$input->getParameterOption('--env')
>             )) {
>                 return;
>             }
>         }
> 
>         if (! env('APP_ENV')) {
>             return;
>         }
> 
>         $this->setEnvironmentFilePath(
>             $app, $app->environmentFile().'.'.env('APP_ENV')
>         );
>     }
> ```

Thanks bro
