### ISSUE TITLE
MySQL's connection get error in any artisan commands

### ISSUE THREAD

**Issue by kylesean** [laravel/lumen-framework#1071]
- Lumen Version: 7.1.0
- Laravel Version: Laravel Components ^7.0
- PHP Version: 7.1.29，7.2.18，7.3.5,  7.4.5
- Database Driver & Version: MySQL 5.7

### Description:
Using orm in `schedule` method at Console/Kernel.php will get this error:

```
In Model.php line 1285:
 
Call to a member function connection() on null

``` 

### Steps To Reproduce:
- `User::all()` in Console/Kernel.php shedule fucntion
-  run `php artisan`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by kylesean** [comment]
It's normal on laravel by this using
