### ISSUE TITLE
Framework cannot register exception handler: Call to undefined method Application::handleException

### ISSUE THREAD

**Issue by aetonsi** [laravel/lumen-framework#1072]
- Lumen Version: 7.1.0
- Laravel Version: Laravel Components ^7.0
- PHP Version: 7.4.4
- Database Driver & Version: NA

### Description:
The framework cannot register its error handler if a peculiar error is present.

The error is caused by this misspelled statement: `\App\User::where('id', 1)-- >test()`. Please note that this is not considered a syntax error by php.

In fact, the error reported is the following: `Can't use method return value in write context in ...\web.php`, followed by `Uncaught Error: Call to undefined method ...\Application::handleException() in
...\RegistersExceptionHandlers.php` (see full output below).

I tried with similar structures (eg `(new \stdClass)-- >test()`) or just plain syntactic errors (eg `"".[]`), but they are all caught and rendered by the framework.

### Steps To Reproduce:
Create a new empty project: `composer create-project --prefer-dist laravel/lumen test`.

Edit the default (`/`) route in `routes/web.php`:
```php
$router->get('/', function () use ($router) {
    return \App\User::where('id', 1)-- >test();
});
```

Open the default route. The following error is shown:
```html
<br />
<b>Fatal error</b>: Can't use method return value in write context in <b>T:\test\routes\web.php</b> on
line <b>15</b><br />
<br />
<b>Fatal error</b>: Uncaught Error: Call to undefined method Laravel\Lumen\Application::handleException() in
T:\test\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php:67
Stack trace:
#0 T:\test\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55):
Laravel\Lumen\Application-&gt;handleShutdown()
#1 [internal function]: Laravel\Lumen\Application-&gt;Laravel\Lumen\Concerns\{closure}()
#2 {main}
thrown in <b>T:\test\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php</b> on
line <b>67</b><br />
```

This is evidently rendered by php itself, not by the framework.

<hr>

Have a nice day.

**Comment by driesvints** [comment]
This will be fixed in the next release. Thanks.

**Comment by aetonsi** [comment]
Hi again!
I updated to v7.1.1, i tried again with an empty project and now the error is different, but still present:
```html
<br />
<b>Fatal error</b>: Can't use method return value in write context in <b>G:\tmp\test\test\routes\web.php</b> on line
<b>15</b><br />
<br />
<b>Fatal error</b>: Uncaught TypeError: Argument 2 passed to
Symfony\Component\ErrorHandler\Error\FatalError::__construct() must be of the type int, array given, called in
G:\tmp\test\test\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php on line 80 and defined in
G:\tmp\test\test\vendor\symfony\error-handler\Error\FatalError.php:23
Stack trace:
#0 G:\tmp\test\test\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(80):
Symfony\Component\ErrorHandler\Error\FatalError-&gt;__construct('Can't use metho...', Array, 0)
#1 G:\tmp\test\test\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(67):
Laravel\Lumen\Application-&gt;fatalErrorFromPhpError(Array, 0)
#2 G:\tmp\test\test\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55):
Laravel\Lumen\Application-&gt;handleShutdown()
#3 [internal function]: Laravel\Lumen\Application-&gt;Laravel\Lumen\Concerns\{closure}()
#4 {main}
thrown in <b>G:\tmp\test\test\vendor\symfony\error-handler\Error\FatalError.php</b> on line <b>23</b><br />
```

**Comment by aetonsi** [comment]
Oh ok thanks for reopening, i was just about to create a new ticket..
Thanks
Have a nice day
