### ISSUE TITLE
Implement route caching speed improvements

### ISSUE THREAD

**Issue by dunhamjared** [laravel/lumen-framework#1074]
From my understanding, the awesome route caching improvements from Laravel has yet to be implemented into the Lumen project. 

It would be nice to have this for Lumen as well. 

Related: https://github.com/laravel/framework/pull/31188

**Comment by dunhamjared** [comment]
I swapped out `FastRoute\simpleDispatcher` with `FastRoute\cachedDispatcher` and ran:

```
for ($i = 0; $i < 800; $i++) {
    $router->get('/test-'.$i.'/{foo}', 'TestController');
}
```

...with the following controller:

```
class TestController extends Controller
{
    public function __invoke($foo)
    {
        return 'Invoked - '.$foo;
    }
}
```

...and command:

```
 ab -t 10 -c 1 http://127.0.0.1/test-799/foo
```

And here are the average requests per second:

![image](https://user-images.githubusercontent.com/8052095/80528697-f72a5f80-895b-11ea-8470-bd722ccfa6d5.png)

**Comment by driesvints** [comment]
We have no plans to change the router in Lumen.
