### ISSUE TITLE
Lumen TestCase assertion count bigger than the real when use mockery‘s mock

### ISSUE THREAD

**Issue by szulilin** [laravel/lumen-framework#1079]
- Lumen Version: 5.5
- Laravel Version: 5.5
- PHP Version: 7.0
- Database Driver & Version:

https://github.com/laravel/lumen-framework/blob/5.5/src/Testing/TestCase.php  line：108

### Description:

assertion count bigger than the real when use mockery‘s mock

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
