### ISSUE TITLE
BindingResolutionException with all response() calls

### ISSUE THREAD

**Issue by haroldkyle** [laravel/lumen-framework#1080]
- Lumen Version: 7.1.2
- Laravel Version: 7.12.0
- PHP Version: 7.4.6
- Database Driver & Version: mysqlnd 7.4.6

### Description:
All routes return error:
```
Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Routing\RouteCollectionInterface] is not instantiable while building [Illuminate\Routing\Redirector, Illuminate\Routing\UrlGenerator]. in /home/harold/projects/work/git/sugar-api/vendor/laravel/framework/src/Illuminate/Container/Container.php:1011
```
Routes worked fine with Lumen 6.x, but appear to have problems with the new class `Illuminate\Routing\UrlGenerator` from Laravel 7.12.0.

### Steps To Reproduce:
Fresh install, then I have a route whose controller simply responds: `return response()->json($model)`.

The AppServiceProvider.php has the following, and it's `Illuminate\Routing\Redirector`  that loads the `Illuminate\Routing\UrlGenerator`:
```
    public function register()
    {
        $this->app->singleton('Illuminate\Contracts\Routing\ResponseFactory', function ($app) {
            return new \Illuminate\Routing\ResponseFactory(
                $app['Illuminate\Contracts\View\Factory'],
                $app['Illuminate\Routing\Redirector']
            );
        });
    }
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by haroldkyle** [comment]
Thanks, I'll let you know.  In the meantime, is the [workaround for ResponseFactory described here](https://github.com/tymondesigns/jwt-auth/pull/532) still necessary for Lumen? This is what triggers the Exception, after all.

**Comment by pascalvgemert** [comment]
@haroldkyle We experienced the same issues. We fixed it by replacing the workaround with:

```
$this->app->singleton('Illuminate\Contracts\Routing\ResponseFactory', function ($app) {
    return new \Laravel\Lumen\Http\ResponseFactory;
});
```
