### ISSUE TITLE
Not found route

### ISSUE THREAD

**Issue by espositovitor** [laravel/lumen-framework#1083]
### Technical information:

- Laravel Framework Lumen (7.1.3) (Laravel Components ^7.0)
- PHP Version: 7.4.5

### Description:

I get the Lumen project and start in port 8080 but the initial route in web file is not accessible. Anything changed? It's necessary to more anything?

### Steps To Reproduce:

Clone lumen repository: git clone https://github.com/laravel/lumen
Start Project: PHP -S localhost:8080
Access the default route: curl http://localhost:8080/

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
