### ISSUE TITLE
Bug while adding new job to queue

### ISSUE THREAD

**Issue by theonelucas** [laravel/lumen-framework#1095]
- Lumen Version: 7.0
- PHP Version: 7.2
- Database Driver & Version: MySql

### Description:

Whenever I try to add a new job to a queue, eg: `Queue::push(new BackupJob)` Lumen throws the error `Trying to access array offset on value of type null` that happens in `illuminate/queue/QueueManager.php (line 156)`. This line, containing the code ` return $this->getConnector($config['driver'])`, throws an error because `$config` is null, and `$config` is null because it's the result of the call to `$this->getConfig`, but the function `getConfig` tries to access `$this->app['config']["queue.connections.{$name}"]`, but `queue.connections` doesn't exist in the configuration array. This is the dump of `$this->app['config']` at the moment of the error:

`object(Illuminate\Config\Repository)#7 (1) { ["items":protected]=> array(3) { ["app"]=> array(9) { ["name"]=> string(8) "opendata" ["env"]=> string(5) "local" ["debug"]=> bool(true) ["url"]=> string(16) "http://localhost" ["timezone"]=> string(3) "UTC" ["locale"]=> string(2) "en" ["fallback_locale"]=> string(2) "en" ["key"]=> string(51) "base64:removed=" ["cipher"]=> string(11) "AES-256-CBC" } ["database"]=> array(4) { ["default"]=> string(5) "mysql" ["connections"]=> array(4) { ["sqlite"]=> array(3) { ["driver"]=> string(6) "sqlite" ["database"]=> string(6) "xerxes" ["prefix"]=> string(0) "" } ["mysql"]=> array(13) { ["driver"]=> string(5) "mysql" ["host"]=> string(2) "db" ["port"]=> string(4) "3306" ["database"]=> string(6) "xerxes" ["username"]=> string(4) "root" ["password"]=> string(0) "" ["unix_socket"]=> string(0) "" ["charset"]=> string(7) "utf8mb4" ["collation"]=> string(18) "utf8mb4_unicode_ci" ["prefix"]=> string(0) "" ["strict"]=> bool(true) ["engine"]=> NULL ["timezone"]=> string(6) "+00:00" } ["pgsql"]=> array(10) { ["driver"]=> string(5) "pgsql" ["host"]=> string(2) "db" ["port"]=> string(4) "3306" ["database"]=> string(6) "xerxes" ["username"]=> string(4) "root" ["password"]=> string(0) "" ["charset"]=> string(4) "utf8" ["prefix"]=> string(0) "" ["schema"]=> string(6) "public" ["sslmode"]=> string(6) "prefer" } ["sqlsrv"]=> array(8) { ["driver"]=> string(6) "sqlsrv" ["host"]=> string(2) "db" ["port"]=> string(4) "3306" ["database"]=> string(6) "xerxes" ["username"]=> string(4) "root" ["password"]=> string(0) "" ["charset"]=> string(4) "utf8" ["prefix"]=> string(0) "" } } ["migrations"]=> string(10) "migrations" ["redis"]=> array(4) { ["client"]=> string(8) "phpredis" ["cluster"]=> bool(false) ["default"]=> array(4) { ["host"]=> string(9) "127.0.0.1" ["password"]=> NULL ["port"]=> int(6379) ["database"]=> int(0) } ["cache"]=> array(4) { ["host"]=> string(9) "127.0.0.1" ["password"]=> NULL ["port"]=> int(6379) ["database"]=> int(1) } } } ["queue"]=> array(3) { ["default"]=> string(11) "database​" ["connections"]=> array(5) { ["sync"]=> array(1) { ["driver"]=> string(4) "sync" } ["database"]=> array(4) { ["driver"]=> string(8) "database" ["table"]=> string(4) "jobs" ["queue"]=> string(7) "default" ["retry_after"]=> int(90) } ["beanstalkd"]=> array(4) { ["driver"]=> string(10) "beanstalkd" ["host"]=> string(9) "localhost" ["queue"]=> string(7) "default" ["retry_after"]=> int(90) } ["sqs"]=> array(6) { ["driver"]=> string(3) "sqs" ["key"]=> string(15) "your-public-key" ["secret"]=> string(15) "your-secret-key" ["prefix"]=> string(51) "https://sqs.us-east-1.amazonaws.com/your-account-id" ["queue"]=> string(15) "your-queue-name" ["region"]=> string(9) "us-east-1" } ["redis"]=> array(5) { ["driver"]=> string(5) "redis" ["connection"]=> string(7) "default" ["queue"]=> string(7) "default" ["retry_after"]=> int(90) ["block_for"]=> NULL } } ["failed"]=> array(2) { ["database"]=> string(5) "mysql" ["table"]=> string(11) "failed_jobs" } } } }`

If I manually return `[ "driver" => "database", "table" => "jobs", "queue" => "default", "retry_after" => 90 ]` instead of `$this->app['config']["queue.connections.{$name}"]` it works just fine. My `.env` file is configured correctly, containing the `QUEUE_CONNECTION=database​` property. I tried creating the `config/queue.php` file with the default configuration but I got the same error.

**Comment by driesvints** [comment]
Can you manually add the line below to below this line and try again? https://github.com/laravel/lumen-framework/blob/7.x/src/Application.php#L996

```php
'Illuminate\Queue\QueueManager' => 'queue',
```

**Comment by theonelucas** [comment]
@driesvints Same error

**Comment by driesvints** [comment]
I just tested this myself and it works perfectly for me.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by theonelucas** [comment]
After some digging I discovered that there was a `queue:work` process in the background that was started prior to defining the `QUEUE_CONNECTION=database` env variable.

**Comment by eswachsman** [comment]
@theonelucas and what's the fix for that?

**Comment by theonelucas** [comment]
> @theonelucas and what's the fix for that?

In my case the solution was to stop all the queues running and start one again.
