### ISSUE TITLE
Parameter losts on tests when using a non default Request param on controller

### ISSUE THREAD

**Issue by joao-gsneto** [laravel/lumen-framework#1100]
Lumen (7.2.0) (Laravel Components ^7.0)
PHP 7.4

### Description:
When testing without an default Illuminate\Http\Request parameter on controller, Lumen dont recognize any body param (or GET or POST)

### Steps To Reproduce:
Create an class to override Request

````
class MyRequest extends Request
{
}
````

Do the ref to controller
````
class Controller
{
   public function index( MyRequest $req )
  {
      dd( $req->all());
  }
}
````

Create the testcase
````
public function testIndex()
{
  $this->post( "/req/index", [ "param" => 1, "param2" => 2 ] );
}
````

Result is an empty request on the controller.

On my case i make an "cast" to keep my controller testable:

````
    public function index(Request $req) //default request here
    {
        $request = castObject( $req, new MyRequest()); //myCustom request with my custom stuff
        $params = $request->all();

        //validate request params and validate user
        $this->validate($request, $request->rules(), $request->messages() );
   }

function castObject($sourceObject, $destination)
{
    if (is_string($destination)) {
        $destination = new $destination();
    }
    $sourceReflection = new ReflectionObject($sourceObject);
    $destinationReflection = new ReflectionObject($destination);
    $sourceProperties = $sourceReflection->getProperties();
    foreach ($sourceProperties as $sourceProperty) {
        $sourceProperty->setAccessible(true);
        $name = $sourceProperty->getName();
        $value = $sourceProperty->getValue($sourceObject);
        if ($destinationReflection->hasProperty($name)) {
            $propDest = $destinationReflection->getProperty($name);
            $propDest->setAccessible(true);
            $propDest->setValue($destination, $value);
        } else {
            $destination->$name = $value;
        }
    }
    return $destination;
}

````

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
