### ISSUE TITLE
Uncaught ReflectionException: Method Closure::handle() does not exist

### ISSUE THREAD

**Issue by foremtehan** [laravel/lumen-framework#1104]
Lumen Version: ^7.0

Passing closure to dispatch method not allowed in lumen ? But doc says :

 >Lumen's queued jobs function identically to Laravel's queued jobs

```php
dispatch(function (){
        echo 'Hello world';
})
```

```
Fatal error: Uncaught ReflectionException: Method Closure::handle() does not exist in C:\xampp\htdocs\project\vendor\illuminate\container\BoundMethod.php:149
```

**Comment by driesvints** [comment]
Queueing closures isn't possible in Lumen. I'll send in a PR to the docs.

**Comment by driesvints** [comment]
https://github.com/laravel/lumen-docs/pull/185
