### ISSUE TITLE
Using database cache with locks - Call to undefined function Illuminate\Cache\now()

### ISSUE THREAD

**Issue by Justas-S** [laravel/lumen-framework#1107]
- Lumen Version: v7.2.1
- Laravel Version: v7.27.0
- PHP Version: 7.4.9(cli)
- Database Driver & Version: SQLite

### Description:

The `DatabaseLock` references the `now()` helper which is defined in [Laraavel foundation](https://github.com/laravel/framework/blob/v7.27.0/src/Illuminate/Foundation/helpers.php#L574). Lumen does not have access to this component.

### Steps To Reproduce:

1. Set your cache provider to `database`
2. Try to acquire a lock. For example by calling `Cache::lock('example')->get(function () {});`

**Comment by driesvints** [comment]
https://github.com/laravel/framework/pull/34262

**Comment by driesvints** [comment]
Fixed in framework. Will be tagged soon.
