### ISSUE TITLE
'Please provide a valid cache path' exception thrown but all framework folders are present

### ISSUE THREAD

**Issue by 0ctavia** [laravel/lumen-framework#1108]
Containerised php version 7.3.20 with Lumen 7.2.1, served by nginx.

I am trying to add a view that holds the documentation of my API but have run into issues. The other routes work fine.
My route is simply 
```
$router->get('/', function () {
  return view('documentation');
});
```
There is a file called 'documentation.blade.php' in resources/views/

At first I had multiple errors _file_put_contents(): failed to open stream. Permission denied._
I changed permissions on the storage/logs folders and its contents.

After that the error became **_"please provide a valid cache path"_**
(thrown at line 36 of the myapp/vendor/illuminate/view/Compilers/Compiler.php )

Googling this error led to a flurry of solutions suggesting to create missing folders within the framework folder. However both the views and cache folders are present. 

My .env cache is set to CACHE_DRIVER = file

I appreciate any help or suggestions on how I could fix this issue.

**Comment by driesvints** [comment]
Please resubmit with a filled out issue template.
