### ISSUE TITLE
migrate:fresh drops literally all tables

### ISSUE THREAD

**Issue by t-tomek** [laravel/lumen-framework#1113]
- Lumen Version: 8.0.1
- Laravel Version: #.#.#
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7.26-29

### Description:
Use of `DB_PREFIX` does not stop `migrate:fresh` from deleting **only** prefixed tables. It deletes **all** tables in `DB_DATABASE` database. It might be misleading as prefixes are commonly used to distinguish different systems in the same database. One should be warned about not taking prefixes into account and\or confirm that action.

**Comment by GrahamCampbell** [comment]
I don't think this is a bug, actually. Similarly, flushing cache does the same thing, ignoring prefixes.

**Comment by t-tomek** [comment]
Mayby you would if you had accidentally deleted all tables like me...

I was not aware that not prefixed tables would be deleted.
Laravel docs warns:
> Flushing the cache does not respect the cache prefix and will remove all entries from the cache

Migrations have no such warning. 

Besides I wasn't flushing database (what is more flushing in DB context does not destroy **any** stored data) but I wanted just a fresh start for my prefixed tables in project. 

If it's not a bug so what's the point of prefixing? Just to have longer names?

**Comment by GrahamCampbell** [comment]
Prefixing is useful to avoid conflicts on shared servers. I'd not recommend using it though, tbh. If you want to share the same redis server for cache and sessions, you can do this by having more than one "database".

**Comment by driesvints** [comment]
Hey @t-tomek. The docs literally says:

> The migrate:fresh command will drop **all tables** from the database

I don't know how much more explicit we can be about that.

**Comment by driesvints** [comment]
In general I recommend database backups to prevent these things. Also, the `migrate:fresh` command wasn't really meant to be run production. That's why it has the confirmable trait applied.
