### ISSUE TITLE
Move PendingChain from Illuminate\Foundation\Bus to \Illuminate\Bus

### ISSUE THREAD

**Issue by kanidjar** [laravel/lumen-framework#1117]
Hi,

Using Batches and Chains, I've noticed that PendingBatch is part of the Illuminate\Bus package while PendingChain is part of the Illuminate\Foundation package, making it impossible to use with Lumen.

Any reason for that? Would it be possible to move it to \Illuminate\Bus?

<img width="557" alt="screenshot" src="https://user-images.githubusercontent.com/12607242/94993856-250f7200-0594-11eb-9090-9880c7a5c7d7.png">

**Comment by driesvints** [comment]
Looks like the PR was rejected and we won't be supporting this in Lumen. Feel free to send in a PR to the docs if you like. Thanks.

**Comment by kanidjar** [comment]
hi @driesvints , first PR was initially closed because @GrahamCampbell asked me to target 9.x because of BCs

**Comment by driesvints** [comment]
Okay, re-opened the other one.
