### ISSUE TITLE
uuid for "failed_jobs" table is not being generated/inserted by failed job handler process

### ISSUE THREAD

**Issue by smacabra** [laravel/lumen-framework#1119]
- Lumen Version: ^8.0
- PHP Version: 7.4
- Database Driver & Version: mysql (don't know how to check the driver version...)

### Description:
The "php artisan queue:failed-table" generates a migration file in which the "failed_jobs" table has the "uuid" column. This "uuid" column doesn't have a default value and when a job fails the handler doesn't try to generate an "uuid" and insert it along the others values at the "failed_jobs" table, making the failed job disappear. For reference I've logged the commands run at my database and here is the "prepare" statement:

insert into `failed_jobs` (`connection`, `queue`, `payload`, `exception`, `failed_at`) values (?, ?, ?, ?, ?)

The failed job handler needs to generate an uuid and insert it correctly.
For now the workaround is to just remove the "uuid" column from the failed_jobs table.

### Steps To Reproduce:
- Create a new Lumen project version ^8.0
- Run "php artisan queue:failed-table" and "php artisan migrate"
- Configure your queue
- Create a Job and make it fail, the failed job won't be inserted at the failed_jobs table

**Comment by driesvints** [comment]
You need to configure the `QUEUE_FAILED_DRIVER` as `database-uuids` if you want to make use of UUID's. That's part of this step here from the Laravel 8.x upgrade guide:

https://laravel.com/docs/8.x/upgrade#failed-jobs-table-batch-support

<img width="763" alt="Screenshot 2020-10-08 at 14 23 35" src="https://user-images.githubusercontent.com/594614/95458009-eb62b080-0971-11eb-95d7-e578d2fedcb8.png">

Also: the Lumen docs recommend to add this table manually and not make use of the artisan command. This prevents the uuid column from being added:
 
<img width="691" alt="Screenshot 2020-10-08 at 14 24 31" src="https://user-images.githubusercontent.com/594614/95458107-0a614280-0972-11eb-972f-275c359c78dc.png">
