### ISSUE TITLE
Lumen, dotenv and server environment variables

### ISSUE THREAD

**Issue by wjgilmore** [laravel/lumen-framework#112]
I've built a simple Lumen microservice which retrieves some data from database and sends the JSON-formatted results to client. Relevant characteristics: 

* Using the `DB` facade and am managing local database connection settings per usual in `.env`.
* Uncommented `Dotenv::load(__DIR__.'/../');` in `bootstrap/app.php` so `.env` settings can be loaded.
* Copied `vendor/laravel/lumen-framework/config/database.php` into a newly created `config` directory.

This all works great locally, however when I deploy to Heroku I'm receiving the error:

    PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with 
    message 'Dotenv: Environment file .env not found or not readable. Create 
    file with your environment settings at /app/bootstrap/../.env' in 
    /app/vendor/vlucas/phpdotenv/src/Dotenv.php:26 

Logically I don't want to use a `.env` file in production, preferring to instead using server environment variables. I've deployed several Laravel applications to Heroku in this fashion and the server environment variables are read by the `dotenv` library no problem, which makes this issue particularly confusing since I would presume this behavior would not change in Lumen after uncommenting `Dotenv::load(__DIR__.'/../');`

I'll keep digging but wanted to report this as something seems to be amiss (likely me).

**Comment by wjgilmore** [comment]
As it turns out this is indeed a case of user error. I was not aware that the `dotenv` library does indeed require a `.env` file; I thought it *also* read the server environment variables, meaning one could forego inclusion of a `.env` file in production. However in hosting environments where symlinking games commonly used with Capistrano is not possible, I'd rather not deal with the `.env` file at all. The easy fix is to comment  out `Dotenv::load` in `bootstrap/app.php` (I had previously uncommented it), and then just use `getenv()` to retrieve the server environment variable.

**Comment by FWSimon** [comment]
this still not work, i have tried with env(), getenv etc. nothing work to get the ENV settings

**Comment by sinkcup** [comment]
```
composer require vlucas/phpdotenv
```

https://github.com/vlucas/phpdotenv
