### ISSUE TITLE
Segmentation fault php8 with JIT enabled

### ISSUE THREAD

**Issue by notihnio** [laravel/lumen-framework#1128]
**My configuration:**

laravel/lumen-framework v8.2.0

vlucas/phpdotenv v5.2.0

php docker image: php:8.0.0RC3-fpm
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0RC3, Copyright (c), by Zend Technologies
    with Xdebug v3.0.0beta1, Copyright (c) 2002-2020, by Derick Rethans

OPcache (dev env configuration)

opcache.enable=1
opcache.enable_cli=1
opcache.revalidate_freq=0
opcache.validate_timestamps=1
opcache.max_accelerated_files=1000
opcache.memory_consumption=100M
opcache.max_wasted_percentage=10
opcache.interned_strings_buffer=16
opcache.fast_shutdown=1
**opcache.jit_buffer_size=100M**

**Error**
Occurs when I enable jit (opcache.jit_buffer_size=100M) and only then:

`php artisan` => Segmentation fault

And the trace 

`php -d xdebug.mode=trace artisan`

`Fatal error: Uncaught TypeError: Dotenv\Parser\EntryParser::Dotenv\Parser\{closure}(): Argument #1 ($val) must be of type array, null given, called in /code/core/vendor/graham-campbell/result-type/src/Success.php on line 78 and defined in /code/core/vendor/vlucas/phpdotenv/src/Parser/EntryParser.php:163
Stack trace:
#0 /code/core/vendor/graham-campbell/result-type/src/Success.php(78): Dotenv\Parser\EntryParser::Dotenv\Parser\{closure}(NULL)
#1 /code/core/vendor/vlucas/phpdotenv/src/Parser/EntryParser.php(165): GrahamCampbell\ResultType\Success->map(Object(Closure))
#2 /code/core/vendor/graham-campbell/result-type/src/Success.php(93): Dotenv\Parser\EntryParser::Dotenv\Parser\{closure}(Array)
#3 /code/core/vendor/vlucas/phpdotenv/src/Parser/EntryParser.php(166): GrahamCampbell\ResultType\Success->flatMap(Object(Closure))
#4 [internal function]: Dotenv\Parser\EntryParser::Dotenv\Parser\{closure}(Object(GrahamCampbell\ResultType\Success), 'ProjectY')
#5 /code/core/vendor/vlucas/phpdotenv/src/Parser/EntryParser.php(167): array_reduce(Array, Object(Closure), Object(GrahamCampbell\ResultType\Success))
#6 /code/core/vendor/vlucas/phpdotenv/src/Parser/EntryParser.php(52): Dotenv\Parser\EntryParser::parseValue('ProjectY')
#7 /code/core/vendor/graham-campbell/result-type/src/Success.php(93): Dotenv\Parser\EntryParser::Dotenv\Parser\{closure}('PRODUCT_NAME')
#8 /code/core/vendor/vlucas/phpdotenv/src/Parser/EntryParser.php(57): GrahamCampbell\ResultType\Success->flatMap(Object(Closure))
#9 /code/core/vendor/graham-campbell/result-type/src/Success.php(93): Dotenv\Parser\EntryParser::Dotenv\Parser\{closure}(Array)
#10 /code/core/vendor/vlucas/phpdotenv/src/Parser/EntryParser.php(58): GrahamCampbell\ResultType\Success->flatMap(Object(Closure))
#11 /code/core/vendor/vlucas/phpdotenv/src/Parser/Parser.php(45): Dotenv\Parser\EntryParser::parse('PRODUCT_NAME=Pr...')
#12 /code/core/vendor/graham-campbell/result-type/src/Success.php(93): Dotenv\Parser\Parser::Dotenv\Parser\{closure}(Array)
#13 /code/core/vendor/vlucas/phpdotenv/src/Parser/Parser.php(48): GrahamCampbell\ResultType\Success->flatMap(Object(Closure))
#14 [internal function]: Dotenv\Parser\Parser::Dotenv\Parser\{closure}(Object(GrahamCampbell\ResultType\Success), 'PRODUCT_NAME=Pr...')
#15 /code/core/vendor/vlucas/phpdotenv/src/Parser/Parser.php(49): array_reduce(Array, Object(Closure), Object(GrahamCampbell\ResultType\Success))
#16 /code/core/vendor/vlucas/phpdotenv/src/Parser/Parser.php(28): Dotenv\Parser\Parser::process(Array)
#17 /code/core/vendor/graham-campbell/result-type/src/Success.php(93): Dotenv\Parser\Parser::Dotenv\Parser\{closure}(Array)
#18 /code/core/vendor/vlucas/phpdotenv/src/Parser/Parser.php(29): GrahamCampbell\ResultType\Success->flatMap(Object(Closure))
#19 /code/core/vendor/vlucas/phpdotenv/src/Dotenv.php(222): Dotenv\Parser\Parser->parse('#{production,te...')
#20 /code/core/vendor/vlucas/phpdotenv/src/Dotenv.php(237): Dotenv\Dotenv->load()
#21 /code/core/vendor/laravel/lumen-framework/src/Bootstrap/LoadEnvironmentVariables.php(49): Dotenv\Dotenv->safeLoad()
#22 /code/core/bootstrap/app.php(7): Laravel\Lumen\Bootstrap\LoadEnvironmentVariables->bootstrap()
#23 /code/core/artisan(18): require('/code/core/boot...')
#24 {main}
  thrown in /code/core/vendor/vlucas/phpdotenv/src/Parser/EntryParser.php on line 163
`

**Without enabling jit it works**

**Comment by driesvints** [comment]
Not sure if Lumen has support for JIT or if we'll ever provide it.

**Comment by GrahamCampbell** [comment]
This looks like a bug in PHP. Unlike preloading, JIT should "just work".
