### ISSUE TITLE
Getting the error 404 Not Found when deploying Lumen API app to Ubuntu 20.04/Nginx/PHP 7.4

### ISSUE THREAD

**Issue by Djas2017** [laravel/lumen-framework#1131]
- Lumen Version: #.#.#
# php artisan --version
Laravel Framework Lumen (7.2.2) (Laravel Components ^7.0)

- PHP Version: #.#.#
# php -v
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

- Database Driver & Version:

### Description:
The developer developed the app on his local computer. This screensjot show his testing locally:

![api-developer-lumen-create-user-tested-locally-Screenshot (73)(1)](https://user-images.githubusercontent.com/25626639/98714062-6eeb3500-2356-11eb-9b65-b780f1e6dc9d.png)

When uploading the app to the Ubuntu Server 20.04 / Nginx/PHP 7.4/Mysql server, I get an error: "404 Not Found" when I go to: "https://domain_name_replaced_here.tld/userCat/api/v1/create_user"

### Steps To Reproduce:
- In Nginx vhost: Set: root /var/www/app/html;

- Put the app content inside: /var/www/app/html/

- When uploading the app to the Ubuntu Server 20.04 / Nginx/PHP 7.4/Mysql server, I get an error: "404 Not Found" when I go to: "https://domain_name_replaced_here.tld/userCat/api/v1/create_user"

Is there something I am missing?

**Comment by GrahamCampbell** [comment]
Are you deploying to a sub-directory "userCat"? Lumen does not support that.

**Comment by Djas2017** [comment]
Thanks Graham for the followup.
As I said the root folder to which the app code was deployed to is: root /var/www/app/html
The api I want it to be accessible like: https://domain_name_replaced_here.tld/userCat/api/v1/getSingleUser/user/{useridhere}/{tokenhere}

**Comment by GrahamCampbell** [comment]
And what does your route look like please?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
