### ISSUE TITLE
Method Laravel\\Lumen\\Http\\Request::validate does not exist.

### ISSUE THREAD

**Issue by mikield** [laravel/lumen-framework#1135]
- Lumen Version: 8.2.1
- PHP Version: 7.4.11

### Description:

The core `Laravel\Lumen\Http\Request` class, which extends `Illuminate\Http\Request` class with an annotation to a `validate` method seems not to have it.

I understand that annotations is not a public available API, but mentioning this method - describes bad usage behavior for the devs.

### Steps To Reproduce:

1) Clean install Lumen Version 8.2.1 
2) Type hint  `Laravel\Lumen\Http\Request` into a route.
3) Try to call `validate` method on the `Laravel\Lumen\Http\Request`.

**Comment by driesvints** [comment]
This is indeed not available in Lumen.
