### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by dishcheng** [laravel/lumen-framework#1137]
- Lumen Version: 6.3.5
- PHP Version: 7.2.x

### Description:

https://github.com/illuminate/container/commit/aa6e7030cba7458bbeeddfb1ddb54b3c2f7ba113
 
when I use resource route and use controller method
```
  /**
     * @param $productCode
     */
    public function show($productCode)
    {
       return $productCode;
    }
```
will throw `Unable to resolve dependency [Parameter #0 [ <required> $productCode ]] in class App\\Http\\Controllers\\Api\\Customer\\Product\\ProductSellController`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by dishcheng** [comment]
> Hey there,
> 
> Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.
> 
> Thanks!

![image](https://user-images.githubusercontent.com/26062252/100841705-a01cd800-34b2-11eb-8da0-e93afce7b95a.png)

lumen6.x LTS don't fix bug?

**Comment by driesvints** [comment]
Lumen 6 isn't LTS. Only Laravel is LTS.

**Comment by driesvints** [comment]
It says so right above the section you highlighted.

**Comment by dishcheng** [comment]
Thanks
