### ISSUE TITLE
Unable to delay jobs

### ISSUE THREAD

**Issue by rapid-tech** [laravel/lumen-framework#1138]
- Lumen Version: 8.2.1
- PHP Version: 7.4.13
- Database Driver & Version: SQLite

### Description:
After the latest update, we are no longer able to delay queued jobs.
The delay property is completely ignored and the jobs will run multiple times per second.

### Steps To Reproduce:

Create a job and add a delay.
Run the queue worker.

**Comment by GrahamCampbell** [comment]
Please run compose update again.

**Comment by rapid-tech** [comment]
Hi Graham

Running composer update did not resolve my issue.
I've resorted to adding and locking illuminate/queue to v8.16.1.

Now the delays work as expected.

Thanks
