### ISSUE TITLE
Add tags to the laravel/lumen repository

### ISSUE THREAD

**Issue by 0xRaf** [laravel/lumen-framework#1139]
Hi,

Not sure if it goes there as I can't make a pull request for this.

If you don't look specifically for the laravel/lumen repository, it's almost invisible :
- https://github.com/search?l=PHP&o=desc&p=2&q=laravel&s=stars&type=Repositories
- https://github.com/search?l=PHP&o=desc&p=2&q=framework&s=stars&type=Repositories
- https://github.com/search?l=PHP&o=desc&q=micro-framework&s=stars&type=Repositories

Adding tags like "laravel", "framework" and "micro-framework" to the repository can increase its visibility drastically.

**Comment by driesvints** [comment]
No plans for this
