### ISSUE TITLE
InvalidArgumentException: Unknown formatter "unique"

### ISSUE THREAD

**Issue by ProteanCode** [laravel/lumen-framework#1140]
- Lumen Version: 8.2.1
- PHP Version: 7.4.13
- Database Driver & Version: Postgres 13

### Description:
Whenever I run unit tests I get the error about unknown faker provider.

### Steps To Reproduce:
Run unit tests

### Additional info
I do not have a separated directories for Feature or Unit tests since every test in my project is a Feature test from logical point of view. I will try to revert the original structure of /tests directory to see if it will help, but this should not be the case whenever a php class is in a Feature directory.

Also the docs in Lumen v8 uses factory() helper which is no longer available.

### Workaround
`$f = \Database\Factories\UserFactory::new(); $user = $f->createOne();`

### Related issue:
https://github.com/laravel/framework/issues/34384

**Comment by driesvints** [comment]
I can run Lumen's default test from the skeleton just fine. There's nothing much to go on here from this issue. If you have more info to reproduce this feel free to share it.
