### ISSUE TITLE
"Class 'League\Flysystem\Adapter\Local' not found" when using local storage method

### ISSUE THREAD

**Issue by Tukizz** [laravel/lumen-framework#1142]
- Lumen Version: 8.2.1
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 5.7.24

### Description:
I have error in my fresh lumen installer, it's throw error "Class 'League\Flysystem\Adapter\Local' not found" when i use local storage

### Steps To Reproduce:
i found the solve in this link https://github.com/thephpleague/flysystem/issues/1239#issuecomment-736276334 

i check in my lumen vendor/illuminate/filesystem/FilesystemManager.php on line 11 it's still use old type but when i change manual it's still throw error

maybe the package need to be update

**Comment by Tukizz** [comment]
when i use "league/flysystem": "^1.1" it's working

**Comment by driesvints** [comment]
Flysystem v2 isn't supported at this time. Please use v1.
