### ISSUE TITLE
Facades/Eloquent seems to (almost) work fine without withFacades/withEloquent?

### ISSUE THREAD

**Issue by fractalf** [laravel/lumen-framework#1147]
- Lumen/Laravel Version: `Laravel Framework Lumen (8.2.1) (Laravel Components ^8.0)`
 
- PHP Version: `7.3.19`

### Description:

in `./bootstrap/app.php` these two lines are commented out by default
```php
// $app->withFacades();
// $app->withEloquent();
```

I didn't really pay this much attention and both facades and eloquent have been working fine.

..until I started to write some tests on some methods etc, then I got the error 

```
There was 1 error:
RuntimeException: A facade root has not been set.
```

I started digging around, and then noticed I hadn't "activated" facades, but they shure as hell have been working up until now.

After uncommenting these two lines, the test ran successfully without the error.

This is a bit confusing, is this a bug?

Thank you

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
