### ISSUE TITLE
ValidatesWhenResolved not working.

### ISSUE THREAD

**Issue by Andreyco** [laravel/lumen-framework#115]
If request implements ValidatesWhenResolved (i.e. via ValidatesWhenResolvedTrait), it is not validated automatically.  

I have following request class (in short)
```php
class FormRequest extends Request implements ValidatesWhenResolved {

	use ValidatesWhenResolvedTrait;
    
}
```

`ValidationServiceProvider::registerValidationResolverHook` is executed as expected, but (looks like) after Request is resolved, thus `afterResolving` is not executed.  
This portion of code is never executed
```php
$this->app->afterResolving(function(ValidatesWhenResolved $resolved)
		{
			$resolved->validate();
		});
```

I registered Illuminate\Validation\ValidationServiceProvider in App\Providers\AppServiceProvider which at least started to call `validate` method on Request but fails on resolving validator. It interferes with app's https://github.com/laravel/lumen-framework/blob/5.0/src/Application.php#L684 (recursive calls?)

Am I trying to run feature which is not actually supported or is there a bug?

**Comment by GrahamCampbell** [comment]
We don't support this out of the box. I suggest you just use Laravel.

**Comment by Andreyco** [comment]
No problem at all. I opted for Laravel. Out of curiosity, is this caused by different router/route handler resolving process?
