### ISSUE TITLE
Illuminate session component - problem with lumen

### ISSUE THREAD

**Issue by nepster-web** [laravel/lumen-framework#1151]
Hello. 

I use lumen and I added https://github.com/illuminate/session component in my project.
Now I need to use **previousUrl** and this feature does not work.

let's try to figure it out.

https://github.com/illuminate/session/blob/master/Middleware/StartSession.php#L203

We use illuminate/router
https://github.com/illuminate/session/blob/master/Middleware/StartSession.php#L8

but, lumen doesn't support this component and illuminate/session  doesn't have a illuminate/router require https://github.com/illuminate/session/blob/master/composer.json#L16

Perhaps we can remove the check for ```$request->route() instanceof Route``` ?
or add illuminate/router require in composer/json ?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
