### ISSUE TITLE
Inconsistent cache configuration compared to Laravel

### ISSUE THREAD

**Issue by ssi-anik** [laravel/lumen-framework#1152]
- Lumen Version: 8.x
- Laravel Version: 8.x
- PHP Version: 7.4
- Database Driver & Version:

### Description:
There is an inconsistency between the Lumen and Laravel database & cache config.

### Steps To Reproduce:
- Lumen framework is shipped with a `broadcasting` config file. which by default uses the `default` redis config
- Redis broadcasting driver uses [`database.redis.options.prefix`](https://github.com/illuminate/broadcasting/blob/master/BroadcastManager.php#L242-L248) for the prefix.
- Lumen framework's database config doesn't even use that key. [Lumen config](https://github.com/laravel/lumen-framework/blob/0603a83a3b6385a12acc3c6aa50858e4907fb6e4/config/database.php#L112) and [Laravel config](https://github.com/laravel/laravel/blob/c1b56831dfb96cfc1e87d40f44f7b2cca07c351c/config/database.php#L124-L127)

**Comment by driesvints** [comment]
Feel free to PR that 👍
