### ISSUE TITLE
Sometimes the environment config is not loaded properly

### ISSUE THREAD

**Issue by Albvadi** [laravel/lumen-framework#1155]
- Lumen Version: (7.2.2) (Laravel Components ^7.0)
- PHP Version: 7.2.19
- Database Driver & Version: N/A

### Description:
Sometimes, randomly, using `app()->environment()` I get `local` instead of `development` (or the value configured in my .env file)

![lumen](https://user-images.githubusercontent.com/6285255/107974061-51adae80-6fb6-11eb-9959-39254057ada8.gif)

### Steps To Reproduce:
- Configure `APP_ENV` in the .env file
```env
APP_ENV=development
```
- Create new route and return the environment:
```php
$router->get('/environment', function () use ($router) {
    return app()->environment();
});
```
I think is related tih PHP and multithread. There are some related reports like https://github.com/laravel/lumen-framework/issues/605, https://github.com/laravel/lumen-framework/issues/585, https://github.com/laravel/lumen/pull/132
Finally, @GrahamCampbell in https://github.com/laravel/lumen/pull/132#issuecomment-499140906 says it´s solved in his PRs, but I´m not sure it´s my fault...

Also, reviewing [phpdotenv upgrading guide](https://github.com/vlucas/phpdotenv/blob/master/UPGRADING.md#v2-to-v3) there is a example code to make dotenv work properly. I have put that code before the `LoadEnvironmentVariables` in `bootstrapp/app.php` and it seems to have solved my problem, but again I don't know if it is the correct way or if it should work without adding any additional code.

Thank you.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by AnonimBella** [comment]
I got this error too and I solved it by adding dotenv manually in bootstrap.php. I'm using Lumen ^9.0 and PHP 8.0.27
