### ISSUE TITLE
Laravel 8 function setKeysForSaveQuery conflict

### ISSUE THREAD

**Issue by MarcosPauloSouzaMiranda** [laravel/lumen-framework#1157]
- Lumen Version: ^8.0
- PHP Version: 8.0.1

### Description:
The lumen framework encounters the same problem as laravel, I suspect that is why it is using an outdated dependency on laravel / database.

The BUG correction issue is [#34578](https://github.com/laravel/framework/issues/34578).

Att,
Marcos

**Comment by GrahamCampbell** [comment]
Lumen will get the latest Laravel version. If it is pulling an old version, this is probably due to something in your composer.json pinning the version (possibly implicitly via a dependency of a dependency).
