### ISSUE TITLE
Model::setKeysForSaveQuery(Illuminate\Database\Eloquent\Builder $query) should be compatible with Illuminate\Database\Eloquent\Model::setKeysForSaveQuery($query)

### ISSUE THREAD

**Issue by ketanyekale** [laravel/lumen-framework#1158]
- Lumen Version: 8.2.3
- PHP Version: 7.3.27

### Description:
It is the same issue as https://github.com/laravel/framework/issues/34585 but with lumen-framework.
Please replace ~protected function setKeysForSaveQuery($query)~ by `protected function setKeysForSaveQuery(Builder $query)` in the files below:

1. illuminate/database/Eloquent/Model.php
2. illuminate/database/Eloquent/Relations/MorphPivot.php 
3. illuminate/database/Eloquent/Relations/Concerns/AsPivot.php

### Steps To Reproduce:
It is the same issue as https://github.com/laravel/framework/issues/34585

**Comment by GrahamCampbell** [comment]
> Fixed on patch 8.7.1.

Upgrade your dependencies.

**Comment by ketanyekale** [comment]
illuminate/database is already on v8.32.1 

Created a PR https://github.com/illuminate/database/pull/267

Please release a new version soon.

**Comment by driesvints** [comment]
This method doesn't exists in Lumen.
