### ISSUE TITLE
Packages don't work!

### ISSUE THREAD

**Issue by irazasyed** [laravel/lumen-framework#116]
I know Lumen is not trying to be Laravel but there are several packages out there that could've been used with Lumen, but due to some helper functions, it doesn't work with Lumen.

For example `database_path` one of the packages i was trying to use with Lumen throws undefined fatal error, similarly there are few other helper functions that are common with Laravel but due to no support in Lumen, it doesn't work. 

Why can't we have these small helpers common in Laravel, So that we can use all those amazing Packages out there with Lumen too?

Currently, I end up manually adding package service providers into my custom service providers but that's really not a good thing TBH.

**Comment by GrahamCampbell** [comment]
Yes, this is known. If you want packages, use Laravel.
