### ISSUE TITLE
Missing Support Policy?

### ISSUE THREAD

**Issue by dunhamjared** [laravel/lumen-framework#1161]
I created a pull request assuming Lumen 6.x supported PHP 8 just as Laravel 6.x supports PHP 8.
Source: https://blog.laravel.com/laravel-php-8-support

However, I was told that I must upgrade for PHP 8 support. 
Source: https://github.com/laravel/lumen-framework/pull/1160#issuecomment-801731728

Does this mean 6.x is no longer supported? 
Is Lumen not following the same support lifecycle as Larval? 

If so, could we have Lumen's support lifecycle documented?

**Comment by driesvints** [comment]
Hey @dunhamjared. That blog post is about Laravel, not Lumen. Our official support policy can be found here in the docs: https://laravel.com/docs/8.x/releases#support-policy

![Screenshot 2021-03-18 at 15 21 08](https://user-images.githubusercontent.com/594614/111641670-a9ca1180-87fd-11eb-97a7-8edfdc38859c.jpg)

**Comment by dunhamjared** [comment]
Thank you @driesvints !! Did not see this.
