### ISSUE TITLE
Check batch's status not working normally

### ISSUE THREAD

**Issue by hungnc89** [laravel/lumen-framework#1162]
- Lumen Version: 8.0
- Laravel Version: #.#.#
- PHP Version: 7.3
- Database Driver & Version: MariabDb 10.3

### Description:
Issue with batch, exactly issue with function finished() to check batch's  status.
When I have multi jobs in a batch, if once of them have an exception, batch status checked by finished function will return true, in fact, has more jobs still running.

### Steps To Reproduce:

- Create multi jobs with batch, one of them throw exception.
- Create one controller to check batch status and go to it after run batch to create multi jobs available in database ( Make sure job have exception at the first )
- We will see finished status of batch is true.

Sorry, my english is not fluency

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
