### ISSUE TITLE
Class 'Illuminate\Foundation\Bus\PendingChain' not found

### ISSUE THREAD

**Issue by djalmamanfrin** [laravel/lumen-framework#1163]
- Lumen Version: 8.2.3
- Laravel Version: #.#.#
- PHP Version: 7.4.15
- Database Driver & Version:

### Description:
I was trying to use [Job Chaing](https://laravel.com/docs/8.x/queues#job-chaining) to specify a list of queued jobs. Then I received the respective exception:.
Looking into the 'Illuminate\Support\Facades\Bus' the `chain` method inform:
` * @method static \Illuminate\Foundation\Bus\PendingChain chain(array $jobs)`

I looked for about the error and found the [issue #1117](https://github.com/laravel/lumen-framework/issues/1117). Maybe it has correlation.

### Steps To Reproduce:
```
\Illuminate\Support\Facades\Bus::chain([
    new Job01(),
    new Job02()
->dispatch();
```

**Comment by GrahamCampbell** [comment]
Job chaining cannot be used outside of the framework. It is not available in lumen or via direct installation of the illuminate package. You must use the whole framework.
