### ISSUE TITLE
cant use `$app->configure('services')`

### ISSUE THREAD

**Issue by YogiPristiawan** [laravel/lumen-framework#1164]
- Lumen Version: 8.2.3
- Laravel Version: 8.0
- PHP Version: 7.4.9
- Database Driver & Version: 15.1

### Description:
when i create `config/services.php` and then register to `$app->configure('services')` the `config()` doesn't work. instead i am register with `config(['key' => 'value'])` manually.

**Comment by driesvints** [comment]
Works fine for me:

```
$router->get('/', function () use ($router) {
    return config('services');
});
```

![Screenshot 2021-04-08 at 09 37 33](https://user-images.githubusercontent.com/594614/113986965-1f9a2980-984e-11eb-9e34-5857ff315abe.jpg)
