### ISSUE TITLE
Call to a member function locksFor()

### ISSUE THREAD

**Issue by liweiphp** [laravel/lumen-framework#1165]
- Lumen Version: 7.2.2
- PHP Version: 7.4.13
- Database Driver & Version:
postgresql 12.3
### Description:
1.use session
2.phpunit multiple api request in one test
3.console phpunit

Call to a member function locksFor() on array {"exception":"[object] (Error(code: 0): Call to a member function locksFor() on array at /app/vendor/illuminate/session/Middleware/StartSession.php:60)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by liweiphp** [comment]
feedback,
After upgrade 8.0 version the problem fix.
