### ISSUE TITLE
A Request object passed to run() get lost if passed through middleware

### ISSUE THREAD

**Issue by MarkG-IEL** [laravel/lumen-framework#1166]
- Lumen Version: 8.2.3
- PHP Version: 8.0.3
- Database Driver & Version:

### Description:
Passing an `\Illuminate\Http\Request` object like `app()->run($request);` "loses" itself when global middleware is present. The execute path goes:

`run()` -> `dispatch()` -> `sendThroughPipeline()`
 
In `sendThroughPipeline()`, if there are global middleware, a new `Request` object is generated and passed to the middleware pipeline and subsequent controllers. This problem is subtly masked by the fact that the `$method` and `$pathInfo` are already parsed from the request that is passed in, so the correct controller is called, but with an incorrect `Request` object.

The issue may be that `parseIncomingRequest()` is binding `Request::class`, but  `sendThroughPipeline()` is looking for a binding at `'request'` in `send($this->make('request'))` [line 420], but I may be missing something subtle here.

### Steps To Reproduce:
```
$request = Request::create(
                uri: '/test',
                method: 'POST',
                server: ['CONTENT_TYPE' => 'application/json'],
                content: '{"test": 1}'
            );
app()->run($request);
```
You will not get the content, and the method will be GET in the controller.

**Comment by driesvints** [comment]
Please provide the exact minimum amount of code to reproduce this, thanks.

**Comment by MarkG-IEL** [comment]
@driesvints, this was a case of me trying to use `app()->run()` in an artisan command to basically route data I was listening for from an event queue through the application. What I needed to do was to instantiate another instance of the application and use that:
```
$app = require __DIR__ . '/../../../bootstrap/app.php';
ob_start();
$app->run($request);
echo ob_end_flush();
```

No bug really, just not a common use and the fact that `app()` was properly routing (even though it lost the request) was confusing.
