### ISSUE TITLE
php artisan  not work in lumen 7.2.2

### ISSUE THREAD

**Issue by ycit-alzuabiri** [laravel/lumen-framework#1167]
- Lumen Version: 7.2.2
- Laravel Version: 7.0

### Description:
when I use php artisan in lumen 7.2.2 project . I have this error

**In Container.php line 1017:
  Target [Illuminate\Contracts\Console\Kernel] is not instantiable.**  

i search in web to find solution I didn't  have correct answer

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
