### ISSUE TITLE
Session middleware broken?

### ISSUE THREAD

**Issue by kraffslol** [laravel/lumen-framework#117]
I'm using a fresh install of Lumen on Homestead. I've changed nothing but the app.php file where all I've done is uncommented
`'Illuminate\Session\Middleware\StartSession',`

After I've saved and try to visit the default route I get this error
`Argument 1 passed to Illuminate\Session\Middleware\StartSession::addCookieToResponse() must be an instance of Symfony\Component\HttpFoundation\Response, string given`
Looking further into the error I can see that it tries to give the addCookieToResponse Response argument the contents of the view file.
`StartSession->addCookieToResponse('<html> <head> <title>Lumen</title>...., object(Store))`

I'm not sure what is causing this problem but it seems to reside in the StartSession.php file inside the handle function.
`$response = $next($request);`

I hope is helpful to find and fix the problem, if there is one at all.

**Comment by hasokeric** [comment]
i am having the same thing... only when my routes do return 'some text';

**Comment by vluzrmos** [comment]
#156 
Somehow the framework is not converting the returned string into a response object.

**Comment by taylorotwell** [comment]
Fixed in 5.1.1

**Comment by vluzrmos** [comment]
:+1:

**Comment by adrian7** [comment]
:+1:
