### ISSUE TITLE
eloquent different results in ambient similar

### ISSUE THREAD

**Issue by DProgrammerOf** [laravel/lumen-framework#1170]
### Infos:
- Lumen Version: 8.2.3
- Laravel Version: 8
- PHP Version: 8.0.2
- Database Driver & Version: (mysql) 10.1.47-MariaDB-0ubuntu0.18.04.1

### Description:
The purpose of the code is to return the positions of a vehicle within the date range given by the user. 
Problems in retrieving values from a table with clauses **whereBetween**, I do not necessarily know whether it is because of this or something else.
I executed the exact same codes and settings (.env) in the same environment and obtained totally different results using **laravel** _(returning 252 registers - CORRECT)_ and **lumen** _(returning 0 registers - WRONG)_. 

### Steps To Reproduce:
The exact steps reproduced in two librarys ( [laravel/lumen](https://github.com/laravel/lumen) and [laravel/laravel](https://github.com/laravel/laravel)).
The test was carried out by sending a request [**GET** "/veiculos"] with the parameters: 
* imei = 355929100096610
* data=2021-05-11
* hora1=13:00
* hora2=15:00

**Table structure:**
```sql

CREATE TABLE `gprmc` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `imei` varchar(25) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `satelliteFixStatus` char(1) DEFAULT 'A',
  `latitudeDecimalDegrees` varchar(25) NOT NULL,
  `latitudeHemisphere` char(1) DEFAULT 'S',
  `longitudeDecimalDegrees` varchar(25) NOT NULL,
  `longitudeHemisphere` char(1) DEFAULT 'W',
  `speed` float NOT NULL,
  `direcao` int(11) NOT NULL DEFAULT '0' COMMENT 'Sentido que o veiculo se move',
  `gpsSignalIndicator` char(1) DEFAULT 'F',
  `infotext` mediumtext,
  `address` mediumtext,
  `km_rodado` float(12,5) DEFAULT NULL,
  `converte` int(11) DEFAULT '0',
  `ligado` char(1) DEFAULT 'N',
  `voltagem_bateria` char(5) DEFAULT NULL,
  `carregamento` char(1) DEFAULT NULL,
  `protocol` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `attributes` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accuracy` double DEFAULT NULL,
  `network` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `valid` bit(1) DEFAULT NULL,
  `servertime` timestamp NULL DEFAULT NULL,
  `fixtime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `altitude` float DEFAULT NULL,
  `course` float DEFAULT NULL,
  `deviceid` float DEFAULT NULL,
  PRIMARY KEY (`id`,`imei`,`date`,`fixtime`) USING BTREE,
  UNIQUE KEY `id` (`id`),
  KEY `date` (`date`),
  KEY `fixtime` (`fixtime`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=63483150 DEFAULT CHARSET=utf8 ROW_FORMAT=REDUNDANT;
```

 **App\Models\Gprmc**
```php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Gprmc extends Model
{
    protected $table = 'gprmc';
}
```

**App\Http\Controllers\VeiculoController**
```php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Gprmc;

class VeiculoController extends Controller
{
    public function index(Request $request)
    {
        $imei = $request->input('imei');
        $data = $request->input('data');
        $data = implode('-', array_reverse(explode('/', $data)));
        $horaInicio = $request->input('hora1').':00';
        $horaFinal 	= $request->input('hora2').':59';
        $dataInicio = $data.' '.$horaInicio;
        $dataFinal = $data.' '.$horaFinal;

        $Gprmc = new Gprmc;
        $GprmcVeiculo = $Gprmc
            ->where('imei', $imei)
            ->whereBetween('date', [$dataInicio, $dataFinal])
            ->get();

        dd($GprmcVeiculo);
    }
}
```

### Results:
**Lumen ([laravel/lumen](https://github.com/laravel/lumen)): ![Lumen result](https://dprog.com.br/LumenResult.png)**
**Laravel ([laravel/laravel](https://github.com/laravel/laravel)): ![Laravel result](https://dprog.com.br/LaravelResult.png)**

**Comment by silvesterwali** [comment]
try remove the instant $Gprmc = new Gprmc;

```php
 $GprmcVeiculo =Gprmc
            ->where('imei', $imei)
            ->whereBetween('date', [$dataInicio, $dataFinal])
            ->get();
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
