### ISSUE TITLE
withFacades() should accepts a parameter indicating the fascades that should not be loaded

### ISSUE THREAD

**Issue by yadakhov** [laravel/lumen-framework#118]
I was incorporating Lumen to a legacy PHP application today and encountered some problems with re-declaring  classes.

The existing PHP application already have a Cookie and DB class declared which conflicted with Lumen's fascades.

It would be useful if the $app->withFascade() function accept a parameter indicating only the fascades to be loaded or maybe the fascades not to load/

Something like:

`Application->withFacades($without)`

```php
$app->withFacades([
    'DB',
    'Cookie'
]);
```

I can do a PR if this enhancement is wanted.

**Comment by radmen** [comment]
IMO that's a bad API design. calling `withFacades()` with a list of facades as argument suggest that this facade should be loaded.

**Comment by lukasgeiter** [comment]
I have to agree with @radmen. The simplest way to solve your problem would probably be to namespace your application or create the aliases you want manually (or just avoid facades completely)
