### ISSUE TITLE
Make ViewException (and others) reportable with standard logging

### ISSUE THREAD

**Issue by the-real-christoph** [laravel/lumen-framework#1181]
Lumen 8.2.4

When encountering errors while processing view files, ViewException is thrown.

The problem is that Illuminate\View\ViewException implements "report" and "render" methods which do nothing really. But by implementing this methods also Laravel\Lumen\Exceptions\Handler does not allow any further reporting.

For bug hunting it would be very nice to have an option to always log such exceptions, even if they implement a custom "report" method.

I can easily add this logging in my own App\Exceptions\Handler.php but it would be nice to have this option integrated into Lumen itself, also to save new developers the effort of finding out what causes the blank pages.

Let me know if I got anything wrong or provide more details on this.

**Comment by driesvints** [comment]
Feel free to attempt a pr

**Comment by the-real-christoph** [comment]
That was fast :-)
I'll try (not that fast)
