### ISSUE TITLE
Http::baseUrl not working for pool requests

### ISSUE THREAD

**Issue by MohammadZarifiyan** [laravel/lumen-framework#1191]
- PHP Version: 8.0

### Description:
Http baseUrl has no effecc

### Steps To Reproduce:

```
use Illuminate\Http\Client\Pool;
use Illuminate\Support\Facades\Http;

public function sendRequest(){
        return Http::baseUrl('http://example.com')->pool(fn (Pool $pool) => $this->createRequestPool($pool));
 }
 
public function createRequestPool(Pool $pool): array {
// returns some array of pool requests like this:
// [
//           $pool->get('first'),
//         $pool->get('second'),
//        $pool->get('third'),
//    ]
 }
```

# Outgoing requests:
```
http://first
http://second
http://third
```

# Expected outgoing requests:
```
http://example.com/first
http://example.com/second
http://example.com/third
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
