### ISSUE TITLE
Post not working properly in pool requests

### ISSUE THREAD

**Issue by MohammadZarifiyan** [laravel/lumen-framework#1192]
- PHP Version: 8.0

### Description:
No data is sent by post method.

### Steps To Reproduce:
```
use Illuminate\Http\Client\Pool;
use Illuminate\Support\Facades\Http;

$responses = Http::pool(fn (Pool $pool) => [
    $pool->post('http://localhost/first', $data1),
    $pool->post('http://localhost/second', $data2),
    $pool->post('http://localhost/third', $data3),
]);
```

The endpoint server does not receive any of the $data1 or $data2 or $data3.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
