### ISSUE TITLE
Route middleware doesn't support termination

### ISSUE THREAD

**Issue by borys-p** [laravel/lumen-framework#1204]
- Lumen Version: `master` branch
- Laravel Version: `master` branch
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:

Laravel and Lumen differ in the way they handle the `terminate()` method in http middleware. While Laravel calls it on **both** global middleware and route middleware, Lumen does it only on global middleware, which doesn't seem correct.

Code examples:
- [Laravel on the `master` branch](https://github.com/laravel/framework/blob/c3fab4a37d84e6920f91fd78346e70184888e530/src/Illuminate/Foundation/Http/Kernel.php#L192) (combines both middleware stacks)
- [Lumen on the `master` branch](https://github.com/laravel/lumen-framework/blob/master/src/Concerns/RoutesRequests.php#L139) (uses only the global middleware stack)

I ran into that issue when trying to add `terminate()` to the auth middleware, which usually protects only a subset of routes. When looking for answers I found [this issue](https://github.com/laravel/lumen-framework/issues/1078), but the author never responded.

I will be happy to provide a PR if that is indeed a bug, not expected behavior of Lumen.

### Steps To Reproduce:

Define a middleware with `terminate()` method, attach it to a single route only and note that this method never gets called.

**Comment by driesvints** [comment]
Welcoming PR's

**Comment by borys-p** [comment]
@driesvints preparing a proper PR takes time. That's why I asked for confirmation if that is actually an issue, not a design decision.

**Comment by driesvints** [comment]
I personally suggest to use Laravel if you need that.

**Comment by borys-p** [comment]
That's not an option in our case, unfortunately. But this change can be made in a way that doesn't affect performance at all.
