### ISSUE TITLE
artisan migrate command doesn't run with mysql-schema.dump file

### ISSUE THREAD

**Issue by binarweb** [laravel/lumen-framework#1213]
- Lumen Version: 8.3.4
- Laravel Version: #.#.#
- PHP Version: 7.4.16
- Database Driver & Version:  MySQL 8.0.27

### Description:

Running the `artisan migrate` drops the required `migrations` table prior to running the actual migrations.

The problem is the `mysql-schema.dump` file. If I rename/remove this file, the migrations run ok.

### Steps To Reproduce:

1. create the migration table `artisan migrate:install`
2. create a migration

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCurrenciesTable extends Migration
{
    public function up()
    {
        Schema::create('posts', function (Blueprint $table) {
            $table->id();
            $table->string('name', 255);
            $table->string('short', 5);
        });
    }

    public function down()
    {
        Schema::dropIfExists('posts');
    }
}
```
3. run `artisan migrate`

The following error appears:

```text
Loading stored database schema: /var/www/html/blog/database/schema/mysql-schema.dump
Loaded stored database schema. (17.62ms)

In Connection.php line 712:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.migrations' doesn't exist (SQL: select `migration` from `migrations` order by `batch` asc,  
`migration` asc)                                                                                                                                                   


In Connection.php line 368:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.migrations' doesn't exist
```

**Comment by driesvints** [comment]
This isn't supported in lumen. Please use Laravel if you need this. Thanks.

**Comment by binarweb** [comment]
What is not supported in Lumen?

**Comment by driesvints** [comment]
Dumping migrations

**Comment by binarweb** [comment]
Now I see that the `mysql-schema.dump` does not exist in original [laravel/lumen](https://github.com/laravel/lumen) repo.

How did it end up in my project then?

**Comment by binarweb** [comment]
Now I see that the `mysql-schema.dump` does not exist in original [laravel/lumen](https://github.com/laravel/lumen) repo.

How did it end up in my project then?
