### ISSUE TITLE
Migration error in azure sql db

### ISSUE THREAD

**Issue by mihiranchathuranga** [laravel/lumen-framework#1215]
[previous exception] [object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to t
he value of 'NO_AUTO_CREATE_USER' at /var/www/html/vendor/illuminate/database/Connectors/MySqlConnector.php:170)
[stacktrace]
#0 /var/www/html/vendor/illuminate/database/Connectors/MySqlConnector.php(170): PDOStatement->execute()
#1 /var/www/html/vendor/illuminate/database/Connectors/MySqlConnector.php(39): Illuminate\\Database\\Connectors\\MySqlConnector->setModes()
#2 /var/www/html/vendor/illuminate/database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
#3 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#4 /var/www/html/vendor/illuminate/database/Connection.php(926): call_user_func()
#5 /var/www/html/vendor/illuminate/database/Connection.php(961): Illuminate\\Database\\Connection->getPdo()
#6 /var/www/html/vendor/illuminate/database/Connection.php(405): Illuminate\\Database\\Connection->getReadPdo()
#7 /var/www/html/vendor/illuminate/database/Connection.php(331): Illuminate\\Database\\Connection->getPdoForSelect()
#8 /var/www/html/vendor/illuminate/database/Connection.php(664): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#9 /var/www/html/vendor/illuminate/database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback()
#10 /var/www/html/vendor/illuminate/database/Connection.php(339): Illuminate\\Database\\Connection->run()
#11 /var/www/html/vendor/illuminate/database/Schema/MySqlBuilder.php(18): Illuminate\\Database\\Connection->select()
#12 /var/www/html/vendor/illuminate/database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable()
#13 /var/www/html/vendor/illuminate/database/Migrations/Migrator.php(608): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExi
sts()
#14 /var/www/html/vendor/illuminate/database/Console/Migrations/MigrateCommand.php(93): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#15 /var/www/html/vendor/illuminate/database/Console/Migrations/MigrateCommand.php(64): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prep
areDatabase()
#16 /var/www/html/vendor/illuminate/database/Migrations/Migrator.php(541): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Datab
ase\\Console\\Migrations\\{closure}()
#17 /var/www/html/vendor/illuminate/database/Console/Migrations/MigrateCommand.php(81): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#18 /var/www/html/vendor/illuminate/container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#19 /var/www/html/vendor/illuminate/container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /var/www/html/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 /var/www/html/vendor/illuminate/container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /var/www/html/vendor/illuminate/container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#23 /var/www/html/vendor/illuminate/console/Command.php(134): Illuminate\\Container\\Container->call()
#24 /var/www/html/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#25 /var/www/html/vendor/illuminate/console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#26 /var/www/html/vendor/symfony/console/Application.php(1005): Illuminate\\Console\\Command->run()
#27 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#28 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#29 /var/www/html/vendor/illuminate/console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#30 /var/www/html/vendor/laravel/lumen-framework/src/Console/Kernel.php(116): Illuminate\\Console\\Application->run()
#31 /var/www/html/artisan(35): Laravel\\Lumen\\Console\\Kernel->handle()
#32 {main}
"}

In Connection.php line 671:
                                                                                                                                                      
  SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' (SQL: select * from  
   information_schema.tables where table_schema = adrik_backend and table_name = migrations and table_type = 'BASE TABLE')                            
                                                                                                                                                      

In MySqlConnector.php line 170:
                                                                                                                                  
  SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER'

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
