### ISSUE TITLE
Mail configuration not able to set dynamically in queue job

### ISSUE THREAD

**Issue by AkshayGadekar** [laravel/lumen-framework#1216]
We are trying to send mails to thousands of recipients through queue job and SMTP credentials are dynamic based on the tenant of those recipients. So we are setting mail credentials using Config::set('mail', $smtp_params) in queue job. But when run php artisan queue:work command, only first queue job takes dynamic Config SMTP params, next jobs takes whatever was set at first queue job.
Because of this next sent emails gets sent by config set at first queue job only. How can we set mail config dynamically in queue job?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
