### ISSUE TITLE
Composer package breaks project when using recommended app()->langPath() method

### ISSUE THREAD

**Issue by halloei** [laravel/lumen-framework#1221]
- Lumen Version: 8.3.4
- Laravel Version: 8.83.1
- PHP Version: 8.1.2
- Database Driver & Version: %

### Description:
I did not yet upgrade my Laravel and Lumen projects to version 9, but I did prepare my Laravel and Lumen packages for it.  
The [upgrade guide](https://laravel.com/docs/9.x/upgrade#the-lang-directory) recommends to set the path for package language files with `app()->langPath()` instead of hard-coding it. I changed that and did now a simple `composer update` in my Lumen project (still version 8) and it broke, because its [Application class](https://github.com/laravel/lumen-framework/blob/1b05a57a038866d1db10631dc2e5e3f5491cdf09/src/Application.php) does not contain a `langPath()` method. I'm surprised version 9 of the framework doesn't either.

### Steps To Reproduce:

In your Lumen project, pull in a Laravel/Lumen package with the following service provider:

```php
class MyPackageServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        $this->publishes([__DIR__ . '/../lang' => $this->app->langPath() . "/vendor/my-package"]);
    }
}
```

**Comment by driesvints** [comment]
It's `getLanguagePath` in Lumen: https://github.com/laravel/lumen-framework/blob/1b05a57a038866d1db10631dc2e5e3f5491cdf09/src/Application.php#L605

**Comment by halloei** [comment]
I noticed that. But it's not possible to call that method since it's protected. However, if it was public, should we add a switch to our package's service providers that checks for Laravel (use `langPath()`) or Lumen (use `getLanguagePath()`)? Seems odd to me.

**Comment by driesvints** [comment]
@halloei you can send in a PR for a langPath method if you want. I didn't see the method was protected.
