### ISSUE TITLE
v9 missing schedule:* Commands

### ISSUE THREAD

**Issue by shawnnaquin** [laravel/lumen-framework#1224]
- Lumen Version: 9.0.0
- PHP Version: 8.1.2
- Database Driver & Version: mysql, 8.0.23 MySQL Community Server - GP

### Description:
issue: when I upgrade from v8 to v9 the schedule:* commands are missing.
expectation: the schedule:* commands should still exist
     
### Steps To Reproduce:
- open composer.json change v8 to v9:
        "illuminate/support": "^9",
        "laravel/lumen-framework": "^9",
- run "composer update"
- run "php artisan list | grep schedule:"
- try to run "php artisan schedule:run"

an error will occur:
  "There are no commands defined in the "schedule" namespace."

I've upgraded through many versions of lumen, and have never seen this issue. screenshot attached.

![larvel](https://user-images.githubusercontent.com/9139012/155014041-dd7258ba-a963-4d0c-b502-1f9693dcbad3.png)

**Comment by driesvints** [comment]
Thanks for reporting. I managed to figure it out and sent in a fix: https://github.com/laravel/lumen-framework/pull/1225

**Comment by shawnnaquin** [comment]
Thanks all for the quick response!
