### ISSUE TITLE
Disk [s3] does not have a configured driver

### ISSUE THREAD

**Issue by stojankukrika** [laravel/lumen-framework#1226]
- Lumen Version: 9.0.1
- PHP Version: 8.0.15

### Description:
I get this as an error when sending mail with s3 attachment "Disk [s3] does not have a configured driver".

### Steps To Reproduce:
In boostrap/app.php file I added this:
`$app->configure('filesystems');`

composer.json file have:
`"require": {
       "php": "^8.0",
        "laravel/lumen-framework": "^9.0.1",
        "vlucas/phpdotenv": "^5.4.1",
        "illuminate/mail": "^9.0",
        "league/flysystem-aws-s3-v3": "^3.0"
    },
`

filesystems.php:
`
'default' => env('FILESYSTEM_DRIVER', 's3'),
'disks' => [
        'awss3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
        ],
 ],
];
`

**Comment by driesvints** [comment]
`FILESYSTEM_DRIVER` needs to become FILESYSTEM_DISK and in your case it needs to be set to `FILESYSTEM_DISK=awss3`.

Please read the Lumen and Laravel upgrade guides:

https://lumen.laravel.com/docs/9.x/upgrade#upgrade-9.x
https://laravel.com/docs/9.x/upgrade

**Comment by stojankukrika** [comment]
Tnx @driesvints I have multiple S3 directories how to handle that?

**Comment by driesvints** [comment]
@stojankukrika best to ask that on a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
