### ISSUE TITLE
Database configuration is not perfect

### ISSUE THREAD

**Issue by lscar** [laravel/lumen-framework#1227]
- Lumen Version: 9.0.1
- PHP Version: 8.0.16

### Description:
Singleton connection will be resident in memory, it is recommended to turn on persistent connection for better performance.
So I want to configure "PDO::ATTR_PERSISTENT => true" of "mysql options" and redis is the same.Currently the above configuration cannot be achieved without changing the loading logic.

I hope to get reply and support as soon as possible, thank you！

**Comment by driesvints** [comment]
Feel free to attempt a PR if you want 👍
