### ISSUE TITLE
.env not loaded properly

### ISSUE THREAD

**Issue by vatsake** [laravel/lumen-framework#1229]
- Lumen Version: 9.x
- PHP Version: 8.0.1
- Database Driver & Version: mysql

### Description:
Sometimes the ENV is not properly loaded in production.
I get "server error", log says:
[2022-03-24 08:15:53] production.ERROR: Database hosts array is empty. (SQL: .... {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): Database hosts array is empty. (SQL: ... at ........\\api\\vendor\\illuminate\\database\\Connection.php:712)

### Steps To Reproduce:
Move config from Vendor/laravel/lumen-framework/config -> ROOT/config
In bootstrap/app conf: $app->configure('database')
and now sometimes env('') doesn't load properly

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
