### ISSUE TITLE
Form requests

### ISSUE THREAD

**Issue by Andrei-Vakulski** [laravel/lumen-framework#124]
Is there plans to add awesome Form Request from Laravel 5 to Lumen?

**Comment by GrahamCampbell** [comment]
No. You can still set them up with some ioc bindings though.

**Comment by xiphiaz** [comment]
Can someone enlighten us on how we might go about enabling Form Request for lumen? I'm building a simple REST API but would like to keep my controllers lean with typehinted request objects. It seems like an odd commission from the leaner version of laravel that seems tailored for API's

**Comment by ActuallyACat** [comment]
Sorry to comment on a closed issue, but I totally agree with @xiphiaz. Lumen is tailored to APIs, using the provided validate function in each controller works - but it's bulky. Being able to type hint requests by default would be a massive, massive help.
