### ISSUE TITLE
Service container is not deferring call of boot methods on service providers

### ISSUE THREAD

**Issue by michalkvasnicak** [laravel/lumen-framework#126]
If I register service provider in `bootstrap/app.php`, boot method is called immediately after registration and not after registration of all service providers.

Is this intended behaviour? Because if it is so, then boot method on service provider doesn't make sense and I don't have mechanism to "decorate" services and I have to register service providers in right order.

Example:

```php

// bootstrap/app.php
$app->register('QueryBusServiceProvider');
$app->register('AppServiceProvider');

// QueryBusServiceProvider.php

class QueryBusServiceProvider extends ServiceProvider
{
   public function register()
   {
      $this->app->singleton('QueryBus');
   }
}

// AppServiceProvider.php
class AppServiceProvider extends ServiceProvider
{
   public function boot()
   {
       $queryBus = $this->app->make('QueryBus');
       $queryBus->addExecutor($this->app->make('SomeService'));
   }
}
```

**Comment by silentred** [comment]
Please try `$app->register('QueryBusServiceProvider');`

**Comment by michalkvasnicak** [comment]
It doesn't work like this either. Boot is called immediately after register of service provider. https://github.com/laravel/lumen-framework/blob/5.0/src/Application.php#L230

**Comment by silentred** [comment]
You are right. Guessing providers need to be put in an array, then their register() and boot() could be invoked separately. You could pull request on this issue.

**Comment by michalkvasnicak** [comment]
Ok I will try but I need a few days.
