### ISSUE TITLE
Errors appears on logs even on fresh install

### ISSUE THREAD

**Issue by toto33331** [laravel/lumen-framework#1261]
On a fresh install of Lumen 9, after a few minutes, a new log file is created with this error:

`local.ERROR: Uncaught Error: Call to undefined function app_path() in Command line `

After correcting it by [this colution](https://stackoverflow.com/questions/61882276/how-to-call-app-path-function-in-laravel-lumen) there's a new error 

`local.ERROR: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #1 [ <required> $cachePath ]] in class Illuminate\View\Compilers\Compiler in C:\wamp64\www\lumen9\vendor\illuminate\container\Container.php:1106`

Any chance of correcting it ?

**Comment by driesvints** [comment]
I can install Lumen and run it just fine.

**Comment by CarlosGCJesus** [comment]
a

> On a fresh install of Lumen 9, after a few minutes, a new log file is created with this error:
> 
> `local.ERROR: Uncaught Error: Call to undefined function app_path() in Command line `
> 
> After correcting it by [this colution](https://stackoverflow.com/questions/61882276/how-to-call-app-path-function-in-laravel-lumen) there's a new error
> 
> `local.ERROR: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #1 [ <required> $cachePath ]] in class Illuminate\View\Compilers\Compiler in C:\wamp64\www\lumen9\vendor\illuminate\container\Container.php:1106`
> 
> Any chance of correcting it ?

Same problem... OpenAI  thinks its .env CACHE_DRIVER=array|file|... missing but nothing so far in my research:
Runnig under WSL2.0 Ubuntu20.04
"require": {
        "php": "^8.1",
        "laravel/lumen-framework": "^10.0"
}
