### ISSUE TITLE
Errors appears on logs even on fresh install

### ISSUE THREAD

**Issue by toto33331** [laravel/lumen-framework#1262]
Since my [last report](https://github.com/laravel/lumen-framework/issues/1261#issue-1471483330) has been closed without even read my words I repost it with more explanation.
Here we go again:

On a fresh install of Lumen 9, after a few minutes, a new log file is created with this error:

local.ERROR: Uncaught Error: Call to undefined function app_path() in Command line

After correcting it by [this solution](https://stackoverflow.com/questions/61882276/how-to-call-app-path-function-in-laravel-lumen) there's a new error **_(in the log file created => \storage\logs\lumen-2022-12-01.log every few minutes)_**

local.ERROR: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #1 [ <required> $cachePath ]] in class Illuminate\View\Compilers\Compiler in C:\wamp64\www\lumen9\vendor\illuminate\container\Container.php:1106

_Tested on several installs and computers_

**Comment by driesvints** [comment]
Please try a support channel. And I want to suggest to switch to Laravel as we're not actively developing Lumen anymore.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
