### ISSUE TITLE
php artisan migrate does not work when a parent directory has brackets in its name.

### ISSUE THREAD

**Issue by d3pr3x** [laravel/lumen-framework#1263]
- Lumen Version: 9.1.5
- Laravel Version: 9.0.0
- PHP Version: 8.1.2
- Database Driver & Version: MariaDB

### Description:

In Microsoft Windows, "php artisan migrate" does not work when the main directory containing the project has bracket symbols. It creates the migration table but not the rest of the tables.

### Steps To Reproduce:

Open a terminal:

```
mkdir "C:\[BUG]"
cd "C:\[BUG]"
composer create-project laravel/lumen buggy
cd buggy
composer install
```

Configure a new MySQL database in the .env file.

```
php artisan make:migration Articles
```

Add a table.

```
php artisan migrate
```

The expected result is that the table you created would be migrated to the database.
The current result is that only the "migrations" table is created.

This has been tested in 3 different machines with the same result.

Yes, I know I can put my apps in a different directory to make them work, but this caught us by  surprise. Renaming the directory does solve the problem.

**Comment by driesvints** [comment]
I suggest you switch to the laravel framework for now. Otherwise we'd appreciate a PR for this.
