### ISSUE TITLE
Console erro report

### ISSUE THREAD

**Issue by Teasercry** [laravel/lumen-framework#1268]
### Lumen Version

10.0.0

### PHP Version

8.2.4

### Database Driver & Version

Aplication

### Description

Constant error in the log stating:: 

[2023-06-21 14:09:30] local.ERROR: Uncaught Error: Call to undefined function app_path() in Command line code:1
Stack trace:
#0 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Call to undefined function app_path() in Command line code:1
Stack trace:
#0 {main}
  thrown at Command line code:1)
[stacktrace]

### Steps To Reproduce

tail -f storage/logs/lumen*.log

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
