### ISSUE TITLE
"prune-failed" not available

### ISSUE THREAD

**Issue by maclonghorn** [laravel/lumen-framework#1270]
### Lumen Version

8.0.0

### PHP Version

8.x

### Description

The following command is not available:
```
php artisan queue:prune-failed
```
The following class should be added: `PruneFailedJobsCommand`

### Steps To Reproduce

From CLI run:
```
php artisan queue:prune-failed
```

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
