### ISSUE TITLE
php artisan queue:failed-table is failing. (Affects every Illuminate\Console\MigrationGeneratorCommand).

### ISSUE THREAD

**Issue by Kudze** [laravel/lumen-framework#1273]
### Lumen Version

10.0.2

### PHP Version

8.3.0

### Description

CLI `queue:failed-table` fails to execute on (10.x). (Did not check from which version its broken)

![image](https://github.com/laravel/lumen-framework/assets/14080617/275b0f7d-c735-415c-a1f8-13a308959573)

I did some initial digging and the reason for it to not execute is because there is no `joinPaths`method in [Lumen Application class](https://github.com/laravel/lumen-framework/blob/10.x/src/Application.php). However, `joinPaths` method exists in [Laravel Application class](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Application.php).

This method is being used from [MigrationGeneratorCommand](https://github.com/illuminate/console/blob/10.x/MigrationGeneratorCommand.php#L117).

I would love an opportunity to appear in contributors list, therefore I could push pull request that resolves this issue.

By the way, the method is not mentioned in [ApplicationContract](https://github.com/illuminate/contracts/blob/master/Foundation/Application.php). Maybe it should be mentioned inside contract if its used from another composer package?

So I would just add `joinPaths` methods to [Lumen Application class](https://github.com/laravel/lumen-framework/blob/10.x/src/Application.php). (I would also update other path functions to utilise this function when merging paths like in [Laravel Application class](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Application.php))

### Steps To Reproduce

1. Create new lumen project: `composer create-project --prefer-dist laravel/lumen blog`
2. Execute the (example) cli: `php artisan queue:failed-table`

**Comment by driesvints** [comment]
We'd appreciate a PR here 👍 

> By the way, the method is not mentioned in [ApplicationContract](https://github.com/illuminate/contracts/blob/master/Foundation/Application.php). Maybe it should be mentioned inside contract if it's used from another composer package?

I don't think we should take immediate action here.

**Comment by crynobone** [comment]
Hi there,

Can you please upgrade to latest console and filesystem releases, this issue should be fixed.
