### ISSUE TITLE
Custom session driver

### ISSUE THREAD

**Issue by Kemito** [laravel/lumen-framework#134]
Creating custom session driver (memcache http://laravel.io/bin/PXXQz ! NOT memcached)
If i am trying to set session id ($app->session->setId(session_id()) and save it ($app->session->save())
It throws me an error (undefined index _sf2_meta) If i do it before SessionStart middleware it gives out that i dont have session driver set. 
So i register provider before this middlewares (my custom session driver middleware) and then it starts session BUT it keeps regenerate session id or something like that. I have set session id length to 40, same as in my php settings i use ("session.name", "laravel_sessions")
as you can see i have implemented memcache driver and it seems correct. I can dump out data in read method (dd($this->memcache->get(session_id()) and there is data but when i return data (data is serialized array) it just keeps regenerate session id. In Laravel docs there is methods which explains how to implement it. But is it even possible to share sessions? I have 1 system where it uses native PHP BUT the session data is stored in memcache. Is it some sort of bug? I just don`t understand why i can`t just return data from my driver by giving session_id() (php function) because when i dump data there is data from memcache but when it is returned there is nothing.

Sorry for messy issue. I hope you got the point. If not please feel free to ask questions to provide more information.

**Comment by GrahamCampbell** [comment]
Ask on the forums please.
