### ISSUE TITLE
Following basic example for controllers give me an error; looks dependency related.

### ISSUE THREAD

**Issue by stijlfigurant** [laravel/lumen-framework#136]
`Argument 1 passed to Laravel\Lumen\Routing\Controller::getMiddlewareForMethod() must be an instance of Illuminate\Http\Request, instance of Symfony\Component\HttpFoundation\Request given, called in [redacted]vendor\laravel\lumen-framework\src\Application.php on line 1238 and defined`

Basically following the given example: http://lumen.laravel.com/docs/controllers#basic-controllers

**Comment by stijlfigurant** [comment]
Ah, found the culprit

Used this example: http://todiadiyatmo.com/running-laravel-lumen-from-sub-directory/ to get it to display on apache, but that used the Symfony dependency. Changed it to the Illuminate one now, and it works.

Would be helpful to include above example in documentation? Scratched my head quite a bit over this :)

**Comment by GrahamCampbell** [comment]
We don't support running from a subdirectory.
