### ISSUE TITLE
Fatal error due to new methods in Illuminate Application interface

### ISSUE THREAD

**Issue by martinssipenko** [laravel/lumen-framework#137]
Following Pull Request to laravel 5.1 has raised Fatal error on lumen 5.1 https://github.com/laravel/framework/pull/9135

```
Fatal error: Class Laravel\Lumen\Application contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Foundation\Application::getCachedCompilePath, Illuminate\Contracts\Foundation\Application::getCachedServicesPath)
```

**Comment by jonathanpmartins** [comment]
Same problem here! Whats happened?

**Comment by taylorotwell** [comment]
Lumen 5.1 is no where near ready. I haven't even started accounting for the Laravel 5.1 changes.

**Comment by taylorotwell** [comment]
Lumen 5.1 will probably release later this month.

**Comment by jonathanpmartins** [comment]
@taylorotwell can I use ShouldBroadcast another way? Testing here from some new APP
