### ISSUE TITLE
How can I specify branch 5.0 in composer?

### ISSUE THREAD

**Issue by cdarken** [laravel/lumen-framework#144]
I want to install the latest version of 5.0 branch, but composer always pull the releases. How can I tell it to ignore the releases tags?

I already searched in other places for the solution, cannot find anything helpful.

**Comment by GrahamCampbell** [comment]
`5.0.*`

**Comment by cdarken** [comment]
Thank you.

**Comment by GrahamCampbell** [comment]
Don't think about it like branches. Just think, "i want 5.0.x". It doesn't matter what the branch name is. :)

**Comment by cdarken** [comment]
Actually no, it's not working, that still pulls 5.0.10 tag, it needs to be 5.0.x-dev

**Comment by GrahamCampbell** [comment]
`5.0.x-dev` is WRONG.

**Comment by GrahamCampbell** [comment]
`5.0.*@dev` will give you unreleased 5.0.x if you want that.

**Comment by cdarken** [comment]
Composer behaves a bit strange, I had 5.0 and of course it pulled 5.0.0, but after that I tried 5.0.x-dev and I got this:
```
  - Removing laravel/lumen-framework (v5.0.0)
  - Installing laravel/lumen-framework (5.0.x-dev 6016d8c)
    Downloading: 100%
```
But 5.0.*@dev work for current 5.0 branch, so thanks again. I forgot about the `@dev` notation.
