### ISSUE TITLE
Not able to send json data wit CrawlerTrait

### ISSUE THREAD

**Issue by megawubs** [laravel/lumen-framework#149]
I've just updated my app to Lumen 5.1 and started to use the crawler helpers. But it seems to be impossible to send JSON content with a post request.

This is the code I have:

```PHP
<?php
$filesystem = new \Illuminate\Filesystem\Filesystem();
$data = $filesystem->get(__DIR__ . "/postDummies/customer.json");
$headers = ['X-Signature' => md5($customer . env("API_SECRET"))];
$this->post('hooks/customer', $data, $headers);
```

whereas the test fails as it expects $data to be an array, that's internally used as the request parameters and not the content. In fact, it's completely impossible to send JSON content through this method.

Because of this, and another issue I'll report, I have to do this to get a request working:

```PHP
$filesystem = new \Illuminate\Filesystem\Filesystem();
$data = $filesystem->get(__DIR__ . "/postDummies/customer.json");
$headers = ['X-Signature' => md5($customer . env("API_SECRET"))];

$request = Request::create('/hooks/customers', 'POST', [], [], [], [], $data);
$request->headers->add($headers);
$this->response = $this->app->prepareResponse($this->app->handle($request));

$this->assertResponseStatus(201);
```

**Comment by GrahamCampbell** [comment]
You need to encode the data yourself and set the content type header.

**Comment by kidshenlong** [comment]
Having similar issues and I'm unsure how to post raw JSON when testing. Would it be possible to get an example of how you'd do this as what I have below isn't working. (I'm in Laravel 5.1 btw).
```
$this->post('/endpoint', [json_encode(['foo' => 'bar'])], ['HTTP_CONTENT_TYPE' => 'application/json']);
```

**Comment by kidshenlong** [comment]
Not to worry. Just seen that this is a pull request in the Laravel 5.1 core.
https://github.com/laravel/framework/pull/9904
