### ISSUE TITLE
What happened to templates and blade?

### ISSUE THREAD

**Issue by aaronpk** [laravel/lumen-framework#153]
I thought I was going insane because I had remembered seeing Blade templates referenced on the Lumen docs and I can't find them anymore. A quick Google search linked to this URL http://lumen.laravel.com/docs/templates which no longer exists.

**Comment by lukasgeiter** [comment]
They are still in the framework, but the site was probably removed from the docs, because it works exactly the same as in Laravel: http://laravel.com/docs/5.1/blade

**Comment by aaronpk** [comment]
I guess not seeing it on the Lumen page anymore makes me wary of using it, because I'm worried it will be removed from Lumen in the future. It would be nice to know for sure if Blade is something that is planning on sticking around for long-term support of Lumen.

**Comment by lukasgeiter** [comment]
Lumen 5.1 is a LTS version and it's still in there, so I wouldn't worry too much. Even if it were removed it won't be hard to add it back in for your app since it's just a component that has to be included and used.

**Comment by aaronpk** [comment]
okay, thanks!
