### ISSUE TITLE
Sessions only working on CookieSessionHandler

### ISSUE THREAD

**Issue by vluzrmos** [laravel/lumen-framework#157]
Any other session handlers doesn't work, I tried with Redis, File, Memcached and only works with the CookieSessionHandler. Every request generates a new session.

Steps:
All middleware enabled - ok
Servers Redis & Memcached - ok
Exts php5-memcached and php5-redis - ok
Dependencies illuminate/redis e predis/predis - ok

my route to test sessions:
```php
$app->get('session', function () use ($app) {

	$session = $app['session.store'];
	
	$key = 'totals';

	$totals = $session->get($key, 0);

	$session->set($key, ++$totals);

	return $totals;
});
```

**Comment by mamor** [comment]
see #155

you need wait to 5.1.1

or

composer.json 5.1.x-dev

**Comment by vluzrmos** [comment]
Oh, that is it, thanks! I override the method "callTerminableMiddleware" and works fine!
@mamor

**Comment by GrahamCampbell** [comment]
`5.1.x-dev` No, that's wrong. `5.1.*@dev` is what you want.
