### ISSUE TITLE
Call to undefined method Laravel\Lumen\Application::getNamespace()

### ISSUE THREAD

**Issue by MadsLundholmDk** [laravel/lumen-framework#158]
when trying to run the command php artisan make:seeder UserTableSeeder i got this error.

Stack Trace:
PHP   1. {main}() /home/vagrant/tomorrowweb/artisan:0
PHP   2. Laravel\Lumen\Console\Kernel->handle() /home/vagrant/tomorrowweb/artisan:35
PHP   3. Symfony\Component\Console\Application->run() /home/vagrant/tomorrowweb/vendor/laravel/lumen-framework/src/Console/Kernel.php:75
PHP   4. Symfony\Component\Console\Application->doRun() /home/vagrant/tomorrowweb/vendor/symfony/console/Application.php:126
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/vagrant/tomorrowweb/vendor/symfony/console/Application.php:195
PHP   6. Illuminate\Console\Command->run() /home/vagrant/tomorrowweb/vendor/symfony/console/Application.php:878
PHP   7. Symfony\Component\Console\Command\Command->run() /home/vagrant/tomorrowweb/vendor/illuminate/console/Command.php:136
PHP   8. Illuminate\Console\Command->execute() /home/vagrant/tomorrowweb/vendor/symfony/console/Command/Command.php:259
PHP   9. Illuminate\Container\Container->call() /home/vagrant/tomorrowweb/vendor/illuminate/console/Command.php:150
PHP  10. call_user_func_array:{/home/vagrant/tomorrowweb/vendor/illuminate/container/Container.php:502}() /home/vagrant/tomorrowweb/vendor/illuminate/
container/Container.php:502
PHP  11. Illuminate\Database\Console\Seeds\SeederMakeCommand->fire() /home/vagrant/tomorrowweb/vendor/illuminate/container/Container.php:502
PHP  12. Illuminate\Console\GeneratorCommand->fire() /home/vagrant/tomorrowweb/vendor/illuminate/database/Console/Seeds/SeederMakeCommand.php:60
PHP  13. Illuminate\Console\GeneratorCommand->buildClass() /home/vagrant/tomorrowweb/vendor/illuminate/console/GeneratorCommand.php:61
PHP  14. Illuminate\Console\GeneratorCommand->replaceNamespace() /home/vagrant/tomorrowweb/vendor/illuminate/console/GeneratorCommand.php:134

**Comment by GrahamCampbell** [comment]
We don't have a make command?

**Comment by MadsLundholmDk** [comment]
When i run php artisan it's list under available commands.

vagrant@homestead:~/tomorrowweb$ php artisan
Laravel Framework version Lumen (5.1.0) (Laravel Components 5.1.*)

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --env[=ENV]       The environment the command should run under.
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help                Displays help for a command
  list                Lists commands
  migrate             Run the database migrations
  serve               Serve the application on the PHP development server
 cache
  cache:clear         Flush the application cache
  cache:table         Create a migration for the cache database table
 db
  db:seed             Seed the database with records
 make
  make:migration      Create a new migration file
  make:seeder         Create a new seeder class
 migrate
  migrate:install     Create the migration repository
  migrate:refresh     Reset and re-run all migrations
  migrate:reset       Rollback all database migrations
  migrate:rollback    Rollback the last database migration
  migrate:status      Show the status of each migration
 queue
  queue:failed        List all of the failed queue jobs
  queue:failed-table  Create a migration for the failed queue jobs database table
  queue:flush         Flush all of the failed queue jobs
  queue:forget        Delete a failed queue job
  queue:listen        Listen to a given queue
  queue:restart       Restart queue worker daemons after their current job
  queue:retry         Retry a failed queue job
  queue:subscribe     Subscribe a URL to an Iron.io push queue
  queue:table         Create a migration for the queue jobs database table
  queue:work          Process the next job on a queue
 schedule
  schedule:run        Run the scheduled commands
