### ISSUE TITLE
Cannot use cache "Class cache.store does not exist"

### ISSUE THREAD

**Issue by valorin** [laravel/lumen-framework#161]
There appears to be a bug in the Cache component somewhere that prevents it from working on Lumen with the `file` and `array` drivers. (It may affect the others too, I haven't tested then.)

On a fresh install of Lumen, set `CACHE_DRIVER=file` in `.env` and run this route:

```
use Illuminate\Contracts\Cache\Repository;

$app->get('/', function (Repository $cache) use ($app) {
    return $cache->rememberForever('debug', function () {
        return mt_rand(1, 10);
    });
});
```

It should result in this:

```
ReflectionException in Container.php line 736: Class cache.store does not exist
```

I've built a test case that replicates the bug easily: https://github.com/valorin/lumen-cache-bug

```
git clone https://github.com/valorin/lumen-cache-bug
cd lumen-cache-bug/
composer install
php artisan serve
```

Then visit it in your browser, and it should be showing the error.

**Comment by Keoghan** [comment]
I had a little poke around in a fresh install of lumen and found that causing the 'cache' to be made by the `Application` class allows the snippet to work - as below:

```php
use Illuminate\Contracts\Cache\Repository;

app('cache');

$app->get('/', function (Repository $cache) use ($app) {

    dd($cache->rememberForever('debug', function () {
        return mt_rand(1, 10);
    }));
});
```

It doesn't appear that lumen is creating the singleton (and therefor loading the cache service provider) during a normal http request. 

For console - `Application::prepareForConsoleCommand()` does:
```php
        $this->make('cache');
        $this->make('queue’);
```
but this doesn't appear to happen elsewhere in the lumen code.

**Comment by GrahamCampbell** [comment]
Looks like `cache.store` is missing from the provides method of our service provider then.

**Comment by Keoghan** [comment]
Hi Graham, 

`cache.store` appears in the service provider `provides()` method. 

I think the problem is that the service provider isn't loaded until 'cache' is made - although I admit I am quite a newbie :)

```php
/**
     * Register container bindings for the application.
     *
     * @return void
     */
    protected function registerCacheBindings()
    {
        $this->singleton('cache', function () {
            return $this->loadComponent('cache', 'Illuminate\Cache\CacheServiceProvider');
        });
    }
```

**Comment by valorin** [comment]
@GrahamCampbell, Is there a reason you closed this issue? 

It definitely sounds like you've agreed that it's a bug, but I can't see a commit that fixes or, or another issue reporting it - I don't want it to be forgotten and not fixed...

**Comment by GrahamCampbell** [comment]
Sure. :)

**Comment by valorin** [comment]
Thanks @GrahamCampbell :-)

**Comment by kjareena** [comment]
Hi **GrahamCampbell**,

I am also getting same error.
![test](https://cloud.githubusercontent.com/assets/15811342/26816879/9be7acb8-4ab1-11e7-91fa-0c5afceeeddc.png)

Actually my application is 5.0.16 version. Now i upgrade my application to 5.4 
here i am getting this error pls help me.

Advanced thanks...
