### ISSUE TITLE
[5.1] Switch parameters order for seeStatusCode method

### ISSUE THREAD

**Issue by jaoued** [laravel/lumen-framework#162]
Hi,

Inside CrawlerTrait in `seeStatusCode`, the parameters past to `assertEquals` should be **switched** (expected, actual) rather than (actual, expected).

Refer to signature : 
```php
 public static function assertEquals($expected, $actual, $message = '', $delta = 0.0, $maxDepth = 10, $canonicalize = false, $ignoreCase = false)
```

Regards

**Comment by GrahamCampbell** [comment]
We're open to PRs.
