### ISSUE TITLE
Storage Filesystem doesn't work

### ISSUE THREAD

**Issue by gfazioli** [laravel/lumen-framework#168]
Hi there, I  need help! Has someone used Storage facade in Lumen? For example, `$disk = Storage::disk( 'local' );` ? I comment out `FILESYSTEM_DRIVER=local` in `.env` file and I comment out `$app->withFacades();` in `bootstrap/app.php`… but still doesn’t work for me… please help. What I'm doing wrong?       

```php
    Log::info( '#2.1 before get storage' );

    try {
      // Get disk
      $disk = Storage::disk( 'local' );
    } catch( \Exception $e ) {
      throw new \Exception( 'Unable get local storage' );
    } finally {
      Log::info( '#1.1 after get storage' );
      Log::info( [ 'e' => $e ] );
    }

    Log::info( ' #3.1 after get storage' );
```
Only the first Log is out for me… no error and  no warning… :disappointed:

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by gfazioli** [comment]
Ok, solve : `composer require "league/flysystem: ~1.0"`

**Comment by acidjazz** [comment]
after requiring that, add all of this to your bootstrap/app.php

```php
<?

$app->configure('filesystems');
class_alias('Illuminate\Support\Facades\Storage', 'Storage');  
...

$app->singleton(
    Illuminate\Contracts\Filesystem\Factory::class,
    function ($app) {
        return new Illuminate\Filesystem\FilesystemManager($app);
    }
);

**Comment by hakuno** [comment]
It also works without Facades on 5.6 version.

```
$app->singleton('filesystem', function ($container) {
    return $container->loadComponent('filesystems', 'Illuminate\Filesystem\FilesystemServiceProvider', 'filesystem');
});

$app->alias('filesystem', 'Illuminate\Filesystem\FilesystemManager');
```
So it can be resolved.

`$storage = app('filesystem');`

Thanks.

**Comment by chobitpapa** [comment]
there just register provider (5.6):

```php
$app->configure('filesystems');
class_alias('Illuminate\Support\Facades\Storage', 'Storage');
...

$app->register(Illuminate\Filesystem\FilesystemServiceProvider::class);
```
i read this [post](https://nicksilvestro.net/2016/05/28/adding-laravels-storage-facade-into-lumen/)
