### ISSUE TITLE
Eloquent compare date from datetime field

### ISSUE THREAD

**Issue by Ugluth** [laravel/lumen-framework#172]
Hello, I'm migrating a project from laravel 4.1 to a new project using lumen 5.1. Everything works fine, however I've kind of hit a wall regarding one particular query. I have a field checkin_at, which is a timestamp (in MySQL). I need to get the results that are checking in the next day. So this is what I'm using:

`Booking::whereRaw('DATE(checkin_at) = "?"', [Carbon::tomorrow()->toDateString()])->get();`

This query returns 0 rows from eloquent. The query that is actually being executed is correct, here's the sql that is being generated:

`([0] => Array ( [query] => select * from bookings where DATE(checkin_at) = "?"
[bindings] => Array
(
[0] => 2015-07-03
)
[time] => 0.24
))`

When i run this query directly in the database I get back 1 result as I should. Anyone has any idea why this is the case?

**Comment by GrahamCampbell** [comment]
Ask on the forums please.
