### ISSUE TITLE
Sub-Domain Routing (Docs Header)

### ISSUE THREAD

**Issue by TuckerWhitehouse** [laravel/lumen-framework#173]
It was mentioned in #99, but there is a sub-header on the routing docs page for "Sub-Domain Routing" which appears to be unsupported by Lumen, and there is no corresponding section in the docs.

**Comment by GrahamCampbell** [comment]
Ask on the forums please.

**Comment by catalinux** [comment]
@GrahamCampbell : whats to ask on forum? It looks to be a bug in docs http://lumen.laravel.com/docs/routing#route-group-sub-domain-routing? Where should we address that issue?

**Comment by antonybudianto** [comment]
Next time you should post issues / PR to the [related repository](http://laravel.com/docs/5.1/contributions), Here is the PR for that
[lumen doc fix](https://github.com/laravel/lumen-docs/pull/61)

**Comment by TuckerWhitehouse** [comment]
@antonybudianto thanks for the suggestion, but I didn't want to post a PR and issues are disabled on the docs repo.
