### ISSUE TITLE
Class 'Cache' not found

### ISSUE THREAD

**Issue by bradroberts** [laravel/lumen-framework#174]
I'm trying to use caching, but receive an error "Class Cache not found." I'm not sure how to troubleshoot this. Can anyone point me in the right direction?

````
<?php

namespace App\Http\Controllers;

use Cache;
use Laravel\Lumen\Routing\Controller as BaseController;

class Controller extends BaseController
{
    public function index() {

        $test = Cache::get('foo', 'bar');

        return view('index');
    }
}
````

**Comment by lukasgeiter** [comment]
Did you uncomment `$app->withFacades()` in `bootstrap/app.php`? Also please note that this is not a support forum. Github issues should only be used for bug reports.

**Comment by bradroberts** [comment]
That was it. Thank you. Sorry for posting here.
