### ISSUE TITLE
Docs Bug - Broken Link!

### ISSUE THREAD

**Issue by TuckerWhitehouse** [laravel/lumen-framework#176]
As #173 was misunderstood and ignorantly closed, I'll try again.
In the Lumen docs for routing, there is a header for "Sub-Domain Routing", which GOES NOWHERE!
There is NO SECTION for this, as it appears to be an unsupported feature at this time.
http://lumen.laravel.com/docs/routing#route-group-sub-domain-routing

**Comment by ArjanSchouten** [comment]
There is an open pull request for that: https://github.com/laravel/lumen-docs/pull/61. Let's wait for that one.

**Comment by antonybudianto** [comment]
Fixed [here](https://github.com/laravel/lumen-docs/pull/62)
