### ISSUE TITLE
Application::withFacades conflicts with pecl module Event

### ISSUE THREAD

**Issue by pa-m** [laravel/lumen-framework#184]
Hi,
when module event is installed, (with pecl install event)
php artisan crashes with message "cannot redeclare class Event"
because Application::withFacades calls 
class_alias('Illuminate\Support\Facades\Event', 'Event');

Best regards

**Comment by jaoued** [comment]
+1

**Comment by GrahamCampbell** [comment]
Just don't call with facades then.

**Comment by GrahamCampbell** [comment]
You can use facades without all the alias stuff just by calling `Facade::setFacadeApplication($app);`.

**Comment by GrahamCampbell** [comment]
Make sure `$app` is the application instance. :)
