### ISSUE TITLE
Use of PHP superglobals in Application class

### ISSUE THREAD

**Issue by AndrewCarterUK** [laravel/lumen-framework#186]
Hello,

I'm currently developing a series of packages which can be used to create FastCGI applications in PHP. FastCGI applications can stay alive between requests and gain quite serious performance increases. I've already built a couple of packages that allow you to easily convert a Symfony, Slim or Silex application into a FastCGI one - but I came across issues when I tried to do the same with Lumen.

My FastCGI packages rely on being able to provide an application with a Request object (PSR-7 or HttpFoundation) and then receiving a Response object. The use of PHP superglobals in Lumen's Application class (Application::getMethod() and Application::getPathInfo()) obviously cause problems here.

Shouldn't the HTTP method and path information be retrieved from the Request object rather than the Application class?

As far as I can see, the current approach unnecessarily limits the Application class to being able to process one Request-Response cycle per construction?

Anyway - I'd be interested to hear your thoughts are on this. I'm really keen to build a Lumen adapter to my FastCGI libraries but I can't see a clean way forward without making a messy extension to the Application class.

Regards,

Andrew

**Comment by GrahamCampbell** [comment]
If you provide a request object as the first parameter to the `dispatch` method, then we never use those super globals. :)

**Comment by AndrewCarterUK** [comment]
I was more concerned about Lumen apps using those methods.

I assumed Application::getMethod() was public but I've just realised it's protected.

Should Application::getPathInfo() be protected also to prevent apps from using them to obtain information they should retrieve from the request object?

**Comment by GrahamCampbell** [comment]
> Should Application::getPathInfo() be protected also to prevent apps from using them to obtain information they should retrieve from the request object?

Maybe, yeh. Ping @taylorotwell.

**Comment by AndrewCarterUK** [comment]
Should this be reopened whilst discussion of whether Application::getPathInfo() should be public is still ongoing?

**Comment by GrahamCampbell** [comment]
I'll make a new issue. :)

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/lumen-framework/issues/190
