### ISSUE TITLE
ResponseFactory should implement ResponseFactory interface

### ISSUE THREAD

**Issue by ifeltsweet** [laravel/lumen-framework#187]
Why isn't ResponseFactory implementing all the methods available in ResponseFactory interface?

**Comment by xiphiaz** [comment]
:+1: This is in conflict with the documentation too - see http://lumen.laravel.com/docs/responses#view-responses
If I try to do the documented call
```
return response()->view('hello', $data)->header('Content-Type', $type);
```

I get

`Call to undefined method Laravel\\Lumen\\Http\\ResponseFactory::view()`

**Comment by xiphiaz** [comment]
A clumsy workaround is
```
        return response(view('hello', $data)->render(), $statusCode, $headers);
```

**Comment by GrahamCampbell** [comment]
It can't implement that interface because we don't implement all methods from that interface.

**Comment by GrahamCampbell** [comment]
That said, we probably need a more basic interface to implement then.

**Comment by xiphiaz** [comment]
@GrahamCampbell ok, yea. At worst the documentation should be updated so the example works.

**Comment by GrahamCampbell** [comment]
Yeh. Ping @taylorotwell. Your call. :)

**Comment by ifeltsweet** [comment]
Also, why shouldn't `view` method be implemented in Lumen's ResponseFactory if view factory is already bundled with Lumen and available without extra bindings?

**Comment by aaronpk** [comment]
This is really confusing. Shouldn't at least the docs be updated to not include an example that doesn't work?

From http://lumen.laravel.com/docs/responses#view-responses:

```php
return response()->view('hello', $data)->header('Content-Type', $type);
```

...which of course fails because there is no view method.

**Comment by mallardduck** [comment]
Don't want to be 'that guy', but I just ran into similar issues.

I thought it should be noted that the docs are still incorrect and include examples that do not work. Maybe now that Laravel and Lumen 5.4 are out the docs can get updated appropriately?

**Comment by driesvints** [comment]
Documentation has been updated since.
