### ISSUE TITLE
expectEvents is trying to throw Laravel\Lumen\Testing\Exception which doesn't exist

### ISSUE THREAD

**Issue by kfirba** [laravel/lumen-framework#192]
Hello.

When I try to use the `expectEvents()` method and the event wasn't fired, the method is trying to throw a `Laravel\Lumen\Testing\Exception` exception which doesn't exist. The quick fix is to modify the method and add a `\` so it will look for the exception in the global namespace:

```php
public function expectsEvents($events)
    {
        $events = is_array($events) ? $events : func_get_args();

        $mock = Mockery::spy('Illuminate\Contracts\Events\Dispatcher');

        $mock->shouldReceive('fire')->andReturnUsing(function ($called) use (&$events) {
            foreach ($events as $key => $event) {
                if ((is_string($called) && $called === $event) ||
                    (is_string($called) && is_subclass_of($called, $event)) ||
                    (is_object($called) && $called instanceof $event)) {
                    unset($events[$key]);
                }
            }
        });

        $this->beforeApplicationDestroyed(function () use (&$events) {
            if ($events) {
                throw new \Exception(
                    'The following events were not fired: ['.implode(', ', $events).']'
                );
            }
        });

        $this->app->instance('events', $mock);

        return $this;
    }
```

**Comment by GrahamCampbell** [comment]
> The quick fix is to modify the method and add a \ so it will look for the exception in the global namespace:

Just need to import it.

**Comment by kfirba** [comment]
@GrahamCampbell Import it in my test class?

**Comment by GrahamCampbell** [comment]
I've patched this: https://github.com/laravel/lumen-framework/commit/aca59f3fa8018873b8281d1f8f6d7d01cc5a497f.

**Comment by kfirba** [comment]
@GrahamCampbell Well yea.. that's the same thing ;-)

**Comment by GrahamCampbell** [comment]
Our code style is never to prefix names with a slash. We always import.

**Comment by kfirba** [comment]
@GrahamCampbell Sure. How can I get this fixed w/o waiting for a release?

**Comment by GrahamCampbell** [comment]
Just use `5.1.*@dev` as a version constraint. :)

**Comment by kfirba** [comment]
@GrahamCampbell I see :) How long will it be until the patch will reach a stable version?

**Comment by GrahamCampbell** [comment]
Not sure. I'll ask Taylor. He's in charge. :)

**Comment by GrahamCampbell** [comment]
Expect a release in the next few minutes. :)

**Comment by kfirba** [comment]
@GrahamCampbell I see. Thanks a lot :) Was annoying seeing the tests break just for such a small mistake :hushed:

**Comment by GrahamCampbell** [comment]
Update: the release is available now. :)

**Comment by kfirba** [comment]
@GrahamCampbell Okay that was quick O_O
