### ISSUE TITLE
boot is called right after when each provider is registered

### ISSUE THREAD

**Issue by arec** [laravel/lumen-framework#194]
Should it be called when all providers are registered?

**Comment by GrahamCampbell** [comment]
Not quite. We defer things for performance in Lumen.

**Comment by GrahamCampbell** [comment]
If you need Laravel like service provider behaviour, use Laravel. :)

**Comment by arec** [comment]
http://lumen.laravel.com/docs/providers
On Lumen docs for boot, it says **This method is called after all other service providers have been registered**

The doc is misleading.

**Comment by kressaty** [comment]
Could this be causing an issue where, after registering a service provider that extends Broadcaster with a new driver, the broadcaster is somehow losing the extended driver, as if it's being loaded again or out of order?

**Comment by philbates35** [comment]
I just came across this myself, where I was expecting to be able to resolve a binding in Service Provider A that was bound in Service Provider B, but was getting an error `Target is not instantiable` error.

In the current state (like @arec pointed out), the docs are incorrect - "This method is called after all other service providers have been registered" - this isn't the case at all.

It seems either the section on the boot method needs removing from the docs , or the Laravel-like functionality is added where `boot` is only called after all service providers have been registered.
