### ISSUE TITLE
Route groups are not inheriting properties

### ISSUE THREAD

**Issue by kfirba** [laravel/lumen-framework#197]
Hello.

When we define a route something like:

```php
$app->group(['prefix' => 'v1'], function() {
    $app->get('somewhere', 'somewhereController@index');

    $app->group(['middleware' => ''my.middleware.here], function() {
        $app->get('another', 'anotherController@another');
    });
});
```

If I will try to access `/v1/somewhere` it's going to return:

```
Class somewhereController does not exist
```

It's not looking for the `App\Http\Controllers\somewhereController` but for the class name itself, means it doesn't inherit the namespace from the definition in `app.php`:

```php
$app->group(['namespace' => 'App\Http\Controllers'], function ($app) {
	require __DIR__.'/../app/Http/routes.php';
});
```

A way to go "around" this is to define the `prefix` in `app.php`:

```php
$app->group(['prefix' => 'v1', 'namespace' => 'App\Http\Controllers'], function ($app) {
	require __DIR__.'/../app/Http/routes.php';
});
```

Now I can simply get rid of the first route group and my `routes.php` file will look something like:

```php
$app->get('somewhere', 'somewhereController@index');

$app->group(['middleware' => ''my.middleware.here], function() {
    $app->get('another', 'anotherController@another');
});
```

The route `/v1/somewhere` will work as expected and hit the right controller method.

The issue now is that if I try to access `/v1/another` it will return a "not found route", now the prefix `v1` doesn't apply anymore. it's also going to look for `anotherController` and not `App\Http\Controllers\anotherController`.

To fix it, I have to re-prefix it:

```php
$app->get('somewhere', 'somewhereController@index');

$app->group(['prefix' => 'v1', 'namespace' => 'App\Http\Controllers', 'middleware' => ''my.middleware.here], function() {
    $app->get('another', 'anotherController@another');
});
```

This also applies to simply ANY route group. It completely doesn't inherit it's parent properties. A more complex example would be (Look at how nasty and how many times I have to repeat my self in order to get it working):

```php
<?php
// app.php
$app->group(['prefix' => 'v1', 'namespace' => App\Http\Controllers'], function ($app) {
	require __DIR__.'/../app/Http/routes.php';
});


// routes.php
$app->post('users', 'UsersController@store');
$app->get('confirm/{token}', 'UsersController@confirm');

$app->post('authenticate', 'UsersController@authenticate');

$app->group(['prefix' => 'v1', 'middleware' => 'my.auth'], function($app) {

    // Routes that the user has to own the
    // resource in order to access them
    $app->group(['prefix' => 'v1', 'middleware' => ['my.auth', 'user.own.resource']], function($app) {
        // profile routes
        $app->post('users/{user_id}/profiles', 'ProfilesController@store');
    });

});
```

Disgusting. If I decide to change my middleware from `my.auth` to `his.auth` then I will have to change it everywhere. Same goes for the prefix.

Do you know how can I solve this? It's getting nasty and very hard to define routes.

**Comment by efriandika** [comment]
Same issue with me... 
I hope it will be solved in next release.. :)

**Comment by efriandika** [comment]
I can fix your issues n it's working for me.

    $app->group(['prefix' => 'v1', 'namespace' => 'App\Http\Controllers'], function() {
        $app->get('somewhere', 'somewhereController@index');

        $app->group(['middleware' => 'my.middleware.here'], function() {
            $app->get('another', 'anotherController@another');
        });
    });


You have to add full name space `App\Http\Controllers` in your group

**Comment by efriandika** [comment]
I can fix your issues n it's working for me.

    $app->group(['prefix' => 'v1', 'namespace' => 'App\Http\Controllers'], function() {
        $app->get('somewhere', 'somewhereController@index');

        $app->group(['middleware' => 'my.middleware.here'], function() {
            $app->get('another', 'anotherController@another');
        });
    });


You have to add full namespace `App\Http\Controllers` in your group

But... i hope lumen developers can fix them (without writing full namespace in group routing -> like laravel) in next release.

**Comment by stevijo** [comment]
Hey ive done some work on this (basically copying some laravel code). Should at least work for middleware and namespace inheritance as tested https://github.com/laravel/lumen-framework/compare/5.1...stevijo:inheritance . Not sure if this is planned to be a feature for a upcoming version.

**Comment by GrahamCampbell** [comment]
This is intentionally omitted to keep lumen simple. It's not a planned feature, sorry.
