### ISSUE TITLE
there is no paramater() method on the resolved route instance

### ISSUE THREAD

**Issue by kfirba** [laravel/lumen-framework#198]
Hello.

In lumen the router is actually the `Application` class. The problem with this is that when we are trying to use the request object to get the a route parameter (in a middleware for example) it errors since there is no `parameter()` method:

```php
function handle($request, Closure $next)
{
    dd($request->route()); // returns an array and not an object
   
    return $next($request);
}
```

Now if we do some call like:

```php
$request->route('user_id');
```

it's actually going to try and do something like:

```php
$request->route()->parameter('user_id');
```

The problem is, as mentioned above, that the `route()` method returns an array, therefore there is no `parameter` method and we can't get the route parameters elegantly. Right now I have to dive into the array and extract the parameter. I just hope that the rules to get the parameter are absolute so the route parameters will always be accessible from:

```php
$parameters = $request->route()[2];
```

I think you either need to remove the call to `parameter` and mention that the method will return an array and not a router object or add a parameter method.

**Comment by piokom123** [comment]
@GrahamCampbell can you please explain why did you close that ticket? That problem really exists.
