### ISSUE TITLE
Laravel APP + Lumen workers

### ISSUE THREAD

**Issue by cfv1000** [laravel/lumen-framework#203]
Hello,

I want to use LUMEN as a worker for email delivery, on a separate server.

My main APP is written with Laravel:

```
\Mail::queue('template', $data, $callback);
```

```
php artisan queue:listen sqs
```
Will trigger exceptions at callback unserialization. 

Any suggestions?

Thanks

**Comment by GrahamCampbell** [comment]
Yeh, you can't serialise a closure and have a different app unserialize it.

**Comment by GrahamCampbell** [comment]
> Any suggestions?

Write a custom mailer to do what you want. I did exactly this, and actually use it in exactly the same context as you, but it's closed source, sorry.
