### ISSUE TITLE
Lumen Framework cannot seem to coexist with Laravel in same Composer project

### ISSUE THREAD

**Issue by simensen** [laravel/lumen-framework#214]
I'm working on a project that will have several web applications. I wanted to be able to have a mixture of both Laravel and Lumen applications. I also wanted to keep them all in the same repository. It seems to be working OK so far (for the one Laravel app in a subdirectory) with a few minor issues (optimizing assumes certain things in certain places, for example) but we just ran into something pretty major.

If Laravel and Lumen are installed in the same package, things from Illuminate/Foundation conflict. The first one we've seen is Support\Providers\EventServiceProvider. This conflicts because the signature of boot is different between what Laravel and Lumen expect. So even though the classes have the same name in the same namespace and in the same path, the two are apparently actually very different.

Is the intention that the Foundation / Foundation\Support stuff should be identical between Lumen and Laravel? Is there a specific reason why the code is just inline in Lumen rather than calling into one of the packages to get that stuff installed?

We may end up just creating everything as Lumen apps instead of mixing Lumen & Laravel, but that would incur some overhead right now to back out of the Laravel project. Doable, but if we could just get going with a Laravel + Lumen combo out of the box that would be much better. :)

**Comment by GrahamCampbell** [comment]
Laravel and lumen cannot be installed together. I guess it was a mistake that we forgot to actually mark the two as conflicting in composer.

**Comment by simensen** [comment]
@GrahamCampbell Thanks for the response. I'm actually kinda shocked about this. Maybe it is hinted at somewhere but it never occurred to me that you could not install both at the same time. I know I've seen several times that you can migrate from Lumen to Laravel quite easily so I guess it is easy to make the assumption that they are compatible enough with each other that they could at least coexist in the same Composer project.

Maybe this isn't the right place for this, but I'd love to learn more about the reasons behind this. I'm sure it makes sense from certain perspectives but it is quite surprising to me. Are there plans to ever merge the two or is this going to be the case for the foreseeable future?

Thanks for the quick response!

**Comment by HenkPoley** [comment]
It would be nice if Lumen Installer would set up new projects with this in composer.json

```json
    "conflict": {
        "laravel/framework": "*"
    },
```

So new Lumen developers don't accidentally install packages that remove Lumen. Makes it a more intentional decision.

Maybe also document the steps needed to migrate to Laravel. Since it's not entirely a drop-in situation out of the box.
