### ISSUE TITLE
Queue:failed and Queue:flush commands don't use the defined database drivers

### ISSUE THREAD

**Issue by ariponce** [laravel/lumen-framework#217]
I'm using Sqlite as my database driver and when i run the ```php artisan queue:flush``` and ```php artisan queue:failed``` commands i get an access denied PDO exception. 

I checked the database value that it's passed to the **DatabaseFailedJobProvider** class and i always get mysql.

On my .env file i have both **DB_CONNECTION** and **QUEUE_DRIVER** set to database.

The rest of commands (work, listen, etc) work as expectedgo.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/lumen-framework/blob/5.1/config/queue.php#L90

**Comment by GrahamCampbell** [comment]
You need to set that config.
