### ISSUE TITLE
Two classes: same class name, same namespace

### ISSUE THREAD

**Issue by s001dxp** [laravel/lumen-framework#218]
the class found here:
lumen-framework/src/Foundation/Support/Providers/EventServiceProvider.php

And the class found here:
framework/src/Illuminate/Foundation/Support/Providers/EventServiceProvider.php

Both share the same class name and namespace:
namespace Illuminate\Foundation\Support\Providers;

Shouldn't the namespace of the first class I mention be:
Foundation/Support/Providers

**Comment by GrahamCampbell** [comment]
You cannot install laravel/framework and lumen at the same time. They're not designed for that.

**Comment by crynobone** [comment]
Regardless, for what reason does this file use `Illuminate` namespace when it should be under `Laravel\Lumen` namespace? 

https://github.com/laravel/lumen-framework/blob/5.1/src/Foundation/Support/Providers/EventServiceProvider.php#L3

<https://github.com/laravel/lumen-framework/blob/5.1/composer.json#L59> doesn't autoload any `Illuminate` namespace.

**Comment by GrahamCampbell** [comment]
Yeh, I know. I've already pinged Taylor to ask him about this.
