### ISSUE TITLE
Lumen 5.1 tied to PHP >= 5.5.9 - lower to any 5.5.x please

### ISSUE THREAD

**Issue by SvenRtbg** [laravel/lumen-framework#225]
Is there a specific reason to not support the earlier versions of PHP 5.5? There is a specific travis configuration for 5.5.9, but no explanation why this is the minimum version required.

Requiring specific patch levels of PHP always has the potential of annoying people unless there are reasons - from my perspective, the last PHP version that had serious bugs making earlier versions unusable was PHP 5.3 with the patch levels 5.3.3, 5.3.9 and 5.3.23. I haven't so far encountered any libraries requiring specific patch levels of PHP 5.4 or later.

**Comment by lukasgeiter** [comment]
This has been extensively discussed on the commit itself: 8349040e7381d083868fa40bd7dcaf301f0347e3

**Comment by JoostK** [comment]
Not running the latest patch version is plain stupid, because of security issues that are present in these older versions. PHP 5.3 in itself can already be considered ancient, as support for it has been dropped some time ago.

To answer your question, PHP 5.3.9 fixed an issue with bcrypt hashes. The hashes from before PHP 5.3.9 can be considered broken.

**Comment by SvenRtbg** [comment]
@JoostK: I was referring to the 5.3 patch versions because these are the reasonable milestones for libs supporting that old version to appear as a requirement in the composer.json - not because I would want to run that old PHP.

@lukasgeiter: I cannot find that commit in the Lumen repo. You are probably referring to this: https://github.com/laravel/framework/commit/8349040e7381d083868fa40bd7dcaf301f0347e3

A valid answer to "why" would be: Lumen inherits this requirement from it's Laravel components, which will not change due to infrastructure support on Travis CI which only offers 5.5.9 explicitly.
