### ISSUE TITLE
Authorization from 5.1.11 install guide?

### ISSUE THREAD

**Issue by xiphiaz** [laravel/lumen-framework#234]
How do I install the Authorization feature added in 5.1.11? (http://laravel.com/docs/5.1/authorization) I was just about to implement my own logic then this came along! 

I've tried doing compose update, then compose require illuminate/auth directly but it doesn't seem to help. Any ideas?

**Comment by GrahamCampbell** [comment]
Yeh, it's not available for lumen yet. It'll be available within the next few days.

**Comment by GrahamCampbell** [comment]
Laravel 5.1.13 has just been released, and 5.1.13 is now tagged on all illuminate packages. You'll need to give it about 15 mins to finish, and be propagated on packagist, then you're good to go.

**Comment by xiphiaz** [comment]
@GrahamCampbell am I right in saying that Lumen's support for Authorization is limited as the traits are missing for auth? They seem to be present the laravel core, not the illuminate auth package that gets included into Lumen.

https://github.com/laravel/framework/tree/99afe79dcbe466e07dcdd1554ade3d4fc11164f0/src/Illuminate/Foundation/Auth/Access
