### ISSUE TITLE
Route parameters are URL-encoded

### ISSUE THREAD

**Issue by kAlvaro** [laravel/lumen-framework#238]
Given this code:

    $app->get('hello/{name}', function ($name) {
        return "Hello, $name!";
    });

... and loading this URL:

    http://example.com/hello/<u>café

... rendered page looks like this:

    Hello, %3Cu%3Ecaf%C3%A9!

In other words, route parameters are not URL-decoded when they reach my custom handler.

**Comment by GrahamCampbell** [comment]
That's the expected behaviour.

**Comment by kAlvaro** [comment]
Since users won't possibly expect to find URL encoding outside URL context, may I suggest it's explicitly mentioned in the [documentation](http://lumen.laravel.com/docs/routing#route-parameters), together with a brief description of the rationale behind the design decision?
