### ISSUE TITLE
Controllers can't be found inside a route group

### ISSUE THREAD

**Issue by geocine** [laravel/lumen-framework#239]
Eg. This will throw an error **Class ServicesController does not exist**

```
$app->group(['prefix' => 'v1' ], function ($app) {
    $app->get('/delete','ServicesController@remove');
});
```

To be able to fix this I must explicitly define the namespace 

```
$app->group(['prefix' => 'v1' , 'namespace' => 'App\Http\Controllers'], function ($app) {
    $app->get('/delete','ServicesController@remove');
});
```

This should not be the case because this is already defined by default on the **bootstrap\app.php**

```
$app->group(['namespace' => 'App\Http\Controllers'], function ($app) {
    require __DIR__.'/../app/Http/routes.php';
});
```

**Comment by GrahamCampbell** [comment]
Yeh, groups don't inherit in lumen, so you need to define the namespace over and over inside nested groups.

**Comment by jonvargas** [comment]
Won't this be fixed?

**Comment by IanNorris** [comment]
I also ran into this. It is not intuitive that this is the case and feels like a bug. At very least the documentation needs to be updated to mention this (if it is already mentioned, it needs mentioning again on the routes page). It is especially confusing as the namespace is set in app.php, so it isn't obvious that routes.php is actually already within a group unless you've dived a bit deeper into how things work.

**Comment by bogdanghervan** [comment]
I also feel that this needs to be better documented.

[This example here](https://lumen.laravel.com/docs/5.2/routing#route-group-namespaces) suggests that namespaces are inherited and a developer should "register controller routes without specifying the full `App\Http\Controllers` namespace prefix.", but this is not the case (at least) with the default namespace group in `bootstrap/app.php`.

I'm defining an additional group in `routes.php` for routes that should get the `auth` middleware. I could apply the middleware to the default namespace group in `bootstrap/app.php`, but that would mean all routes will require authentication and I was hoping to define that more down the road in `routes.php`.

**Comment by pashamesh** [comment]
@bogdanghervan +1

**Comment by jonwurtzler** [comment]
@bogdanghervan +1

**Comment by najib00** [comment]
@bogdanghervan +1
so the documentation not in sync with codes. here i thought that my env is broken.

**Comment by gokigoks** [comment]
What's the resolution for this? its become unintuitive

**Comment by yuloh** [comment]
@geocine looks like this was fixed, can you close this issue?
