### ISSUE TITLE
Double bindings cause extend issues

### ISSUE THREAD

**Issue by ifeltsweet** [laravel/lumen-framework#243]
The way Lumen binds singletons breaks `extend` functionality and `resolving` callbacks. In `Laravel\Lumen\Application` most core bindings are defined the following way:

    $this->singleton('view', function () {
        return $this->loadComponent('view', 'Illuminate\View\ViewServiceProvider');
    });

and inside `ViewServiceProvider` we have another:

`$this->singleton('view', function () {...`

and if inside my `ViewComposerServiceProvider` I have:

    $this->app->extend('view', function ($view) {
        $view->composer(
            'profileBar.loggedIn', 'Acme\Http\ViewComposers\ProfileBarComposer'
        );

        return $view;
    });

the extend closure will be called twice.

To fix this, in `Illuminate\Container\Container` inside `make` method  we can check if instance of this type is already managed after we `build` or `make` `$concrete`. (Yes, this check will be made for the second time in this function, but there's a good reason for this.):

    if (isset($this->instances[$abstract])) {
        return $this->instances[$abstract];
    }

Alternatively (if you think this breaks things), we can introduce `makeComponent` (name doesn't matter) method in `Laravel\Lumen\Application` for all core bindings that are bound this way. This method will not call extenders or fire callbacks for these "temporary" singletons - thus fixing the problem. We will need a map of which components are being loaded this way, which can be accomplished by using something like `singletonComponent` instead of `singleton` inside the register bindings functions.

I've tested out first and second approach locally and everything works nicely. Let me know if this is something you are willing to have and I'll submit a PR.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by taylorotwell** [comment]
It's unlikely I will devote much time to fixing this because 1) Lumen is supposed to be an opinionated micro framework and 2) i already think Lumen is way too heavy and plan to drastically shrink it for the next release back down to what I intended it to be: router and database.
