### ISSUE TITLE
PSR RequestInterface Type-Hinting in Middleware

### ISSUE THREAD

**Issue by nnnnathann** [laravel/lumen-framework#246]
Hello, first of all thank you for this library, very useful.

I'm having an issue getting psr type-hinting described [here](http://lumen.laravel.com/docs/requests#psr7-requests) to work in middleware.

Example:

```php
class MyMiddleware {
    public function handle(\Psr\Http\Message\RequestInterface $request, Closure $next) {
        echo get_class($request); // Illuminate\Http\Request
    }
}
```

My Lumen Framework package version is tied to the "5.1.*" semver.

I was assuming that middleware would provide the same type-hinting on ->handle that controllers would, is that not the case?

Thanks,
nathan

**Comment by GrahamCampbell** [comment]
Yeh, I don't think the update was ever made to Lumen. Ping @taylorotwell.

**Comment by nnnnathann** [comment]
Out of curiosity, is there a way I can just build a Psr request from the Illuminate request manually? I've done some minimal searching can't figure out where that code is.

Thanks for the quick response @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Yes, there is a way. Feel free to look at how laravel does it.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by taylorotwell** [comment]
You need to type hint it in the constructor.

**Comment by taylorotwell** [comment]
Yeah it may not have been updated yet.

**Comment by yuloh** [comment]
@nnnnathann this is fixed, can you close this issue?
