### ISSUE TITLE
[Log::info()] loged time problem.

### ISSUE THREAD

**Issue by pfdtk** [laravel/lumen-framework#251]
**e.g.**

my computer time is 9:00 (using php date() function)

but when i use 

`Log::info('some thing')`

the loged time is

`1:00`

my timezone set in php.ini is

`Asia/Chongqing`

is that a bug? or how should i do to get the correct time.

thanks!

**Comment by phanan** [comment]
Try setting `APP_TIMEZONE` In you `.env` file.

**Comment by GrahamCampbell** [comment]
I think the time is intentionally logged in UTC.
