### ISSUE TITLE
Why is the Application class returning html?

### ISSUE THREAD

**Issue by jacksierkstra** [laravel/lumen-framework#257]
I installed Lumen today and the first page I saw was the welcome page. I looked into the code and saw the method $app->welcome() is being called and returned by the standard '/' route. Then I looked into the Application class and saw the method welcome and all it does is outputting HTML. I don't really understand why you would put such a method into the Application class. Call me a nitpicker, but can somebody explain this?

**Comment by GrahamCampbell** [comment]
Please direct questions to the forums.
