### ISSUE TITLE
DB_SCHEMA needed in .env

### ISSUE THREAD

**Issue by jelkevdh** [laravel/lumen-framework#258]
I'm having multiple schema's in my Postgresql db

I need to be able to specify this schema in my .env file.
In database.php the schema entry for the pgsql driver needs to be changed to:

'schema'   => env('DB_SCHEMA', 'public'),

**Comment by GrahamCampbell** [comment]
Feel free to add this to your own app.

**Comment by jelkevdh** [comment]
But why not make this a part of lumen?
It's an integral part of the postgre setting.

**Comment by Garbee** [comment]
@jelkevdh Taylor just merged PR #363 which fixes this. If you want something, sometimes you just need to submit a PR vs open an issue. That way Taylor himself will see and address it.
