### ISSUE TITLE
 Illuminate\Database\Eloquent\Factory bug 

### ISSUE THREAD

**Issue by gambledor** [laravel/lumen-framework#261]
In my testcase when I try to create a model by factory like the following
~~~
$factory->defineAs(App\Models\Permission::class, 'create_user', function (Faker\Generator $faker) {
    return [
        'name' => "create_user ",
        'display_name' => 'user creation',
        'description' => 'She is able to create a new user',
        'created_at' => '2015-10-06 13:37:26',
        'updated_at' => '2015-10-06 13:37:26'
    ];
});
~~~
where 'name' is my primary key, the factory does not value it with the value I've assigned ('create_user') but with 0 (zero).
Here there is its dump
~~~
#attributes: array:5 [
    "name" => 0
    "display_name" => "user creation"
    "description" => "She is able to create a new user"
    "created_at" => "2015-10-06 13:37:26"
    "updated_at" => "2015-10-06 13:37:26"
  ]
~~~

**Comment by GrahamCampbell** [comment]
Can't replicate. Maybe check your casts and migrations.

**Comment by gambledor** [comment]
Even if I already did it, It has no mean to look into my migrations and I do not have any cast. Moreover I do not hit the database since I create it by make and not create.
