### ISSUE TITLE
No support for multiple middleware in a group?

### ISSUE THREAD

**Issue by FoxxMD** [laravel/lumen-framework#264]
I have routes set up like this

```php
$app->group(['middleware' => ['oauth', 'oauthUserMiddleware']], function($app) {
        $app->delete('/accounts/{id}/identities/{identId}', ['uses' => 'AccountController@deleteIdentity', 'middleware' => 'accountMiddleware']);
        $app->post('/accounts/{id}/identities', ['uses' => 'AccountController@addIdentity', 'middleware' => 'accountMiddleware']);
});
```

In the documentation for [route groups](http://lumen.laravel.com/docs/routing#route-groups) under middleware

> To assign middleware to all routes within a group, you may use the middleware key in the group attribute array. Middleware will be executed in the order you define this **array**

Which to me sounds like (and with precedent set by Laravel) I can have an array of middleware, executed in the order I set them in.

However, when I try to run these routes I get an `array to string conversion` error in this function in [`application.php`](https://github.com/laravel/lumen-framework/blob/5.1/src/Application.php#L1071)

```php
protected function mergeMiddlewareGroup($action)
{
    if (isset($this->groupAttributes['middleware'])) {
        if (isset($action['middleware'])) {
            $action['middleware'] .= '|'.$this->groupAttributes['middleware'];
        } else {
            $action['middleware'] = $this->groupAttributes['middleware'];
        }
    }

    return $action;
}
```

This reads as though I can only have **one** middleware for my group. Is the correct?

**Comment by danharper** [comment]
Just encountered this bug myself.

Looks like the code's expecting you to be using the "piped-string" style syntax e.g. `oauth|oauthUserMiddleware`.

For now, I've just switched to that.

**Comment by GrahamCampbell** [comment]
This was actually intended. Lumen's routing layer has intentionally avoided supporting this in the interest of staying simple.

**Comment by itmayziii** [comment]
@GrahamCampbell  

I have a few points on why the current solution is not staying simple and I hope this is given further consideration as a breaking API change for V6.

1. Arrays are the de facto way of describing a list of things in PHP, not a string separated by | which is ironically converted to an array anyways in the code.
2. The | separator is not mentioned in the docs.
3. Laravel itself supports an array of middleware and staying consistent is an important part of developer productivity.
