### ISSUE TITLE
PHPUnit test throwing ErrorException: Cannot redeclare class JWTAuth

### ISSUE THREAD

**Issue by cvinothkumar** [laravel/lumen-framework#276]
Getting below error, while running "phpunit" on my lumen project root folder.

There was 1 error:
ExampleTest::testBasicExample
ErrorException: Cannot redeclare class JWTAuth

..\bootstrap\app.php:29
..\tests\TestCase.php:12
..\vendor\laravel\lumen-framework\src\Testing\ApplicationTrait.php:35
..\vendor\laravel\lumen-framework\src\Testing\TestCase.php:43

**Comment by GrahamCampbell** [comment]
> JWTAuth

Unrelated to Lumen.

**Comment by catalinux** [comment]
@cvinothkumar : probably your app.php has a class_alias or something like that. The problem with TestCase is that it reloads the app object including its app.php. That means: check if class_exists before class_alias. Somehting like this:

```php
if (!class_exists('Config')) {
    class_alias(Config::class, 'Config');
}

**Comment by djordn** [comment]
@catalinux Thanks a lot!
