### ISSUE TITLE
redirect()->back()->send() won't save session

### ISSUE THREAD

**Issue by dubcanada** [laravel/lumen-framework#283]
Hello,

If you call `redirect()->back()->send()` it won't trigger the session save, you need to manually call `app('session')->save()`. The reason why I can't use just `redirect()->back()` is cause I am not in a controller.

Is there a better way to do this and have it trigger the session save or a reason why it doesn't trigger the session save?

**Comment by bkstar123** [comment]
Is there any response on this issue? I have faced the same situation

**Comment by bkstar123** [comment]
I found the answer for Laravel 5.4; you simply call like: return back()->send()->save() :-)
