### ISSUE TITLE
Documentation wrong for "boot" service provider method.

### ISSUE THREAD

**Issue by wpromatt** [laravel/lumen-framework#293]
The documentation for service providers in lumen claims that the "boot" method is called after all service providers have been called. Unless, I'm missing something, isn't the boot method called directly after the register method on each provider:

```php
// src/Application.php 277 - 278
    /**
     * Register a service provider with the application.
     *
     * @param  \Illuminate\Support\ServiceProvider|string  $provider
     * @param  array  $options
     * @param  bool   $force
     * @return \Illuminate\Support\ServiceProvider
     */
    public function register($provider, $options = [], $force = false)
    {
        if (! $provider instanceof ServiceProvider) {
            $provider = new $provider($this);
        }

        if (array_key_exists($providerName = get_class($provider), $this->loadedProviders)) {
            return;
        }

        $this->loadedProviders[$providerName] = true;

        $provider->register();
        $provider->boot();
    }
```

I'm finding many such examples of these "small" issues in the documentation.

**Comment by GrahamCampbell** [comment]
No, it is called after all have been booted. That code sample you've pasted is for when you register a service provider later on at runtime, after all others have already booted.
