### ISSUE TITLE
Lumen 5.2

### ISSUE THREAD

**Issue by xiphiaz** [laravel/lumen-framework#296]
Now Laravel 5.2.0 is released, is lumen going to update or remain on 5.1?

**Comment by crynobone** [comment]
https://github.com/laravel/lumen-framework/compare/5.1...master

**Comment by xiphiaz** [comment]
Oh right okay, so coming soon then

**Comment by GrahamCampbell** [comment]
Lumen is not getting released at the same time as Laravel.

**Comment by GrahamCampbell** [comment]
It's not ready yet. Check back in a few weeks. ;)
