### ISSUE TITLE
Middleware failures in route groups: "ErrorException in Application.php line 1102: Array to string conversion"

### ISSUE THREAD

**Issue by k98kurz** [laravel/lumen-framework#298]
> Migrated from the main laravel-framework issue tracker.

## Overview of Issue

> The documentation implies that this is supported. If it is not supported, the documentation needs to be clarified.

When nesting route groups in Lumen, the ability to pass an array of middleware to the nested group or route definition completely breaks, resulting in `ErrorException in Application.php line 1102: Array to string conversion`.

### Working code (outside of a route group):

    $app->get('/api/v0/test-role/admin', ['middleware' => ['apiauth', 'is:admin'], 'uses' => 'Controller@testApiRoleAdmin']);

### Non-working code - middleware array in route within a route group:

    $app->group(['prefix' => 'api/v0/users/{id}', 'namespace' => 'App\Http\Controllers\Api', 'middleware' => 'apiauth'], function ($app) {
        $app->patch('roles', ['middleware' => ['load:App\User', 'can:manage roles'], 'uses' => 'UserController@rolesUpdate']);

### Non-working code - middleware array in route group within a route group:

    $app->group(['prefix' => 'api/v0', 'namespace' => 'App\Http\Controllers\Api', 'middleware' => 'apiauth'], function ($app) {
        $app->group(['prefix' => '/api/v0/users/{id}', 'namespace' => 'App\Http\Controllers\Api', 'middleware' => ['apiauth', 'load:App\User']], function ($app) {

### Non-working code - single middleware string on a route within a group with middleware array:

    $app->group(['prefix' => 'api/v0/users/{id}', 'namespace' => 'App\Http\Controllers\Api', 'middleware' => ['apiauth', 'load:App\User']], function ($app) {
        $app->get('things', ['middleware' => 'can:see things', 'uses' => 'UserController@things']);

It does not matter what middleware I choose, adding an array of middleware to a nested route or group definition always fails. It also does not matter what route or group is assigned the middleware array.

## The buggy `Application.php` code that generates this error:

    protected function mergeMiddlewareGroup($action)
    {
        if (isset($this->groupAttributes['middleware'])) {
            if (isset($action['middleware'])) {
                $action['middleware'] = $this->groupAttributes['middleware'].'|'.$action['middleware'];
            } else {
                $action['middleware'] = $this->groupAttributes['middleware'];
            }
        }

        return $action;
    }

## Another strange bug worth noting

When using the following syntax, the middleware classes are suddenly no longer defined.

    $app->group(['prefix' => 'api/v0', 'namespace' => 'App\Http\Controllers\Api', 'middleware' => 'apiauth'], function ($app) {
        $app->group(['prefix' => '/api/v0/users/{id}', 'namespace' => 'App\Http\Controllers\Api', 'middleware' => 'apiauth'], function ($app) {
            $app->patch('roles', 'UserController@rolesUpdate')->middleware(['load:App\User', 'can:manage roles']);

The above results in `ReflectionException in Container.php line 737: Class load does not exist`, despite the fact that it is defined in my bootstrap/app.php file and otherwise works with routing.

    $app->routeMiddleware([ //...
        'load' => 'App\Http\Middleware\LoadResourceMiddleware',
        // ...
    ]);

**Comment by GrahamCampbell** [comment]
Thanks for reporting, but as I explained in the other issue, lumen doesn't support nested groups, and it's not a planned feature.

**Comment by k98kurz** [comment]
After further testing, I found that it is not actually a nested group bug. The bug occurs within a single group.

**Comment by GrahamCampbell** [comment]
You must pass an array to the middleware key.

**Comment by GrahamCampbell** [comment]
`'middleware' => []`

**Comment by GrahamCampbell** [comment]
rather than a string

**Comment by GrahamCampbell** [comment]
Tbh, I've not actually tested this. Please let me know if that doesn't work either.

**Comment by k98kurz** [comment]
Passing an array does not work. Example:

    $app->group(['prefix' => 'api/v0/users/{id}', 'namespace' => 'App\Http\Controllers\Api', 'middleware' => 'apiauth'], function ($app) {
        $app->patch('roles', ['middleware' => ['load:App\User', 'can:manage roles'], 'uses' => 'UserController@rolesUpdate']);

**Comment by CurosMJ** [comment]
If we pass strings to both the group definition, and the route definition, then it is working, otherwise it is not.
