### ISSUE TITLE
Catch All Routes vs Defined Routes in Lumen

### ISSUE THREAD

**Issue by kevintanjung** [laravel/lumen-framework#303]
The current version that Lumen Framework used for `nikic/fast-route` is `0.4.*` and resulting the following bug still exist on `fast-route`. 

https://github.com/nikic/FastRoute/issues/50

It has been fixed on the newer versions, and currently `nikic/fast-route` is at `v0.7.0`, any plan to update the `composer.json` dependencies?

**Comment by crynobone** [comment]
@taylorotwell @GrahamCampbell can we bump `5.2` to `v0.7.0` since it going to be released within the week.

**Comment by kevintanjung** [comment]
I'm just hoping that the `5.1` user will get the same treatment...

**Comment by crynobone** [comment]
Unlikely to happen, 5.2 already upgraded to `v0.6.0`, if they were going to go with that route it would have been bump to 5.1 already.

**Comment by GrahamCampbell** [comment]
> I'm just hoping that the 5.1 user will get the same treatment...

Only 5.2 will get it because it's breaking.
