### ISSUE TITLE
Upgrade guide for 5.1 -> 5.2 missing notice about all the testing traits being removed

### ISSUE THREAD

**Issue by xiphiaz** [laravel/lumen-framework#310]
Upgrading to 5.2 I found there was missing testing traits that I was depending on, see diff in commit https://github.com/laravel/lumen-framework/commit/b63c9525740082c68752efd4bb5aa421dda73213 which removes a lot of functionality which doesn't appear to be noted in the [upgrade guide](https://lumen.laravel.com/docs/5.2/upgrade). 
Still not sure how I can get the traits back..

**Comment by jfoliveira** [comment]
+1
I'm still trying to figure out what's the recommended approach to replace the methods previously defined on removed traits, such as:

```php
$this->seeStatusCode(...)
```
This method was part of `Testing/CrawlerTrait.php` that has been removed.

**Comment by matthew-james** [comment]
I opened a PR to update the documentation [here](https://github.com/laravel/lumen-docs/pull/80).

**Comment by xiphiaz** [comment]
@matthew-james oh thanks! I didn't realise the docs were open source, I should issue PR's rather than issues
