### ISSUE TITLE
Can't use route middleware

### ISSUE THREAD

**Issue by ricardokenji** [laravel/lumen-framework#311]
I was testing and set up ExampleMiddleware: 

boostrap/app.php
```
$app->routeMiddleware([
   'example' => 'App\Http\Middleware\ExampleMiddleware'
]);
```

and at controller
```
function __construct(){
   $this->middleware('example');
}
```

When i run i get this error:
```
ErrorException in RoutesRequests.php line 552:
Undefined variable: parameters
```

I checked line 552 and $parameters is really not defined.

If i try using middleware with route:
```
$app->get('/', ['middleware' => 'example', 'HomeController@index']);
```
I get this error:
```
ErrorException in RoutesRequests.php line 486:
Undefined variable: closure
```
I tried with 5.1 and 5.2.1

With 5.1 controller middleware works and route middleware doens't.
With 5.2.1 neither work.

**Comment by GrahamCampbell** [comment]
It was fixed in 5.2.2. Please upgrade before posting an issue.

**Comment by jfoliveira** [comment]
@GrahamCampbell packagist is still retrieving v5.2.1: https://packagist.org/packages/laravel/lumen-framework

**Comment by kirensiva** [comment]
$app->post('user/add', ['middleware' => $m1, 'uses' => 'UserController@registerUser' ]);
