### ISSUE TITLE
The option --env[=ENV] in the artisan cli is not working.

### ISSUE THREAD

**Issue by gvsrepins** [laravel/lumen-framework#312]
The option --env[=ENV] in the artisan cli is not working.

If tinker is load, try this:
``​php artisan --env=testing tinker`` 

after this: 
​``app()->environment()``

It also don't work with any other artisan command. :(

**Comment by xiphiaz** [comment]
Tinker appears to be a feature only of laravel/framework - maybe try add an issue there as as far as I know lumen doesn't support tinker?
