### ISSUE TITLE
getRoutes removed. Any alternative for 5.2?

### ISSUE THREAD

**Issue by jfoliveira** [laravel/lumen-framework#313]
[This commit](https://github.com/laravel/lumen-framework/commit/82adca8e67269498387fd0090037e6c40821ef99) removed method `getRoutes` from `Application.php`

How can I programmatically retrieve the list of routes after upgrading to Lumen 5.2?

**Comment by GrahamCampbell** [comment]
What use case did you have for this?

**Comment by mstaack** [comment]
have been using it together with: https://github.com/appzcoder/lumen-route-list

**Comment by GrahamCampbell** [comment]
Hmmm. I'm probably vote not to restore this method. Ping @taylorotwell since you deleted it. ;)

**Comment by jfoliveira** [comment]
@mstaack the mentioned package is also dependent on the `getRoutes` method, see [here](https://github.com/appzcoder/lumen-route-list/blob/1.0/src/RoutesCommand.php#L33), and is therefore unlikely to work with Lumen 5.2.

@GrahamCampbell thanks.
There is no need to restore the method as long as property `routes` in [src/Concerns/RoutesRequests](https://github.com/laravel/lumen-framework/blob/5.2/src/Concerns/RoutesRequests.php#L29) is made public.

Once this property is public one could replace `app()->getRoutes()` with direct access to `app()->routes` property.

**Comment by jfoliveira** [comment]
I sent a new [pull request](#316) bringing the method back.
Better bring the method back than turn `app()->routes` public as having the method existing code remains compatible with 5.2.
Please review the PR.
