### ISSUE TITLE
Laravel\Lumen\Routing\ValidatesRequests missing

### ISSUE THREAD

**Issue by philippzentner** [laravel/lumen-framework#314]
It seems like Laravel\Lumen\Routing\ValidatesRequests is missing but neither the upgrade guide nor the validation chapter has been updated regarding this.

**Comment by philippzentner** [comment]
I see, you packed them into ProvidesConvenienceMethods

**Comment by GrahamCampbell** [comment]
Thanks for the report. We're open to PRs to the docs to correct this if you wouldn't mind. ;)
