### ISSUE TITLE
redirect() doesn't work, Lumen 5.2

### ISSUE THREAD

**Issue by fengqi** [laravel/lumen-framework#315]
```
ReflectionException in Container.php line 736:
Class url does not exist
```

I've try to register container bind
```
$app->singleton('url', function ($app) {
    return new Laravel\Lumen\Routing\UrlGenerator($app);
});
```
then:
```
Class session.store does not exist
```

So i try it again:
```
$app->singleton('url', function ($app) {
    return new Laravel\Lumen\Routing\UrlGenerator($app);
});

$app->singleton('session', function ($app) {
    return $app->loadComponent('session', 'Illuminate\Session\SessionServiceProvider');
});

$app->singleton('session.store', function ($app) {
    return $app->loadComponent('session', 'Illuminate\Session\SessionServiceProvider', 'session.store');
});
```

So, is the solution just don't use redirect() ?

**Comment by GrahamCampbell** [comment]
Lumen doesn't support sessions.

**Comment by GrahamCampbell** [comment]
> Class session.store does not exist

Where is this error coming from anyway?

**Comment by GrahamCampbell** [comment]
> So i try it again:

You definitely shouldn't try to bind the session stuff like that.

**Comment by fengqi** [comment]
Yep. 
Redirector and redirectResponse depend session.store.

>Where is this error coming from anyway?

I use is like redirect()->route('some..')->withErrors('some..');

**Comment by GrahamCampbell** [comment]
> Redirector and redirectResponse depend session.store.

Well, either that needs to be changed to make it optional, or it need to be documented that the redirector is unavailable in lumen.

**Comment by fengqi** [comment]
Yes.

**Comment by darkwinternight** [comment]
Right now, redirects are explicitly mentioned in the documentation, yet they don't work:

https://lumen.laravel.com/docs/5.2/responses#redirects

**Comment by phuongngoc** [comment]
I confirm redirect() does not work.
Just simple route:

$app->get('/', function () use ($app) {
    return redirect('/foo');
});

**Comment by sstringer** [comment]
I can confirm redirects do not work in Lumen 5.2, too.

**Comment by mohislm** [comment]
Confirmed: redirect doesn't work in Lumen 5.2.

**Comment by lapshin1988** [comment]
Confirmed also: redirect doesn't work in Lumen 5.2.

**Comment by maxheckel** [comment]
Confirmed as well, redirect does not work.

**Comment by toocool** [comment]
:+1:

**Comment by yuloh** [comment]
@fengqi this is fixed, can you close this issue?
