### ISSUE TITLE
Conflict with Pecl Event; can't use artisan console

### ISSUE THREAD

**Issue by yuloh** [laravel/lumen-framework#321]
I have the [PECL Event](http://php.net/manual/en/class.event.php) extension installed.

Because the [`prepareForConsoleCommand`](https://github.com/laravel/lumen-framework/blob/5.2/src/Application.php#L663) calls `withFacades`, The `Event` facade is aliased as `Event`.

This results in a `Cannot redeclare class Event ` exception.

Not sure if this is something you would want to fix, but I figured I would report it in case anyone else has the same issue.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell. I think we should just remove the alias registration for all aliases tbh.

**Comment by GrahamCampbell** [comment]
Maybe add another method for registerAliases?

**Comment by acgrid** [comment]
Got same problem.
What about introducing short namespaced facade class. Using statement appending is now greatly supported in recent IDEs.

**Comment by GrahamCampbell** [comment]
@yuloh, @sinall, @acgrid I've prepared a PR that addresses this: #433. Please tell me what you think.

**Comment by acgrid** [comment]
@GrahamCampbell Thanks.
I totally agree this PR. Honestly, it brings little trouble to reference a namespaced facade in phpstorm when the automatic import `using` statement is enabled.

**Comment by GrahamCampbell** [comment]
Great. :)

**Comment by GrahamCampbell** [comment]
I'll have a chat to Taylor about this when he get's back from Holiday.
