### ISSUE TITLE
Any estimated timeline for Lumen 5.2.3?

### ISSUE THREAD

**Issue by jfoliveira** [laravel/lumen-framework#322]
When can we expect a new version including [the changes added after 5.2.2 release](https://github.com/laravel/lumen-framework/compare/v5.2.2...5.2)?

**Comment by GrahamCampbell** [comment]
It'll be released when it's ready. You can use `5.2.*@dev` or whatever for now if you need a change not yet released.

**Comment by jfoliveira** [comment]
`It'll be released when it's ready.`

Sure. Sounds like any other software in the world then.
If you could point me to doc that states the definition of done in your development process I will try my best to not ask questions that might sound too obvious.
