### ISSUE TITLE
includeDefaultCommands flag removed from Console\Kernel

### ISSUE THREAD

**Issue by yuloh** [laravel/lumen-framework#326]
The [`includeDefaultCommands`](https://github.com/laravel/lumen-framework/blob/5.1/src/Console/Kernel.php#L35) flag was removed.

I use doctrine so I registered my own `db:seed` command.  After updating to 5.2 my tests failed because they were calling the wrong command.

I'm just going to override the constructor but I figured I would report this in case it was unintentional.

**Comment by GrahamCampbell** [comment]
Thanks for the report. Laravel doesn't follow semver, so our minor releases are breaking.
