### ISSUE TITLE
Running multiple Tests

### ISSUE THREAD

**Issue by catalinux** [laravel/lumen-framework#328]
When I run more than 40 files of Tests I get this error
`Cannot use object of type Illuminate\Support\Facades\Config as array in /vendor/illuminate/database/DatabaseManager.php on line 251`

This error does not appear when I run each test one by one, or each folder one by one.

In my setUp method  I have

```
    public function setUp()
    {
        \Illuminate\Support\Facades\Facade::clearResolvedInstances();
        parent::setUp();
}
```

My ServiceProviders (that boot when the app boots) works a lot with \Config::set and \Config::get

I have `$app->withFacades();` also enabled

Is there a problem with the Config facade?

**Comment by GrahamCampbell** [comment]
Instead of using the facades, use `$this->app->config->` in your service providers.

**Comment by GrahamCampbell** [comment]
NB It's generally a bad practice to be messing with config at runtime.

**Comment by catalinux** [comment]
Ok, tx. I needed to setup the database credentials for a connection dynami from the service provider.  I'll look for other solutions
