### ISSUE TITLE
5.2 requires PHP >= 5.6.0?

### ISSUE THREAD

**Issue by PrestonStahley** [laravel/lumen-framework#329]
Upgraded a Lumen project from 5.1 to 5.2 and running on a CentOS box with php 5.5.31 throws the following error:

    PHP Fatal error:  Call to undefined function Illuminate\\Encryption\\hash_equals() in /var/www/html/scores/vendor/illuminate/encryption/BaseEncrypter.php on line 79

It looks like the native hash_equals function requires PHP >= 5.6.0.
http://php.net/manual/en/function.hash-equals.php

The Lumen 5.2 docs and composer.json both specify php 5.5.9 as the minimum version.
https://lumen.laravel.com/docs/5.2/installation#installation

Has this changed in 5.2?

**Comment by GrahamCampbell** [comment]
Only Lumen 5.3 will require php 5.6.4+. Lumen 5.2 only needs 5.5.9+, like 5.1.

**Comment by GrahamCampbell** [comment]
It is a bug that `"symfony/polyfill-php56": "~1.0",` is missing from the `lumen/lumen` default app though.

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/lumen/pull/55.

**Comment by GrahamCampbell** [comment]
Change of plan. This has been patched in the framework repo: https://github.com/laravel/lumen-framework/commit/7327e63723fcc70d2397b77da26a008788436c2c.

**Comment by GrahamCampbell** [comment]
Thanks for reporting.

**Comment by PrestonStahley** [comment]
:+1:
