### ISSUE TITLE
Lumen no longer implements the Application contract.

### ISSUE THREAD

**Issue by matthew-james** [laravel/lumen-framework#330]
I usually write my service provider closures with a type hint so that PHPStorm doesn't freak out:

```
$this->app->singleton('db', function (Application $app) {
    // do stuff.
});
```

I type hinted the Application contract so I could test the package without installing Lumen.  Since Lumen no longer implements the Application contract, the service providers broke.

I assume this change was intentional since Lumen can't implement methods like `getCachedCompilePath`.  Should I submit a PR to update the upgrade guide?

**Comment by GrahamCampbell** [comment]
> Should I submit a PR to update the upgrade guide?

Yes please.

**Comment by matthew-james** [comment]
Submitted at https://github.com/laravel/lumen-docs/pull/82.  Thanks!
