### ISSUE TITLE
lumen storage::put error

### ISSUE THREAD

**Issue by GGNB** [laravel/lumen-framework#331]
Driver [] is not supported.

**Comment by Chimit** [comment]
Have the same message after upgrade to Lumen 5.2 from 5.1. I'm using S3 driver.

**Comment by grischka** [comment]
same problem here. any updates/fixes?

**Comment by feeekkk** [comment]
Also running into this now...

**Comment by feeekkk** [comment]
Ah of course, you need to add in a copy of filesystems.php into a /config/ folder. You can pull in the one from laravel and edit it a little bit to load from your .env file

**Comment by kkomelin** [comment]
The following fixes the issue for my local file system:
```
$app = new Laravel\Lumen\Application(
    realpath(__DIR__ . '/../')
);

// Setup configuration parameters.

config([
    "filesystems" => [
        'default' => 'local',
        'disks' => [
            'local' => [
                'driver' => 'local',
                'root' => storage_path('app'),
            ],
        ],
    ],
]);
```
Source: https://laracasts.com/discuss/channels/lumen/lumen-cusom-config-not-being-picked-up/replies/149651

Of course you may use env() function to load params from .env, something like this:

```
config([
  "filesystems" => [
    'default' => 'local',
    'disks' => [
      'local' => [
        'driver' => 'local',
        'root' => storage_path(env('FILESYSTEM_FOLDER')),
      ],
    ],
  ],
]);
```
