### ISSUE TITLE
Custom config folder documentation?

### ISSUE THREAD

**Issue by TiagoMaiaL** [laravel/lumen-framework#332]
The configuration used by lumen is mainly manipulated through the .env file. But this is not the only way to get configurations working, as i saw that it's also possible to use Laravel's config folder structure. Why this option is not documented in the configuration docs?(https://lumen.laravel.com/docs/5.2/configuration#environment-configuration)

**Comment by catalinux** [comment]
Don't you have here: https://lumen.laravel.com/docs/5.2/configuration#accessing-configuration-values ?

**Comment by innerspirit** [comment]
Just a heads up, the Lumen docs don't mention config folders. I ran into this issue while googling about it.
