### ISSUE TITLE
Different Bus Provider not working

### ISSUE THREAD

**Issue by mikefrancis** [laravel/lumen-framework#334]
Trying to use a different Bus provider for my application by doing the following, as described in the [docs](https://lumen.laravel.com/docs/5.2/providers):

## bootstrap/app.php

```php
<?php

// ...

$app->register(App\Providers\AppServiceProvider::class);
$app->register(App\Providers\BusServiceProvider::class);
```

## app/Providers/BusServiceProvider.php

```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class BusServiceProvider extends ServiceProvider
{
    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind(\Illuminate\Contracts\Bus\Dispatcher::class, function ($app) {
            return new \AltThree\Bus\Dispatcher($app);
        });
    }
}
```

But whenever I try to call any methods on `AltThree\Bus\Dispatcher`, they don't exist, suggesting that the bind failed.

**Comment by GrahamCampbell** [comment]
This isn't a bug in lumen.

**Comment by GrahamCampbell** [comment]
You can';t just setup a binding like that. You MUST remove the other bus service provider and use alt-three's.

**Comment by mikefrancis** [comment]
@GrahamCampbell Ok, how would you go about doing that then? The only reference I can find to the set up of an original bus service provider is in `Application` ([link](https://github.com/laravel/lumen-framework/blob/5.2/src/Application.php#L247))

**Comment by GrahamCampbell** [comment]
You'll have to extend the application file and rebind it. Lumen isn't really built for this sort of thing.

**Comment by mikefrancis** [comment]
Ok, forgive me for being subjective, but I'm sure you can appreciate this seems a little contrived - especially when since 5.2 we can't use `dispatchFrom` or `dispatchFromArray`, but fair enough - thanks for the solution.

When you say, "Lumen isn't really built for this sort of thing." - why? Apologies if I'm missing something but it seems like a legitimate thing to swap out.

**Comment by GrahamCampbell** [comment]
Yes it is, but it's not going to be "easy" like in laravel.
