### ISSUE TITLE
lumen Model problem

### ISSUE THREAD

**Issue by GGNB** [laravel/lumen-framework#338]
I have created models in app folder like this
![qq 20160121203032](https://cloud.githubusercontent.com/assets/14269355/12480522/f395e80e-c07d-11e5-8696-f6d227a79c71.png)
In controller ,It works like this 
![qq 20160121203214](https://cloud.githubusercontent.com/assets/14269355/12480554/287f5168-c07e-11e5-8714-80c969f8f625.png)
But It doesn't work like this
![qq 20160121203233](https://cloud.githubusercontent.com/assets/14269355/12480563/37d84520-c07e-11e5-9079-56910a08fbab.png)
error
![qq 20160121203403](https://cloud.githubusercontent.com/assets/14269355/12480578/55189658-c07e-11e5-83b6-c3234dfc06c7.png)
why?

**Comment by GrahamCampbell** [comment]
Please ask on the fourms. I can can assure you this is not a bug in lumen.

**Comment by GGNB** [comment]
how to fix?
