### ISSUE TITLE
Unit Testing: Instance of Illuminate Response not returned

### ISSUE THREAD

**Issue by lukeed** [laravel/lumen-framework#340]
In accordance with the Lumen docs, running the following code:
```php
public function testExample()
{
    $response = $this->call('GET', '/api/posts');

    $this->assertEquals(200, $response->status());
}
```

...**should** "get the full `Illuminate\Http\Response` object".

Instead, `Symfony\Component\HttpFoundation\Response` is used & therefore, an "Error to undefined method Symfony\....\Response::status()" appears.

**Comment by GrahamCampbell** [comment]
> ...should "get the full Illuminate\Http\Response object".

What does your code look like that returns it?

**Comment by lukeed** [comment]
^^ Above is the test.

PostContoller@index:
```php
public function index()
{
    $posts = Post::with(['author', 'category']);
    return $this->showCollection($posts);
}
```

ApiController:
```php
public function showCollection($collection, $transformer = null)
{
    $items = $collection->paginate($this->limit);
    $transformer = $transformer ?: $this->transformer;

    return $this->respondWithPagination($items, [
        'data' => $transformer->transformCollection($items->all()),
    ]);
}
```

`respondWithPagination` just merges a dry paginattion data array into the response. Then passes everything through the `response()` helper.

Nothing fancy.

**Comment by lukeed** [comment]
I've even pulled in `use Illuminate\Http\Response;` directly to return status codes by name.

**Comment by lukeed** [comment]
@GrahamCampbell Far simpler examples:

```php
$app->get('/', function () {
	return response(['hello' => 'its me']);
});

$app->get('/', function () {
	return 'hello?'
});
```

Test pointing at the updated endpoint.

Both return instances of `Symfony\Component\HttpFoundation\Response`

**Comment by GrahamCampbell** [comment]
Something wrong must be happening in `respondWithPagination`.

**Comment by lukeed** [comment]
I knew you'd suggest that :wink:, hence simpler examples above :point_up:

**Comment by GrahamCampbell** [comment]
I don't see how that's possible.

https://github.com/laravel/lumen-framework/blob/5.2/src/Http/ResponseFactory.php#L21

What middlewares do you have?

**Comment by GrahamCampbell** [comment]
Is this happening on a fresh lumen 5.2 install?

**Comment by lukeed** [comment]
Ahh, thanks! 

Yes, it was *nearly* fresh install of 5.2. Aside from stubbing out some routes a few days ago, I installed [Clockwork](https://github.com/itsgoingd/clockwork), which does implement a middleware.
