### ISSUE TITLE
I have some question about VerifyCsrfToken

### ISSUE THREAD

**Issue by xcerx** [laravel/lumen-framework#345]
i use laravel with angular. when angular request by POST, My application always crash because it cannot to decrypt header "X-XSRF-TOKEN"

```
if (! $token && $header = $request->header('X-XSRF-TOKEN')) {
    $token = $this->encrypter->decrypt($header);
}
```

I have no idea how to fix it.

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums.
