### ISSUE TITLE
Question : How to integrate Mail Component?

### ISSUE THREAD

**Issue by atapatel** [laravel/lumen-framework#346]
in lumen 5.2, i have required illuminate/mail component  but still it is not working. is there any major changes regarding it?

**Comment by catalinux** [comment]
Did you configure it?   I see that there were some changes also in laravel 5.2 (The pretend mail configuration option has been removed. Instead, use the log mail driver, which performs the same function as pretend and logs even more information about the mail message.) https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0
