### ISSUE TITLE
[Lumen 5.1] Can't inject DatabaseManager into a Controller 

### ISSUE THREAD

**Issue by nguyentienlong** [laravel/lumen-framework#350]
Works well with Laravel 5.1
```
<?php

namespace App\Http\Controllers;

use Illuminate\Database\DatabaseManager;

class SandboxController extends Controller
{

    /**
     * [$db description]
     * @var DatabaseManager
     */
    protected $db;

    public function __construct(DatabaseManager $db)
    {
        $this->db = $db;
    }

    public function index()
    {
        dd($this->db);
    }
}
```

but with Lumen 5.1
I had this error
```
Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Database\DatabaseManager
```

I think there is no consistent between Lumen and Laravel in database binding.

L5 https://github.com/laravel/framework/blob/5.2/src%2FIlluminate%2FFoundation%2FApplication.php#L1038
```
'db'                   => ['Illuminate\Database\DatabaseManager'],
```
Lumen 5 https://github.com/laravel/lumen-framework/blob/master/src/Application.php#L761
```
 'db' => 'registerDatabaseBindings',
```
I don't know what is the purpose of this different.

**Comment by nguyentienlong** [comment]
There is work around solution for this here https://github.com/laravel/lumen-framework/issues/51

**Comment by nguyentienlong** [comment]
I don't know why you close this issue without an explaination @GrahamCampbell . Is it violate some rule or unresolvable ?

**Comment by maximebeaudoin** [comment]
@nguyentienlong You need to register the alias manually. You can do it in `boostrap/app.php`

In your Laravel reference `'db' => ['Illuminate\Database\DatabaseManager']` doing exactly this.

In your Lumen reference ` 'db' => 'registerDatabaseBindings'` is for resolution binding to load the component via the service provider, this is not a alias binding.

I think the `db` should be register here https://github.com/laravel/lumen-framework/blob/master/src/Application.php#L720
