### ISSUE TITLE
Behat not working on 5.2

### ISSUE THREAD

**Issue by pmartelletti** [laravel/lumen-framework#359]
@taylorotwell On version 5.2, after `Application` stopped implementing `HttpKernelInterface`, it's no longer possible to run Behat as the `Symfony\Component\HttpKernel\Client' class used in `Behat\Mink\Driver\BrowserKitDriver` is expecting as first parameter, a `HttpKernelInterface` instead of `Application`.

Why did Application stopped implementing this interface? As there is nothing about that in [here](https://lumen.laravel.com/docs/5.2/upgrade), just about the contract interface.

Any ideas of how I could solve this issue? Thanks.

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums.
