### ISSUE TITLE
Session middleware now broken?

### ISSUE THREAD

**Issue by carbontwelve** [laravel/lumen-framework#361]
Has using the `Illuminate\Session\Middleware\StartSession` middleware been disabled? Attempting to use results in the following:

```
BindingResolutionException in Container.php line 839:
Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\Manager
```

I guess sessions are now no longer supported in lumen as of 5.2, hurrah for breaking changes. It would be useful to have documentation of what is not available in lumen compared to what was available before.

**Comment by adrian7** [comment]
@carbontwelve I am having the same issue. Is the StartSession middleware really not usable any more?

**Comment by carbontwelve** [comment]
@adrian7 they removed sessions and views from Lumen. Apparently lumen is no longer a micro-framework like Slim or Silex but rather something that is tightly focused on developing stateless web api's.

If you are using it to write an API, you should look at passing using the Bearer scheme with the `Authorization` header with something like [JWT](https://jwt.io/introduction/) to keep a users session between requests.

**Comment by maojindao55** [comment]
@carbontwelve  I am having the same issue, too! but i use captcha which is depend on session. how can captcha works?
