### ISSUE TITLE
Change $app variable of Support Manager

### ISSUE THREAD

**Issue by sasin91** [laravel/lumen-framework#364]
Hello, this is more of a bug report with a solution than an issue, please move or delete if found inappropriate. 

I noticed the Manager called when trying to use Session thru Http\Request, is Illuminate\Support\Manager.

This manager requests \Illuminate\Foundation\Application where in Lumen (afaic), App is Laravel\Lumen\Application

Changing it manually, works :)

Best regards

**Comment by GrahamCampbell** [comment]
> This manager requests \Illuminate\Foundation\Application where in Lumen (afaic), App is Laravel\Lumen\Application

There is no typehint there.
