### ISSUE TITLE
[ReflectionException] Class path.database does not exist

### ISSUE THREAD

**Issue by latelatelate** [laravel/lumen-framework#370]
Sorry in advance if this a baum issue rather than lumen, but when trying to run:

`php artisan baum:install MODEL`

after installing [etrepat/baum](https://github.com/etrepat/baum), this error is thrown:

`[ReflectionException] Class path.database does not exist`

**Comment by GrahamCampbell** [comment]
Please report this to the package maintainer.

**Comment by GrahamCampbell** [comment]
They are making bad assumptions.

**Comment by latelatelate** [comment]
Thanks for the quick response, sorry for posting here, will do
