### ISSUE TITLE
Results are duplicated by column numbers

### ISSUE THREAD

**Issue by plcosta** [laravel/lumen-framework#375]
Hi there!

 I am build a simple query using Eloquent. I have the following action in my controller:

```php
  public function index()
  {
    $beds = Bed::all();
    return response()->json($beds);
  }
```

This is the json result:

```
[
  {
	"0": 2,
	"1": 2000001,
	"2": 3,
	"3": "2016-02-02 21:43:58",
	"4": "2016-02-02 21:43:58",
	"id": 2,
	"bed_id": 2000001,
	"status_id": 3,
	"created_at": "2016-02-02 21:43:58",
	"updated_at": "2016-02-02 21:43:58"
  },
  {
	"0": 3,
	"1": 2000002,
	"2": 4,
	"3": "2016-02-02 21:43:58",
	"4": "2016-02-02 21:43:58",
	"id": 3,
	"bed_id": 2000002,
	"status_id": 4,
	"created_at": "2016-02-02 21:43:58",
	"updated_at": "2016-02-02 21:43:58"
  }
]
```
The problem is not directly in this query, but any response has duplicates columns (as numbers). 

Any thoughts?

**Comment by GrahamCampbell** [comment]
no bug

**Comment by GrahamCampbell** [comment]
you actually have two rows

**Comment by Garbee** [comment]
Can you provide a minimal sample that reproduces the error? I'm not seeing this happen here.

Graham, the problem isn't two results. It is the results each have columns and then a copy on the data as numeric properties.

**Comment by plcosta** [comment]
@Garbee Please take a look at: https://gist.github.com/plcosta/d3586ed721b6022906a7

@GrahamCampbell like Garbee said, the problem isn't two results. It is the results each have columns and then a copy on the data as numeric properties. The problem is not directly in this query, but any response has duplicates columns (as numbers).

![lumen-duplicate](https://cloud.githubusercontent.com/assets/1139813/13488874/8c46a8fa-e102-11e5-81b6-db0ff04d679d.png)

Can you reopen this issue?

**Comment by GrahamCampbell** [comment]
Please open the issue on laravel since eloquent has nothing to do with lumen.

**Comment by plcosta** [comment]
@GrahamCampbell it occurs with Lumen and Eloquent only. But with Laravel and Eloquent have no problem. I'll try there.

**Comment by plcosta** [comment]
I tested now and the problem persists without Eloquent.

**Comment by Garbee** [comment]
I'm unable to replicate the issue here. Perhaps there is something going on in your configuration causing this.

Without a vagrant box or docker container to run that replicates the issue, it appears nothing is wrong in the framework.

**Comment by plcosta** [comment]
@Garbee Thanks! I'll test.

**Comment by plcosta** [comment]
@Garbee @GrahamCampbell This problem occurs when I use two database connections. I created a config directory in my project and add the file config/database.php with two connections. When I remove that, works fine.

**Comment by plcosta** [comment]
Finally the problem was solved. 

When the database.php file is created, you need to add the fetch param, like this:

```
<?php

return [

    'fetch' => PDO::FETCH_CLASS,
...
]
```

**Comment by Garbee** [comment]
@plcosta The fetch parameter is already [set to that by default](https://github.com/laravel/lumen-framework/blob/5.2/config/database.php#L16). I would be surprised if that is the actual cause of the issue.

**Comment by plcosta** [comment]
@Garbee Apparently, when you create the database.php file, the default file is overwritten. So, you need to copy the entire file. 
Please, make a test. Create a config directory in your project and add the file config/database.php without the fetch parameter.

**Comment by MrigKush** [comment]
I am also facing same issue.
but thanks to @plcosta for his solution.
Issue Resolved

**Comment by gokigoks** [comment]
@plcosta thanks alot brother! saved us a few hours of digging.

**Comment by PrinceDavis** [comment]
thanks bro @plcosta

**Comment by CammoKing** [comment]
Very helpful, thank you so much!

**Comment by drcarino** [comment]
just use 
$rows = $pdo->fetchAll(\PDO::FETCH_ASSOC);
