### ISSUE TITLE
Lumen loading laravel/framework as Composer dependencies

### ISSUE THREAD

**Issue by kevintanjung** [laravel/lumen-framework#378]
Is it the intended behavior that when `laravel/lumen-framework` requiring Illuminate submodules (`illuminate/auth`, `illuminate/broadcast`, etc.), it will install the `laravel/framework` into the `vendor` folder?

I thought that the idea behind sub-splitting each of the Illuminate submodules is when for example a package or library requiring the Illuminate submodules that it will only retrieve the Illuminate submodules instead of the whole `laravel/framework` library.

I am using the `5.2.*` release.
<img width="730" alt="screen shot 2016-03-10 at 2 14 32 am" src="https://cloud.githubusercontent.com/assets/3804463/13647292/fe39e270-e665-11e5-8198-7ea26e6c2681.png">

**Comment by GrahamCampbell** [comment]
No, this is a bug in benconstable/phpspec-laravel.

**Comment by GrahamCampbell** [comment]
It requires all of laravel for no reason: https://github.com/BenConstable/phpspec-laravel/blob/master/composer.json#L17.

**Comment by kevintanjung** [comment]
Ah, I see, thanks a lot, didn't see that one.
