### ISSUE TITLE
Undefined variable: closure for callable route callbacks.

### ISSUE THREAD

**Issue by matthew-james** [laravel/lumen-framework#379]
If you try to use a callable as a route callback instead of a closure or the 'Class@method' syntax, an undefined variable error results.

Example test:

```php
public function testCallableDispatching()
    {        
        $app = new Application;
        $controller = new LumenTestController(new LumenTestService());
        $app->get('/show/{id}', [$controller, 'show']);

        $response = $app->handle(Request::create('/show/25', 'GET'));

        $this->assertEquals(200, $response->getStatusCode());
        $this->assertEquals('25', $response->getContent());
    }
```

It's caused by [this line](https://github.com/laravel/lumen-framework/blob/5.2/src/Concerns/RoutesRequests.php#L501).

I assume callbacks aren't supported so should we throw an exception instead?

**Comment by GrahamCampbell** [comment]
You passed an invalid parameter through. The phpdoc say only closures please.

**Comment by matthew-james** [comment]
The phpdoc just says [mixed](https://github.com/laravel/lumen-framework/blob/5.2/src/Concerns/RoutesRequests.php#L104).  It isn't in the documentation that you *have* to use a closure or the Class@method syntax either.

**Comment by GrahamCampbell** [comment]
Looks like a derp in our phpdoc then. `mixed` should be avoided at all costs.
