### ISSUE TITLE
Commands are missing, why ?

### ISSUE THREAD

**Issue by nnnikolay** [laravel/lumen-framework#384]
Hi, I've few small questions: 

- Why Lumen does not have commands at all ?
- Why Lumen does not have non-queued Jobs ?
- Why Lumen does not have nonself-handled Jobs ?

P.S.: I understand that you point that framework for microservices, but what's the reason, not having all (or any)  of previously mentioned features ? 

It would be just nice to know, what to do, if you need it.

Thanks.

**Comment by GrahamCampbell** [comment]
It should be trivial for you to add it to your app, as with everything else from laravel.

**Comment by GrahamCampbell** [comment]
> Why Lumen does not have nonself-handled Jobs ?

Laravel had them removed too.

**Comment by GrahamCampbell** [comment]
If you want to use the fully powered bus from Laravel 5.1, with the new stuff from 5.2 added into it to, check out github.com/AltThree/Bus.

**Comment by nnnikolay** [comment]
> Laravel had them removed too

Yeah, but why ? :) what the point ? Just curious to know.

> It should be trivial for you to add it to your app, as with everything else from laravel

Sometimes it's so far from reality :) But in that particular case I don't need to add anything.
`app(Dispatcher::class)->dispatchNow(new SuperJob)`
