### ISSUE TITLE
Lumen testing. UploadedFile validation failed

### ISSUE THREAD

**Issue by koliesnik** [laravel/lumen-framework#398]
In my controller's action to upload file I have a validation rule`['file' => 'image']`;
I create a test UploadedFile instace like this:
`$uploadedFile = new UploadedFile(base_path(self::UPLOAD_PATH), $name, $mimeType, null, null, true);`
As you can see, the 6th parameter (**$test**) is true, it's required for testing. But, during tests, when the `$uploadedFile` come to Validator, parameter **$test** is **false** and the rest of the instance is the same as was created.
Is there's another way to test file uploading? Or how can I fix this?

**Comment by don-bartolome-engrade** [comment]
I had the same issue, and it end up being because I was using `Symfony\Component\HttpFoundation\File\UploadedFile` instead of `Illuminate\Http\UploadedFile`

**Comment by mnabialek** [comment]
Yes, you need to use `Illuminate\Http\UploadedFile` now instead of `Symfony\Component\HttpFoundation\File\UploadedFile` to make it work. For details look at http://stackoverflow.com/questions/36857800/laravel-5-2-testing-uploadedfile-misses-the-test-value-after-post-bug

**Comment by koliesnik** [comment]
Thanks! It helps to me.
