### ISSUE TITLE
Validation doesn't work for PATCH

### ISSUE THREAD

**Issue by Ryuske** [laravel/lumen-framework#401]
Validation doesn't work at all if the HTTP method is PATCH. Originally I thought it was a Dingo API issue, but then I tested with just Lumen and it still had the same results.

I am using Lumen version 5.2.6.

So, I have a route for updating a resource, and I am using `$app->patch()` in my routes file. And then in my controller I am using `$this->validate($request, $rules)`. The problem is, no matter what input I supply to the route, I always get a 422 Unprocessable Entity. Even if the validation passes. So that is the first problem.

The 2nd problem is that when I do get the 422 status, AND the validation should actually fail, I don't get any error messages or anything. I get an empty response. I've followed along `dd()`'ing and ValidationException is getting the errors properly, and everything seems to right, except the response is still empty.

If all I do is change the code in the routes file from `$app->patch` to `$app->post` and change the method in Postman, everything works as expected. I haven't tested any other HTTP methods. I can provide more specific code if necessary, but my specific code doesn't really matter, I've tried at least a dozen different variations to validate the input, and they all performed the same way. 

Let me know if you need anything else, or if I need to clarify anything. Thanks!

**Comment by yuloh** [comment]
Hi @Ryuske,

I wrote some tests to check if this is a bug and it seems to work correctly.  You can view the tests [here](https://github.com/laravel/lumen-framework/compare/5.2...yuloh:test-patch-validation-works).

I'm guessing you are sending a JSON body.  Are you sure you are sending the `application/json` header with your request?  The JSON body will not be parsed if you don't send a json content type, so the validation will fail resulting in a 422 status code.

You can set the content type in postman like this:

![postman-content-type](https://cloud.githubusercontent.com/assets/9440455/14861835/dd049f68-0c7c-11e6-9cc9-97ed06d29e95.png)

If you aren't sending a JSON request body, add some details of what request you are sending.

**Comment by jlaswell** [comment]
I'm also curious if this has anything to do with [form method spoofing](https://laravel.com/docs/master/routing#form-method-spoofing) bleeding over. That may be a big stretch though, but would probably be worth taking a quick look at.

**Comment by Ryuske** [comment]
I am pretty sure it was related to not sending application/json, but Lumen was too much of a pain for and missing too much of the functionality I wanted. So I switched to using Laravel and everything worked fine.
