### ISSUE TITLE
Request for Routes list command

### ISSUE THREAD

**Issue by sohelamin** [laravel/lumen-framework#411]
Hi @taylorotwell,

Thanks for keep creating such the amazing stuffs.

In lumen, Most of us badly need the **php artisan route:list** command same as laravel.
I was also built a [package](https://github.com/appzcoder/lumen-route-list) for this. 
My question is, Should not we implement this in the core?
It might be helpful for us.

Regards,
Sohel Amin

**Comment by GrahamCampbell** [comment]
Sorry, lumen is intentionally light. Feel free to keep using the package of course.
