### ISSUE TITLE
Target [Illuminate\Contracts\Validation\Factory] is not instantiable.

### ISSUE THREAD

**Issue by RubenWalraevens** [laravel/lumen-framework#412]
We want to inject the Factory in our controller (Like below). This works in laravel, but not for Lumen:
![image](https://cloud.githubusercontent.com/assets/12528648/15258906/5f23581c-194e-11e6-890a-b09c68ab969d.png)

The only thing we can do in Lumen is:
```sh
app('validator') // Which is returning an instance of the validator.
```
But as far as I can see they are in laravel and lumen the same.

Also, when you go further in the controller logic of Lumen, you see that we actually use the contract:
![image](https://cloud.githubusercontent.com/assets/12528648/15258936/9e9e4d80-194e-11e6-906d-4a9fd51b05b2.png)

**Comment by Garbee** [comment]
I think the bound resolution is left out to be as fast as possible.

On the note of:
> Also, when you go further in the controller logic of Lumen, you see that we actually use the contract:

This isn't the case at all. The return documentation is simply saying we are returning *something* of that interface. It is not affecting anything at runtime, it is just there for the developer. It is returning whatever is bound to that contract to the internal registry.

**Comment by Garbee** [comment]
Ah, just checked the [documentation](https://lumen.laravel.com/docs/5.2/container)....

> To resolve things out of the container, you may either type-hint the dependency you need on a class that is already automatically resolved by the container, such as a route Closure, controller constructor, controller method, middleware, event listener, or queued job.

So, either the docs need updating or this functionality is broken.

**Comment by RubenWalraevens** [comment]
Yeah, that part of the app('validator') that is returning an instance of the contract is wrong indeed. Nevermind on that.

But the fact that the functionallity is probably broken is another case.

**Comment by mallinus** [comment]
BindingResolutionException in Container.php line 752:
Target [Illuminate\Database\ConnectionInterface] is not instantiable while building [Ichtus\OAuth2\OAuth2Manager].

I'm getting the same exception here but for different contract type hint.
