### ISSUE TITLE
Perfomance downgrade

### ISSUE THREAD

**Issue by nnnikolay** [laravel/lumen-framework#413]
I've found significant performance downgrade after updating my dependencies, where illuminate components been updated from 5.2.28 to 5.2.31 version number. Changes are really huge up to 18%. 

I compared my code with and without changes and blackfire shows me that
<img width="213" alt="screenshot 2016-05-16 09 04 52" src="https://cloud.githubusercontent.com/assets/11268878/15282705/4a0f3bc8-1b45-11e6-97b9-bf3b86feb77e.png">

On the same code only three "nodes" are different, and each of them is a closure in Pipeline.php

**Comment by GrahamCampbell** [comment]
Your screenshot is poor quality it's impossible to read it.

**Comment by nnnikolay** [comment]
The main point of it is to show the difference in general. What part of it you'd like to read? 
<img width="506" alt="screenshot 2016-05-16 09 37 30" src="https://cloud.githubusercontent.com/assets/11268878/15295949/6a46c020-1b93-11e6-9d4f-8c370576bc70.png">

**Comment by nnnikolay** [comment]
Hi, for a few last days we've made a lot of testing, and we can confirm that 5.2.31 components compare with 5.2.28 has performance downgrade. Unfortunately we still can not figure out what exactly why produce it, but blackfire shows us that the difference between two branches only in Pipeline.php (see above). Master branch we have illuminate components version 5.2.28, and branch Dev we have 5.2.31. On production, staging and local servers Dev works way slower. If we will take composer.lock from Master and put it into Dev performance the same.

To confirm/refuse my suspects I want to ask you, what it the easiest way to install lumen with different set of components?

**Comment by nnnikolay** [comment]
Interesting news, with version 5.2.32 perfomance issue fixed 👍

**Comment by GrahamCampbell** [comment]
Great. ;)
