### ISSUE TITLE
redis:unserialize(): Error at offset 0 of 4632 bytes

### ISSUE THREAD

**Issue by starit** [laravel/lumen-framework#415]
How can I get unserilize data by using Cache?
Cache::get() will get a string from redis then unserialize() it.  I don't need unserialize

**Comment by starit** [comment]
I forgot to say that the cache driver is redis.

**Comment by GrahamCampbell** [comment]
Laravel only supports reading it's own cached data from the cache. You can't read unserialized data from something else.
