### ISSUE TITLE
Lumen 5.2 is always in production mode

### ISSUE THREAD

**Issue by codercms** [laravel/lumen-framework#417]
I have a problem with lumen's exception debug output. I have enabled debug mode, but it doesn't seem to work properly.

My config/app.php:
```php
<?php
return [
    'env' => 'local',
    'debug' => true,
    'key' => env('APP_KEY', 'SomeRandomString!!!'),
    'cipher' => 'AES-256-CBC',
    'locale' => env('APP_LOCALE', 'en'),
    'fallback_locale' => env('APP_FALLBACK_LOCALE', 'en'),
];
```
In bootstrap/app.php i have:

```php
$app->configure('app');
```

So, i checked - the config file is loaded succesfully.
But when my app throwing an exception lumen just output - "Whoops, looks like something went wrong."
There is no any debug info. Also when i use `php artisan migrate` i see - "Application In Production!" notice.
What's the problem?

P.S i don't want to use .env config file.

**Comment by JKair** [comment]
In `vendor/laravel/lumen-framework/src/Application.php line 134`
you must use .env to change the env

**Comment by codercms** [comment]
@JKair thanks for the answer.

**Comment by hakuno** [comment]
@codercms What did you do? It's not good to change the framework itself.

**Comment by rojonunoo** [comment]
awesome this fixed my problem too ..
