### ISSUE TITLE
[5.1] Filled validation rule missing in implicitRules.

### ISSUE THREAD

**Issue by AlexCW** [laravel/lumen-framework#418]
I am working on an application that uses Lumen 5.1. As part of an update endpoint on the API I needed to use the 'filled' validation rule. Although not documented in the 5.1 docs the function is present in the Validator class, however it does not work. The reason being, 'Filled' is missing from the implicitRules array in the class. I have noticed that this has since been on Lumen 5.2, due to Illuminate\Validation 5.2 however I am unable to upgrade right now.

As an alternative solution I have used the addImplicitExtension() method to add 'Filled' to the array, but this is not the cleanest solution especially when using the ValidatesRequests trait in the controllers.

Would there be any possibility of adding this rule to the array in Illuminate\Validation 5.1?

Thanks.

**Comment by GrahamCampbell** [comment]
No, sorry.
