### ISSUE TITLE
Unable to install defuse/php-encryption v2.0 due to constraint on paragonie/random_compat

### ISSUE THREAD

**Issue by nogrp** [laravel/lumen-framework#419]
Lumen requires `"paragonie/random_compat": "~1.1" ` and [defuse/php-encryption](https://github.com/defuse/php-encryption) version 2.x requires `"paragonie/random_compat": "~2.0"`.

Fix is to upgrade `laravel/lumen-framework`  to use `"paragonie/random_compat": "~2.0"`.

I cloned latest `laravel/lumen-framework` and changed the version constraint, all unit tests pass but the problem is that I've no idea if they cover anything related to `"paragonie/random_compat"` (reason being that I've to use the framework so I couldn't devote time to digging through code and tests).

I'm reporting the issue if any other people stumble upon this problem until it gets resolved.

Cheers and have a nice day :)

**Comment by GrahamCampbell** [comment]
Thanks, we're aware of this issue, but can't do anything until symfony budge.

**Comment by GrahamCampbell** [comment]
See https://github.com/symfony/symfony/issues/18226.

**Comment by GrahamCampbell** [comment]
Hmm, it seems they allow it now. I'll speak to Taylor again.

**Comment by nogrp** [comment]
Thanks for the quick comment. However, since issue isn't resolved currently and it could be, could we leave the issue open so it doesn't slip past you guys? :)

**Comment by GrahamCampbell** [comment]
It's ok, I'll definitely remember. This issue affects laravel too.

**Comment by nogrp** [comment]
Alright, thank you for your time and have a nice day! :)
