### ISSUE TITLE
Deploying application - production enviornment - not settled by default

### ISSUE THREAD

**Issue by evertramos** [laravel/lumen-framework#426]
Not sure if this is an issue... 

To deploy my Lumen application I had to change my _./public/index.php_ file as it show blow:

From:
`$app->run();`

To:
`$app->run($app->make('request'));`

Fount in an asnwer at StackOverflow ([here](http://stackoverflow.com/questions/36436967/just-installed-lumen-and-got-notfoundhttpexception)).

Is that right? Or I am missing something? 

This is not in the documentation from [Lumen site](http://lumen.laravel.com/docs/5.2).

Thanks!

**Comment by GrahamCampbell** [comment]
You shouldn't need to do that. Are you installing in a subfolder?

**Comment by GrahamCampbell** [comment]
If so, that's not supported on Lumen.

**Comment by evertramos** [comment]
Yes I was... let's try pointing out to public folder.

**Comment by evertramos** [comment]
@GrahamCampbell thank you.. you are right... but could you tell me why it does work this way? would that be a bad option? 

Thanks!



http://www.wikiespirita.org.br/we_wikisearch/public/

**Comment by GrahamCampbell** [comment]
Lumen is just super fast out of the box because we make some assumptions and short cuts. One of these is that the application is in the root folder.
