### ISSUE TITLE
Overwriting controller path on middleware

### ISSUE THREAD

**Issue by belohlavek** [laravel/lumen-framework#431]
I'm trying to overwrite the controller path for a request inside a middleware, but I can't seem to find a way to access $request->route()->getAction() because $request->route() returns an array (may be #119:question:)

Has this been done recently (version 5.1 or greater)? How?

Thanks for reading.

**Comment by GrahamCampbell** [comment]
I don't think this is possible. Feel free to discuss your specific requirements on the forums, and I'm sure someone can help you.
