### ISSUE TITLE
TestCase class includes app.php for the second time, which may cause issues

### ISSUE THREAD

**Issue by ecolotko** [laravel/lumen-framework#432]
If execute PHPUnit tests the, file **bootstrap/app.php** will be included twice:
1. In phpunit.xml, which provides: `bootstrap="bootstrap/app.php"`;
2. In TestCase's method createApplication: `return require __DIR__.'/../bootstrap/app.php';`.

In case, when some of providers, registered inside of app.php, creates aliases, this double inclusion will cause an Error:

> Cannot declare class ExampleAlias, because the name is already in use

This issue may be fixed by changing `require` function to `require_once` inside of createApplication method:

``` php
public function createApplication()
{
    $app = require_once __DIR__.'/../bootstrap/app.php';

    // if $app is boolean true, file was already included
    return true === $app ? app() : $app;
}
```

**This solution may break testing purpose, because it won't create a new application, but work only as a singleton for App instance instead.**

Someone suggests to add `class_exists` before any alias creation, but if I want add more helper functions or classes declared in app.php it will cause more redundant checks.

So, is this a right way?

**Comment by ksassnowski** [comment]
Take a look at my proposed solution in #447.

**Comment by l0rb** [comment]
Could this be reopened? The proposed solution does not stop bootstrap from being included for every test. This leads to problems with all kinds if things like defining constants in bootstrap. Either the environment of the previous test should be properly teared down after the test. or bootstrap only included once for all tests.

**Comment by usamabinshahid97** [comment]
Did you find the solution to this problem yet? @l0rb
