### ISSUE TITLE
Using return types of PHP 7 in controller methods results in a wrong response

### ISSUE THREAD

**Issue by keyball** [laravel/lumen-framework#438]
Hi, 

I'm using Lumen 5.2.7 with PHP 7.0.4, and I got a text/html response, when I used a return type of the controller's method, e.g. 

```
  /**
   * Log in user
   *
   * @return string
   */
  public function login() : string {
	...
    // if none of the values is true - return a response with code 400
    if ( !( $deviceMail || $namePassword || $deviceToken ) ) {
      return response()->json(
        [ 'status' => 'error:specify device id and email or user name and password or refresh token and device id' ],
        Response::HTTP_BAD_REQUEST
      );
    
}
```

I got these headers:

    Status Code: 200 OK
    Cache-Control: no-cache
    Connection: keep-alive
    Content-Type: text/html; charset=UTF-8
    Date: Mon, 20 Jun 2016 09:22:33 GMT
    Server: nginx
    Transfer-Encoding: chunked

And this body:

    HTTP/1.0 404 Not Found
    Cache-Control: no-cache
    Content-Type:  application/json
     
    {"status":"error:User cannot be found - refresh token, id or password are not provided"}

But as I removed the return type, the result is as expected:
`public function login()  {`

The headers:

    Status Code: 404 Not Found
    Cache-Control: no-cache
    Connection: keep-alive
    Content-Type: application/json
    Date: Mon, 20 Jun 2016 09:28:04 GMT
    Server: nginx
    Transfer-Encoding: chunked

And the body:

    {
        "status": "error:User cannot be found - refresh token, id or password are not provided"
    }

Perhaps (until eventually fixed) could You make a note in the documentation about this issue - it can spare much time of debugging :)

Greetings, 
Lucas

**Comment by mikerockett** [comment]
A `Response` is not a `string` and so the return should be of type `Response`, no?

**Comment by GrahamCampbell** [comment]
Indeed, yes. Laravel's responses are objects, but they do have a `__toString` method. ;)

**Comment by mikerockett** [comment]
True that, was just pointing out that they're not the same and don't produce the same results.

**Comment by keyball** [comment]
Yes, but it is only half true. If you consider this code, which is a very simple schematics of the response mechanism:


```
class Response {

  protected $response = '';

  public function __construct( $response = '' ) {
    $this->response = $response;
  }

  public function json( $content ) {
    return new JsonResponse( $content );
  }

  public function __toString() {
    return $this->response;
  }
}

class JsonResponse extends Response {

  public function __construct( $response ) {
    parent::__construct( json_encode( $response ) );
  }
}


class Controller {

  public function login() : string {

    $response = [
      'code' => 200,
      'message' => 'Test message'
    ];
    return ( new Response() )->json( $response );
  }
}

$obj = new Controller();
var_dump( $obj->login() );
```

When you set declare( strict_types = 1 ); - you'll get an error, which is correct:

> PHP Fatal error:  Uncaught TypeError: Return value of Controller::login() must be of the type string, object returned in ...

But if (e.g. for compatibility reasons) you'll use declare( strict_types = 0 ) ( or you don't use declare construct, as it is default set to 0 ), you'll get:

> string(37) "{"code":200,"message":"Test message"}"

and this result gives back the string! So the return type of the method provides the string type if the strict mode isn't set.

If we take this example directly in Lumen code, as I did in my previous message - a wrong response will be returned (this with headers within the body and the wrong Content-Type). This can be interpreted wrongly by persons, which are starting their adventure with Lumen (e.g. me, as I'm working with it since 2 weeks).  So I'd proposed only to make a note in the docs, to cover this phenomenon, because as more and more developers will use PHP7, so more can be frustrated through this issue. Especially if they will add the return type to the method and get a weird response ( it took several hours, before I got this idea, to remove the return type - as there was no error, just the response looked unusual :) )

Greetings,
Lucas

**Comment by GrahamCampbell** [comment]
This is due to PHP's type system. If strict types are off, it will attempt to cast the returned value to a string. Doing that will result in you loosing all the headers from the controller, and the response code.

**Comment by crynobone** [comment]
> When you set declare( strict_types = 1 ); - you'll get an error, which is correct

```php
return (new Response())->json($data);
``` 

return an instance of `JsonResponse` which doesn't have `__toString()` method.

**Comment by keyball** [comment]
@crynobone JsonResponse extends Response?

@GrahamCampbell : you're right, what didn't change the fact, it is not mentioned in the docs as a potential pitfall :)
