### ISSUE TITLE
Call to undefined function csrf_token()

### ISSUE THREAD

**Issue by buihoang91tin** [laravel/lumen-framework#440]
I have create this form
![image](https://cloud.githubusercontent.com/assets/9276526/16515994/7326eeec-3f9f-11e6-9e28-c70418513563.png)

And when I submit this form, It's response 

```
FatalErrorException in 912fc13c8cc9a6942efdfe7fbdb8613faa9cb14b.php line 10:
Call to undefined function csrf_token()
```

How can I resolve this

**Comment by GrahamCampbell** [comment]
Yes, we don't have a `csrf_token()` function on lumen.

**Comment by GrahamCampbell** [comment]
Lumen is built for writing APIs, not applications with views.

**Comment by buihoang91tin** [comment]
So when I try with views ít's response
`{"error":"token_not_provided"}`

So it's still OK when I try login with android device. I just try to login in desktop before login with other device

**Comment by buihoang91tin** [comment]
But I saw this. Why this document written
[https://lumen.laravel.com/docs/5.1/routing](https://lumen.laravel.com/docs/5.1/routing)

**Comment by buihoang91tin** [comment]
So Can I login with not token. Please reply me.

**Comment by cvassios-ekko** [comment]
@buihoang91tin did you ever figure out a solution to this?
