### ISSUE TITLE
queue:listen workers are not stopped when timeout exception is thrown

### ISSUE THREAD

**Issue by chrislam** [laravel/lumen-framework#446]
When a queued job takes longer than the `--timeout` set on `queue:listen` I'm seeing the `ProcessTimedOutException` being thrown and the `queue:listen` process itself is stopped but it's child process which is working on the job continues to run.

When combined with supervisor restarting the stopped `queue:listen` process, I have been seeing jobs processed multiple times.

Is there a setting where I can ensure that the worker process is stopped when the listener process stops?

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
