### ISSUE TITLE
prepare() not called for all Responses

### ISSUE THREAD

**Issue by avictor** [laravel/lumen-framework#449]
As an example, the simple route:

$app->get( '/version', function() {
    return response()->json( '1.0.0' );
});

The client sends request as HTTP/1.1:

GET /version HTTP/1.1
User-Agent: curl/7.35.0
Host: example.com
Accept: _/_

But response generated by Lumen is always HTTP/1.0:

HTTP/1.0 200 OK
Date: Fri, 22 Jul 2016 15:50:08 GMT
Server: Apache
Cache-Control: must-revalidate, no-cache, no-store, private
Pragma: no-cache
Content-Length: 7
Connection: close
Content-Type: application/json

Comparing Laravel to Lumen it seems there is a missing call to prepare() in prepareResponse() in vendor/laravel/lumen-framework/src/Application.php

**Comment by orottier** [comment]
I noticed the same. The protocol switching kills the `Connection: keep-alive` in my setup

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by avictor** [comment]
I just spun up an AWS instance and tested the latest version of Lumen.  It's still broken.
Version tested:  Lumen (5.7.1) (Laravel Components 5.7.*)


```
> curl -v http://xyz.elasticbeanstalk.com/
* Connected to xyz.elasticbeanstalk.com (34.246.77.31) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: xyz.elasticbeanstalk.com
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Date: Tue, 02 Oct 2018 12:53:55 GMT
< Server: Apache
< Cache-Control: no-cache, private
< Content-Length: 40
< Connection: close
< Content-Type: text/html; charset=UTF-8
< 
* Closing connection 0
Lumen (5.7.1) (Laravel Components 5.7.*)
```

Request is sent as HTTP/1.1, but Lumen forces response as HTTP/1.0.

This absolutely kills performance since HTTP/1.1 features such as Connection keep-alive cannot be used.

I really should not be forced to hack the vendor code, or add protocol-specific middleware.   The HTTP protocol should be handled by the framework.

**Comment by driesvints** [comment]
Seems to be working ok for me:

```
 ✝ ~/Sites/lumen-test  master±  curl -v http://lumen-test.test
* Rebuilt URL to: http://lumen-test.test/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to lumen-test.test (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: lumen-test.test
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.15.4
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Powered-By: PHP/7.2.10
< Cache-Control: no-cache, private
< Date: Tue, 02 Oct 2018 14:13:37 GMT
< 
* Connection #0 to host lumen-test.test left intact
Lumen (5.7.1) (Laravel Components 5.7.*)%                  
```

Are you sure there isn't anything changed in your code? Are you using a fresh Lumen 5.7 setup? Does the instance you spun up provide HTTP/1.1? Just thinking out loud here.

**Comment by JacksonIV** [comment]
I made a PR to fix this. I add the `prepare` method to the response.

**Comment by driesvints** [comment]
Thanks @JacksonIV! You're on 🔥

**Comment by orottier** [comment]
I'd like to refer you to the discussion at https://github.com/laravel/lumen-framework/pull/464 where this approach was rejected
