### ISSUE TITLE
[Docs] No mention on `view` being back in 5.2.1+

### ISSUE THREAD

**Issue by hdra** [laravel/lumen-framework#456]
Opening an issue here since there is no way to ask this in the docs repo. 

I was wondering why is there no mention of the view being back in Lumen since this [commit ](https://github.com/laravel/lumen-framework/commit/30afe4ee2b65e026b316ecdb9a08d7b8f8075bc2)? 

I have been using Lumen for a project since 5.2.0 and have always kept to the latest release and I just noticed this.

Should I send a PR for the docs or is there no need to bother with it since Laravel 5.3 is coming out soon anyway?

**Comment by bcinco** [comment]
I believe it was because it was a quick decision, and that they're currently focused on Laravel 5.3, then Lumen 5.3 which will most likely mention Views being back again.

**Comment by GrahamCampbell** [comment]
Looks like the docs are just wrong. We're open to PRs. :)

**Comment by maciekmp** [comment]
Why there are still no word about views in docs?

**Comment by arashifunsho** [comment]
Please add views back to doc. Thanks

**Comment by iErik** [comment]
It's been more than one year and a few versions, the documentation is still omitting information about one of the main features of the framework. Just can't understand that.

**Comment by scheMeZa** [comment]
Even me

**Comment by arashifunsho** [comment]
I guess we'll have to stick to the Views documentation from laravel

**Comment by AbeEstrada** [comment]
I you like me landed this page looking for the `views` documentation, here are some useful links in the meantime:

- https://lumen.laravel.com/docs/5.1/views
- https://laravel.com/docs/5.6/views

**Comment by es02** [comment]
> Looks like the docs are just wrong. We're open to PRs. :)

Given this is still an issue:
https://github.com/laravel/lumen-docs/pull/166

Let's see if they'll actually merge it ;)
