### ISSUE TITLE
MakesHttpRequests cannot construct PATCH requests with JSON body.

### ISSUE THREAD

**Issue by bcinco** [laravel/lumen-framework#459]
Example test:

```
$this->patch(
   $uri = "/user/2?url_a=url_b",
   array('data_a' => 'data_b')
   $headers = array(
      //'Content-Type' => "application/x-www-form-urlencoded"
      'Content-Type' => "application/json"
);
```

If you set the content type to `application/json` then dump `$request->getContent()`, it will have a `Symfony\Component\HttpFoundation\ParameterBag` object containing an empty array.  Because this cannot be decoded as JSON, `$request->json()` gets null.  `"{data_a : data_b}"` is not passed at all.  Using `x-www-formurlencoded` would include that into `$request->input()`, but it's really not ideal to put PATCH operation like this into the URL:
```
{
    "operations": [
        { "op":"replace", "path":"name", "value":"0" }
    ]
}
```

The cause is that the `patch()` method does not correctly construct requests containing a body. 
\Laravel\Lumen\Testing\Concerns\MakesHttpRequests.php:

```
public function patch($uri, array $data = [], array $headers = [])
{
    $server = $this->transformHeadersToServerVars($headers);
    $this->call('PATCH', $uri, $data, [], [], $server);
    return $this;
}
```

A simple fix is to create a custom method, such as `patchWithBody` to accept $content and pass it to `$this->call()`.  The JSON data can be passed through it, which can then be read via `$request->json()` once execution reaches the API controller.

**Comment by cristiangrama** [comment]
If you want to pass json data you should not be using `$this->patch` because that does not passes any content https://github.com/laravel/lumen-framework/blob/5.4/src/Testing/Concerns/MakesHttpRequests.php#L113.

Instead use `$this->json('PATCH', ...)` which would make a PATCH request with content.

**Comment by bcinco** [comment]
@cristiangrama 
That is true, but what is the point of a PATCH method that doesn't accept content?  If we have to use json() to patch, then why have patch()?

**Comment by cristiangrama** [comment]
@bcinco That's useful for sending content as form data (`application/x-www-form-urlencoded`) rather then json. It's nice to have it like that so that you can differentiate in your tests really easy what type of call to make based on your app.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
