### ISSUE TITLE
Lumen 5.1 | Namespace inheritance in nested route group

### ISSUE THREAD

**Issue by zxz054321** [laravel/lumen-framework#461]
According to the [doc](https://lumen.laravel.com/docs/5.1/controllers)
(These paragraphs have been removed in the document of Lumen 5.2)

> Controllers & Namespaces
> 
> It is very important to note that we did **not need to specify the full controller namespace** when defining the controller route. **We only defined the portion of the class name that comes after the App\Http\Controllers namespace "root"**. By default, the bootstrap/app.php file will load the routes.php file within **a route group containing the root controller namespace**.
> 
> If you choose to nest or organize your controllers using PHP namespaces deeper into the App\Http\Controllers directory, simply use the specific class name **relative to the App\Http\Controllers root namespace**. So, if your full controller class is App\Http\Controllers\Photos\AdminController, you would register a route like so:
> 
> $app->get('foo', 'Photos\AdminController@method');

Everything is ok
```
$app->get('hi', 'FooController@bar');
$app->get('foo/bar', 'FooController@bar');
```

These routes should be OK, too
```
$app->group(['prefix' => 'foo'], function ($app) {
    $app->get('bar', 'FooController@bar');
});
```

But actually that will throw a ReflectionException. Lumen can't find my controller class.

After adding `'namespace' => 'App\Http\Controllers'`, the route group works.
```
$app->group(['prefix' => 'foo', 'namespace' => 'App\Http\Controllers'], function ($app) {
    $app->get('bar', 'FooController@bar');
});
```

**Comment by GrahamCampbell** [comment]
Nesting groups more than one level is not supported. Lumen is intentionally simple.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell RE docs.

**Comment by lalxyy** [comment]
Yeah this actually happens. My Lumen version in `composer.json` is 5.2.8. Alternatively I'm using duplicate prefixes in my route definitions.

**Comment by lalxyy** [comment]
@zxz054321 
See issue #239 ...?
We're talking about the same issue.

**Comment by GrahamCampbell** [comment]
Moving over to the other issue.
