### ISSUE TITLE
Route group parameters inheritance

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/lumen-framework#462]
I'm quite used to Laravel's route parameters inheritance and it struck me that apparently it doesn't work like that in Lumen. I wanted to ask if this is an intended/desired behavior?

When I want to pass some routes through different middlewares it looks like I need to repeat same declaration on every level. When I say:
```php
$app->group(['middleware' => 'auth'], function () use ($app) {
    $app->post('notifications', 'NotificationController@store');
    $app->group(['middleware' => 'admin'], function() use ($app) {
        $app->get('users', 'UserController@index');
    });
});
```
route `GET /users` is sent only through `admin` middleware and doesn't go through `auth` middleware. Morover, the `'namespace' => 'App\Http\Controllers'` parameter isn't passed down the hierarchy, hence `Undefined class FooController` errors are thrown.

From what I saw this happens because Lumen's router replaces `$groupAttributes` with new set of parameters instead of merging them like the Laravel's router does.

Problem is, I have quite a complicated prefix and middleware based route hierarchy and the `routes.php` file would become totally unreadable if I needed to repeat previously declared parameters in every group declaration.

Is there a way around this? Can I toggle `$groupAttributes` merging instead of replacing? Should I make a PR with this functionality?

Thanks.

**Comment by GrahamCampbell** [comment]
Nested groups of more than one level deep arn't supported for simplicity. Please use laravel if you have more advanced requirements.
