### ISSUE TITLE
Controller receives wrong router parameters

### ISSUE THREAD

**Issue by sstativa** [laravel/lumen-framework#475]
Hi there,

I don't know why, but I always thought that route parameters are passed to the controller in the order from left to right. However, I've just got a situation when my controller received parameters in reverse order. 

After a bit of testing and debugging, I found a solution, however, I'm not so sure is this a bug or just a lack of proper documentation.

Consider these 3 cases:
1. route `users/{user_id}/file/{uuid}` calls `saveFile(Request $request, $user_id, $uuid)`
2. route `users/{a}/file/{b}` calls `saveFile(Request $request, $user_id, $uuid)`
3. route `users/{user_id}/file/{uuid}` calls `saveFile(Request $request, $userId, $uuid)`

In first two cases `$user_id` and `$uuid` will be assigned correctly. However, the last example will be broken, `$userId` will get a value of `{uuid}` and `$uuid` - the value of `{user_id}`. It looks like the Lumen firstly passes parameters having the same name in route and controller's method, then it passes remain parameters. 

So, if this is not a bug, I think it should be clearly stated in the documentation.

**Comment by jcrowe206** [comment]
Thank you for this. I thought I was going crazy!

**Comment by NizarBlond** [comment]
+1

**Comment by loeffel-io** [comment]
is there any solution for this problem?

**Comment by jcrowe206** [comment]
https://github.com/laravel/lumen-framework/issues/475#issuecomment-340801974 is the solution. Rename your route parameters so that either none or all of the are exactly the same as the named arguments in your controller method

**Comment by driesvints** [comment]
Yeah, you need to rename your controller parameters so they match the route parameters.
