### ISSUE TITLE
Facades issue

### ISSUE THREAD

**Issue by sunsunych** [laravel/lumen-framework#478]
On new Lumen 5.3.0 project after uncommenting `bootstrap/app.php` line 26 `$app->withFacades();` i've got parse error:
`Parse error: parse error in /vendor/illuminate/support/Facades/Facade.php on line 238`

**Comment by GrahamCampbell** [comment]
Please upgrade to PHP 5.6.

**Comment by hakirra** [comment]
@GrahamCampbell  
Parse error: parse error in vendor/illuminate/support/Facades/Facade.php on line 52
I PHP version 7.1 ,but parse error
