### ISSUE TITLE
Defining custom validation enables Eloquent!

### ISSUE THREAD

**Issue by hpaknia** [laravel/lumen-framework#483]
We decided to disable eloquent in bootstrap file. After a couple of days I noticed I can use use models while having eloquent disabled (which should not be possible). After a little bit of digging into the code I found out my custom validation rule is the root cause. Hear in this file: [https://github.com/laravel/framework/blob/5.3/src/Illuminate/Validation/ValidationServiceProvider.php#L57](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Validation/ValidationServiceProvider.php#L57) code accesses to $app['db'] variable which causes framework constructs db (eloquent):

```
$this->app->singleton('validation.presence', function ($app) {
    return new DatabasePresenceVerifier($app['db']);
});

```

I suppose is a bug.
**Custom validator code in boot method of app service provider:**

```
        app('validator')->extend('mongoId', function($attribute, $value, $parameters) {
            if ($value instanceof \MongoDB\BSON\ObjectID) {
                return true;
            }
            try {
                new \MongoDB\BSON\ObjectID($value);
                return true;
            } catch (\Exception $e) {
                return false;
            }
        });
```

**Trace:**
./vendor/illuminate/validation/ValidationServiceProvider.php(57): Illuminate\Container\Container->offsetGet('db')
./vendor/illuminate/container/Container.php(1182): Laravel\Lumen\Application->make('db')

**Comment by mikerockett** [comment]
DB and Eloquent are not the same thing.

**Comment by hpmhpm** [comment]
They might not be the exact same thing, but apparently accessing $app['db'] results in **Laravel\Lumen\Application->make('db')** which this code enables eloquent.

**Comment by mikerockett** [comment]
I see - you're referring to [this](https://github.com/laravel/lumen-framework/blob/414fa00eb0efadb1e39f977b8703ed4a3c579323/src/Application.php#L674).

**Comment by hpmhpm** [comment]
Yes. AFAIK using eloquent models without enabling it is impossible and after adding a custom validator I was able to use those models. By the way I had noticed enabling eloquent consumes ~300KB of memory, but after adding that custom validator enabling or disabling eloquent had no effect on php memory pick usage.

**Comment by hpaknia** [comment]
Any updates here?

**Comment by yuloh** [comment]
You can't use `db` without booting the `DatabaseServiceProvider`, which [sets the connection on the model](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/DatabaseServiceProvider.php#L23).

If you don't want eloquent models to be usable, you can just unset the connection after the db component boots:

```php
Model::unsetConnectionResolver();
```

It's not really a bug.  Eloquent just uses the same service provider.

**Comment by GrahamCampbell** [comment]
Please feel free to continue this on the forums.
