### ISSUE TITLE
Socialite ignores config/services.php in Lumen

### ISSUE THREAD

**Issue by chimit** [laravel/lumen-framework#486]
The configuration files from `/vendor/laravel/lumen-framework/config/` and `/config/` directories are loaded automatically in Lumen, but not `services.php`, which is used in Socialite.

To make it work you need to manually add
```
$app->configure('services');
```
into `/bootstrap/app.php`.

There is no any information about it in Lumen or Socialite documentation, and it causes many questions like these:
https://laracasts.com/discuss/channels/lumen/cant-get-config-data-in-lumen
http://stackoverflow.com/questions/33135470/laravel-socialite-on-lumen-credentials-are-not-sent-along
http://stackoverflow.com/questions/39599791/lumen-with-socialite-the-parameter-app-id-is-required

Please, give us the right way to solve this problem: fix Socialite/Lumen or clarify the documentation.

**Comment by GrahamCampbell** [comment]
Please send a pr to the docs. :)

**Comment by chimit** [comment]
Does fixing Socialite make more sense? It's a little bit strange, that you have to manually apply config files for some Laravel components and don't have to do that for another.
