### ISSUE TITLE
Getting a PSR7 request in middleware

### ISSUE THREAD

**Issue by nsh-core** [laravel/lumen-framework#487]
I've read through the documentation regarding psr7 requests

https://lumen.laravel.com/docs/5.2/requests#psr7-requests

I have no problem getting a psr7 request in my controller as it seems the bridging component works after the middleware and before the controller, Ive tried implementing libraries from the PSR7 middlewares library https://github.com/oscarotero/psr7-middlewares/ such as CORS and my own request logging interface. 

```
public function handle(ServerRequestInterface $request, Closure $next)
{
   //do stuff
}
```

but the handle() always expects $request to be an illuminate\request

I don't like hacking core of any framework to get an implementation, so what would be the best course of action here, to create a middleware that is always pipelined first converting all requests into psr7 requests, which seems like a bandaid solution, the other option is to contribute to illuminate\http making all request compliant to the psr-7 standard which is what "you should do".

Is there any roadmap to implement the psr-7 standard

**Comment by pablorsk** [comment]
I trying to do the same task. But if your problem is CORS, temporally, you can do use https://github.com/barryvdh/laravel-cors.  Off course is not PSR7 but can work together.

For now, I triying apply this tutorial: https://medium.com/@barryvdh/using-stackphp-middleware-in-laravel-5-abd9e2177e6d

Any ideas are welcome...

**Comment by pablorsk** [comment]
Hi @jkirkby91-2, I found the solution :tada: 

[CORS middleware for Lumen and PSR-7](https://gist.github.com/pablorsk/5df7aad7a1c5f7612c6bc3d46505e23e)

**Comment by driesvints** [comment]
Laravel has support for getting a PSR7 type request through its router by requiring some packages. Maybe the same thing can be done in Lumen. https://laravel.com/docs/5.7/requests#psr7-requests

It's probably best if you start a discussion first in https://github.com/laravel/ideas about it and then wip up a PR.
