### ISSUE TITLE
constructors in controller not being called?

### ISSUE THREAD

**Issue by gokigoks** [laravel/lumen-framework#491]
I have been having headaches about my _construct() not being called on all of my controllers..
I don't think I have to show examples as all of constructors are pretty generic like

public function _construct(SomeHelper $helper)
{
   $this->middleware('some_middleware');
   //or
   $this->helper = $helper;
}

Does anyone else have this issue?

**Comment by bobbybouwmann** [comment]
You constructor needs two underscores
```
public function __construct(SomeHelper $helper)
```
