### ISSUE TITLE
Redis queue not working

### ISSUE THREAD

**Issue by khromov** [laravel/lumen-framework#497]
When using `php artisan queue:listen` the queue is not processed. In fact, `redis-cli monitor` shows that no commands are even sent to Redis.

I've traced the problem  to the `migrateExpiredJobs` function in `RedisQueue`:
https://github.com/illuminate/queue/blob/master/RedisQueue.php#L186

Basically, when `->eval()` is invoked it seems the queue listener hangs, because you can't log anything under the migrateExpiredJobs call. I tried removing it but it was the same issue with the next eval call just below that.

I think there's something wrong with the way Predis or Lumen uses LUA scripts, please advise.

Redis version: 3.2.4, using `predis/predis` version `1.1.1`, PHP 7.0.10

**Comment by djoks** [comment]
Hmm that's weird since I actually got redis running with lumen this week without any real difficulty.  My only problem is that artisan queue:work creates soo many processes and ends up eating all my memory and crashing my server.

**Comment by khromov** [comment]
I was able to get this to work after rebooting the computer, but another colleague has the same issue upon initially installing Redis. It seems to be a Mac-specific Redis bug that is resolved after rebooting. Closing this request.
