### ISSUE TITLE
Lumen controller switches route parameters.

### ISSUE THREAD

**Issue by rotexhawk** [laravel/lumen-framework#502]
I am running Lumen 5.3 and using PHP's build-in server. The following code produces inconsistent output. 
http://localhost:8080/user/1/contact/2

```
$app->get('/user/{id}/contact/{contactId}', 'UserController@addContact');

public function addContact($userId, $contactId){
        return $userId . ' ' . $contactId;
}

```

This outputs 2,1 but If I change my variables from $userId to $a and $contactId to $b. 
It outputs 1,2 

I tested this in the browser and postman and it seems like lumen switches the values depending on how I name my variable. 

Also tried to output one variable at a time to see if php was doing any crazy optimization but the result was the same.

**Comment by bobbybouwmann** [comment]
This is basic behaviour from Laravel and Lumen. It will try to do the dependency injection first. After that it will try to match the variable names with the names of the routes and finally it will handle the once it can't handle in the first two steps. 

The solution is simple here. Keep the same variable names as the route. I think it also adds more consistency to your application ;)

**Comment by rotexhawk** [comment]
Got it. Don't you think it makes more sense for Laravel/Lumen to honor the order of arguments instead of trying to match them ? You can see how matching causes confusion and inconsistent result. Why is {contactId} not matched with $contactID ?

**Comment by bobbybouwmann** [comment]
$contactId is matched with {contactId} since you get 2,1 as output back. But like I said it's the order that messes this up.

I think you can create an issue on the internals repo or ask around in Slack why this is done. I don't know the history, only the behaviour ;)
