### ISSUE TITLE
When will new version release?

### ISSUE THREAD

**Issue by atapatel** [laravel/lumen-framework#507]
When will new version release for separate route folder?

**Comment by bobbybouwmann** [comment]
It's already released.. Take a look at the current 5.3 and master branch ;)

**Comment by atapatel** [comment]
@bobbybouwmann yeah but new tag is not released yet!!

**Comment by bobbybouwmann** [comment]
Tag should be there shortly ;) 

Ping @taylorotwell

**Comment by atapatel** [comment]
👍

**Comment by GrahamCampbell** [comment]
Yeh, a release will be out soon. :)
