### ISSUE TITLE
Missing Application dependencies?

### ISSUE THREAD

**Issue by torkiljohnsen** [laravel/lumen-framework#509]
`Laravel\Lumen\Application` version 5.3.0 seems to have some imports that are missing in the composer dependencies?

`Zend\Diactoros\Response`
`Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory`

![skjermbilde 2016-10-20 kl 11 25 24](https://cloud.githubusercontent.com/assets/318089/19554324/5bbf2010-96b8-11e6-9815-cf6c1553ab8a.png)

**Comment by yuloh** [comment]
They are only used if you want PSR-7 support.  It won't break anything if you don't use PSR-7.

https://lumen.laravel.com/docs/5.3/requests#psr7-requests
