### ISSUE TITLE
IOC not resolving $app in DatabaseManager

### ISSUE THREAD

**Issue by cainmi** [laravel/lumen-framework#51]
To replicate:

- Fresh lumen install
- Modify `app/Http/routes.php` to include the following:

```php
use Illuminate\Database\DatabaseManager as DB;

$app->get('/', function(DB $db) {
    dd($db);
});
```

This is what I get:
**`Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Database\DatabaseManager`**

I realise I can use facades or `app()->make('db')`, but I would prefer not to.

@taylorotwell, am I missing something here? Do I need to bind `$app` myself?

**Comment by cainmi** [comment]
This works fine in Laravel proper however.

**Comment by crynobone** [comment]
<https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Application.php#L1016-L1062> is not available in Lumen, and that would be on purposed.

You can add it on your own in `bootstrap/app.php`:

```php
$app->alias('db', 'Illuminate\Database\DatabaseManager');
```

**Comment by cainmi** [comment]
Thanks for the suggestion, but the DB dependency resolves fine without the alias.

But when DatabaseManager is being instantiated, it's own dependencies aren't being injected... mainly it seems just `$app` can't be located.

https://github.com/illuminate/database/blob/master/DatabaseManager.php#L44

If you try my example on a fresh Lumen install you'll see what I mean.

**Comment by crynobone** [comment]
> But when DatabaseManager is being instantiated, it's own dependencies aren't being injected... mainly it seems just $app can't be located.

That because every time you typehint `DatabaseManager`, it try to create a new instance instead of resolving from the `db` alias (that how it done in Laravel, and why you only seeing this with Lumen). 

Even if we typehint `Manager` to use `Illuminate\Contracts\Application\Application` you still need to create an alias of that in `bootstrap\app.php` or otherwise it will resolve a new Application instance.

**Comment by cainmi** [comment]
Going with your original suggestion though, I still get a `class db cannot be found` exception.

**Comment by crynobone** [comment]
After `$app->withEloquent();`?

**Comment by cainmi** [comment]
Ahh. Thank you.
After uncommenting `$app->withEloquent();` it works.

Why is this?
I was planning on using the basic query builder without Eloquent, to keep it super light.

**Comment by crynobone** [comment]
`$app->withEloquent();` does nothing except resolve/make `db` instance, nothing more.

<https://github.com/laravel/lumen-framework/blob/5.0/src/Application.php#L787>

**Comment by cainmi** [comment]
Spot on. Thanks for your help Mior.
