### ISSUE TITLE
Support the http method HEAD

### ISSUE THREAD

**Issue by rickshawhobo** [laravel/lumen-framework#516]
Per the documentation,

```
$app->get($uri, $callback);
$app->post($uri, $callback);
$app->put($uri, $callback);
$app->patch($uri, $callback);
$app->delete($uri, $callback);
$app->options($uri, $callback);

```

 all http methods are supported but the method HEAD seems to be missing.
Any chance it could be supported?

**Comment by yuloh** [comment]
Since Lumen uses FastRoute [HEAD requests are automatically matched to the GET request for that path](https://github.com/nikic/FastRoute#a-note-on-head-requests).

As a workaround you can specify a GET handler and check the method in the handler.

**Comment by hakuno** [comment]
One more option: the [HTTP 204](https://httpstatuses.com/204) has same effect. It receives only the HTTP header (response).

> The server has successfully fulfilled the request and that there is no additional content to send in the response payload body.


**Yes.** You can proceed with HEAD (request) as @yuloh said with no problem :smile: 

_Maybe this thread can be closed._
