### ISSUE TITLE
ReflectionException  after upgrading from 5.3.1 to 5.3.2

### ISSUE THREAD

**Issue by adrevol** [laravel/lumen-framework#517]
Hello Team, 

Here was  my previous  Composer.json 

"require": {
        "php": ">=5.6.4",
        "laravel/lumen-framework": "5.3.*",
        "vlucas/phpdotenv": "~2.2",
        "dusterio/lumen-passport": "^0.1.2",
        "guzzlehttp/guzzle": "^6.2",
        "illuminate/mail": "^5.3",
        "intervention/image": "^2.3",
        "illuminate/filesystem": "^5.3"
}

Initially   my  installation was consisting  Lumen 5.3.1 

I ran  a  Composer Update   which  converted  my Lumen  to 5.3.2 

All of  sudden   My  API  Endpoints  started throwing  Reflection Exception  because  namespace started appearing  Twice  

**App\Http\Controllers\**App\Http\Controllers\UserController

Thanks in advance.

**Comment by tsari** [comment]
It seems that the \Laravel\Lumen\Concerns\RoutesRequests::group method was changed so the calls in the bootstrap/app.php and in your routes.php will both add the namespace App/Http/Controllers.

You can remove the namespace from your routes.php and you're good to go.

**Comment by mstaack** [comment]
exactly: https://github.com/laravel/lumen-framework/commit/7c2df56331075975bf94a7247e6a1f8b2bd8f664

**Comment by tsari** [comment]
To have such an issue in a patch level version is ... uncool

**Comment by GrahamCampbell** [comment]
The early point releases are considered a little bit "beta" typically. Expect breaking changes around .0 -> .4 ish in general.

**Comment by GordonSchmidt** [comment]
There are naming conventions for alpha and beta versions as well on semver.org. If your releases are unstable, please mark them as such.
A real release shouldn't break on a new path level version.

**Comment by reense** [comment]
This is why i should remove the composer auto update from our build process. This crashed our production build today.. Took me two hours to find this haha 🤒

**Comment by GrahamCampbell** [comment]
Things always change because people always complain about things that were changed in a new minor release and force us to change them.

**Comment by GrahamCampbell** [comment]
I mean, we don't intentionally set out to break stuff, we'd rather get it perfect first time, but in software engineering, that often doesn't happen. :)
