### ISSUE TITLE
5.3 Method shuffle does not exist when doing composer update

### ISSUE THREAD

**Issue by tomswinkels** [laravel/lumen-framework#519]
When we do an composer update of Laravel Lumen 5.3.1 we get the following error;

Method shuffle does not exist.
Macroable.php on line 52

Is there any with the same problem?

**Comment by tim-hanssen** [comment]
I have the same problem in my environment.
Got this error after running a deployment with Envoyer. Reverting back doenst fix the problem.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
