### ISSUE TITLE
Is there a LTS version for Lumen micro framework?

### ISSUE THREAD

**Issue by ChaminW** [laravel/lumen-framework#520]
I am going to move my product with Lumen 5.x micro PHP framework. Lumen documentation does not mention anything related to LTS version. 
Is there any LTS version for Lumen or any information about supportability and maintainability of Lumen released versions?
As I heard Long Term Support for Lumen is the same as Laravel's LTS. Is this correct?

**Comment by GrahamCampbell** [comment]
In theory, I guess so, but so far nobody has really reported anything to fix.
