### ISSUE TITLE
How do I handle before router ?

### ISSUE THREAD

**Issue by vluzrmos** [laravel/lumen-framework#53]
Hello @taylorotwell ,

How do I handle the before router event? like laravel/framework does...

I need before any route check if method is OPTIONS and return new response or inject some CORS headers: Like https://github.com/barryvdh/laravel-cors/blob/master/src/CorsServiceProvider.php#L53

Because without that, I have to dynamic create an route->options do any request, like:

https://gist.github.com/vluzrmos/1238a0c81bfd90853f58

Also, I tried to do that on middlewares, but doens't works too.

```php
public function handle($request, Closure $next)
   if($request->isMethod('OPTIONS')){
       return new Response('OK', 200, $headers); //the cors headers
   }
   
  return $next($request);
} 
```

Thanks!

**Comment by taylorotwell** [comment]
Middleware will work.
