### ISSUE TITLE
Class Illuminate\View\View contains 1 abstract method [...] - randomly

### ISSUE THREAD

**Issue by simplenotezy** [laravel/lumen-framework#530]
I have experienced this bug happen several times, taking down my application. It happens out of nowhere. Clearing all caches does not help anything. Doing a `sudo reboot` fixes the issue.

Any ideas why this might be happening?

    Fatal error: Class Illuminate\View\View contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\View\View::name) in /home/forge/domain.com/envoyer/releases/20161206183607/bootstrap/cache/compiled.php on line 14800

**Comment by simplenotezy** [comment]
A memory leak might trigger this error.

**Comment by GrahamCampbell** [comment]
> Doing a sudo reboot fixes the issue.

Doesn't look like a bug with us, rather, with PHP itself.

**Comment by simplenotezy** [comment]
@GrahamCampbell running php `PHP 7.0.1-5+deb.sury.org~trusty+1`, any idea upgrading to php 7.1 would solve?

**Comment by GrahamCampbell** [comment]
Upgrading to at least the newest 7.0 would be a good idea. 7.0.1 is full of bugs.

**Comment by GrahamCampbell** [comment]
For example, I'm currently running:

```
PHP 7.0.13-3+deb.sury.org~xenial+1
```
