### ISSUE TITLE
Routing doesn't work when deployed to a sub directory

### ISSUE THREAD

**Issue by yuloh** [laravel/lumen-framework#533]
The default [`getPathInfo` method](https://github.com/laravel/lumen-framework/blob/5.3/src/Concerns/RoutesRequests.php#L824) doesn't strip the base url, so deploying to a sub directory like `my-site.com/v1/` will cause the router to attempt to match a request to `/my-site.com/v1/` as `/v1/` instead of `/`.

Reproduction steps:

These steps are a little convoluted since normally public would be set to the web root but they illustrate the problem.

1.) From the root directory of a new lumen app, run `php -S localhost:8000`
2.) Visit `http://localhost:8000/public/` from the browser

Expected output: The default route `/` should be matched.
Actual output: You get a 404 not found.

You can work around the issue by changing the last line of `public/index.php` to `$app->run(\Illuminate\Http\Request::capture());`, since HttpFoundation strips the base url.

**Comment by yuloh** [comment]
I [made a branch](https://github.com/laravel/lumen-framework/compare/5.3...yuloh:subdirectory-routing) that fixes this, but I don't feel 100% confident it will work in every situation without breaking something.

**Comment by CurosMJ** [comment]
You should be using nginx / apache to map the requests to localhost / your domain to the `public/index.php` file in your project. 

If you want to use `php -S localhost`, then you should be running the command from inside the public folder of your project. Hope that helps !

**Comment by yuloh** [comment]
The PHP -s example was just the simplest way to reproduce the issue. It's also an issue using nginx and you can't work around it without doing some crazy path rewriting that isn't necessary with Laravel.

**Comment by KISdesigners** [comment]
just use `$app->run( $app->make('request') );` instead of `$app->run( );`

**Comment by GrahamCampbell** [comment]
Doing that will lead to lower performance.

**Comment by arnabrahman** [comment]
Yup solved it by adding ```$app->run(\Illuminate\Http\Request::capture())``` but  ``` $app->run( $app->make('request')); ```  doesn't work.

**Comment by GrahamCampbell** [comment]
> Yup solved it by adding

As I said, that'll lead to slower performance. Might as well just use Laravel.
