### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by gmsantos** [laravel/lumen-framework#534]
It's been a while since [last release](https://github.com/laravel/lumen-framework/releases/tag/v5.3.2). [Some changes](https://github.com/laravel/lumen-framework/compare/v5.3.2...5.3) still not tagged. Could a new release be tagged? 

Have the impression that Lumen is a bit abandoned. Think it's interesting some kind of release schedule or something.

**Comment by GrahamCampbell** [comment]
> Have the impression that Lumen is a bit abandoned.

Definitely not. There's just not much changed since the last release.

> Think it's interesting some kind of release schedule or something.

Lumen tracks the Laravel release cycle, though is often a few weeks behind.

> Could a new release be tagged?

Yes, I think so. I'll ask taylor now. :)

**Comment by gmsantos** [comment]
Thanks @GrahamCampbell . Sorry if I sounded rude, English isn't my native language :)
