### ISSUE TITLE
Helper route() don't support the secure param

### ISSUE THREAD

**Issue by OSTraining** [laravel/lumen-framework#544]
I'm trying to force the route to https, but the helper doesn't allow that

The route function doesn't pass the "$secure" param to the UrlGenerator instance:

```
function route($name, $parameters = [], $secure = null)
{
    return (new Laravel\Lumen\Routing\UrlGenerator(app()))
                ->route($name, $parameters);
}
```

**Comment by GrahamCampbell** [comment]
Thanks for the report. :)

**Comment by andergmartins** [comment]
You're welcome ;) glad to help.
