### ISSUE TITLE
A typo in Laravel\Lumen\Exceptions\Handler.php

### ISSUE THREAD

**Issue by bostin** [laravel/lumen-framework#564]
Lumen (5.4.3) (Laravel Components 5.4.*)

![image](https://cloud.githubusercontent.com/assets/17870778/22636924/c1fdfb28-ec79-11e6-9237-dfa04bdb1f41.png)
```
use Illuminate\Http\Exceptions\HttpResponseException;
```

**Comment by mwoszczyna** [comment]
Hi, this should be fixed now: https://github.com/laravel/lumen-framework/pull/581

**Comment by bostin** [comment]
@mwoszczyna thanks.
