### ISSUE TITLE
lumen 5.4 can't get request headers in serviceProvider

### ISSUE THREAD

**Issue by liyu001989** [laravel/lumen-framework#565]
I want to set my locale,  so I add this code in AppServiceProvider
```
 $request = app('request');
 //dd($request->headers);
 // dd($request->all());
 $acceptLanguage = $request->header('accept-language');
 if ($acceptLanguage) {
     $language = current(explode(',', $acceptLanguage));
     app('translator')->setLocale($language);
 }
```
when I upgrade to 5.4 it's not work, I can't get anything in request, is it a bug?

**Comment by GrahamCampbell** [comment]
Where abouts in your service provider?

**Comment by liyu001989** [comment]
<img width="396" alt="2017-02-07 9 59 24" src="https://cloud.githubusercontent.com/assets/2981799/22694633/efdc7024-ed82-11e6-855d-d9f0d5bee7ac.png">

same code, 5.3 is ok. 5.4 get null

**Comment by dshepherd** [comment]
I’ve just encountered this issue too. It seems that an empty Request object is being returned, with default property values (‘path’ = ‘/‘, method = ‘GET’ etc). 

This didn’t happen in 5.3 and it doesn’t happen in Laravel 5.4.

**Comment by austenc** [comment]
I believe I'm running into the same issue when trying to do a CORS request on Lumen 5.4. It seems the request (using either `app('request')` or the below `$this->app->request`) is a blank object, and not the current request. Same code on lumen 5.3.x returns `OPTIONS` as expected

```
  public function register()
  {
    $request = $this->app->request;

    dd($request->getMethod()); // This is 'GET' when it should be 'OPTIONS' in my case
    ...
  }
```

**Comment by austenc** [comment]
I've done a bit more digging, and it looks like adding this line back (and the `registerRequestBindings` method) fixes the issue I'm having.

https://github.com/laravel/lumen-framework/commit/2ce2eaaaebd315eefcba312de1e568a1b39fcaa5#diff-c9248b3167fc44af085b81db2e292837L874

**Comment by irazasyed** [comment]
Same issue here! I upgraded from 5.2 to 5.4 and it broke this part. I ended up moving the logic to a middleware.

**Comment by Except10n** [comment]
@GrahamCampbell why remove the prepareRequest in initial  Application ?  This leads to serviceprovider can not get a parsed request obj

**Comment by austenc** [comment]
@Except10n it makes more sense to do processing and request logic in middleware, as that isn't what the service provider is for. https://laravel-news.com/request-object-changes-in-lumen-5-4

**Comment by liyu001989** [comment]
> The alternative solution is to copy whatever code you put in your Service Providers that uses the request object, and move it to a global middleware; the middleware will run directly after the request is captured.

ok, I know

**Comment by Except10n** [comment]
@austenc I see, thx a lot

**Comment by peppeocchi** [comment]
@austenc 
How would you mock your bindings in your tests, if they happen in a middleware, and they depend on the request?
For example, if your bindings depend on a version that's on one header of the request.
