### ISSUE TITLE
Support ISO8601 Format

### ISSUE THREAD

**Issue by meness** [laravel/lumen-framework#569]
- Lumen Version: 5.4.4
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
As documentation noted about `$dateFormat`:

> This property determines how date attributes are stored in the database, **as well as their format when the model is serialized to an array or JSON**

It is good to convert dates to the ISO8601 format as described on [here](https://geemus.gitbooks.io/http-api-design/content/en/responses/use-utc-times-formatted-in-iso8601.html) and [JSON API](http://jsonapi.org/recommendations/#date-and-time-fields) but MySQL `timestamp` datatype uses another format. So, defining a same format for both ways (store in the database and serialize model to an array) may produce an exception or not a good expectation result.

**Note:** I didn't test anything, that's just a vision!

A workaround is defining an accessor:
```php
public function getXAttribute($value){
    $c = Carbon::createFromFormat('Y-m-d H:i:s', $value);
    return $c->toW3cString();
}
```

Above accessor produces a well formatted output for X attribute (i.e. `2017-02-11T19:20:44+00:00`)

**Comment by driesvints** [comment]
You answered your own question. You can indeed use an accessor or mutator for this :)
