### ISSUE TITLE
terminate() method from middleware not called

### ISSUE THREAD

**Issue by meness** [laravel/lumen-framework#571]
_Lumen Version: 5.4.4_

I register the middleware as global one by following line into `bootstrap/app.php`:
```php
$app->middleware([
    App\Http\Middleware\ResponseLoggerMiddleware::class,
]);
```

`handle()` will be called as expected but `terminate()` will not.

And, the middleware is:
```php
namespace App\Http\Middleware;

use App\Jobs\LogResponseJob;
use Closure;

class ResponseLoggerMiddleware {

    public function handle($request, Closure $next) {

        return $next($request);
    }

    public function terminate($request, $response) {

        // dd('called');
    }
}
```

**Note:** I'm not using the middleware along with routes because I know it is registered globally.

**Comment by vwmoose** [comment]
Same here, can't seem to get terminate() to work even though handle() is called.

**Comment by dreamysmurf** [comment]
The `dd` won't work because at the point where `terminate` is called the response is already returned, have you tried `Log`?

**Comment by matrixn** [comment]
I have the very same issue, lumen framework 5.4 with dingo/api loaded and this code in middleware 

`
<?php
namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Log;

class Logging
{

	public function handle($request, Closure $next)
	{
		Log::info("Accessing [" . __FUNCTION__ . "]");
		return $next($request);
	}

	public function terminate($request, $response)
	{
		Log::info("Accessing [" . __FUNCTION__ . "]");
	}
}
`


Apparently the terminate is never called... perhaps i am doing something wrong.. here is the entry in bootstrap/app.php

`
$app->middleware([
	'logging' => App\Http\Middleware\Logging::class,
]);
`

handle works just fine..but terminate is never hited.

I've also tried to register the middleware on route and declare it in route for testing purpose..but same issue is happening, handle is hit but not terminate.

Can someone point to me where I'm doing wrong? 

Thanks

**Comment by thiagomarini** [comment]
Same here, handle works fine but terminate is never called. Weirdly enough terminate is called when running tests 🤕

**Comment by driesvints** [comment]
Seems to be fixed in the latest release. Please update to 5.7.

**Comment by phannaly** [comment]
I'm using Laravel 5.7.10 and still get this issue. It only gets called on test
