### ISSUE TITLE
Ability to configure log monog

### ISSUE THREAD

**Issue by b3njamin** [laravel/lumen-framework#58]
Currently it defaults to writing to lumen.log, would be good if this is customizable out of the box. Would make it easier to use with services like heroku or with docker.

**Comment by nlogachev** [comment]
Already possible. For example, to log to stdout:

```php
$logger = $app->make(\Psr\Log\LoggerInterface::class);
$logger->popHandler();
$logger->pushHandler(new \Monolog\Handler\ErrorLogHandler());
```

**Comment by austin881** [comment]
@entreprenik2, Where does one put this code? And how do I use it? `$logger->debug()`?

I too would like my `Log:debug()` to go to standard streams (`stderr` or `stdout`) because I'm running in Docker containers and don't want anything written to file.

**Comment by entreprenik2** [comment]
@austin881 You can put it at the top of your `routes.php` file if the app is simple enough, or basically anywhere that will get called on every request before routes are processed, for example `App\Providers\AppServiceProvider`.
