### ISSUE TITLE
visit uri /v1.0/profile and /v1.0/profile/ return different in lumen 5.4.5

### ISSUE THREAD

**Issue by liugj** [laravel/lumen-framework#582]
visiting by uri  "/v1.0/profile", it's works. but I visit by   "/v1.0/profile/", it's return 404
I found  difference is in file src/Concerns/RoutesRequests.php function parseIncomingRequest  between 5.4.5 and 5.4.4 
5.4.4
```
    protected function parseIncomingRequest($request)
    {   
        if ($request) {
            $this->instance(Request::class, $this->prepareRequest($request));

            return [$request->getMethod(), $request->getPathInfo()];
        } else {
            $this->instance(Request::class, Request::capture());

            return [$this->getMethod(), $this->getPathInfo()];
        }   
    }
```
5.4.5
```
    protected function parseIncomingRequest($request)
    {   
        if (! $request) {
            $request = Request::capture();
        }   

        $this->instance(Request::class, $this->prepareRequest($request));

        return [$request->getMethod(), $request->getPathInfo()];
    }  
```

**Comment by Except10n** [comment]
I met the same problem

**Comment by hakuno** [comment]
The "/v1.0/profile" is the correct browser convention currently.

For instance, "/v1.0/profile?id=10" is right. However. "/v1.0/profile/?id=10" is fixed by the browser.

Take into account.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
