### ISSUE TITLE
Use utfmb4 charset as default

### ISSUE THREAD

**Issue by sijad** [laravel/lumen-framework#587]
laravel uses utfmb4 [by default](https://github.com/laravel/laravel/blob/master/config/database.php#L49-L50)
in laravel document it has been [mentioned](https://github.com/laravel/docs/blob/5.4/migrationas.md#index-lengths--mysql--mariadb)

lumen also should uses this setting as well or at least it should be mentioned in Lumen document.

**Comment by GrahamCampbell** [comment]
Please send a PR to do the docs, thanks. :)

**Comment by sijad** [comment]
changing default setting isn't a better solution?

**Comment by GrahamCampbell** [comment]
Or, change the default here. Send a PR to do whatever you think is best, and Taylor will review it.
