### ISSUE TITLE
What is the long term support for Lumen?

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/lumen-framework#59]
I'm building out microservices using Laravel right now. I'd like to use Lumen because I don't need views. Should I switch over to Lumen?

Is there a swift way to go from lumen to laravel and vice versa? Assuming I don't views, and what not.

**Comment by taiyaei** [comment]
Microframeworks are perfect for microservices, Lumen included. If you want to stay in the Laravel ecosystem, then use Lumen. Alternatively, try out the others, the most popular being Slim and Silex.

> Is there a swift way to go from lumen to laravel and vice versa? Assuming I don't views, and what not.

From the bottom of the Lumen homepage:

> Have a Lumen project you want to upgrade to the full Laravel framework? It couldn't be easier. Since Lumen is powered by Laravel's components, just drop your code into a Laravel installation. You won't have to change a thing.

As for Long Term Support, I imagine it'll be the same as Laravel's support is right now, but don't quote me on that.

**Comment by taiyaei** [comment]
@taylorotwell I said I didn't know for sure in my reply, but my guess here is that Long Term Support for Lumen is the same as Laravel's LTS. Is this correct? I don't want to have said that it (probably) is when it isn't.

**Comment by GrahamCampbell** [comment]
> Laravel's LTS

There are no "LTS" releases of Laravel or Lumen, however, large bugs may be backported to 4.2, and security fixes all the way to 4.0 if needed.

**Comment by taiyaei** [comment]
> There are no "LTS" releases of Laravel or Lumen

Used to be the case, not anymore :) And sorry for the mixup on the definition of LTS, I kind of associate (at least some) security fixes as being partial LTS, but that's a whole other discussion.

https://twitter.com/laravelphp/status/594141694460755969
> Announcement: Laravel 5.1 will be the first Laravel LTS release in the framework’s history.


https://twitter.com/laravelphp/status/594229859531927553
> Lumen 5.1 should kind of inherit the Laravel LTS since it uses most of the same components


Details about what LTS more or less entails:
https://twitter.com/laravelphp/status/594144499422466048
> probably will be bug fixes for 2 years and security fixes for 3  years

Looks like this one can be closed.
