### ISSUE TITLE
Add method makeWith() into Illuminate\Contracts\Container\Container

### ISSUE THREAD

**Issue by wins1908** [laravel/lumen-framework#593]
Hello,
I'm using Container->make($abstract, array $parameters = []) in 5.2.
After upgraded to 5.4, second parameter is removed.
I looked on branch 5.4 and there is another method supported second parameters "makeWith()"
https://github.com/illuminate/container/blob/5.4/Container.php

Could we update container contract on 5.4 to have that method?
Thank you

**Comment by artaex** [comment]
This was fixed in 5.5 (see [Container.php](https://github.com/illuminate/container/blob/5.5/Container.php#L584)).

**Comment by artaex** [comment]
[Fixed in 5.5](https://github.com/illuminate/container/commit/461330325e5cbdc28126db4a5b16624edfa8ad94#diff-067c34cd7490ce67b9fd4ea53f523f5f)

**Comment by wins1908** [comment]
thank you
