### ISSUE TITLE
APP_URL not set in Lumen.

### ISSUE THREAD

**Issue by boonstoppel** [laravel/lumen-framework#595]
Helper function url('/to/path') returns http:///to/path. Looking at the lumen code APP_URL is never set. 

This was reported before bug closed and never addressed:
https://github.com/laravel/lumen-framework/issues/391

**Comment by GrahamCampbell** [comment]
The `url` function was never meant to read that variable, just like it doesn't in laravel?

**Comment by GrahamCampbell** [comment]
Are you referring to this from the web, or cli please?

**Comment by GrahamCampbell** [comment]
Taking a closer look at this, this is not a bug. Lumen doesn't have this feature: https://github.com/laravel/lumen-framework/blob/5.4/config/app.php.
