### ISSUE TITLE
This test did not perform any assertions 

### ISSUE THREAD

**Issue by gavinrobertszeco** [laravel/lumen-framework#596]
Hey all,

Currently creating an API and writing some integration tests and I've been hit with a Risky flag on my tests that use the helper functions within the MakesHttpRequests trait.

    public function test_should_405_if_not_post()
    {
        $this->json('GET', 'oauth/token')->seeJson([
            'message' => '405 Method Not Allowed',
            'status_code' => 405
        ]);
    }

When you look at `seeJson`, you can see there are assertions being made, however PHPUnit flags them as Risky with:

    There was 1 risky test:

    1) AuthenticationTest::test_should_405_if_not_post
    This test did not perform any assertions

    OK, but incomplete, skipped, or risky tests!
    Tests: 1, Assertions: 0, Risky: 1.

Now I know I can disable this within PHPUnit but thought I would check that this is expected?

Thanks

**Comment by gavinrobertszeco** [comment]
Updating to the following removed the Risky status:

    public function test_should_405_if_not_post()
    {
        $this->json('GET', 'oauth/token')->seeJson([
            'message' => '405 Method Not Allowed',
            'status_code' => 405
        ])->seeStatusCode(405);
    }

**Comment by roelywoely** [comment]
+1

**Comment by bgraf-zlab** [comment]
👍 
I experience a similar problem, which I further described [in the laracasts forum](https://laracasts.com/discuss/channels/testing/lumen-using-seejson-reports-this-test-did-not-perform-any-assertions). I tracked it down to assertions being called via `call_user_func` in `MakesHttpRequests:seeJsonContains()` (line 287) – when the methods are being called directly instead, there's no warning about risky tests. I don't know who's to blame here, though ;-).

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
