### ISSUE TITLE
Fatal error: Cannot redeclare class DatabaseSeeder, in seeding

### ISSUE THREAD

**Issue by gauravjain028** [laravel/lumen-framework#600]
When I use Factory helper in my seeds, I get the error on running seeds

Fatal error: Cannot redeclare class DatabaseSeeder .

It was warning yesterday, but after recent update it stopped working. Any idea how to fix that?

**Comment by ArmeniaH** [comment]
This can be related to
https://github.com/laravel/lumen-framework/issues/598

**Comment by laurencei** [comment]
Try updating to Lumen `5.4.6`

Looks like Taylor might have fixed it here: https://github.com/laravel/lumen-framework/commit/d196ab911cf7c5e3b5725d36388ee85b50613105

**Comment by ArmeniaH** [comment]
This issue can be closed

More info 

https://github.com/laravel/lumen-framework/issues/598#issuecomment-292534784

and 

https://github.com/laravel/lumen-framework/commit/d196ab911cf7c5e3b5725d36388ee85b50613105
