### ISSUE TITLE
Event broadcasting with Lumen not working

### ISSUE THREAD

**Issue by michaeldzjap** [laravel/lumen-framework#602]
I am trying to integrate event broadcasting into a fresh Lumen 5.4.6 project using Homestead, but I am not having much luck so far. I am pretty sure I've set everything up correctly. 

If I use `sync` as the queue driver I get a

```
Fatal error: Maximum function nesting level of '512' reached, aborting! in /home/vagrant/Code/lumen-test/vendor/illuminate/container/Container.php on line 685
```

When I use `database` as the queue driver the job does end up in the `jobs` table of my db, but it doesn't get processed at all (it seems not even an attempt is made) and no error is thrown.

The steps I took to enable event broadcasting in Lumen:

1. Set up a queue listener in Homestead using Supervisor. The program I used is:

```
[program:lumen-test]
process_name=%(program_name)s_%(process_num)02d
command=php /home/vagrant/Code/lumen-test/artisan queue:work --sleep=3 --tries=3
autostart=true
autorestart=true
user=vagrant
numprocs=8
redirect_stderr=true
stdout_logfile=/home/vagrant/Code/lumen-test/storage/logs/lumen-test.log
```

2. Registered `EventServiceProvider` and `BroadcastServiceProvider` in `bootstrap/app.php`:

```
$app->register(App\Providers\EventServiceProvider::class);
$app->register(\Illuminate\Broadcasting\BroadcastServiceProvider::class);
```

3. Made sure the queue is up and running by triggering a simple test event (that isn't broadcast). This works fine.

4. Copied the `broadcasting.php` config file from a fresh L5.4 project to the config folder of my Lumen project and loaded it in `bootstrap/app.php`:

```
$app->configure('broadcasting');
```

5. Added the necessary vars in `.env`:

```
QUEUE_DRIVER=database
BROADCAST_DRIVER=log
```

I've included a test project that demonstrates the problem. There is a `/test` GET route that triggers the event to be broadcast.

As far as I understand, I do not need to set up an event listener in case of a broadcast event right? Since the whole idea is that it is broadcast over a web socket. But since I am using the log driver shouldn't the event simply be logged?

[lumen-test.zip](https://github.com/laravel/lumen-framework/files/915597/lumen-test.zip)

**Comment by catalinux** [comment]
Have you tried with 
```
QUEUE_DRIVER=sync
BROADCAST_DRIVER=redis

**Comment by michaeldzjap** [comment]
But I would have to install Redis for that first no? And set up a websocket server. I know how to do all that, but I'd like to get the most simple case working first before moving on to more complicated setups.

I did try Pusher in my "real" project and that didn't work either. Same thing, events ending up in my `jobs` table, but not getting processed.

**Comment by michaeldzjap** [comment]
Ok, by analysing [this](https://github.com/laravel/lumen-framework/issues/500) I have managed to at least get rid of the recursion/nesting error. It turns out you shouldn't register the `BroadcastServiceProvider` yourself in `bootstrap/app.php`, since this is already taken care of (it seems) in `src/Application.php` of the Lumen source. Now when I use

```
QUEUE_DRIVER=sync
BROADCAST_DRIVER=log
```

The broadcasted event gets logged successfully. However, still having the same issue with `QUEUE_DRIVER=database` and `BROADCAST_DRIVER=log` though. The event ends up in my `jobs` table, but nothing get processed (`attempts` column stays at 0). Is this by design perhaps? I.e. can you maybe not use the `database` driver for queue and `log` for broadcast at the same time? Can't really see a reason why this wouldn't be possible though...

**Comment by chimit** [comment]
Hi, @michaeldzjap!
And how did you setup auth routes? I mean `/broadcasting/auth`.

**Comment by chimit** [comment]
Thanks for the answer, @michaeldzjap! It's still possible to implement those routes manually. Echo allows to provide headers in the constructor, so using tokens instead of sessions is possible. Anyway, it would be much better if Lumen provides this by default.

**Comment by mowangjuanzi** [comment]
The solution is 
```php
// bootstrap/app.php
$app->withFacades(false);
```
