### ISSUE TITLE
Service Provider Boot method called before all Register methods called

### ISSUE THREAD

**Issue by Nais777** [laravel/lumen-framework#607]
- Lumen Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: NA

### Description:

According to the **[documentation](https://lumen.laravel.com/docs/5.4/providers#writing-service-providers)** for the `boot()` method in Service Providers: **This method is called after all other service providers have been registered** but I am finding this to not be the case. Instead, the `boot()` method is called immediately after the `register()` method for a given Service Provider.

### Steps To Reproduce:

Create a new `Lumen` app: `Lumen new test-app`.

Enable the `AppServiceProvider` and `AuthServiceProvider` in `bootstrap\app.php`.

In each Service Provider, put `$this->app['log']->info("Booting AppServiceProvider");` in each `boot()` and `register()` methods, replacing `Booting` with `Registering` and `AppServiceProvider` with `AuthServiceProvider` where applicable. Alternativly, you could just write `Booting` or `Registering`.

Run `php artisan list`.

Look in `storage/logs/lumen.log` and you should see something like this:

~~~
[2017-04-19 22:04:50] lumen.INFO: Registering AppServiceProvider  
[2017-04-19 22:04:50] lumen.INFO: Booting AppServiceProvider  
[2017-04-19 22:04:50] lumen.INFO: Registering AuthServiceProvider  
[2017-04-19 22:04:50] lumen.INFO: Booting AuthServiceProvider  
~~~

Attached is a lumen application with the changes already made.

[test-lumen.zip](https://github.com/laravel/lumen-framework/files/938849/test-lumen.zip)

**Comment by hongaar** [comment]
Just ran into the same problem. Seems like this has already been discussed before in https://github.com/laravel/lumen-framework/issues/399. However, this issue was closed early without a concrete answer or solution.

**Comment by GrahamCampbell** [comment]
The docs are incorrect. Registering a service provider at runtime will register and boot it, immediately. The docs are referring to registering a service provider at config time, before the app has started.

**Comment by GrahamCampbell** [comment]
I hope this distinction makes sense.

**Comment by laurencei** [comment]
@GrahamCampbell - is there a way to register a service provider at config time in Lumen, since there is only a `.env` file? Or is the only way to do it at runtime?

**Comment by hackel** [comment]
I just ran into this as well.  The `Laravel\Lumen\Application::register` method makes the existing behaviour pretty damn clear.  I'm just not clear of the advantage of doing it this way.  Lumen seems to ignore the `app.providers` configuration key entirely.  There's no ProviderRepository or anything in Lumen.  I think I'll just switch to Laravel as well.

**Comment by Nais777** [comment]
Can you give an example of "registering a service provider at config time"? Currently, I had to create a separate provider to contain all of my `boot` logic since the `boot` method is called immediately following the `register` method.

**Comment by hongaar** [comment]
@Nais777 that's actually a pretty clever idea.

**Comment by ragboyjr** [comment]
@Nais777 This has been fixed and merged into lumen master.
