### ISSUE TITLE
URLs with a trailing slash result in a 404

### ISSUE THREAD

**Issue by rjmackay** [laravel/lumen-framework#608]
- Lumen Version: 5.4.6
- PHP Version: 5.6

### Description:
Issue #66 is back
When writing in routes.php :
```
$app->get('welcome', function() { return 'Hello'; });
```
It responds to `http://mysite.dev/welcome` but with a trailing slash `http://mysite.dev/welcome/`, the site throws a 404. Unlike Laravel 5, where both URLs are recognised as the same.

**Comment by hakuno** [comment]
The Lumen doesn't use the same route component of Laravel. So it doesn't fix the URL as done somewhere else.

That's OK. See why:

With trailing slash, conventionally a directory:

> http://example.com/foo/

Without trailing slash, conventionally a file:

> http://example.com/foo

Your own browser tend to fix that. Check it out by making one XHR with trailing slash at end. There'll be fixed to be without that.

So, your http://mysite.dev/welcome actually is http://mysite.dev/index.php/welcome that's a file!

**Comment by rjmackay** [comment]
> Your own browser tend to fix that. Check it out by making one XHR with trailing slash at end. There'll be fixed to be without that.

Sure, but browsers are not the only client we need to support. Lumen in particular is often used to build APIs where the client might not be an API.

Anyway. Looks like @Except10n has fixed it.. thanks!
