### ISSUE TITLE
Testing/Concerns/MakesHttpRequests.php is not fully PhpUnit >= 6.0 compatible

### ISSUE THREAD

**Issue by bennsen** [laravel/lumen-framework#609]
- Lumen Version: 5.4.6
- PHP Version: 7.1

### Description:
laravel/lumen-framework/src/Testing/Concerns/MakesHttpRequests.php does not consequently use `PhpUnit\Framework\Assert`. In one case it references `PHPUnit_Framework_Assert` instead of `PHPUnit\Framework\Assert`, see `MakesHttpRequests::seeJsonContains()` while recursively iterating data. 

Here, the follwing is being invoked:
```
call_user_func(['PHPUnit_Framework_Assert', $method], ...
``` 

To be completely PhpUnit >= 6.0 compat, it should be:
```
call_user_func(['PHPUnit\Framework\Assert', $method], ...
``` 

### Steps To Reproduce:
Run UnitTest asserting `$this->seeJsonContains($foo)`, with `$foo` as complex data structure

**Comment by stephen-dunn** [comment]
+1
