### ISSUE TITLE
Support DateTime RFC3339 format on validation rule

### ISSUE THREAD

**Issue by wins1908** [laravel/lumen-framework#611]
- Lumen Version: 5.4.19
- PHP Version: 7.1
- Database Driver & Version: PostgreSQL 9.x

### Description:
Validation failed on checking RFC3339 format of value "2010-01-01T09:09:00Z", which is followed [RFC3339](https://www.feedvalidator.org/docs/error/InvalidRFC3339Date.html), 

### Steps To Reproduce:
Submit value "2010-01-01T09:09:00Z" to a field which has a validation rule:
`$this->validate($request, ['datetime' => ['date_format:'.\DateTime::RFC3339]]);`
a ValidationException will be thrown with message "The datetime does not match the format Y-m-dTH:i:sP."

### Investigation Result:
At method [ValidateAttributes::validateDateFormat](https://github.com/illuminate/validation/blob/v5.4.19/Concerns/ValidatesAttributes.php#L363),
after converted successfully from a string to \DateTime object, there is a comparison between RFC3339 format of \DateTime object and the submitted string, here is "2010-01-01T09:09:00+00:00" and "2010-01-01T09:09:00Z". 
That's why that string is failed validation rule.

### Suggestion:
I suggest to check errors via `\DateTime::getLastErrors()`:
```php
    protected function validateDateFormat($attribute, $value, $parameters)
    {
        $this->requireParameterCount(1, $parameters, 'date_format');

        if (!is_string($value) && !is_numeric($value)) {
            return false;
        }

        $date       = DateTime::createFromFormat($parameters[0], $value);
        $lastErrors = \DateTime::getLastErrors();

        return $date && $lastErrors['warning_count'] === 0 && $lastErrors['error_count'] === 0;
    }
```

**Comment by driesvints** [comment]
Think this is a little too specific but feel free to open a discussion at https://github.com/laravel/ideas to check if others agree with your proposal.

**Comment by sicbb** [comment]
This is clearly a bug. So why is this ticket closed?

**Comment by enso-media** [comment]
I can also confirm this. The problem still exists years later in current Lumen and Laravel versions.
This is definitely a bug, as perfectly fine values according to RFC 3339 gets validated as wrong.

**Comment by driesvints** [comment]
This isn't a bug. We use the underlying PHP DateTime class to validate this. If you really believe this is a bug please file a bug report on the PHP issue tracker.

**Comment by enso-media** [comment]
@driesvints the problem was very detailed explained by @wins1908, and he also delivers a working and correct solution.
Its not a PHP bug, as a generated RFC 3339 string with +00:00 as timezone is as fine and valid as just the letter Z. Both are valid according to the RFC 3339 specification. But your implementation by just comparing two strings cannot reflect this.

**Comment by mpyw** [comment]
This is not a bug in Laravel or PHP, but rather a specification of PHP itself. Fortunately, this has been resolved with a new feature in PHP 8.

- [New `p` date format for UTC `Z` time zone designation - PHP 8.0 • PHP.Watch](https://php.watch/versions/8.0/date-utc-p-format)

The following code works. Unfortunately, there isn't yet a constant like `\DateTime::RFC3339`, so it might be good to replace 'P' with 'p'.

```php
$this->validate($request, ['datetime' => ['date_format:'.strtr(\DateTime::RFC3339, 'P', 'p')]]);
```

**Comment by mpyw** [comment]
Looks to be **NOT** fixed in Laravel 10

- https://github.com/illuminate/validation/blob/394d1b214dee590d65e43bd2c15265ae3927bafb/Concerns/ValidatesAttributes.php#L538-L567

I also believe absolutely this is a Laravel bug.
