### ISSUE TITLE
Regular validation is invalid to chinese characters

### ISSUE THREAD

**Issue by yeoman-chen** [laravel/lumen-framework#615]
- Lumen Version: 5.4.*
- PHP Version: 7.0.5
- Database Driver & Version:mysql 5.6.7

### Description:
Regular validation is invalid to chinese characters. Set From validate rule to either alpha_dash or regular expression: [[A-Za-z0-9_-]], when input "886思密达" verifycation throw

### Steps To Reproduce:
1、 validate rule:
$this->validate($request, [
            'user_name' => 'required|alpha_dash',
        ]);
input：886思密达
result: pass
2、 validate rule:
$this->validate($request, [
            'user_name' => 'required|regex:[[A-Za-z0-9_-]]',
        ]);
input：886思密达
result: pass

what is the reason？ It is the frame bug?

**Comment by brian-lamb-software-engineer** [comment]
im getting a similar issue
```
(3/3) QueryException
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xE8\x89\xBE\xE7\x9C\x9F...' for column 'name' at row 1 (SQL: insert into `users` (`name`,```

```
values (Aizhen Ren 艾真 任, 
```

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
