### ISSUE TITLE
phpunit does not work out of the box

### ISSUE THREAD

**Issue by rickshawhobo** [laravel/lumen-framework#616]
- Lumen Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: None

### Description:
Cannot run phpunit out of the box

### Steps To Reproduce:

Following the lumen installation directions
```
~/.composer/vendor/bin/lumen new test
cd test
chmod a+x vendor/bin/phpunit
./vendor/bin/phpunit
```

```
You need to set up the project dependencies using Composer:

    composer install

You can learn all about Composer on https://getcomposer.org/.
```

Even after running `composer install` it will not work. The only thing that works is if I delete `composer.lock` and `vendor` and run `composer install` again.

**Comment by mikejw** [comment]
Getting this issue as well.

**Comment by linuxjuggler** [comment]
If you have installed lumen using the **lumen [installer](https://github.com/laravel/lumen-installer)** you will face an issue that composer will not link files in bin directory correctly (each time you will face a different issue), you will have to delete the vendor directory and then run `composer install` again.

**Comment by linuxjuggler** [comment]
@rickshawhobo since we identify the issue as a problem with the Lumen *installer* it would be nice if you can close this issue as it has nothing to do with the framework.

thanks

**Comment by rickshawhobo** [comment]
@linuxjuggler The lumen installer project has no way to make a new issue. Can we keep it here for tracking?

**Comment by linuxjuggler** [comment]
@rickshawhobo its not something for me to decide tbh, but I dont think its something will be fixed any soon

**Comment by rickshawhobo** [comment]
Thanks I'll take a look at the installer code and see if I can spot the bug and make a pull request @linuxjuggler

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
