### ISSUE TITLE
request method get from app object is not correct

### ISSUE THREAD

**Issue by shyandsy** [laravel/lumen-framework#619]
- Lumen Version: 5.4.6
- PHP Version:7.1
- Database Driver & Version: MySql 5.6

### Description:
i send an options request to the server, but the 
```
echo $request->method() . "<br>";
```
shows its GET request

### Steps To Reproduce:
modify the App\ProvidersAppServiceProvider;
```
public function register()
    {
        /** @var \Illuminate\Http\Request $request */
        $request = $this->app->make('request');
        echo $_SERVER['REQUEST_METHOD'] . "<br>";
        echo $request->method() . "<br>";
        if($request->isMethod('OPTIONS')) {
            $this->app->options($request->path(), function(){ echo 111;
                return response('OK', 200);
            });
        }
```
then u will see:
echo $_SERVER['REQUEST_METHOD']  shows OPTIONS
but
$request->method()  shows GET

**Comment by GrahamCampbell** [comment]
You need to access the request object from inside boot, or from only inside a callback delayed from executing at register time.

**Comment by GrahamCampbell** [comment]
Ideally, access the request object from the controller.

**Comment by shyandsy** [comment]
i wanna create options request processor globaly

how can i do that

发自我的 iPhone

**Comment by GrahamCampbell** [comment]
Still with a middleware.
