### ISSUE TITLE
Lumen Socialite - Session store not set on request.

### ISSUE THREAD

**Issue by pmventura** [laravel/lumen-framework#620]
- Lumen Version: 5.4.2
- PHP Version: 7.1.4
- Database Driver & Version: MySQL

### Description:
Not sure if this the right place to write the issue since there's no way to put in laravel/socialite repo. Knowing that the lumen, doesn't work in the session. How do I solve this using socialite package in Lumen?

Error: "Session store not set on request".

### Steps To Reproduce:

Access this method

`public function redirectToProvider($provider)
    {
        return Socialite::driver($provider)->redirect();
    }
`

@GrahamCampbell @taylorotwell

**Comment by pmventura** [comment]
@GrahamCampbell do you have any suggestions?

**Comment by F1NaL** [comment]
@pmventura try use 
```
return Socialite::driver($provider)->stateless()->redirect();
```

**Comment by pmventura** [comment]
@F1NaL 

I got an error. Here's the response

`{"message":"Call to undefined method Symfony\\Component\\HttpFoundation\\RedirectResponse::header()","status_code":500}`

**Comment by F1NaL** [comment]
Try ```composer require illuminate/routing```

**Comment by GrahamCampbell** [comment]
> Try composer require illuminate/routing

Definitely should not be needed on Lumen.

**Comment by GrahamCampbell** [comment]
Lumen is not really designed for sessions to work I think?

**Comment by F1NaL** [comment]
As i now Lumen designed for API service. Look to jwt token for auth users

**Comment by pmventura** [comment]
@F1NaL @GrahamCampbell 

Does it mean that there's no way to fix laravel socialite in Lumen?

**Comment by hakuno** [comment]
My Socialite works perfectly

```
    public function redirectToLinkedin()
    {
        return Socialite::driver('linkedin')->stateless()->redirect();
    }
```

I do use that with `laravel/socialite` with no extra.

@pmventura  Since that's no bug. I suggest you to close this thread.
