### ISSUE TITLE
Timezone detection

### ISSUE THREAD

**Issue by hakuno** [laravel/lumen-framework#624]
- Lumen Version: 5.4
- PHP Version: 7.0
- Database Driver & Version: Postgres

### Description:
Lumen is unable to detect my timezone. And it's affecting my product.

Ps.: I don't use the dot-env. [You know why](https://github.com/laravel/lumen-framework/pull/617).

### Steps To Reproduce:
`var_dump(date("H:i:s"));`
`var_dump(Carbon\Carbon::now());`

**It always returns UTC.**

What I did to solve? I added a line into bootstrap/app.php to test

`date_default_timezone_set(config('app.timezone'));`

Now I get the correct answer: "America/Sao_Paulo".

### My suggestion:

Someone got to make a PR for that definitely. The problem is found at:

```
    // Application.php
    public function __construct($basePath = null)
    {
        date_default_timezone_set(env('APP_TIMEZONE', 'UTC'));
```

The solution is:

```
    // Application.php
    public function __construct($basePath = null)
    {
        date_default_timezone_set(env('APP_TIMEZONE', config('app.timezone', 'UTC')));
```

Maybe I'll create one tomorrow. It is needed.

**Comment by Azakur4** [comment]
is only add this to ur .env carbon use UTC by default and ignore the php.ini

APP_TIMEZONE=timezone

**Comment by youmingdot** [comment]
`config()` is not available in `Application::__construct()` because it has not been initialized. You can set it in `.env` by `APP_TIMEZONE`.

**Comment by hakuno** [comment]
@youmingdot  I can't cache `dot-env` with Lumen. And it gives me runtime problems. So I removed it. My app depends on `config` function only. The core must work with both.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
