### ISSUE TITLE
Lumen guards broken in AuthServiceProvider

### ISSUE THREAD

**Issue by Azakur4** [laravel/lumen-framework#625]
- Lumen Version: 5.4.6
- PHP Version: 7.1
- Database Driver & Version: Mysql

### Description:
Can't capture the request in the boot function of AuthServiceProvider class, actually this is happen with the last fix on the container bound position https://github.com/laravel/framework/commit/778b1ff0d7d3227f178344a6621edbd999770b4d

In laravel, the request is instantiate from the beginning and when this pass for the instance method of the container class the object is updated but in lumen this don't happen cuz when we call to the refresh method of the container the request object never was instantiated before and with this in the AuthProviderService we get a empty Request object.

### Steps To Reproduce:

- This is easy get a clean installation of Lumen 5.4.6
- Uncomment AuthServiceProvider in bootstrap/app.php
- Go to app/Providers/AuthServiceProvider.php and dump the Request object inside of the closure in viaRequest call
- After that make a http request to ur installation and pass any header

PD: this is bad cuz i have a system with JWT authentication and i can't validate any user of my system cuz i can't capture the token in the header of the request.

**Comment by mstaack** [comment]
@Azakur4 you should use a middleware for that....don't use request class in your service provider

**Comment by Azakur4** [comment]
actually i don't create a Request object in the AuthServiceProvider, i follow the example of the lumen boilerplate that he use the request objecte inside the closure of viaRequest method see this:

https://github.com/laravel/lumen/blob/master/app/Providers/AuthServiceProvider.php#L26-L39

**Comment by mstaack** [comment]
and what gives `$request->headers`?

**Comment by Azakur4** [comment]
return and empty array `[]`

**Comment by Azakur4** [comment]
@taylorotwell some help with this pls

**Comment by Mathius17** [comment]
I'm having the same problem after I updated  the dependencies (`lumen-framework` from 5.4.6 to 5.4.7)

**Comment by Mathius17** [comment]
@Azakur4 How did you manage to solve the issue?

**Comment by Azakur4** [comment]
i put this line in my composer.json

section `require`

"illuminate/container": "5.4.19"

in that version of the container all is working after that the problem appear.

**Comment by Mathius17** [comment]
Thank you @Azakur4! I discovered that my issue was with an external package but thanks for the tip anyway!

**Comment by catalinux** [comment]
@Azakur4 

I had a similar problem , when my request was not yet binded. When do you register your code? In boot or in register method?

**Comment by Azakur4** [comment]
@catalinux in boot

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
