### ISSUE TITLE
[IMPROVMENT] file type of .env to .env.ini

### ISSUE THREAD

**Issue by ZiperRom1** [laravel/lumen-framework#627]
- Lumen Version: 5.4
- PHP Version: 7.X

Hello there, first Lumen is such a nice framework to build API : thanks for this awesome tool !

I have a question / suggestion, why the `.env` file that contains many useful parameters is not a `INI` file ?
INI file extension would allow the file to be more structured and also would have a pretty highlighting in IDE and could also contain comments etc ...
PHP use this system with the famous `php.ini` file and it is really great.

I know you can pass config parameters in file like `config.php` or stuff like that but you lose the advantages of `.exemple` and the parameters would be spread over multiple config files.

**Comment by hakuno** [comment]
# Why .env?

> You should never store sensitive credentials in your code. Storing configuration in the environment is one of the tenets of a twelve-factor app. Anything that is likely to change between deployment environments – such as database credentials or credentials for 3rd party services – should be extracted from the code into environment variables.
Basically, a .env file is an easy way to load custom configuration variables that your application needs without having to modify .htaccess files or Apache/nginx virtual hosts. This means you won't have to edit any files outside the project, and all the environment variables are always set no matter how you run your project - Apache, Nginx, CLI, and even PHP 5.4's built-in webserver. It's WAY easier than all the other ways you know of to set environment variables, and you're going to love it.


Source [phpdotenv](https://github.com/vlucas/phpdotenv)

**Comment by ZiperRom1** [comment]
So `ini` file cannot be parsed like a `.env` file to get the values from ?

There is a simple built in PHP function [parse_ini_file](http://php.net/manual/en/function.parse-ini-file.php) which is perfect to get parameters values from a file, even with type casting if you want.

**Comment by GrahamCampbell** [comment]
I think .env if fine. If you want to use another library that supports ini, that's still fine, you can do that. There will not be anything built into the core though.
