### ISSUE TITLE
Issue regarding middleware parameters

### ISSUE THREAD

**Issue by henninghorn** [laravel/lumen-framework#63]
In middleware in Laravel 5 you can add middleware specific parameters like this:

````
// In your routes
Route::group(['middleware' => 'acl', 'role' => 'admin'], function(){});

// In your middleware
$request->route()->getAction()['role'];
````

In Lumen $request->route()->getAction() doesn't exists.
To replicate the Laravel 5 behaviour, you would to this:

````
$request->route()[2]['role'];
````

**But** you can't add the middleware parameter in a $app->group, like so:
````
$app->group(['middleware' => 'acl', 'role' => 'admin'], function(){});
````

Instead you have to add the parameter to your specific route, like this:
````
// Routes
$app->group(['middleware' => 'acl'], function()
{
	$app->get('roles', ['uses' => 'App\Http\Controllers\RoleController@index', 'role' => 'admin']);
});

// Middleware
$request->route()[2]['role'];
````

I would like to be able to add the additional middleware parameters in a route group (like in above L5 example), or within a controller like this: $this->middleware('acl', ['role' => 'admin']);

I'm not sure where to look in order to create/correct this behaviour in Lumen, but I would grate full if this could be added.

Thank you for reading this.

Examples of use in Laravel 5:
- http://www.jeffmould.com/2015/04/22/pass-parameters-to-middleware-in-laravel-5/
- https://github.com/kodeine/laravel-acl/blob/1.0/src/Kodeine/Acl/Middleware/HasPermission.php

**Comment by lukasgeiter** [comment]
Already implemented for 5.1 #8524

**Comment by lukasgeiter** [comment]
Middleware parameters have been implemented for Laravel 5.1 (laravel/framework#8524) and since Lumen uses the same components I'm pretty sure it will become available for the micro-framework as well.

**Comment by henninghorn** [comment]
I see, I hope it will be available in Lumen as well.
Thank you for your contribution.

**Comment by GrahamCampbell** [comment]
This is on our roadmap, yes.

**Comment by prograhammer** [comment]
I was looking for `getAction` in Lumen as well, I use it to change target controllers during middleware.

**Comment by parallelaus** [comment]
Any ideas when this will be implemented. Currently this issue is stopping us from moving all our API's to Lumen

**Comment by henninghorn** [comment]
@parallelaus 

Seems to have been implemented if you look at the docs:
- https://lumen.laravel.com/docs/5.4/middleware#middleware-parameters
