### ISSUE TITLE
Is Lumen dead?

### ISSUE THREAD

**Issue by deividaspetraitis** [laravel/lumen-framework#636]
Hey folks.

Just noticed about quite large amount open issues here and project has only few commits per month in average comparing with Laravel repo https://github.com/laravel/framework/commits/5.4

Is Lumen still actively maintained or is it dead?

**Comment by GrahamCampbell** [comment]
Not dead, just works fine (apart from the open issues, for which we'd love PR fixes), and pulls in the good stuff from Laravel. :)

**Comment by atapatel** [comment]
@GrahamCampbell  Seems like this article is misleading https://jason.pureconcepts.net/2017/02/lumen-is-dead-long-live-lumen/ . 

Thank you for your clarification.
