### ISSUE TITLE
Trailing slashes in routes not allowed anymore

### ISSUE THREAD

**Issue by bastuijnman** [laravel/lumen-framework#639]
- Lumen Version: 5.4.6
- PHP Version: 7.0.18
- Database Driver & Version: N/A

### Description:
Hey guys,

We were running into an interesting issue where accessing one of our API routes with a trailing slash from our client library. When running on Lumen version 5.4.4 this was running fine, but for some reason it was breaking on 5.4.6 (generating a `404` response).

After some debugging we noticed that in the following commit: 83fd12f4bc5ca9d8bc16ec341838e5086edf4c0c
The `getPathInfo` and `getMethod` methods are removed from the `RouteRequest` class. In the `5.4.4` version, when the incoming request is parsed without a given request object the `getPathInfo` method will strip any trailing slash from the given request path retrieved from the captured request object.

In version `5.4.6` the flow is remodeled a bit so the `getPathInfo` method is always called on the request object itself, which is a Symfony HttpFoundation request. In the HttpFoundation request object the trailing slash is not trimmed and thus the response will be a `404` as the route path can not be found.

I was just curious as to whether this was a deliberate decision (and thus you consider trailing slashed to be treated as part of the route) or if this slipped under the radar.

Thanks,

Bas Tuijnman
24i

### Steps To Reproduce:
* Use `5.4.4`
* Add route returning a valid response
* Access using `/route/`
* Observe response being returned correctly with `200` status code
* Switch to `5.4.6`
* Access using `/route/`
* Observe response status code being `404`

**Comment by Except10n** [comment]
#613

**Comment by bastuijnman** [comment]
Right, so this will be fixed in `5.4.7` correct?

**Comment by Except10n** [comment]
I guess maybe next month, Lumen 5.5
