### ISSUE TITLE
`mix()` is missing

### ISSUE THREAD

**Issue by rtheunissen** [laravel/lumen-framework#644]
`mix()` is part of Illuminate\Foundation which isn't part of lumen-framework.

**Comment by GrahamCampbell** [comment]
I think this is fine to be honest. Lumen is really meant for small APIs.

**Comment by allanfreitas** [comment]
@rtheunissen , I've made a repo example, I've done this once :) 
I've updated to 5.4 and laravel-mix 1.4

@GrahamCampbell I agree with you, but I made it one time.

Its a simple View for SPAs :)

https://github.com/allanfreitas/lumenwithmixandreact

**Comment by rifton007** [comment]
Same problem as @rtheunissen with Lumen 6.x and Laravel Mix 5.x
