### ISSUE TITLE
5.5 setRouteResolver no support in Illuminate\Http\Request

### ISSUE THREAD

**Issue by Except10n** [laravel/lumen-framework#650]
- Lumen Version: 5.5.0
- PHP Version:7.2
- Database Driver & Version: NAN

### Description:
$request['xxxxxx']  throw an exception, 

> Call to a member function parameter() on array

Lumen set the resolver will return one array
```
$this->currentRoute = $routeInfo;

$this['request']->setRouteResolver(function () {
    return $this->currentRoute;
});

```

Illuminate\Http\Request > __get()  > route()  call parameter on array
```
$route = call_user_func($this->getRouteResolver());

        if (is_null($route) || is_null($param)) {
            return $route;
        }

        return $route->parameter($param);
```

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
