### ISSUE TITLE
Undocumented APP_TIMEZONE env option

### ISSUE THREAD

**Issue by martinsik** [laravel/lumen-framework#652]
- Lumen Version: *
- PHP Version: *
- Database Driver & Version: *

### Description:
 Maybe I'm just blind but I didn't find any documentation regarding `APP_TIMEZONE` variable in `.env`. I just noticed its behavior has changed recently between `5.4.6` and `5.4.7` and now it shouldn't override the default timezone.

https://github.com/laravel/lumen-framework/blob/v5.4.6/src/Application.php#L83

https://github.com/laravel/lumen-framework/blob/v5.4.7/src/Application.php#L83

**Comment by hakuno** [comment]
That's okay.

Because it must not override with `UTC` when no _dotenv's_ is found.

The app environment has other directives from **PHP.INI** and `configure`/`config` functions that should be respected too.
