### ISSUE TITLE
Fatal exceptions are handled twice

### ISSUE THREAD

**Issue by tobiassjosten** [laravel/lumen-framework#657]
- Lumen Version: 5.5
- PHP Version: 7.0.22
- Database Driver & Version: n/a

### Description:
When a controller throws a fatal exception it'll be sent to and reported/rendered by the exception handler twice, duplicating the output.

In my example I have a [`CrashController`](https://github.com/tobiassjosten/lumen-exception-bug/blob/master/app/Http/Controllers/CrashController.php) which triggers a `SoapFault`. It's sent to my exception [`Handler`](https://github.com/tobiassjosten/lumen-exception-bug/blob/master/app/Exceptions/Handler.php) which renders an *"i"*.

Expected output: i
Actual output: ii

This also duplicates any logging you might have in the `report()` method of your handler.

### Steps To Reproduce:
See [lumen-exception-bug](https://github.com/tobiassjosten/lumen-exception-bug) for an example.

**Comment by themsaid** [comment]
<img width="1194" alt="screen shot 2017-09-25 at 8 40 04 pm" src="https://user-images.githubusercontent.com/4332182/30824794-f19dbf68-a230-11e7-98e1-dd464d16b163.png">
<img width="466" alt="screen shot 2017-09-25 at 8 40 11 pm" src="https://user-images.githubusercontent.com/4332182/30824793-f19a1b88-a230-11e7-8c14-dc983399d171.png">

**Comment by tobiassjosten** [comment]
@themsaid Are you using PHP's built-in webserver? `php -S '127.0.0.1:8000' -t public`

**Comment by themsaid** [comment]
@tobiassjosten nope I'm running on laravel valet.

**Comment by tobiassjosten** [comment]
@themsaid Sorry, I was being vague – could you try PHP's built-in webserver and see if you get the bug then? That's what I'm using locally when it hits me.

Also, are you on PHP 7.0 or later?

**Comment by tobiassjosten** [comment]
Here's another example of this error, @themsaid: https://github.com/tobiassjosten/lumen-exception-bug/commit/b29dfdd54716c3854e6476239f203273f61bb12e

When visiting that new controller you'd expect to get a "x" response but instead you get a "xi" response. This is because the registered shutdown function kicks in, detects an "uncaught exception", and thus calls the exception handler to create a response for it (the "i" part).

The problem here is that `new \SoapClient('asdf')` (and others, I'm sure) triggers an error that seems to be treated differently to exceptions by PHP. Even if they're caught and handled they still remains in `error_get_last()` and so the shutdown handler does its thing.

With this new information I agree my PR wasn't the best approach. I'd instead suggest to target the shutdown function:

- Either have it be more intelligent (perhaps checking `headers_sent()` triggering a second round).

- Or strip the final catch behaviour from the shutdown function and handle all exceptions and errors solely in `RoutesRequests::dispatch()`.

Let me know what you think. I'd be happy to roll a new PR!

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
