### ISSUE TITLE
URLs with trailing slashed not recognized as in Laravel 5

### ISSUE THREAD

**Issue by skovmand** [laravel/lumen-framework#66]
When writing in routes.php in Lumen 5.0.8:

```$app->get('welcome', function() {
return 'Hello';
});```

It responds to ```http://mysite.dev/welcome``` but with a trailing slash ```http://mysite.dev/welcome/```, the site throws a 404. Unlike Laravel 5, where both URLs are recognised as the same.

One example problem is that I use the class ```LengthAwarePaginator``` with the method ```nextPageUrl()``` which generates an URL with a trailing slash.

**Comment by Peleg** [comment]
i think this became an issue again in 5.4.5. when https://github.com/laravel/lumen-framework/pull/575 was merged it overrode the changes from https://github.com/laravel/lumen-framework/pull/69/commits/0665219d219659f452ea4dda4d85a9a09de78c75. i wonder if we now need a solution similar to the one in Laravel (see https://github.com/laravel/framework/commit/7670d5c9462d5a34295cc5967b0d420cb7a5e6a0)

fwiw, 5.4.4 still works for now
