### ISSUE TITLE
Custom Request object is overridden by default Illuminate\Http\Request

### ISSUE THREAD

**Issue by deividaspetraitis** [laravel/lumen-framework#663]
- Lumen Version: 5.5.x
- PHP Version: 7.1
- Database Driver & Version: N/A

### Description:

I have extended default Illuminate\Http\Request object and binded my custom Request to IoC container. When using phpunit default Illuminate\Http\Request is used instead of binded custom request object that causes creating empty Request object without any data and tests to fail.

### Steps To Reproduce:

1. Extend default` Illuminate\Http\Request`
2. Bind custom `Request` to IoC container.
3. Run phpunit tests where request payload is used ( POST, PATCH, etc ).

**Comment by deividaspetraitis** [comment]
Since my PR was rejected as "a breaking change" please see gist to solve this issue by extending and overriding some classes rather editing Lumen`s source: https://gist.github.com/deividaspetraitis/e24d5151bce9102df78c3fc2adda01bd

**Comment by jgrossi** [comment]
Hey @deividaspetraitis I'm experiencing the same issue. I'm using Laravel's API Resource (5.5) in Lumen, and all `$request` I get in `toArray($request)` are empty. Then I have to get the request again from the service container.

I'm gonna take a look in your gist solution. Thanks for that.
