### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by nasyrov** [laravel/lumen-framework#666]
- Lumen Version: 5.5.x
- PHP Version: 7.1.9
- Database Driver & Version: postgresql 9.6.5

### Description:

Hi guys,

It seems like there is a possible memory leak issue here. We've spotted it once we started to receive quite a lot of traffic. I've tried to profile the app with Blackfire and found that the most memory consuming method is `Composer\Autoload\includeFile`. Any help would be appreciated.

![Memory](https://user-images.githubusercontent.com/1330477/31270513-99f1416e-aa7c-11e7-8c54-6f98711d1057.png)

![Profile](https://user-images.githubusercontent.com/1330477/31270567-c764fe2e-aa7c-11e7-95a6-242e89e4c6f4.png)

### Steps To Reproduce:

1. Deploy the app on Heroku
2. Watch how the memory consumption grows with time

**Comment by ebuildy** [comment]
Hello, if it's really a problem on your server, and you use php-fpm, you can tune the php-fpm pool in order to re-spawn workers faster.

By decreasing ``max_request`` 

(this is not fixing it, but at least decrease the memory leaked).

**Comment by hakuno** [comment]
No error message?

Try update your PHP environment. It has [updates](http://www.php.net/ChangeLog-7.php#7.1.10) like these:

> Fixed bug #75042 (run-tests.php issues with EXTENSION block).
> Fixed bug #74631 (PDO_PCO with PHP-FPM: OCI environment initialized before PHP-FPM sets it up).
> Fixed bug #75152 (signed integer overflow in parse_iv).
> Fixed bug #75097 (gethostname fails if your host name is 64 chars long).

Check it out.

**Comment by nasyrov** [comment]
Thanks @hakuno & @ebuildy!

I tweaked opcache and realpath cache sizes and the situation become a bit better:
realpath_cache_size = 16k
opcache.memory_consumption = 32

![screen shot 2017-10-25 at 16 44 10](https://user-images.githubusercontent.com/1330477/32008321-d31e4c58-b9a3-11e7-80cc-cce779773b43.png)

It might look like a problem with php garbage collector...

**Comment by ebuildy** [comment]
Do you use external library such Imagick?

**Comment by nasyrov** [comment]
@ebuildy Nope, nothing heavy going on during the request. During the request, the following happens:
- dispatch a new job (in the queue) where I save an incoming payload to the database
- analyze the payload (might execute one SQL query where I perform COUNT)

**Comment by ebuildy** [comment]
So you have to dig ;-)

Step by step, disable X features of your app (maybe the SQL connection first), try, re-enable X features , try etc... could be interesting for others.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
