### ISSUE TITLE
Empty Request object in Resource when testing

### ISSUE THREAD

**Issue by jgrossi** [laravel/lumen-framework#667]
- Lumen Version: 5.5.1
- PHP Version: 7.1.8 
- Database Driver & Version: MariaDB 10.2.9

### Description:
When testing and making a request to a specific route, inside the Controller action, using the method injection for Request, I get all information I need:

```php
public function login(Request $request) // $request OK
```

But inside the `Resource` object, in all methods I receive it as a parameter, like `toArray($request)` or `with($request)`, this `$request` object is empty, no route information, no parameters, no path, nothing.

Then I have to get the request again from the service container:

```php
public function with($request) // empty
{
    $request = app(Request::class); // correct

    return $request->is('auth/login') && $this->jwtToken ?
        ['token' => $this->jwtToken] : [];
}
```

### Steps To Reproduce:

1. Create a test case with a call to an endpoint like `/foo`.

```php
$router->get('/foo', function () {
    $resource = App\User::find(1); // or any other model instance

    return new App\Http\Resource\Foo($resource);
});
```

Test case:

```php
public function test_resource_empty_request_object()
{
    $this->json('GET', '/foo');
}
```

2. Make the response a `Response` instance, like `FooResource` for example.

```php
namespace App\Http\Resource;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\Resource;

class Foo extends Resource
{
    /**
     * @param Request $request
     * @return array
     */
    public function toArray($request): array
    {
        $route = $request->route(); // empty
        $route = app(Request::class)->route(); // valid

        return $this->resource->toArray();
    }
}
```

3. Inside the `toArray($request)` method, check that the `$request` is empty, but `app(Request::class)` is not.

### Suggestion

In `Laravel\Lumen\Concerns\RoutesRequests::prepareResponse($response)` method, the request object is empty here (`Request::capture()`), but `app(Request::class)` is not:

```php
$response = $response->toResponse(Request::capture());
```

The `SymfonyRequest::createFromGlobals()` is always returning empty data, then the returned request is always empty.

If I change from `Request::capture()` to `app(Request::class)` it works, the `$request` in `Resource::toArray($request)` is not empty anymore.

```php
$response = $response->toResponse(app(Request::class));
```

### Related Issues

I think this "binding" issue is causing others issues with URL when testing. 

For example, doing `$this->json('GET', '/foo/bar')` works great, but `$this->json('GET', route('foo'))` (named route) returns something like `http://:/foo/bar`, without the correct base URL. The request object is empty as well.

**Comment by dunice** [comment]
The same here.

**Comment by dvdmarchetti** [comment]
Take a look at my workaround to fix the binding issue (#513).
Then let me know if this helped fixing your problem, otherwise I'll dig deeper into it.

**Comment by cdarken** [comment]
@dvdmarchetti your fix doesn't work for the main issue, which is the empty request, only the url generation is fixed.

**Comment by driesvints** [comment]
I can reproduce this. Welcoming PRs for this.
