### ISSUE TITLE
Basepath is set to public directory

### ISSUE THREAD

**Issue by tobias-kuendig** [laravel/lumen-framework#67]
Since [support for built-in PHP server](https://github.com/laravel/lumen-framework/commit/e5e4ac6e082c153c5f9581f6236222a2516b6f26) has been added, my `basepath` is set to `public/`. 

This triggers the following error on every pageload since Monolog is looking for the log file in the wrong directory. 
> [Thu Apr 30 20:31:00 2015] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/project/**public**/storage/logs/lumen.log" could not be opened: failed to open stream: No such file or directory' in /var/www/project/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84

When removing the added `|| php_sapi_name() === 'cli-server'` from the above linked commit, everything works as expected. The `basepath` is now set to `/var/www/project/`.

I am running my app on Ubuntu 15.04 via `php artisan serve`. `php_sapi_name()` returns `cli-server`.

> PHP 5.6.7-1+deb.sury.org~vivid+1 (cli) (built: Mar 24 2015 11:23:09)

**Comment by electrickite** [comment]
Have you tried instantiating Lumen in app.php like this?

    $app = new Laravel\Lumen\Application(
        realpath(__DIR__.'/../')
    );

See https://github.com/laravel/lumen/commit/d1b9f866c30a8d93e8a118effd50b54dd39fd90e

**Comment by tobias-kuendig** [comment]
This has fixed the problem! Thank you very much for pointing that out.

**Comment by creator4ever** [comment]
I set  <code>realpath(__DIR__.'/../')</code>
But didn't work for me My basepath is still shown public/.

PHP 5.4.14 Windows 7
