### ISSUE TITLE
Updating Lumen to v5.5.2 throws ErrorException in ServiceProvider

### ISSUE THREAD

**Issue by michaeldzjap** [laravel/lumen-framework#670]
- Lumen Version: 5.5.2
- PHP Version: 7.1.10
- Database Driver & Version: MySQL 14.14

### Description:
After updating Lumen to version 5.5.2 and trying to visit my site (using homestead) the following error is thrown:

```
ErrorException
Invalid argument supplied for foreach()

in ServiceProvider.php (line 84)

at Application->Laravel\Lumen\Concerns\{closure}(2, 'Invalid argument supplied for foreach()', '.../vendor/illuminate/support/ServiceProvider.php', 84, array('path' => '.../vendor/illuminate/pagination/resources/views', 'namespace' => 'pagination'))

at ServiceProvider->loadViewsFrom('.../vendor/illuminate/pagination/resources/views', 'pagination')
in PaginationServiceProvider.php (line 16)

at PaginationServiceProvider->boot()

...
```

**Comment by acczefly** [comment]
same

**Comment by acczefly** [comment]
(1/1) ErrorExceptionInvalid argument supplied for foreach()
--
in ServiceProvider.php (line 84)
at Application->Laravel\Lumen\Concerns\{closure}(2, 'Invalid argument supplied for foreach()', '/data/projects/live/vendor/illuminate/support/ServiceProvider.php', 84, array('path' => '/data/projects/live/vendor/illuminate/pagination/resources/views', 'namespace' => 'pagination'))in ServiceProvider.php (line 84)
at ServiceProvider->loadViewsFrom('/data/projects/live/vendor/illuminate/pagination/resources/views', 'pagination')in PaginationServiceProvider.php (line 16)
at PaginationServiceProvider->boot()
at call_user_func_array(array(object(PaginationServiceProvider), 'boot'), array())in BoundMethod.php (line 29)
at BoundMethod::Illuminate\Container\{closure}()in BoundMethod.php (line 87)
at BoundMethod::callBoundMethod(object(Application), array(object(PaginationServiceProvider), 'boot'), object(Closure))in BoundMethod.php (line 31)
at BoundMethod::call(object(Application), array(object(PaginationServiceProvider), 'boot'), array(), null)in Container.php (line 549)
at Container->call(array(object(PaginationServiceProvider), 'boot'))in Application.php (line 197)
at Application->register(object(PaginationServiceProvider))in Application.php (line 586)
at Application->loadComponent('database', array('Illuminate\\Database\\DatabaseServiceProvider', 'Illuminate\\Pagination\\PaginationServiceProvider'), 'db')in Application.php (line 334)
at Application->Laravel\Lumen\{closure}(object(Application), array())in Container.php (line 749)
at Container->build(object(Closure))in Container.php (line 631)
at Container->resolve('db', array())in Container.php (line 586)
at Container->make('db', array())in Application.php (line 230)
at Application->make('db')in Application.php (line 698)
at Application->withEloquent()in app.php (line 28)
at require('/data/projects/live/bootstrap/app.php')in index.php (line 14)

**Comment by michaeldzjap** [comment]
For anyone needing a temporary fix; I've managed to get everything up and running again by commenting out line 16 of `PaginationServiceProvider` in vendor/illuminate/pagination/PaginationServiceProvider.php

**Comment by Except10n** [comment]
I get the same error, 

Interim Fix
```
$app->configure('view'); 
// before making the call to "DB"
```

**Comment by dani3l** [comment]
happens even if not using DB at all :/

**Comment by footballencarta** [comment]
Someone has issued a pull request here - https://github.com/illuminate/support/pull/56

Hopefully it gets merged soon!

**Comment by nicolas-wallerand** [comment]
is Fix in https://github.com/illuminate/support/releases/tag/v5.5.17

**Comment by nicolas-wallerand** [comment]
@michaeldzjap please, you can close the issue ?

**Comment by michaeldzjap** [comment]
I'm not in a position to verify if it has solved the issue for me at the moment. Not until tomorrow anyway. But if there is a hurry closing this I'm sure someone with enough repo rights can do it instead?

**Comment by nicolas-wallerand** [comment]
ok :-)
