### ISSUE TITLE
config is not accessible by default

### ISSUE THREAD

**Issue by and800** [laravel/lumen-framework#672]
- Lumen Version: 5.5.2

Sorry for possibly duplicated issue, but I looked through the issue list and didn't see anything similar

Contrary to the docs, you can't simply yield `$value = config('app.locale');` and get that value, config requires manual `$application->configure()` calls to load config file.
So it must be either misleading docs, or config autoload problem

**Comment by youmingdot** [comment]
It will be more suitable to use  `$app->configure()`  to save performance, just the document needs to be updated.

**Comment by and800** [comment]
I completely agree with you. Is this repo the right place to report docs issue?

**Comment by hakuno** [comment]
@and800 Take a look at [here](https://github.com/laravel/lumen-docs).

Thanks!

**Comment by mushan0703** [comment]
Thanks!

**Comment by hakuno** [comment]
@mushan0703 If you're okay with it, so don't forget to close this issue. All right?

**Comment by driesvints** [comment]
Made a PR to the docs to make this more clear ^

Thanks for sending this in.
