### ISSUE TITLE
Route infinite loop

### ISSUE THREAD

**Issue by hakuno** [laravel/lumen-framework#673]
- Lumen Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: Postgres 9.6

### Description:
Sometimes I get this error:

> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 8031165417414817424 bytes) in C:\Apache24\htdocs\lirico\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php on line 47

It's not an output of the default framework debug tool.

So I put a blank in the `registerErrorHandling` method on `Laravel\Lumen\Concerns\RegistersExceptionHandlers` and move on.

I see another error again:

> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 8031165417414817424 bytes) in C:\Apache24\htdocs\lirico\vendor\laravel\lumen-framework\src\Routing\UrlGenerator.php on line 225

It refers to

```
$uri = preg_replace_callback('/\{(.*?)(:.*?)?(\{[0-9,]+\})?\}/', function ($m) use (&$parameters) {
    return isset($parameters[$m[1]]) ? array_pull($parameters, $m[1]) : $m[0];
}, $uri);
```

So did I get one infinite loop issue?

### Steps To Reproduce:
Run.

**Comment by themsaid** [comment]
Please share some informative steps to reproduce the issue, otherwise we can't help.

**Comment by hakuno** [comment]
@themsaid You're right. Thanks.

I can reopen this when I get any news about.
