### ISSUE TITLE
Failed to decode response: zlib_decode(): data error

### ISSUE THREAD

**Issue by Mate38** [laravel/lumen-framework#678]
- Lumen Version: 5.5.*
- PHP Version: 7.0

### Description:

I installed PHP, the necessary dependencies like all other times, I installed the composer and all right, however when trying to create a project (`composer create-project --prefer-dist laravel/lumen blog
`) or install the lumen (`composer global require "laravel/lumen-installer"`), I get this error in return.

### Steps To Reproduce:

```
root@ouvidoria:/home/ouvidoria/Lumen# composer create-project --prefer-dist laravel/lumen apiAppOuv
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Installing laravel/lumen (v5.5.0)
  - Installing laravel/lumen (v5.5.0)
    Downloading: 100%         

Created project in apiAppOuv
> php -r "copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info

                             
  [ErrorException]           
  zlib_decode(): data error  
                             

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
```

**Comment by mstaack** [comment]
this is mostly a problem on your sie & or composer NOT lumen
first check: update composer version if you have an old one

**Comment by Mate38** [comment]
I just installed the composer, so it's the last version.

I have seen in some places of the internet that it may be because of the bad connection, but here is not the case.

**Comment by Mate38** [comment]
An interesting thing that happened, this problem occurred in linux Lubuntu, however when trying to install in Windows, everything worked correctly

**Comment by hakuno** [comment]
> An interesting thing that happened, this problem occurred in linux Lubuntu, however when trying to install in Windows, everything worked correctly

@Mate38, does the same php minor version? "..ouvidoria.."? Você é brasileiro? rs Acho que a questão é no ambiente mesmo.

**Comment by Mate38** [comment]
Sou brasileiro sim, os dois estavam trabalhando com o php 7.0, estava instalando em uma VM e esta estava com dhcp, mudei o ip pra manual e funcionou corretamente, muito estranho pois aqui na rede nem firewall não tem e a banda era a mesma com dhcp ou manual, mas bem, resolveu.

**Comment by Mate38** [comment]
I'm a Brazilian yes, both were working with php 7.0, I was installing in a VM and it was with dhcp, I changed the ip to manual and it worked correctly, very strange because here in the network neither firewall does not have and the band was the same with dhcp or manual, but well, resolved.
