### ISSUE TITLE
[Routing] Call to a member function parameter() on array

### ISSUE THREAD

**Issue by abellion** [laravel/lumen-framework#685]
```php
$request->parameter;
// OR
$request->route('parameter');
// OR
$request->route()->getParameter('parameter');
```
Throws `Call to a member function parameter() on array`.

Bumping because all of the other issues are still alive :

https://github.com/laravel/lumen-framework/issues/291
https://github.com/laravel/lumen-framework/issues/650
https://github.com/laravel/lumen-framework/issues/484
https://github.com/laravel/lumen-framework/issues/119
...

**Comment by hakuno** [comment]
Do

`list($found, $routeInfo, $params) = $request->route() ?: [false, [], []];`

Then

`dd($params);`

Is the expected thing on there?

**Comment by yuloh** [comment]
I proposed a fix for this but it was rejected: https://github.com/laravel/internals/issues/71

Suggested workaround: https://github.com/laravel/lumen-framework/issues/484#issuecomment-300170119

Alternatively you can modify the calling code to expect an array:

```php
$param = $request->route()['parameter'] ?? null;
```

**Comment by xxRockOnxx** [comment]
This issue still exists.

**Comment by codefocus** [comment]
Confirming that this issue still exists.

`Call to a member function parameter() on array in vendor/illuminate/http/Request.php:458`

In my case, this was triggered by calling `$request->json->all()` from a Lumen Controller.

**Comment by xxRockOnxx** [comment]
I just read from an issue that Taylor does not consider it as a bug and says Laravel and Lumen is not 100% compatible so it seems like this will not be fixed.

**Comment by MrPatrickHenry** [comment]
Just to confirm this same issue: "/management/stream/{parameter}" in the uri following lumen documentation. i get this error

```
1/1) FatalThrowableError Call to a member function parameter() on array
--
in Request.php line 501
at Request->route('parameter')in Request.php line 665
```

I was breaking things out in to microservice under the impression that lumen can be migrated in to laravel quite easily.

**Comment by abellion** [comment]
Thanks @JacksonIV

**Comment by JacksonIV** [comment]
@abellion Anytime!

**Comment by lloricode** [comment]
this is already fixed, but when running on test is still same issue

**Comment by loordy** [comment]
> 

> hi @abellion
> this is already fixed, but when running on test is still same issue
> 
> Laravel Framework Lumen (5.7.6)
> PHPUnit 7.4.4
> 
> ```
> testing.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function parameter() on array in ...
> ```

did u find any solutions?

**Comment by Aimsam** [comment]
> > 
> 
> > hi @abellion
> > this is already fixed, but when running on test is still same issue
> > Laravel Framework Lumen (5.7.6)
> > PHPUnit 7.4.4
> > ```
> > testing.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function parameter() on array in ...
> > ```
> 
> did u find any solutions?

the same problem .  
use `$request->route()[2]['xxxxx'] ?? null` can hack it

**Comment by lloricode** [comment]
I used this https://github.com/lloricode/lumen-dingo-boilerplate/blob/master/app/Traits/Hashable.php#L22

**Comment by rigoma** [comment]
use `$request->input()`

`dd($request->input())`

then validate like

`if (empty($request->input()))`

and for a certain field

`if (null !== $request->input('queja_estado'))`

**Comment by kanidjar** [comment]
Any update on this? Awful to trick the framework that way...

**Comment by lloricode** [comment]
already fixed here https://github.com/laravel/lumen-framework/pull/882

**Comment by lloricode** [comment]
but not already relaase tag for it
