### ISSUE TITLE
JSON unquoting extraction operator ->> not work

### ISSUE THREAD

**Issue by robcaa** [laravel/lumen-framework#687]
- Lumen Version: 5.5.2
- PHP Version: 7.1.11
- Database Driver & Version: mysql 5.7.20

### Description:
JSON unquoting extraction operator ->> result is null in a select.
Similar issue in laravel here: https://github.com/laravel/internals/issues/804

### Steps To Reproduce:
```
Anything::select("foo->>bar")->get();
```

produce this query:
```
`foo`->'$.">bar"'
```
The chevron is wrong place.

**Comment by hakuno** [comment]
Try

```
$db = app("db");
Anything::select($db->raw("foo->>'bar'"))->get();
```

Ps.: use `raw` or `selectRaw`. Read the documentation.



References

[How to query JSONB, beginner sheet cheat](https://hackernoon.com/how-to-query-jsonb-beginner-sheet-cheat-4da3aa5082a3)
[Raw Expressions](https://laravel.com/docs/5.5/queries#raw-expressions)

**Comment by robcaa** [comment]
Thanks for the tip.

The raw select works if I give the syntax:
```
Anything::select(DB::raw('foo->>"$.bar"'))->get();
```

**But how much more beautiful would be the syntax:**
```
Anything::select("foo->>bar")->get();
```
Another workaround which works with an earlier MYSQL version (5.7 < MYSQL < 5.7.13)
\DB::raw("JSON_UNQUOTE(JSON_EXTRACT(foo, '$.bar'))");

**Comment by hakuno** [comment]
So we see there's no bug actually.

Now it's concerned about a change. I believe they won't want to. Because you've still the `selectRaw` method.

**Comment by driesvints** [comment]
Always up for pr's if you want to see this get added!
