### ISSUE TITLE
Lumen 5.3 config/queue.php retry_after or expire param for database configuration

### ISSUE THREAD

**Issue by mattallan** [laravel/lumen-framework#693]
- Lumen Version: 5.3
- PHP Version: 7.1.11
- Database Driver & Version: MySQL 5.7.18

### Description:

I'm looking to clear up a bit confusion I have with what is the correct param to use in `config/queue.php` when trying to update the job expiration in the database config

For the database config, the [`config/queue.php`](https://github.com/laravel/lumen-framework/blob/5.3/config/queue.php#L42) in your framework uses the `expire` param, but the documentation says to only use the `retry_after` param (link to [docs](https://laravel.com/docs/5.3/queues#job-expirations-and-timeouts)).

I can't find any docs/information on using the `expire` param. So i'm not sure if i should be removing the `expire` and replacing it with `retry_after` or using `expire`.

Any assistance in clearing this up is appreciated :)

---

Here's a snippet of what my config/queue.php looks like.

```
'connections' => [
		'sync' => [
			'driver' => 'sync',
		],
		'database' => [
			'driver'      => 'database',
			'table'       => 'jobs',
			'queue'       => 'default',
			'retry_after' => 310,
                        // 'expire'   => 310,
		],
		
```

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
