### ISSUE TITLE
Lumen Routes not decoded url

### ISSUE THREAD

**Issue by junliuxian** [laravel/lumen-framework#695]
- Lumen Version: 5.5.#
- PHP Version:  7.0.0
- Database Driver & Version:  Mysql 5.6

### Description:
I tested under the laravel routing can be resolved，I know that lumen and laravel use different routes。I also try to find the answer, can not currently found。I think this should be a bug

### Steps To Reproduce:
request url： http://127.0.0.1/article/1%2C2

```
// lumen result :  1%2C2
// laravel result: 1,2
$router->get('article/{id}', function ($id){
    echo $id; 
});

```

I think the result of  1,2 is correct

**Comment by hakuno** [comment]
By the way, what's the response mimetype?

**Comment by junliuxian** [comment]
Actually, I already commented on the response value。

Laravel response content： 1,2
Lumen response content： 1%2C2

I am direct echo. So the response type is text/html

**Comment by pearl1811** [comment]
Basically Query string only we can encode(sender) and decode(receiver). if you encode the url that will not work. Also you have encoded the url wrongly. 

Find the url original encoded url : http%3A%2F%2F127.0.0.1%2Farticle%2F1%2C2

In your case use the url like below

 http://127.0.0.1/article?id%3D1%2C2

$router->get('article', function (){
    dd(app('request')->get('id'));
});

your result is **array(1) { ["id"]=> string(3) "1,2" }**

(OR)

 http://127.0.0.1/article/1,2

$router->get('article/{id}', function ($id){
    echo $id;
});

result is *"1,2**

**Comment by junliuxian** [comment]
The laravel's route is correctly decoded。

**Comment by driesvints** [comment]
Lumen uses nikic/fast-route which behaves slightly different than the Laravel router. You'll have to do some things manually. If you want parameters to be decoded by default start a discussion in nikic/fast-route to see if people are up for the idea. After that a PR could be made.
