### ISSUE TITLE
route() not including URL parameters - is it intended?

### ISSUE THREAD

**Issue by skovmand** [laravel/lumen-framework#70]
Hi!

First of all thank you for the great work with Lumen!

Having a route, e.g.:
```
$app->get('signin', ['as' => 'signin', 'uses' => 'App\Http\Controllers\SomeController@signIn']);
```

When using ```route('signin', ['username' => 'John']);```, the string returned in Lumen 5.0.8 is ```http://mysite.com/signin``` without the username URL parameter. In Laravel 5, the returned value for the same route is ```http://mysite.com/signin?username=John```

Is this a bug or intended functionality?

**Comment by GrahamCampbell** [comment]
I think the router is intentionally simpler.

**Comment by thasmo** [comment]
Does the `route` function use the router for building the URLs?
