### ISSUE TITLE
`$request` in `Resource` class is not the same request as in the container

### ISSUE THREAD

**Issue by simonhamp** [laravel/lumen-framework#702]
- Lumen Version: 5.5.28
- PHP Version: 7.1.12
- Database Driver & Version: n/a

### Description:
When using the `Resource` class to generate a response, it's using a new instance of the `Request`  object, which is scuppering my ability to rely on changes made to the request that I'm hoping to work with in my `Resource` object.

### Steps To Reproduce:
In Lumen, type-hint the `Request` into a controller, modify some input, and return a `Resource` object.

```
// Controller method
public function index(Request $request)
{
    $request->replace(['foo' => 'bar']);
    return new Resource(['test']);
}
```

Then modify `Resource::toArray()` to inspect the `$request` that's passed in and compare it with one from the Container, e.g.:

```
dd($request, Container::getInstance()->make('request'));
```

For this, my first one has an ID of `#167` and my second (the one I want) has an ID of `#104` - they are **not** the same instance. In my case this is very frustrating as the objects are clearly different as I have modified the request in my controller.

After some investigation, I found that it's because `\Laravel\Lumen\Concerns\RoutesRequests::prepareResponse()` is using `Request::capture()`, which is creating a new Request instance instead of reusing the existing container instance. What's the reasoning for this?

### Workaround
My workaround is to modify explicitly call `response()` from my controller, passing in the request:

```
public function index(Request $request)
{
    $request->replace(['foo' => 'bar']);
    return (new Resource(['test']))->response($request);
}
```

Possibly this is the desired behaviour, but I wasn't expecting it so it caught me out. Hopefully this helps someone else out.

**Comment by hakuno** [comment]
It seems okay for me...

```
// Controller
class Controller extends BaseController
{
    function __construct(Tenancy $tenancy) {
        app('request')->replace(['foo' => 'bar']);
        ...
```

So

```
// AnotherController
public function show(Request $request, $tenantIdentifier, $cartorial_dado_id)
{
    dd($request->input('foo'));
    ...
```

The point is that Resource's `response` method enforces ResourceResponse's `toResponse` method:

```
        return tap(response()->json(
            $this->wrap(
                $this->resource->resolve($request),
                $this->resource->with($request),
                $this->resource->additional
            ),
            $this->calculateStatus()
        ), function ($response) use ($request) {
            $this->resource->withResponse($request, $response);
        });
```

We need to pay attention for `with` and `additional` methods like that. Would it be the issue?

And

```
dd($request, app('request'));
```

Both return the same ID request object for me.

You've said

> For this, my first one has an ID of #167 and my second (the one I want) has an ID of #104 - they are not the same instance.

Maybe [this](https://laravel.com/docs/5.5/eloquent-resources#concept-overview) can explain why

> Every resource class defines a toArray method which returns the array of attributes that should be converted to JSON when sending the response. Notice that we can access model properties directly from the $this variable. This is because a resource class will automatically proxy property and method access down to the underlying model for convenient access.

Ps.: I had to convert the param with `collect` helper. Don't you have any problem?

```
return new Resource(collect(['test']));
```

Any news?

**Comment by simonhamp** [comment]
@hakuno I'm not sure you're understanding my issue. Perhaps it's working differently the way you're doing it.

The main thing I found is that if the modified request object is not explicitly passed into the Resource, the underlying behaviour that automatically converts the Resource into a Response actually creates a fresh Request instance using `Request::capture()`.

That means any changes made to the actual request prior to the response being formed are not available inside the Resource class at the moment of preparing the response.

```php
// For POST ['foo' => 'bar']

$request->replace(['foo' => 'baz']);

return $resource; // Inside Resource (or subclass) $request->input('foo') == 'bar'

// vs

return $resource->response($request); // $request->input('foo') == 'baz'
```

This was unexpected for me, but possibly desired and maybe is the right/best way to do it, I'm not sure. Just wanted to flag in case anyone else comes across it and needs some help as it's not a case that's covered in the docs.

As it happens I think my workaround is enough for now. Explicitly passing the modified request object into the `response` method of the Resource solves my issue. Maybe it's a bit edge-case-y and nobody else will experience this, but in case you do, this is how I 'fixed' it at this point in time.

**Comment by hakuno** [comment]
It would be great if we had some reply from @themsaid @GrahamCampbell @tillkruss @taylorotwell and others.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
