### ISSUE TITLE
 Lumen API File Upload is not working

### ISSUE THREAD

**Issue by vickygillsf** [laravel/lumen-framework#706]
- Lumen Version: 5.5.2
- PHP Version:7.1
- Database Driver & Version:

### Description:

Problem is that , Request object is Returning Null when I am sending , Content-Type: multipart/form-data If I change the Content-Type to application/json is working like a charm, I want to get input file from Api Request . any suggestions??

### Steps To Reproduce:

Here is my code I am using Postman to call the service

```

 if( $request->file('image'))
           {
           $file = $request->file('image')->getClientOriginalName();
           $date = new DateTime();
           $d = $date->format('YmdHms').$file;
           $destinationPath ="images/";
           $request->file('image')->move($destinationPath, $d);
           }
           else 
           {
               $d = '';
           }

         $artistWork = ArtistWork::create([      
            'artist_id' => $request->input('artist_id'),    
            'image'=>$d,
                ]);
```

**Comment by hakuno** [comment]
You must set a configuration directive. See below:

upload_tmp_dir ([source](https://secure.php.net/manual/en/ini.core.php#ini.upload-tmp-dir))

> The temporary directory used for storing files when doing file upload. Must be writable by whatever user PHP is running as. If not specified PHP will use the system's default.
> 
> If the directory specified here is not writable, PHP falls back to the system default temporary directory. If open_basedir is on, then the system default directory must be allowed for an upload to succeed.

Cheers.

**Comment by vickygillsf** [comment]
Hey Hakuno,

Thanks for  answer.

`upload_tmp_dir ` is already setup and all users have full permissions  to access the folder.
still not working.

**Comment by msolhao** [comment]
Hey vickygillsf,

Try dumping the $_FILES superglobal with _var_dump_ and see whats inside.
Check if there is a $_FILES['<your_file>']['error'] key that could help you.

Also check your php.ini _max_file_uploads_ and see if the file size is not too big.

http://php.net/manual/en/ini.core.php#ini.upload-max-filesize

**Comment by vickygillsf** [comment]
Hey msolhao,

I think it is a bug, i have deployed services to live server  and i am calling services from my Pc its working fine, but when i call the service from someone other's PC , The Resquest Object is POST Null value, i have tried all methods, `dd{{ }}`,` var_dump(); , print_r()` Request Object still getting null from Service.

Thanks,

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by jk2K** [comment]
please see https://github.com/laravel/framework/issues/13457#issuecomment-341973180, If your content-type is `multipart/form-data`, the data is available via 'php://input'

**Comment by mingalevme** [comment]
Also check `file_uploads` directive in `php.ini`.

**Comment by mmachnicki** [comment]
A bit late and issue closed, but may be useful for anyone who finds this problem.
Make sure to you use Illuminate\Http\Request; 
When using Laravel\Lumen\Http\Request;  $reguest->file('name'); or $request->allFiles();  returns null
