### ISSUE TITLE
Laravel create duplicate rows in database

### ISSUE THREAD

**Issue by Akashverma11** [laravel/lumen-framework#708]
Hello everybody

I'm facing a problem with laravel 5.4. it creates multiple rows in database using both DB or Modal
public function pagecreater(){
        $page=LandingPage::create(['type'=>'2']);
        return view('admin.scratch.landing_page2')->with('page',$page);
    }

**Comment by hakuno** [comment]
Just a thought...

Maybe your JavaScript (jQuery?) is binding your click button twice.

Can you check how many Ajax requests are being sent? Press browser's F12 to open the network tab and listen to.

You need to unbind the button before of binding that again.

Usually the first time sounds okay. But it gets wrong later. Is not?

**Comment by Akashverma11** [comment]
thanks for your support. i will check it

**Comment by hakuno** [comment]
By the way, the `create` method will create a new row. Maybe you want to use `where` instead of.

**Comment by driesvints** [comment]
Please report Laravel issues to the https://github.com/laravel/framework repo. This issue tracker is only for Lumen issues. Thanks!
