### ISSUE TITLE
Unit testing with expectsEvents does not clear \Event facade cache

### ISSUE THREAD

**Issue by nicholas-eden** [laravel/lumen-framework#710]
- Lumen Version: 5.5.2
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
Test cases using `$this->expectsEvents()` does not override the resolved facade instance.

The function will set the instance in App, but Facade has a static cache of aliases that needs to be cleared.

### Steps To Reproduce:

- Use `\Events::fire()` in a function you are testing.
- Call `$this->expectsEvents()` in a test with the proper event.

The test will fail.

- Call `Illuminate\Support\Facades\Facade::clearResolvedInstance('events')` in your test.

The test will pass.

**Comment by driesvints** [comment]
Heya this works for me. Did you register the `EventServiceProvider`?
