### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by VitorVRS** [laravel/lumen-framework#711]
- Lumen Version: 5.5.2
- PHP Version: 7.1.13
- Database Driver & Version: Postgres 9.6

### Description:

Please generate a new release (5.5.3), i need some fixes done since last release (5.5.2).
Dont want to put dev-master in composer file.

Tks

**Comment by hakuno** [comment]
:rocket:  https://laravel-news.com/laravel-5-5-33

My Lumen is updated with.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
