### ISSUE TITLE
Middleware gets Response object instead of value returned

### ISSUE THREAD

**Issue by mbitokhov** [laravel/lumen-framework#712]
- Lumen Version: 5.5.x
- PHP Version: 7.2
- Database Driver & Version: N/A

### Description:
I wanted to have a middleware use the value returned from the controller and format it so we could have metadata alongside the actual return value. But when I tried to get the output of the controller, it returned a response object instead of the Model/Paginator/etc I returned it. I tried to find the location where it's turning it into response, but I got to `laravel/lumen-framework/src/Concerns/RoutesRequest.php` and then I just got lost between what everything was doing

I know I can get the original value via $response->original. But I was wondering if returning the response was done on purpose or if it was just an oversight

### Steps To Reproduce:
```php
class ApiMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        return get_class($next($request));
    }
}
```

This returns "Illuminate\Http\Response"

**Comment by hakuno** [comment]
It's not the purpose.

**Comment by driesvints** [comment]
You're trying to get the class of the `$next` param which is the response object so it's normal that you get this back.

**Comment by mbitokhov** [comment]
I didn't expect the return value for the controller to be a response object, considering I wasn't returning a response object.

Of course as I said previously, the thing I'm actually looking for is `$response->original` or `$response->getOriginalContent()`

Whether or not this was intended, I realized that it's not a good move to change this, because it'll too much of a breaking change

**Comment by saeednikookalam** [comment]
want you know that response is instanceof which a object?
