### ISSUE TITLE
blade not compiling @section or @if @endif

### ISSUE THREAD

**Issue by barhom** [laravel/lumen-framework#713]
- Lumen Version: 5.5
- PHP Version: PHP 7.2.1

I know that "views" was supposedly removed in Lumen. But actually Views works fine in Lumen and it does have illuminate/view.

Now my problem is that Blade is NOT compiling in my production environment. It works fine in Homstead.

All my @include or @if or whatever is simply not compiling and I get all of these statements in plaintext.

{{ $variable }} IS compiling however, just not the @XXXX sections.

Anyone have any idea?

**Comment by nbpalomino** [comment]
Show some files like config, routes, etc.

**Comment by barhom** [comment]
@nbpalomino 

I found the culprit actually. Blade is not compiling because of an error with regex in my production environment.

The problem is in a function of BladeCompiler.php (inside illuminate/view)

**Comment by driesvints** [comment]
Seems like you'll need to fix your production environment in this case.
