### ISSUE TITLE
Config doesn't get updated in QueueManager

### ISSUE THREAD

**Issue by coderNeos** [laravel/lumen-framework#714]
- Lumen Version: 5.5
- PHP Version: 7.2.1
- Database Driver & Version:

### Description:

I've found that 
```php 
Illuminate\Support\ServiceProvider::mergeConfigFrom()
``` 
called from service provider doesn't affect actual config values in QueueManager (and maybe other instances).

I have installed https://github.com/vyuldashev/laravel-queue-rabbitmq. 

After calling 
```php
VladimirYuldashev\LaravelQueueRabbitMQ\LaravelQueueRabbitMQServiceProvider::register() 
```
app['config'] gets updated with correct driver variables, but later when calling 
```php
Illuminate\Queue\QueueManager::getConfig()
```
variables are reverted to those which where set initially in config/queue.php.

As a result our queue is not working, because it doesn't have needed config variables.

### Steps To Reproduce:

Append these lines of code: 

```php
var_dump($this->app['config']["queue.connections.rabbitmq"]);
```
to 
```php
VladimirYuldashev\LaravelQueueRabbitMQ\LaravelQueueRabbitMQServiceProvider::register() 
```

Add these lines of code: 

```php
var_dump($this->app['config']["queue.connections.{$name}"]);
```

to 
```php 
Illuminate\Queue\QueueManager::getConfig() 
```
before:

```php
return $this->app['config']["queue.connections.{$name}"];
```
then execute

```bash
php artisan queue:work
```

**Comment by driesvints** [comment]
This seems like a problem with the library itself. Try posting an issue on their repo and if the problem really lies with Lumen feel free to reply back or open a new issue.

**Comment by nifrasismail** [comment]
Hi, I'm having the same issue, @coderNeos Do you have any update on this

**Comment by coderNeos** [comment]
To fix this issue i've just copied LaravelQueueRabbitMQ config to project config folder and named it "queue.php"
