### ISSUE TITLE
trans() helper can return array and null but @return comment does not reflect this.

### ISSUE THREAD

**Issue by Donatello-za** [laravel/lumen-framework#716]
- Lumen Version: 5.5
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:
This issue causes warnings in IDE's.

The trans() function in `src/helpers.php` should have `array` and `null` added to the return options. Currently the `@return` comment is:

```
@return \Illuminate\Contracts\Translation\Translator|string
``` 

and should be changed to: 

```
@return \Illuminate\Contracts\Translation\Translator|string|array|null
```

It can return an array or null because the function it calls as part of its last return statement can return an array or null:

```php
return app('translator')->trans($id, $replace, $locale);
```

See [illuminate/translation/Translator.php](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Translation/Translator.php):

```php
    /**
     * Get the translation for a given key.
     *
     * @param  string  $key
     * @param  array   $replace
     * @param  string  $locale
     * @return string|array|null
     */
    public function trans($key, array $replace = [], $locale = null)
    {
        return $this->get($key, $replace, $locale);
    }
```

**Comment by driesvints** [comment]
@Donatello-za sent in a pr for this ^
