### ISSUE TITLE
Laravel\Lumen\Console\Kernel::call not updated

### ISSUE THREAD

**Issue by MarcelBuian** [laravel/lumen-framework#720]
- Lumen Version: 5.6.0

### Description:

```
In Kernel.php line 15:
            
Declaration of Laravel\Lumen\Console\Kernel::call($command, array $parameters = Arra  
  y) must be compatible with Illuminate\Contracts\Console\Kernel::call($command, array  
   $parameters = Array, $outputBuffer = NULL)     
```

This line should be updated
https://github.com/laravel/lumen-framework/blob/5.6/src/Console/Kernel.php#L120
 according to contract
https://github.com/laravel/framework/blob/5.6/src/Illuminate/Contracts/Console/Kernel.php#L24

### Steps To Reproduce:

just write `php artisan`

**Comment by Frondor** [comment]
Happens to me as well.

**Comment by hakuno** [comment]
It seems to be fixed 3 hours ago. But the commit is not merged yet.

Look at https://github.com/laravel/lumen-framework/commit/23182c0fd36bb0444039ff350f1b2d8be7eb99dd

**Comment by MarcelBuian** [comment]
It seems to be fixed. Thanks!
