### ISSUE TITLE
Class 'Ramsey\Uuid\UuidFactory' not found

### ISSUE THREAD

**Issue by MarcelBuian** [laravel/lumen-framework#722]
- Lumen Version: 5.6.1

### Description:
Because we have access to `Str::uuid()` function, I am expecting to have this functionality by default (without installing any additional packages).

https://github.com/laravel/framework/blob/5.6/composer.json#L29
https://github.com/laravel/lumen-framework/blob/5.6/composer.json#L17

### Steps To Reproduce:
simple write `Str::uuid()` or `Str::orderedUuid()`

**Comment by MarcelBuian** [comment]
In addition, the package `moontoast/math` is also required for `Str::orderedUuid()`, otherwise we have `UnsatisfiedDependencyException`

**Comment by mattboban** [comment]
Is there any insight on this as I'm still seeing the issue on Lumen v5.6.3.

Thanks

**Comment by hakuno** [comment]
+1

**Comment by danilolutz** [comment]
+1

**Comment by chimit** [comment]
Apparently, I created a duplicated issue here: https://github.com/laravel/lumen-framework/issues/785

The temporary workaround is to install `ramsey/uuid` package manually:
```
composer require ramsey/uuid --dev
```

**Comment by xxRockOnxx** [comment]
+1.

**Comment by JacksonIV** [comment]
The package is a suggested dependency in Illuminate's support package. I don't think it's supposed to be a dependency within Lumen itself.

**Comment by driesvints** [comment]
Yeah like @JacksonIV says, it's a "suggested" dependency which you can optionally pull in. Just do a `composer require ramsey/uuid`.
