### ISSUE TITLE
[LUMEN-DOCS] Errors/Exceptions information  are gone.

### ISSUE THREAD

**Issue by lukylook** [laravel/lumen-framework#727]
- Lumen Version: 5.6.X
- PHP Version: none
- Database Driver & Version:none

### Description:
on[ lumen docs the errors page](https://github.com/laravel/lumen-docs/blob/5.6/errors.md) , represent only information about logs, and not any words about Errors/Exceptions like : 
[lumen version 5.5](https://github.com/laravel/lumen-docs/blob/5.5/errors.md) or
[laravel  error docs](https://github.com/laravel/docs/blob/5.6/errors.md).

**Comment by driesvints** [comment]
Send in a PR for this ^

Thanks for reporting!
