### ISSUE TITLE
lumen configuration reset after update unlike laravel

### ISSUE THREAD

**Issue by lukylook** [laravel/lumen-framework#728]
- Lumen Version: 5.6.X
- PHP Version:>=7
- Database Driver & Version: more then one mysql database

### Description:
when we change the config files on /vendor/laravel/lumen-frewmwork
after update (composer update)unlike laravel, the config is reset to the default configuration.

### Steps To Reproduce:

1. install lumen - composer create-project project --prefer-dist
2. 
 open the logs on configuration on [/project/vendor/laravel/lumen-freamwork/config/log.php ](https://github.com/laravel/lumen-framework/blob/5.6/config/logging.php#L16)

3. change to:  'default' => 'daily',
4. save.
5. update the project: composer update
6. and the the update change back to the [defualt configuration](https://github.com/laravel/lumen-framework/blob/5.6/config/logging.php#L16)

-  the same thing is with database. when we added more database configuration to the projects

**Comment by Artmann** [comment]
The `vendor/` folder is only supposed to contain third-party code and composer will overwrite its content frequently. In other words, you should never change the content of `vendor/` manually. 

Instead, you should place your config files in the `config/` directory in your project root. For example `my-project/config/logging.php`. For more information about configuring logging you can refer to <https://laravel.com/docs/5.6/logging#configuration>

**Comment by lukylook** [comment]
thanks this is new information on lumen docs before 13 days ago this inforamtion [not shown  in the docs](https://github.com/laravel/lumen-docs/blob/42f0bd8bb41aaebb256b1623c5995c7d6d9130b0/errors.md).

agian thank you.
 I close this issue.
