### ISSUE TITLE
How is logging configured in Lumen 5.6?

### ISSUE THREAD

**Issue by timrogers** [laravel/lumen-framework#736]
- Lumen Version: 5.61
- PHP Version: 7.1.10
- Database Driver & Version: N/A

How is logging configured in Lumen 5.6? Namely, I want to set up Monolog to send logs to stderr.

For context, I'm seeking to configure logging so it works correctly on Heroku, as described [here][1].
It looks like instructions along these lines worked up to Lumen 5.5, but there is no longer a `configureMonologUsing` method which one can call.

The [Lumen 5.6 docs][2] direct you to look at the [Laravel docs][3], whereas in Lumen 5.5 there was [substantive documentation about logging][4].

The Laravel docs suggest editing the `config/logging.php` file, but there is no such file in a Lumen installation.

Thanks ❤️ I realise I'm probably missing something obvious!

[1]: https://devcenter.heroku.com/articles/php-logging#lumen
[2]: https://lumen.laravel.com/docs/5.6/errors
[3]: https://laravel.com/docs/logging
[4]: https://lumen.laravel.com/docs/5.5/errors

**Comment by lukylook** [comment]
@timrogers 
all the configuration of lumen as well as logging locate on [(project_name)/vendor/laravel/lumen-framework/config](https://github.com/laravel/lumen-framework/tree/5.6/config)
NOTE:
if you change some details ,please remmember to check it  after composer update, if you need reoverride your settings again.

**Comment by timrogers** [comment]
Thanks @lukylook. I also found that adding a `config/logging.php` which looks like [the file bundled in Lumen](https://github.com/laravel/lumen-framework/tree/5.6/config) also works.

**Comment by fractalf** [comment]
@lukylook 
Did you manage to log to different channels?

`Log::channel('single')->info('message');`
..this just gives me an error
 _Call to undefined method Monolog\Logger::channel()_
