### ISSUE TITLE
Validation errors are not descriptive enough

### ISSUE THREAD

**Issue by Michael-Brooks** [laravel/lumen-framework#750]
- Lumen Version: 5.6.0
- PHP Version: 7.2.3
- Database Driver & Version: MySQL 5.7.21-0ubuntu0.16.04.1

### Description:
I have set some validation rules...

```
$this->validate( $request, [
	'username' => 'required|unique:users',
	'name'        => 'required',
	'email'        => 'required|email|unique:users',
	'password'  => 'required'
] );
```

If validation doesn't pass, then this is the message we get back... "message":"The given data was invalid."

If the user/email already exists, the error should come back saying "This username already exists" or "This email already exists". If I enter a non-valid email address then the message should say it's invalid. Unless we can create custom error responses, I think "message" should be "messages" or "responses" and return an object of validation errors.

### Steps To Reproduce:
Create some validation rules for your request and break them, you will see a "message":"The given data was invalid." response.

**Comment by Michael-Brooks** [comment]
Fixed using the Validator::make facade. However, it would still be great if $this->validate still returned more specific errors.

**Comment by raunak-gupta** [comment]
Hi,

- Lumen Version: 8.0.1
- PHP Version: 7.3

I was also facing the same issue, so I copied validation.php from vendor to my lang folder, and now I am getting Laravel like error message.

```sh
cp vendor/laravel/lumen-framework/resources/lang/en/validation.php resources/lang/en/
```

```php
public function store(\Illuminate\Http\Request $request)
{
    try
    {
        $this->validate($request, [
            'name'  => 'required',
            'email' => 'required|email|unique:users'
        ]);
    }
    catch (\Illuminate\Validation\ValidationException $e)
    {
        print_r($e->errors());
    }
}
```
