### ISSUE TITLE
SQL Server queries are generated with syntax errors

### ISSUE THREAD

**Issue by Ecksters** [laravel/lumen-framework#751]
- Lumen Version: 5.6.3
- PHP Version: 7.2.2
- Database Driver & Version: sqlsrv v5.2.0 from [msphpsql repository](https://github.com/Microsoft/msphpsql/releases)

### Description:
On Windows Server 2012, running MSSQL Server 2012 (SQL Server 12.0.5207.0), SQL commands generated with Artisan and through Eloquent appear to have syntax errors.

Raw SQL is working with my database configuration, using the DB facade I can properly access and run queries on the database without issue.

### Steps To Reproduce:
Set up a DB that works with the DB facade(can read/write, create tables, etc.).
php artisan make:migrations create_tests_table --create=tests
php artisan migrate

Gives this error:
```
In Connection.php line 664:

SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names.
Aliases defined as "" or [] are not allowed. Change the alias to a valid name. (SQL: create table "" ("id" int identity primary key not null, "migration" nvarchar(255) not null, "batch" int not null))


In Connection.php line 458:

SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
```

The query sent to the DB was:
`create table "" ("id" int identity primary key not null, "migration" nvarchar(255) not null, "batch" int not null)`

Which appears to be missing its table name.

Normal queries through Eloquent appeared to be having issues with using brackets in the table name, not 100% sure what the syntax error was there.

Again, raw queries using the DB facade are working fine, so there is no issue with the connection configuration.

I should note, that I appear to have Eloquent and Artisan commands for everything above working fine with Laravel, but my Lumen installation is having the above problem.

**Comment by AkenRoberts** [comment]
The error itself is coming from `DatabaseMigrationRepository` attempting to create the `migrations` table in the DB. For some reason, it looks like it does not have a table name defined.

The table name comes from the database configuration file. Have you by chance created your own `database.php` config file? You may have forgotten to include the `migrations` key in your config file. I can recreate the same type of error for MySQL doing exactly that:

>   SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` int unsigned not null auto_increment primary key, `migration` varchar(255) not null, `batch` int  
   not null) default character set utf8mb4 collate utf8mb4_unicode_ci)

**Comment by Ecksters** [comment]
Wow. That was it. I had created the database config file because I needed to pass some extra parameters in the options field (`PDO::ATTR_STRINGIFY_FETCHES => false, PDO::SQLSRV_ATTR_FETCHES_NUMERIC_TYPE => true`)

I'm not exactly sure why that seemed to be affecting my Eloquent queries, but everything is working now, thank you very much!

**Comment by AkenRoberts** [comment]
It's not affecting your queries directly - Lumen is attempting to create the `migrations` table in your database _before_ running your `create_tests_table` migration. So the framework is throwing an error before getting to your code.

If you would have used another Eloquent or Query Builder feature in your app with a table you created manually, it likely would have worked fine. 😄 

You're welcome! Happy coding.
