### ISSUE TITLE
artisan key:generate 

### ISSUE THREAD

**Issue by sdh100shaun** [laravel/lumen-framework#76]
Consider as a feature enhancement putting artisan key:generate in Lumen and add to composer script as with Laravel 5

**Comment by GrahamCampbell** [comment]
Already rejected. This would make a good lumen package, though we don't want to include it in the core because it adds overhead to every startup.

**Comment by sdh100shaun** [comment]
OK apologies did not see rejected

**Comment by shulard** [comment]
Is this issue still relevant about overhead ? I just installed Lumen to start a new project and I think adding that command in Lumen can be really helpful...
Maybe adding it in the Console Kernel without running it inside composer script ?

It's just a helper to help generate a valid random key...
