### ISSUE TITLE
Invalid URL with UrlGenerator in tests

### ISSUE THREAD

**Issue by SPie** [laravel/lumen-framework#768]
- Lumen Version: 5.6.3
- PHP Version: 7.1.17

### Description:
I want to use the call method feature tests and I'm using lumen's `UrlGenerator` to get the URL for named routes. The first problem is, that the method docs of the URL Facade don't match the `UrlGenerator` methods.
With lumens UrlGenerator there is no way to not use absolute paths. And if I'm using the `UrlGenerator` for tests, the `Request`'s `getHost()` method returns an empty string.

### Steps To Reproduce:
`echo Illuminate\Support\Facades\URL::route('users')`
-> `http://:/users`

**Comment by chimit** [comment]
Have a similar problem here https://github.com/laravel/lumen-framework/issues/791

**Comment by SPie** [comment]
It works now.
