### ISSUE TITLE
Uncaught ReflectionException: Class config does not exist

### ISSUE THREAD

**Issue by gentcys** [laravel/lumen-framework#772]
- Lumen Version: 5.6.3
- PHP Version: 7.1.15
- Database Driver & Version: MySQL-5.7

### Description:
I use `overload` prefix to create instance mock and add class annotation `@runTestsInSeparateProcesses` and `@preserveGlobalState disabled` to avoid `class already exists` exception. If i write an failed assertion, the real assertion result not output in console.

### Steps To Reproduce:
1. create a test class with `@runTestsInSeparateProcesses` and `@preserveGlobalState disabled` annotations
2. create a example test with failed assertion, such as: `$this->assertEquals(1, 2);`
3. run the test

### Output: 
[This is the error output](https://gist.github.com/gentcys/442ca32f42addad7a82a8b979e16f159)

**Comment by driesvints** [comment]
Heya, I can't seem to reproduce this. Please provide the full test class and any related code so we can get a better idea at what's going on.
