### ISSUE TITLE
Mailer not working - Illuminate\\Contracts\\Container\\BindingResolutionException: Target [Illuminate\\Contracts\\Mail\\Mailer] is not instantiable

### ISSUE THREAD

**Issue by saeedvaziry** [laravel/lumen-framework#774]
- Lumen Version: 5.6
- PHP Version: 7.1

I am getting this error when using mailer to send mail with queue

    Illuminate\\Contracts\\Container\\BindingResolutionException: Target [Illuminate\\Contracts\\Mail\\Mailer] is not instantiable

**Comment by moazam1** [comment]
I am also getting same error

**Comment by driesvints** [comment]
You'll need to require `illuminate/mail` manually since it's not included with Lumen by default. Here's an article on how to set everything up with Mailgun: https://medium.com/@edwardsteven/using-lumen-and-laravel-mail-with-mailgun-270415daed37
