### ISSUE TITLE
DatabaseMigrations trait doesn't revert DB inserts and deletes

### ISSUE THREAD

**Issue by SPie** [laravel/lumen-framework#775]
- Lumen Version: 5.6.1
- PHP Version: 7.1.17
- Database Driver & Version: mysql 5.7.22

### Description:
I'm using the DatabaseMigrations trait in my unit tests. The trait only uses the `rollback` command at the end and the `migrate` command at the beginning. 
The `rollback` command only reverts the last migration and so every insert into the DB or every delete won't get reverted and this causes problems in tests.

**Comment by crhg** [comment]
I also encountered the same problem. This is a problem already fixed in this [PR](https://github.com/laravel/framework/pull/20090) in the laravel framework.
This fix addresses this issue by doing `migrate:refresh` instead of `migrate` at setup time.

I hope that this fix will also be done on lumen.

**Comment by SPie** [comment]
I already opened a [PR](https://github.com/laravel/lumen-framework/pull/776) but it got closed for lack of tests and good explanation of the problem.
If I have time, I'll open it again and add the missing stuff.

**Comment by driesvints** [comment]
This should be fixed now 👍
