### ISSUE TITLE
Dummy request never created for console command causing empty rootUrl

### ISSUE THREAD

**Issue by Blizzke** [laravel/lumen-framework#782]
- Lumen Version: 5.6.3
- PHP Version: 7.2
- Database Driver & Version: N/A

### Description:

I'm trying to generate URLs from a lumen command and the rootUrl is always empty.

I found that there is a [`setRequestForConsole` called in the Kernel constructor](https://github.com/laravel/lumen-framework/blob/5.6/src/Console/Kernel.php#L56) that fakes a request and sets the base url, but this is done only if the request is not `bound`. 

Unfortunately the request is always bound, bound is: [either there is a binding, an actual instance or an alias in the container](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Container/Container.php#L153). Request is always defined as an alias, causing this line to never execute.

### Steps To Reproduce:

None needed.

**Comment by driesvints** [comment]
Heya, think this was fixed with https://github.com/laravel/lumen-framework/pull/805

Let us know if the problem persists.
