### ISSUE TITLE
UploadedFile::getClientSize is deprecated since Symfony 4.1

### ISSUE THREAD

**Issue by wyattis** [laravel/lumen-framework#784]
- Lumen Version: 5.6.3
- PHP Version: 7.1.18-1+ubuntu16.04.1+deb.sury.org+1

### Description:
This error appears when `$request->all()`, `$request->hasForm() `and `$request->file()` are called.

I think line 102 in [UploadedFile.php](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Http/UploadedFile.php) just needs changed to `$file->getSize()` to fix the bug.

#### Stack trace:
    ErrorException: "Symfony\Component\HttpFoundation\File\UploadedFile::getClientSize" is deprecated since Symfony 4.1. Use getSize() instead. in /{path_to_workspace}/vendor/symfony/http-foundation/File/UploadedFile.php:161
    #0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(16384, '"Symfony\\Compon...', '/{path_to_workspace}...', 161, Array)
    #1 /{path_to_workspace}/vendor/symfony/http-foundation/File/UploadedFile.php(161): trigger_error('"Symfony\\Compon...', 16384)
    #2 /{path_to_workspace}/vendor/illuminate/http/UploadedFile.php(102): Symfony\Component\HttpFoundation\File\UploadedFile->getClientSize()
    #3 /{path_to_workspace}/vendor/illuminate/http/Concerns/InteractsWithInput.php(332): Illuminate\Http\UploadedFile::createFromBase(Object(Symfony\Component\HttpFoundation\File\UploadedFile))
    #4 [internal function]: Illuminate\Http\Request->Illuminate\Http\Concerns\{closure}(Object(Symfony\Component\HttpFoundation\File\UploadedFile))
    #5 /{path_to_workspace}/vendor/illuminate/http/Concerns/InteractsWithInput.php(333): array_map(Object(Closure), Array)
    #6 /{path_to_workspace}/vendor/illuminate/http/Concerns/InteractsWithInput.php(314): Illuminate\Http\Request->convertUploadedFiles(Array)
    #7 /{path_to_workspace}/vendor/illuminate/http/Concerns/InteractsWithInput.php(377): Illuminate\Http\Request->allFiles()
    #8 /{path_to_workspace}/vendor/illuminate/http/Concerns/InteractsWithInput.php(344): Illuminate\Http\Request->file('formJsonFile')
    #9 /{path_to_workspace}/app/Http/Controllers/FormController.php(189): Illuminate\Http\Request->hasFile('formJsonFile')

### Steps To Reproduce:
1. Install latest version of lumen
2. Try to upload file and access it with any of these methods -> `$request->all()`, `$request->hasForm() `and `$request->file()`

**Comment by wyattis** [comment]
I was able to downgrade to v4.0 by deleting my vendor directory and updating my `composer.json` to include

    "require": {
       "symfony/http-kernel": "4.0 as 4.1",
       "symfony/http-foundation": "4.0 as 4.1",
       ....
    }

Then `composer clear-cache`and `composer install`.

**Comment by driesvints** [comment]
Heya, this should be fixed in 5.7. Thanks for reporting!
