### ISSUE TITLE
app.locale config failed

### ISSUE THREAD

**Issue by sh7ning** [laravel/lumen-framework#786]
- Lumen Version: v5.6.3
- PHP Version: 7.1.17

### Description:
code in the middleware file like:

```
public function handle(Request $request, Closure $next)
{
    $lang = trim($request->input('lang'));
    $lang = (!$lang || $lang == 'zh_CN') ? 'cn' : 'en';

    app('config')->set(['app.locale' => $lang]);

    app('translator')->setLocale($lang);

    return $next($request);
}
```

but i get `app('config')->get('app.locale')` or `config('app.locale')` with an unexpected result in action method controller file.

then i change code like:
```
public function handle(Request $request, Closure $next)
{
    $lang = trim($request->input('lang'));
    $lang = (!$lang || $lang == 'zh_CN') ? 'cn' : 'en';

    app('translator')->setLocale($lang);

    app('config')->set(['app.locale' => $lang]);

    return $next($request);
}
```
it works right.

i find below code in `vendor/laravel/lumen-framework/src/Application.php`:

```
protected function registerTranslationBindings()
    {
        $this->singleton('translator', function () {
            $this->configure('app'); //here !!!!

            $this->instance('path.lang', $this->getLanguagePath());

            $this->register('Illuminate\Translation\TranslationServiceProvider');

            return $this->make('translator');
        });
    }
```

and
 
```
/**
     * Load a configuration file into the application.
     *
     * @param  string  $name
     * @return void
     */
    public function configure($name)
    {
        if (isset($this->loadedConfigurations[$name])) {
            return;
        }

        $this->loadedConfigurations[$name] = true;

        $path = $this->getConfigurationPath($name);

        if ($path) {
            $this->make('config')->set($name, require $path);
        }
    }
```

I don't know if it is appeared because of this, if so, should it be fixed so that we code without understanding framework how to work?

**Comment by driesvints** [comment]
You'll need to configure the app first before you can set a config value. Try setting `$app->configure('app');` after creating the app in `bootstrap/app.php`.

The reason why it works for the second example is that indeed the configuration happens when you call the translator component. But the app isn't configured by default because it's not needed for every situation. You'll need to explicitly configure the config file which you want to use before you can use it.

Let me know if the problem persists.
