### ISSUE TITLE
Method "fake" of facade Storage is throwing an error: undefined method storagePath

### ISSUE THREAD

**Issue by gui-acab** [laravel/lumen-framework#794]
- Lumen Version: 5.6.4
- PHP Version: 7.2.8
- Database Driver & Version: MySQL 5.7

### Description:

I'm testing a endpoint that uploads a file and i'm using the fake method for Storage but it's getting a error.

### Steps To Reproduce:

At the begin of the test, i invoke:

`Storage::fake('uploaded');` 

And it returns the following error:

`Error: Call to undefined method Illuminate\Container\Container::storagePath()`

This is where the trace gets me:

```
vendor/laravel/lumen-framework/src/helpers.php:307
vendor/illuminate/support/Facades/Storage.php:26
```

**Comment by JacksonIV** [comment]
Everything is working fine for me. the `storagePath` method is defined in Lumen's `Application.php`, which extends the Container. Are your dependencies up to date?

**Comment by driesvints** [comment]
Heya, this is working for me as well. Let us know if this problem persists.
