### ISSUE TITLE
Infinite loop at container when registering cache and running artisan (but not front controller)

### ISSUE THREAD

**Issue by luispabon** [laravel/lumen-framework#795]
- Lumen Version: 5.6.4
- PHP Version: 7.2.7
- Database Driver & Version: n/a

### Description:
I've ran into a strange issue. I'm trying to register the `CacheServiceProvider` so that I can inject a cache store as a dependency into my code via my own service providers, and I'm getting an infinite loop when running artisan. It happens at `Container::make`. It's trying to resolve `cache` in an infinite loop.

This isn't happening however when running lumen via the front controller. Everything works fine, including the cache.

### Steps To Reproduce:

I've been able to reproduce this on a pristine lumen project. It happens exactly at the point of registering the `CacheServiceProvider`, like so:

https://github.com/luispabon/lumen-caching-problemo/blob/bfe7b59663915b11ee6af9de0db30e3ca36a58df/bootstrap/app.php#L27

```
git clone git@github.com:luispabon/lumen-caching-problemo.git
cd lumen-caching-problemo
composer -o install
php artisan
```

**Comment by JacksonIV** [comment]
The `CacheServiceProvider` is already registered within the `Lumen Framework`, i think. You can get an instance by calling `app('cache')`.

**Comment by driesvints** [comment]
Yeah, like @JacksonIV said, the `CacheServiceProvider` is already registered.
