### ISSUE TITLE
Lumen timeline after silex is dead?

### ISSUE THREAD

**Issue by n-for-all** [laravel/lumen-framework#796]
Not sure if this is the correct place to ask this, however is there any plans to kill lumen like Symfony did with silex and whether this framework will last or whether we should be considering upgrading to laravel anytime soon?

**Comment by lukylook** [comment]
I also need the confidence  to  keeping use lumen is to know in 100% that lumen  will be alive in the future not like silex

**Comment by driesvints** [comment]
Hey @n-for-all, think a better place to start a discussion around this is https://github.com/laravel/ideas

@lukylook no need to worry about that. Converting from Lumen to Laravel is pretty easy if you want and tools like laravel shift can help you: https://laravelshift.com/convert-lumen-to-laravel

Let me know if you have more questions!

**Comment by n-for-all** [comment]
Hi Dries and thanks for your reply.

i am aware of the migration process, however migration doesn't always come the easy way, especially if you have been using lumen for a while and all your app controllers and models are written for lumen.

The question is whether to leave lumen and use laravel as a start point or any other framework from now on, since laravel is super slow compared to lumen, we would like to stick with lumen and know its future.

Upgrading to laravel is not an option unfortunately, it takes more resources and much slower than lumen and we found that minimizing resources, server payments for medium and large applications is more effective than using a full framework and more resources with same value.

thanks
