### ISSUE TITLE
UnitTest call(POST) response is not attended type

### ISSUE THREAD

**Issue by Cyrille37** [laravel/lumen-framework#80]
Hi,

The doc say that TestCase::call() returns an Illuminate\Http\Response.
It's the case when calling TestCase::call('GET')
But it's not the case with TestCase::call('POST'), which return a Symfony\Component\HttpFoundation\Response.

Cheers

**Comment by Cyrille37** [comment]
Perhaps a link with isssue #55 ...

**Comment by lukasgeiter** [comment]
Are you sure? I only got a Symfony Response when the route actually didn't exist.

**Comment by Cyrille37** [comment]
You've right.
All my excuses.
Cheers
