### ISSUE TITLE
Lumen error as blank page.

### ISSUE THREAD

**Issue by dotcomdotbd** [laravel/lumen-framework#81]
I'm trying a fresh install with Lumen. Everything is fine except error page showing blank. No messages. Not even "Whoops, looks like something went wrong." .env file debug mode is true.

Please help!!

**Comment by jaoued** [comment]
@dotcomdotbd have you uncomment this line `Dotenv::load(__DIR__ . '/../');` in bootstrap/app.php ?

**Comment by dotcomdotbd** [comment]
Yes, I did. and Database credentials are taking from .env file. Everything is fine except error message. I made some PHP syntax error to test but nothing is showing. Just a blank page. Even when I'm using PHP artisan serve.

**Comment by GrahamCampbell** [comment]
Ask on the forums please. I'd recommend checking your actual php logs. Whitescreen errors are commonly caused by php fatal errors early on in the bootup process.

**Comment by Zemke** [comment]
In my case it was the `.env` file. When I removed it, it worked. Could be because I deleted a few entries that I don’t need like the database info.
