### ISSUE TITLE
Uncaught ReflectionException: Class path.storage does not exist in | Lumen

### ISSUE THREAD

**Issue by royrakesh** [laravel/lumen-framework#812]
- Lumen Version: 5.7.1
- PHP Version: 7.1.3
- Database Driver & Version:

### Description:

Core packages removed when installing new package ex: laravel-permission 
Then project stop working

![image](https://user-images.githubusercontent.com/15174104/45994236-53f2d380-c0b0-11e8-8e77-8b8011fe0168.png)

### Steps To Reproduce:

Create any Lumen project
Then run composer require spatie/laravel-permission

![image](https://user-images.githubusercontent.com/15174104/45994273-81d81800-c0b0-11e8-9fd8-04708e673f7b.png)

**Comment by driesvints** [comment]
hey @royrakesh. Seems like this is an issue for https://github.com/spatie/laravel-permission. It's best to ask there.

**Comment by driesvints** [comment]
Maybe https://github.com/laravel/lumen-framework/issues/798 is related? You might want to link to it when you open an issue on their repo.
