### ISSUE TITLE
Single Action Controller support?

### ISSUE THREAD

**Issue by dels07** [laravel/lumen-framework#819]
- Lumen Version: 5.7.x
- PHP Version: 7.2
- Database Driver & Version: MySQL 8

### Description:
Does Lumen support for Single Action Controller like Laravel does? I asked because Laravel and Lumen use different routing package.

**Comment by driesvints** [comment]
Yes it does! :)

Also: you can always ask these questions in Larachat, Discord, Twitter etc. Please keep this issue tracker free for reporting bugs or problems with Lumen.
