### ISSUE TITLE
Package publishing

### ISSUE THREAD

**Issue by esbenp** [laravel/lumen-framework#82]
Is there any plan to implement vendor publishing in Lumen? I seem to be successful in porting a few Laravel packages over to Lumen fairly easily, however the manual movement of migration and config files is fairly awkward to say the least :-)

**Comment by GrahamCampbell** [comment]
No plans. Lumen is meant to be light. If you're loading it with packages, just use Laravel.

**Comment by aeothomas** [comment]
Surely that contradicts the term "framework" and the reality seen in the lumen composer.json file? Wherein, lumen is composed of packages. I think the community loves the concept of lumen stripping things back for speed - but would like a means of pragmatically adding custom or select packages themselves at their discretion. Wouldn't you agree @GrahamCampbell, @taylorotwell? Or at least a means of being able to manage package config in the context of a lumen app - any examples that you could suggest to help the community understand your vision on this matter in lumen?

**Comment by GrahamCampbell** [comment]
No. Lumen isn't supporting packages or the like.

**Comment by aeothomas** [comment]
Maybe the word 'package' is a loaded term. What would you call this from the lumen-framework composer file? https://github.com/illuminate/session

**Comment by aeothomas** [comment]
I think I see the confusion now - with lumen you refer to these dependencies as 'components' instead of packages as composer does

**Comment by GrahamCampbell** [comment]
What I'm saying as we're not supporting laravel's opinionated package system. Bog standard composer packages are fine.

**Comment by dcelasun** [comment]
For people coming here from Google like I did, apparently there is a package that addresses this issue: https://github.com/irazasyed/larasupport

**Comment by GrahamCampbell** [comment]
> apparently there is a package that addresses this issue: 

Yeh, it's called the Laravel Framework.

**Comment by dcelasun** [comment]
No need to be snarky. In my use case, I wanted the lightweight approach (i.e lack of symfony request, eloquent etc.) of Lumen with basic support for package configs. Evidently, someone else felt the same and created that package.
