### ISSUE TITLE
wrong setting to config connections.mysql.engine

### ISSUE THREAD

**Issue by schwarzhorst** [laravel/lumen-framework#834]
- Lumen Version: 5.7.3
- PHP Version: 7.2.6 (cli)
- Database Driver & Version:

### Description:
Executing command: ./artisan migrate:fresh

leads to 

create table `migrations` (`id` int unsigned not null auto_increment primary key, `migration` varchar(255) not null, `batch` int not null) default character set utf8 collate 'utf8_unicode_ci' engine = 
(without engine set)

because of            
'engine' => env('DB_ENGINE', false),
in 
vendor/laravel/lumen-framework/config/database.php

I assume default should be "null" instead of "false" 

because of 
! is_null($engine = $connection->getConfig('engine'))
in vendor/illuminate/database/Schema/Grammars/MySqlGrammar.php

**Comment by driesvints** [comment]
Should be fixed now with https://github.com/laravel/lumen-framework/pull/833

Waiting on a new release.

**Comment by driesvints** [comment]
Just tagged a new release for this!
