### ISSUE TITLE
First time run php artisan migrate produce sql syntax error

### ISSUE THREAD

**Issue by dewaadiperdana** [laravel/lumen-framework#836]
- Lumen Version: 5.7.3
- PHP Version:7.2.4
- Database Driver & Version: MYSQL version: 5.7.21

### Description:
When first i install lumen, and try to create one migration for my database, then i run:
`php artisan migrate`

It produce sql syntax error:

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for th
  e right syntax to use near '' at line 1 (SQL: create table `migrations` (`id` int unsigned not null auto_increment primary key, `migration` varchar(255) not null,
  `batch` int not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = )`

I've tried to edit the `MySQLGrammar.php` in vendor and find method `compileCreateEngine` which produce the `'engine = '` syntax, the variable `$engine` return a boolean from `$engine = $connection->getConfig('engine')`, but it's value is `true`. And that's the problem, the final create `engine` syntax is empty and produce my problem. Is this a bug on the lumen framework??.

Finnaly i commented out the code inside `compileCreateEngine` method except `return $sql`, and it work as it is.

### Steps To Reproduce:
I run `php artisan migrate` on my console for the first time, and the problems is when lumen try to create the `migrations` table.

**Comment by dewaadiperdana** [comment]
Ok, i resolve my problem, i specifically add `DB_ENGINE` and set it to `InnoDB`. And i don't have the config folder in my lumen folder structure.

**Comment by schwarzhorst** [comment]
... it is fixed in #833.

Adi Perdana <notifications@github.com> schrieb am Sa., 27. Okt. 2018, 08:10:

**Comment by dewaadiperdana** [comment]
Yeah, thanks @schwarzhorst

**Comment by driesvints** [comment]
Just tagged a new release for this!
