### ISSUE TITLE
Error database migration after upgrading Lumen into 5.7.3

### ISSUE THREAD

**Issue by deneuv34** [laravel/lumen-framework#838]
- Lumen Version: 5.7.3
- PHP Version: 7.2.11
- Database Driver & Version: MySQL, 10.1.36-MariaDB, for Linux (x86_64) using readline 5.1

### Description:
error while fresh/new migrate database after upgrading lumen from 5.7.2 to 5.7.3

In Connection.php line 664:
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds   
  to your MariaDB server version for the right syntax to use near '' at line 1 (SQL: create table `course` (`id` int unsigned not   
  null auto_increment primary key, `id_trainer` int not null, `id_category` int not null, `title` varchar(255) not null, `descript  
  ion` varchar(255) not null, `image_cover` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) defau  
  lt character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = ) 
```
In Connection.php line 452:
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds   
  to your MariaDB server version for the right syntax to use near '' at line 1              
```

### Steps To Reproduce:
Just do migrate like `php artisan migrate` or `php artisan migrate:refresh`

**Comment by kim109** [comment]
https://github.com/laravel/lumen-framework/commit/77edb0253648a1b30b74eedb78d8f6a943751886#diff-8a025ad5d4f4fade612727b1bb0e974f

**Comment by driesvints** [comment]
This should be fixed in the next release.

**Comment by driesvints** [comment]
Just tagged a new release!
