### ISSUE TITLE
Default PHP function parameters break routes

### ISSUE THREAD

**Issue by edmarriner** [laravel/lumen-framework#84]
Hi,

There seems to be an issue with having default values for methods in a controller.

```php
public function get_orders(Request $request, $id){} // This works fine
public function get_orders(Request $request, $id = "test") {} // This does not
```

The parameter `$id` will always be set as its default value inside the function.

**Example Route:**
```php
$app->get('/orders/{id}', "App\Http\API\Orders\Orders@get_orders");
```
**Example Controller:**

```php
class Orders extends CoreApi {

    public function get_orders(Request $request, $id = "test"){
	...
    }
}
```
**Example URL:**

```php
www.myapp.com/orders/MY_VALUE
```

I can see that in Container.php on line 524 lumen is calling the function get_orders using call_user_func_array with the following array even though the function only takes two parameters ($request and $id).

```php
Array (
	[0] => Illuminate\Support\Facades\Request Object ( )
	[1]  => test
	[2] => MY_VALUE
) 
```

It appears that the default values are not being overridden with the actual values and instead are being simply appended to the end of the array.

From what I can gather this bad array is being created in the function getMethodDependencies(). It seems to be merging two separate arrays.

```php

protected function getMethodDependencies($callback, $parameters = [])
	{
		$dependencies = [];

		foreach ($this->getCallReflector($callback)->getParameters() as $key => $parameter)
		{
			$this->addDependencyForCallParameter($parameter, $parameters, $dependencies);
		}

		return array_merge($dependencies, $parameters);
	}

```

The `$dependencies` array is all the parameters from the `get_orders` function signature found by using reflection.
The `$parameters` array is the values provided by the router which are taken out of the URL.

I can see that before the array merge happens `$dependencies` has a value of:

```php
array(
	[0] => Illuminate\Support\Facades\Request Object ( )
	[1]  => test
)
```

and  `$parameters` has a value of:

```php
array(
	[0]  => MY_VALUE
)
```

From that code I don't see how the parameters provided from the URL could ever overwrite the defaulted `$id` parameters value?

The array merge just seems to append the real value of `id` to the end of the array. This means the function which takes two parameters `(Request $request, $id = "test")` is passed three parameters with the real value not being assigned to any variable in the signature of the method.

I hope this comes across clearly. 

Is this an issue with the code or is the router not designed to have functions with defaulted values parameters?

**Comment by milosgacanovic** [comment]
I have the exact same problem. Functions should have default argument value by ... well, default :)

**Comment by btpoe** [comment]
I have the same issue.

There are handful of methods in `Application.php` that call on the action with the route params passed through `array_values($routeInfo[2])`. If you simply replace those instances with `$routeInfo[2]` then the problem goes away.

So my question is, what is stripping the keys off the route params doing? I can create a pull request, but I'm assuming there was a reason that `array_values` was added in the first place.

**Comment by GrahamCampbell** [comment]
Lumen doesn't support this. If you want lots of features, Laravel is what you want.

**Comment by btpoe** [comment]
FWIW, [#57](https://github.com/laravel/lumen-framework/pull/57) fixes this issue.

**Comment by milosgacanovic** [comment]
Thanks for the info btpoe.
