### ISSUE TITLE
Registering, booting providers & kernel 

### ISSUE THREAD

**Issue by davoaust** [laravel/lumen-framework#844]
- Lumen Version: 5.7.4
- PHP Version: 7.1.3

### Description:
Lumen 5.7 has moved the provider boot to defer until the request is passed through to the router/kernel handler, however the Kernel calls the cache prior to booting providers to setup the schedule. (https://github.com/laravel/lumen-framework/blob/26e830b9e81eb4dff2b1df0f5b0755cb7a5e9cbe/src/Console/Kernel.php#L54-L61, https://github.com/laravel/lumen-framework/blob/26e830b9e81eb4dff2b1df0f5b0755cb7a5e9cbe/src/Console/Kernel.php#L97-L99)

This causes issue when registering new cache providers (eg. redis-sentinel) that wait for boot to setup, it can be worked around by booting immediately after registering those providers, but should probably be address by booting the providers before the schedule in the Kernel constructor.

### Steps To Reproduce:
1. Clean Lumen install
2. Install monospice/laravel-redis-sentinel-drivers
3. Setup redis-sentinel & register provider
4. Run any console command, resulting message is 'Driver [redis-sentinel] is not supported.'

**Comment by JacksonIV** [comment]
I've opened a PR to fix this.

**Comment by driesvints** [comment]
Done.
