### ISSUE TITLE
Nesting route groups doesn't work

### ISSUE THREAD

**Issue by thasmo** [laravel/lumen-framework#85]
My routes.php looks like this:
```php
// API v1
$app->group(['prefix' => 'v1'], function($app) {
    $app->get('/', function() {
        return 'root';
    });

    // Users
    $app->group(['prefix' => 'users'], function($app) {
        $app->get('/', function() {
            return 'users';
        });
    });
});
```
When calling `/v1` it returns `root`, but when calling `/v1/users` a `NotFoundHttpException` is thrown. This works in Laravel as far as I know. Is this intentionally not working in Lumen? FastRoute doesn't provide the route grouping itself, that's why I thought it may be a bug in Lumen.

**Comment by GrahamCampbell** [comment]
Lumen's routing is intentionally simpler so that performance is maximal. I don't think nested groups are supported.

**Comment by jasonlewis** [comment]
Nope, nested groups aren't supported.

The second route would be available at `/users` because it overwrites the group attributes set by the first group. Lumen doesn't keep track of a group stack like Laravel.

**Comment by Kristories** [comment]
So sad nested group aren't supported.. But, you can use this method :

    $app->group(['prefix' => 'v1/users'], function ($app)
    {
        $app->get('/', function () {
            // Matches The "/v1/users" URL
        });
    });

**Comment by fremail** [comment]
If somebody needs, I made a small lib to fix nested route groups problem: https://github.com/fremail/lumen-nested-route-groups

**Comment by atapatel** [comment]
+1 for this feature in future release.

**Comment by drmyersii** [comment]
I agree with @atapatel. There is no reason this can't be included, but disabled, by default. Please add this feature.

**Comment by GrahamCampbell** [comment]
There are no plans to add this feature. Please use laravel/framework if you want this.
