### ISSUE TITLE
QUEUE_DRIVER replaced by QUEUE_CONNECTION

### ISSUE THREAD

**Issue by sstativa** [laravel/lumen-framework#852]
- Lumen Version: 5.7
- PHP Version: 7.2
- Database Driver & Version: Redis

### Description:
`QUEUE_DRIVER` was replaced by `QUEUE_CONNECTION` in `config/queue.php`, however, `.env` does not reflect this and still uses `QUEUE_DRIVER`.

### Steps To Reproduce:
None

**Comment by driesvints** [comment]
https://github.com/laravel/lumen-framework/blob/5.7/config/queue.php#L16
https://github.com/laravel/lumen/blob/master/.env.example#L19

Both the .env.example from the skeleton and the config file from framework have the new `QUEUE_CONNECTION` key. Can you point to the place where it's wrong?

**Comment by driesvints** [comment]
Ah okay, I know what's wrong. When you create a project with Composer it takes the latest tag from the skeleton repo which was still at the v5.7.0 version. I've tagged a new release with v5.7.6 so if you try again in a few hours or so it should pull in the latest commits which were added. This will also contain the correct env variables now.
