### ISSUE TITLE
Psr/Log/LoggerInterface binding in a service provider causes recursion error

### ISSUE THREAD

**Issue by martroosaare** [laravel/lumen-framework#869]
- Lumen Version: 5.7.7
- PHP Version: 7.2.12
- Database Driver & Version: mysql 5.6.42

### Description:

It seems that composer.phar archive has its own vendor folder in which there is Psr logger package. When editing in PHPStorm, using Psr/Log/LoggerInterface shows up as "multiple definitions exist for class" as there is one in composer.phar and another in app vendor folder. When binding Psr/Log/LoggerInterface to a concrete implementation, like this in a service provider:

$this->app->bind(LoggerInterface::class, Logger::class);

And running the app, it crashes with the error `Error: Maximum function nesting level of '256' reached, aborting! in /srv/http/vendor/illuminate/container/Container.php on line 743`

Commenting out binding removes the error. It seems that DI container is confused about which one to bind.

### Steps To Reproduce:

Install Lumen framework and composer, verify that Psr/Log/LoggerInterface is present in both vendor and in composer.phar and bind Psr/Log/LoggerInterface to a concrete logger in a service provider.

**Comment by driesvints** [comment]
It's recommended to install composer globally instead as a `composer.phar`: https://getcomposer.org/doc/00-intro.md#globally

I also don't really get how the composer.phar could cause this error. Can you perhaps put online a small test repo which recreates this problem?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
