### ISSUE TITLE
Reportable & Renderable Exceptions are not working

### ISSUE THREAD

**Issue by andriihorpenko** [laravel/lumen-framework#873]
- Lumen Version: 5.7.7
- PHP Version: 5.3
- Database Driver & Version: MySQL 5.7

### Description:
Basically, Reportable & Renderable Exceptions are not working in Lumen. Maybe this feature was cut off the **micro**-framework, but it is not mentioned in the documentation.

### Steps To Reproduce:
Follow [documentation guide](https://laravel.com/docs/5.7/errors#renderable-exceptions) and the error is right there.
You will see only the "Whoops" message, meaning Lumen is ignoring render method in custom exception.

**Comment by driesvints** [comment]
If they don't work we could maybe look at getting it implemented.

**Comment by andrewgorpenko** [comment]
That would be so great!
