### ISSUE TITLE
Events fire not removed/replaced

### ISSUE THREAD

**Issue by HumbleBeck** [laravel/lumen-framework#887]
- Lumen Version: 5.8.0
- PHP Version: 7.2.15
- Database Driver & Version:

### Description:

fire method was removed from laravel 5.8 laravel/framework#26392, although its still in lumen
vendor/laravel/lumen-framework/src/helpers.php:202 which cause the error.

```
  Call to undefined method Illuminate\Events\Dispatcher::fire()
```

### Steps To Reproduce:

upgrade lumen from 5.7 to 5.8
the easiest way to see error: ```php artisan make:migration create_something_table```

**Comment by driesvints** [comment]
PR that fixes this was merged: https://github.com/laravel/lumen-framework/pull/888/files
