### ISSUE TITLE
PHPUnit8 Warning

### ISSUE THREAD

**Issue by kim109** [laravel/lumen-framework#889]
hello. i was upgrade PHPUnit8 

and i see this message 

`assertInternalType() is deprecated and will be removed in PHPUnit 9. Refactor your test to use assertIsArray(), assertIsBool(), assertIsFloat(), assertIsInt(), assertIsNumeric(), assertIsObject(), assertIsResource(), assertIsString(), assertIsScalar(), assertIsCallable(), or assertIsIterable() instead.`

https://github.com/laravel/lumen-framework/blob/c2c7a3b5fcd5fb5faf519f5498c0688fd652e93e/src/Testing/Concerns/MakesHttpRequests.php#L248

so I fixed code 
` PHPUnit::assertInternalType('array', $responseData);`  => `PHPUnit:: assertIsArray($responseData);`

**Comment by driesvints** [comment]
Thanks! I've replaced this one. Will be in the next release.
