### ISSUE TITLE
TrimStrings and ConvertEmptyStringsToNull are not available

### ISSUE THREAD

**Issue by chimit** [laravel/lumen-framework#896]
- Lumen Version: 5.7
- PHP Version: 7.2

### Description:
Why are `TrimStrings` and `ConvertEmptyStringsToNull` middleware not available in Lumen? There are no details in the [docs](http://lumen.laravel.com/docs/5.8/validation). Because of that some validation rules like `nullable` don't make sense.

**Comment by driesvints** [comment]
Lumen doesn't has any global middleware by default to make it as lightweight as possible. You'll need to add these manually.
