### ISSUE TITLE
Routes don't match if called with query parameters

### ISSUE THREAD

**Issue by thasmo** [laravel/lumen-framework#90]
Defining a simple route like this:
```php
$app->get('test', function() {
    return 'success';
});
```
When requesting `http://localhost/test?a=b` the route doesn't match. Is this the intended behavior?

**Comment by taylorotwell** [comment]
I can't recreate that. Works for me? :/

**Comment by thasmo** [comment]
Nevermind, seems to be a misconfiguration of local webserver. My bad.
