### ISSUE TITLE
Runing php artisan commands calls schedule function

### ISSUE THREAD

**Issue by ProteanCode** [laravel/lumen-framework#902]
- Lumen Version: 5.8.4
- PHP Version: 7.2.15
- Database Driver & Version: postgresql 9.6

### Description:
Runing php artisan commands calls schedule function, this prevents from running commands when you have empty database and you dispatch jobs that connects to it

`protected function schedule(Schedule $schedule) { dispatch(new EventJob())->onQueue('events'); }`

### Steps To Reproduce:
Create and dispatch any event that access a table in database in schedule method, then run php artisan command with empty database

**Comment by driesvints** [comment]
It's not recommended to put any actions in the schedule method. This method exists to define schedules at which some commands or actions are triggered. You can read more about this here: https://laravel.com/docs/5.8/scheduling#defining-schedules

**Comment by mbpcoder** [comment]
This Issue still exist and it doesn't make sense
I tested on latest version of Lumen
If I ran an artisan command the schedule function in kernel will run!
I  know that we can prevent running scheduled command with withoutOverlapping functionality.
