### ISSUE TITLE
127.0.0.1 is not reachable when init server with localhost

### ISSUE THREAD

**Issue by karimhossenbux** [laravel/lumen-framework#904]
- Lumen Version: 5.8.4
- PHP Version: 7.1.23

### Description:
127.0.0.1:8000 doesn’t work when I init the server with `php -S localhost:8000 -t public`. Only localhost:8000 works.

If I init it with `php -S 127.0.0.1:8000 -t public`, both 127.0.0.1:8000 and localhost:8000 works.

I found this while playing with a nuxt app making calls with axios. Though I’m not sure if issue is from Lumen making the 127.0.0.1 inaccessible. Or axios converting localhost to 127.0.0.1 which make it impossible to access the API server.

Both Lumen and nuxt is freshly install

**Comment by driesvints** [comment]
Both work for me when I try them out. I believe this might be related to something on your machine specifically. Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
