### ISSUE TITLE
php artisan schedule:run --env=testing not working

### ISSUE THREAD

**Issue by ProteanCode** [laravel/lumen-framework#907]
- Lumen Version: 5.8.4
- PHP Version: 7.2.15
- Database Driver & Version: pgsql 9.6

### Description:
I want to run a scheduler in testing env but it isn't working no matter if I run it by using

php artisan --env=testing schedule:run

or 

php artisan schedule:run --env=testing

**Comment by driesvints** [comment]
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. 

Thanks!

**Comment by ProteanCode** [comment]
> Heya, thanks for reporting.
> 
> I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets.
> 
> Thanks!

I will create separate repo later for this

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by hazeem1991** [comment]
iam having the same issue env not loading the testing env not loaded
