### ISSUE TITLE
Paginator dependent on eloquent?

### ISSUE THREAD

**Issue by Tom5om** [laravel/lumen-framework#908]
- Lumen Version: 5.8.9
- PHP Version: 7.3
- Database Driver & Version: MySQL: 5

### Description:
To use Paginator::resolveCurrentPage() or Paginator::resolveCurrentPath() it seems to be dependent on Eloquent.

### Steps To Reproduce:
Fresh install of Lumen
Dont have $app->withEloquent(); in your app.php
In any controller try running Paginator::resolveCurrentPath(), it will return '/' which is the default

We don't actually use eloquent as we have a service that just uses an external API, however we use the pagination. 

Is it possible for us to do this some other way then booting eloquent?

**Comment by driesvints** [comment]
This seems the same issue as https://github.com/laravel/framework/issues/28175 so let's continue the discussion there.
