### ISSUE TITLE
Setting a custom resource path for the application is not working

### ISSUE THREAD

**Issue by maxbublik** [laravel/lumen-framework#91]
I want my templates reside under `app/views` directory. 
Right after creating the application object I set custom resource path but the app still tries to find the views inside `resources/views` directory.

```php
$app = new Laravel\Lumen\Application;
$app->useResourcePath($app->basePath('app'));
```

**Comment by crynobone** [comment]
https://github.com/laravel/lumen-framework/blob/5.0/config/view.php#L17

**Comment by maxbublik** [comment]
Thank you!
Anyway, what is the purpose for this public method? 
It's weird since the method does not do its job and moreover it is not used anywhere in the source code.

Note that `$app->useStoragePath('/not/default/directory')` works as expected.
