### ISSUE TITLE
String escape sequences are parsed when logging Exceptions

### ISSUE THREAD

**Issue by HenkPoley** [laravel/lumen-framework#914]
- Lumen Version: v5.8.5
- Laravel Version:  5.8.4
- PHP Version: 7.2.17
- Database Driver & Version:

### Description:

In storage/logs/lumen-*.log I sometimes see:

```
#17 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Laravel\\Lumen\\Routing\\Router::middleware() at C:\\{path_to_my_project}\
outes\\web.php:33)
```

Note that the last line shouldn't be on a new line (carriage return), and that part should have read "\routes". The '\r' is interpreted as a carriage return.

In the '[stacktrace]' that follows, the string escape characters also interpreted.

### Steps To Reproduce:
Run your Lumen website on Windows, so your paths have backslashes.

This specific one, do a call to an undefined method within `routes\web.php`:

```php
$router->get('/', function () use ($router) {
    // Dummy greeting
    return env('APP_NAME');
})->middleware('foobar');
````

You probably also need these in `.env` to get full debug going 🤷‍♂️
```ini
APP_ENV=local
APP_DEBUG=true
LOG_CHANNEL=stack
```

(I don't need help with wiring the middleware to the routes the proper way, I figured that out)

**Comment by driesvints** [comment]
Unfortunately I don't have any experience with Windows. This seems to me that there's a mis-use of EOL somewhere. Seems to me the `\r` was correctly escaped as `\\r` but it wasn't handled properly?

**Comment by staudenmeir** [comment]
This is caused by `monolog`: https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/LineFormatter.php#L162

At first glance, it looks like this behavior is essential to the way the package works.

**Comment by HenkPoley** [comment]
E.g. "Please don't generate Exceptions in files or directories that start with an 'r' or 'n', or the logs will be slightly incorrect"

**Comment by driesvints** [comment]
I fear that we cannot do much ourselves here. Feel free to open up an issue on the Monolog library.

**Comment by HenkPoley** [comment]
Related Monolog issue: https://github.com/Seldaek/monolog/issues/1185
