### ISSUE TITLE
undefined method relationLoaded

### ISSUE THREAD

**Issue by AmirRezaAzizi** [laravel/lumen-framework#915]
When trying to use **whenLoaded** on resources, I got this error:

> BadMethodCallExceptionCall to undefined method Illuminate\Database\Eloquent\Builder::relationLoaded()
--

**My resource class:**
```
class Service extends JsonResource {
    public function toArray($request) {
        return [
            'user' => UserResource::collection($this->whenLoaded('user')),
            'status' => $this->status,
            'title' => $this->title,
        ];
    }
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
