### ISSUE TITLE
Lumen is micro-framework!

### ISSUE THREAD

**Issue by lukylook** [laravel/lumen-framework#924]
Hello 

Lumen is micro-framework for APIs! and
 give a good fight to other micro framework in other languages . 
 so why we need require [illuminate/view](https://github.com/laravel/lumen-framework/blob/55cd0e0858af1df36ca030dfae947741edd9fae7/composer.json#L38) ?!?

please keep lumen clean and simple targeted to  Apis only :+1: 

if you need  view package this is a BIG SIGN that you need use Laravel instead :smile:

**Comment by driesvints** [comment]
You don't need to use the view component if you don't want to.

**Comment by lukylook** [comment]
OK I agree with your answer but still can you tell what change in "philosophy of lumen" as wrote  first in  [lumen 5.2](https://lumen.laravel.com/docs/5.8/releases#5.2.0)

> 
Lumen 5.2.0 upgrades the framework to use the 5.2 family of Laravel components, as well as introduces some significant changes to Lumen's underlying philosophy and purpose.
Only Stateless APIs

Lumen 5.2 represents a shift on slimming Lumen to focus solely on serving stateless, JSON APIs. As such, sessions and views are no longer included with the framework. If you need access to these features, you should use the full Laravel framework. Upgrading your Lumen application to the full Laravel framework mainly involves copying your routes and classes over into a fresh installation of Laravel. Since Laravel and Lumen share many of the same components, your classes should not require any modification.
> 
@taylorotwell  @driesvints 
thank you!
