### ISSUE TITLE
upgrade Carbon1 to Carbon2

### ISSUE THREAD

**Issue by michealzh** [laravel/lumen-framework#927]
Create new project when using the flowing command:
```
composer create-project laravel/lumen:"5.5.*" lumen55
```

composer promot msssage is as flows:
```
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
```

So we need upgrade `illuminate/support` package, or our Laravel teams need to upgrade Carbon package to Carbon2 that is need by `illuminate/support`.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by mrahmadt** [comment]
Same message when using lumen 5.7

**Comment by michealzh** [comment]
For some reason in my project,after upgrade to lastest version of lumen-framework,we need more unit-test for new version of framework,I will try your suggestion.Thank you very much!

**Comment by alexszilagyi** [comment]
Any fix for this / workaround?

**Comment by otonielguajardo** [comment]
Any update on this?

**Comment by driesvints** [comment]
Please upgrade to the latest Lumen release and Carbon 2. Carbon 1 isn't supported anymore.

**Comment by kamhawy4** [comment]
run  ->   ./vendor/bin/upgrade-carbon

**Comment by blinkerzkc4** [comment]
kamhawy4... ur code works for me Thank u

**Comment by FilipeMeia** [comment]
Thanks for Help
