### ISSUE TITLE
Email validation allows incorrect emailaddress

### ISSUE THREAD

**Issue by GertjanBrouwer** [laravel/lumen-framework#929]
- Lumen Version: 5.8.*
- PHP Version: 7.3
- Database Driver & Version: MariaDB

### Description:
When using the Lumen validator for emailadresses it will allow an emailadress that is not valid.
The emailaddress used: `herr@ ` notice the space after the @-sign.

### Steps To Reproduce:
```
$validator = Validator::make(['email' => 'herr@ '], [
    'email' => 'required|email',
]);

dd($validator->fails()); // returns false, which is not correct
```

**Comment by SPie** [comment]
I'm not sure if you made a mistake in your 'Steps to Reproduce' because `$validator->fails()` returns true on an invalid email address would be the expected behaviour.
Otherwise, this could be your issue.

**Comment by GertjanBrouwer** [comment]
> I'm not sure if you made a mistake in your 'Steps to Reproduce' because `$validator->fails()` returns true on an invalid email address would be the expected behaviour.
> Otherwise, this could be your issue.

You're right. It returned false. Just a typo

**Comment by driesvints** [comment]
Hi there, this is a valid email address. Please see https://github.com/laravel/framework/issues/28233 and tons of other issues in the framework repo about this.
