### ISSUE TITLE
Lumen Exception Handler is not compatible with Symfony 4.4 (when it goes stable)

### ISSUE THREAD

**Issue by crynobone** [laravel/lumen-framework#935]
- Lumen Version: 5.8.x
- Laravel Version: 5.8.x
- PHP Version: any supported version
- Database Driver & Version: N/A

### Description:

Lumen 5.8 allows installation of `symfony/debug` `4.4` which introduce a deprecation and removal of `Symfony\Component\Debug\ExceptionHandler::getContent()` and this is not detected by Travis due to `prefer-stable=true`.

### Steps To Reproduce:

Remove `prefer-stable=true`, run `composer update` and execute phpunit.

**Comment by driesvints** [comment]
@crynobone can you point to the PR where that change was made? I can't find any info on it :thin

**Comment by crynobone** [comment]
https://github.com/symfony/symfony/commit/7057244890c205034a0499d518b0177ae53c338f

From symfony example, they been changing it to use `Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer` to get the body and stylesheet. Not sure if we want to follow that or replicate how Laravel does it.

**Comment by crynobone** [comment]
Here's the PR https://github.com/symfony/symfony/pull/31065 for more detail

**Comment by driesvints** [comment]
Urgh. This is unfortunate. I guess we'd better wait until 4.4 is out and then implement the changes?

**Comment by driesvints** [comment]
@crynobone I can't spot the removal of the `getStylesheet` and `getContent` methods in that commit/pr. Are you sure this is the commit?

**Comment by crynobone** [comment]
<img width="1552" alt="Screen Shot 2019-07-04 at 9 33 18 PM" src="https://user-images.githubusercontent.com/172966/60670516-73225b00-9ea3-11e9-98fc-040817a20318.png">

> Are you sure this is the commit?

Bottomline, it's not there anymore. I don't have enough effort to search each commit. Symfony plans to introduce `ErrorCatcher` component and deprecate `Debug`, and they didn't move `getContent()` to the new class.

**Comment by driesvints** [comment]
@crynobone no problem. I've found the commit and left a message on the PR. 

https://github.com/symfony/symfony/pull/31065/files#diff-facc3bcdbfaa88c930890ad4713b187dL213

**Comment by crynobone** [comment]
![Screen Shot 2019-09-10 at 6 39 42 AM](https://user-images.githubusercontent.com/172966/64571234-cded9c80-d395-11e9-83d9-3ee2dd299f6e.png)

From the response it seem that Symfony team is moving forward with the Breaking Changes.

**Comment by amosmos** [comment]
Hi, This seems to not work indeed.. 
I am getting this error: The "Symfony\Component\Debug\ExceptionHandler" class is deprecated since Symfony 4.4, use "Symfony\Component\ErrorHandler\ErrorHandler" instead.
