### ISSUE TITLE
Job's attempts back to 1 on failed() method

### ISSUE THREAD

**Issue by webkod3r** [laravel/lumen-framework#942]
- Lumen Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
When dealing with failed database jobs due to an exception or max attempts reached, the `$this->attempts()` method evaluates to `1` instead of `$tries + 1`. 

### Steps To Reproduce:
Create a `Job` and set the `public $tries = x`. After the job gets inserted into the DB change the `attempts` column value to `x` (your max attempts allowed). 
Once everything is set-up, run the `artisan` command to process the job: 
```
php artisan queue:work database --once
```
The execution will go directly to the `failed()` inside your job and `$this->attempts()` will evaluate `1`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
