### ISSUE TITLE
Migrations after a certain date will not appear to have worked when running phpunit

### ISSUE THREAD

**Issue by broadstone-connorbrady** [laravel/lumen-framework#946]
- Lumen Version: 5.7.8
- Laravel Version: #.#.#
- PHP Version: 7.2
- Database Driver & Version: MySQL, 5.7

### Description:
When we create a migration after the date 2019_06_30, the PHPUnit tests will failed and act as if the migration has never happened, yet if we change the migration file names to a date before 2019_06_30, the migration will work fine.

For example:

2019_06_29_000000 - will run the tests successfully
2019_06_30_000000 - will fail the tests, in our case it is showing that a migration hasn't run at all because it cannot find a column in the SQL (However, the migration file has been run and that column does exist)

The migration file:

```
class TempJobAddStandbyAt extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('user_job_profile_temporary_jobs', function(Blueprint $table) {
            $table->timestamp('standby_at')->nullable()->after('cancelled_at');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('user_job_profile_temporary_jobs', function(Blueprint $table) {
            $table->dropColumn('standby_at');
        });
    }
}
```

The test function:

```
    public function testCreateTemporaryJobReturns200WithToken() {	
        $company = factory(CompanyProfile::class)->states('with-user')->create();	
        $token = $this->getTokenForUser($company->user);
        $routeInfo = $this->getRouteFromControllerMethod(
            Controller::class, 'createTemporaryJob'	
        );
        $faker = app()->make(\Faker\Generator::class);
        $data = $this->jobFactory->getTempJobArray($faker);	
        $data['shifts'] = [[	
            'start_at' => date('Y-m-d H:i:s', strtotime('+ 2 hour')),	
            'end_at' => date('Y-m-d H:i:s', strtotime('+ 10 hours')),	
            'slots' => 3,	
            'hourly_rate' => $faker->numberBetween(9, 15)	
        ]];	

        $request = $this->requestFromRoute($routeInfo, $data, [
            'Authorization' => "Bearer $token"	
        ]);
        $this->assertResponseStatus(200);
    }
```

This is a strange issue. We change none of the codebase to fix this, it's the filename of the migration that seems to be the issue but we cannot figure out why

### Steps To Reproduce:

1: Create a current migration file
2: Migrate that file
3: Write a test for that 
4: Run PHPUnit, as said above, if the date is after 2019_06_30, the migration will fail

Any help or pointers with this issue would be great as it's affecting migrations for when we need to make significant changes to our database structure via migrations

**Comment by koenwoortman** [comment]
A couple of questions concerning this issue?
- Does this only occur when running PHPUnit? Or also when you rollback and again apply the migrations?
- Which column can't be found in the database?
- In which migration is the `cancelled_at` column created?

**Comment by broadstone-connorbrady** [comment]
Hi @koenwoortman Thank you for getting back to me

1: This only occurs when running PHPUnit. We can rollback and apply the migrations as many times as possible and it'll still work only if the migration file has a date that isn't 2019_06_30_000000

2: The column that is missing is the: standby_at that we are trying to add to the database in the migration

3: The cancelled_at column was create in one of the very first migrations on this project: 2017_08_29_111357_user_migrations.php

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
