### ISSUE TITLE
 Unexpected '=' in /var/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php on line 156

### ISSUE THREAD

**Issue by mathbles703** [laravel/lumen-framework#954]
I have deployed a lumen app on my ubuntu server and I recently upgrade to php 7.3 and it errors when I try to hit the base '/' endpoint with this

PHP Parse error: syntax error, unexpected '=' in /var/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php on line 156

I locally have php 7.1.23. Anyone know of any known problems? Should I downgrade? What if that is not a possibility?

**Comment by driesvints** [comment]
Please fill out the issue template when posting issues.

**Comment by Leomhl** [comment]
I have the same issue! 

FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '=' in /var/www/site/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php on line 156" while reading response header from upstream

**Comment by Leomhl** [comment]
Guys, I updated my php to 7.3 and solved my problem!

**Comment by driesvints** [comment]
Awesome
