### ISSUE TITLE
$this->expectsEvents passes every test, even on an invalid input.

### ISSUE THREAD

**Issue by TNkemdilim** [laravel/lumen-framework#956]
- Lumen Version: #.#.#
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

**Comment by TNkemdilim** [comment]
@driesvints I mistakenly created the issue before I could provide every detail. Would be great if someone could help look into this.

**Comment by driesvints** [comment]
I get: `Error: Class name must be a valid object or a string`.

Please try to upgrade to the latest version to see if the problem persists.

**Comment by TNkemdilim** [comment]
I am currently using the latest version. 

I discovered that on running `$this->expectsEvents(5)` i.e. with a numeric argument, as the first statement in a test block returns `Error: Class name must be a valid object or a string` only when `$this->expectsEvents`.

But with a string (i.e. invalid class name) as an event, it passes, and neither does it inform me that the event path provided was never fired.

Thanks.

**Comment by driesvints** [comment]
@TNkemdilim the latest version is 5.8.31

**Comment by TNkemdilim** [comment]
Just checked the [latest release](https://github.com/laravel/lumen-framework/releases), and it's 5.8.12, which was published 9 days ago.

**Comment by driesvints** [comment]
@TNkemdilim ah, I'm sorry. Mistook this with the Laravel framework repo.

Anyway, I tested this on Lumen but everythign works as expected for both examples above:

`Exception: The following events were not fired: [\App\DoesntExist]`

**Comment by TNkemdilim** [comment]
Thanks @driesvints . I'll take a close look from my end. Thanks a lot for your time.

**Comment by driesvints** [comment]
No problem. Good luck!

**Comment by TNkemdilim** [comment]
I found what was wrong :cry: .

Because I needed a fresh migrated DB for each test, I imported `Laravel\Lumen\Testing\DatabaseMigrations`.

After importing the above, I was also executing a few artisan commands (which I explicitly declared in the `setUp` and `tearDown` methods).

As a result, some declarations were overridden, which resulted in the above issue.
