### ISSUE TITLE
$this->expectsEvents passes every test, even on an invalid namespace.

### ISSUE THREAD

**Issue by TNkemdilim** [laravel/lumen-framework#957]
- Lumen Version: 5.8.12
- PHP Version: 7.3.8
- Database Driver & Version: MySQL

### Description:
I discovered that `$this->expectsEvents` passes, even when an incorrect event namespace is passed in.

### Steps To Reproduce:
Call :
- `$this->expectsEvents(5);`, or
- `$this->expectsEvents('\App\DoesntExist');`

All the above cases pass successfully, which shouldn't be so since no event with the above name is fired.

I don't know if I'm the only one experiencing this.

**Comment by driesvints** [comment]
Please see my answer here: https://github.com/laravel/lumen-framework/issues/956#issuecomment-519546715
