### ISSUE TITLE
dispatch helper function error within unit test

### ISSUE THREAD

**Issue by carbontwelve** [laravel/lumen-framework#959]
- Lumen Version: 5.8.12
- Laravel Components Version: 5.8.*
- PHP Version: 7.3.4  (built: Apr  2 2019 21:57:22)
- Database Driver & Version: n/a

### Description:
When using the `dispatch($job)` helper function ([source](https://github.com/laravel/lumen-framework/blob/5.8/src/helpers.php#L92-L95)) I get the following error: _PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Bus\Dispatcher] is not instantiable. in ..._ I have included the releveant call stack below:

```
Call Stack:
    0.0004     402984   1. {main}() C:\Users\User\PhpstormProjects\deploy\vendor\phpunit\phpunit\phpunit:0
    0.0231    2272856   2. PHPUnit\TextUI\Command::main() C:\Users\User\PhpstormProjects\deploy\vendor\phpunit\phpunit\phpunit:61
    0.0231    2272968   3. PHPUnit\TextUI\Command->run() C:\Users\User\PhpstormProjects\deploy\vendor\phpunit\phpunit\src\TextUI\Command.php:162
    0.0905    6816520   4. PHPUnit\TextUI\TestRunner->doRun() C:\Users\User\PhpstormProjects\deploy\vendor\phpunit\phpunit\src\TextUI\Command.php:206

Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Bus\Dispatcher] is not instantiable. in C:\Users\User\PhpstormProjects\deploy\vendor\illuminate\container\Container.php on line 960
```

### Steps To Reproduce:
Use the `dispatch($job)` helper function and have PHPUnit 8 run the code via unit test. This may actually fail outside of PHPUnit but I haven't tested that yet. What seems to work is replacing it with `app('Illuminate\Contracts\Bus\Dispatcher')->dispatch($job)` which I obtained from the Lumen controller helper trait [here](https://github.com/laravel/lumen-framework/blob/master/src/Routing/ProvidesConvenienceMethods.php#L182-L185).

**Comment by driesvints** [comment]
Heya, this works for me on my local lumen install with the version you mentioned above. 

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
