### ISSUE TITLE
Error tests lumen

### ISSUE THREAD

**Issue by neylsongularte** [laravel/lumen-framework#96]
Try to run this test commented 'parent::tearDown();' and uncommented

<?php

class OlaTest extends TestCase{

    public function tearDown(){
//        parent::tearDown();
    }

    public function testOla(){

        \Session::regenerate();
    }

    public function testOloa(){

        \Session::regenerate();
    }
}

**Comment by GrahamCampbell** [comment]
You probably haven't registered the facades.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/lumen-framework/blob/5.0/src/Application.php#L765

**Comment by neylsongularte** [comment]
My facades is registered

**Comment by GrahamCampbell** [comment]
Even then, we don't process support requests here, sorry. Please ask on the forums.

**Comment by neylsongularte** [comment]
-- ReflectionException: Class config does not exist

public function build($concrete, $parameters = [])
	{
		// If the concrete type is actually a Closure, we will just execute it and
		// hand back the results of the functions, which allows functions to be
		// used as resolvers for more fine-tuned resolution of these objects.
		if ($concrete instanceof Closure)
		{
			return $concrete($this, $parameters);
		}
// $concrete == 'config'
		$reflector = new ReflectionClass($concrete);

**Comment by neylsongularte** [comment]
https://github.com/laravel/framework/issues/8547

**Comment by neylsongularte** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="bootstrap/app.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false"
         syntaxCheck="false">
    <testsuites>
        <testsuite name="Application Test Suite">
            <directory>./tests/</directory>
        </testsuite>
    </testsuites>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>
    </php>
</phpunit>

**Comment by neylsongularte** [comment]
The facades are the problem.

**Comment by delatbabel** [comment]
This is definitely a bug, not a support request.  I don't believe that just telling people to disable facades is a solution.

Another example of this is that if I run two or more calls to DB::statement in the same application space I get the following exception thrown with traceback:

```
[2015-05-17 05:35:05] lumen.ERROR: exception 'ReflectionException' with message 'Class config does not exist' in .../vendor/illuminate/container/Container.php:776
Stack trace:
#0 .../vendor/illuminate/container/Container.php(776): ReflectionClass->__construct('config')
#1 .../vendor/illuminate/container/Container.php(656): Illuminate\Container\Container->build('config', Array)
#2 .../vendor/laravel/lumen-framework/src/Application.php(365): Illuminate\Container\Container->make('config', Array)
#3 .../vendor/illuminate/container/Container.php(1231): Laravel\Lumen\Application->make('config')
#4 .../vendor/illuminate/database/DatabaseManager.php(259): Illuminate\Container\Container->offsetGet('config')
#5 .../vendor/illuminate/database/DatabaseManager.php(83): Illuminate\Database\DatabaseManager->getDefaultConnection()
#6 .../vendor/illuminate/database/DatabaseManager.php(58): Illuminate\Database\DatabaseManager->parseConnectionName(NULL)
#7 .../vendor/illuminate/database/DatabaseManager.php(304): Illuminate\Database\DatabaseManager->connection()
#8 .../vendor/illuminate/support/Facades/Facade.php(210): Illuminate\Database\DatabaseManager->__call('statement', Array)
```

I can (for example) rebuild the application by calling 

```
return require __DIR__.'/../bootstrap/app.php';
```

... before each test, but in that case the effects of the previous DB statement are lost (such as setting a PostgreSQL search path).

**Comment by zot24** [comment]
+1

**Comment by neylsongularte** [comment]
Resolved:
https://github.com/laravel/lumen-framework/commit/c5d599b086f20a6c0db69ba6ff1f00999ef68654
