### ISSUE TITLE
Will be v6 lumen also as Laravel 6?

### ISSUE THREAD

**Issue by stojankukrika** [laravel/lumen-framework#962]
Hi,
Laravel is become 6.0 did Lumen follow it? I ask it because I see less commit here then in Laravel so asks is this microframework dies or something other will comes from laravel kitchen :D

**Comment by driesvints** [comment]
We'll release Lumen 6.0 in a week or two when Laravel 6.0 has gotten some adoption.

**Comment by stojankukrika** [comment]
tnx a loot for lightning response :D :D :D
