### ISSUE TITLE
queue:work in lumen memory leak

### ISSUE THREAD

**Issue by visionyimian** [laravel/lumen-framework#965]
* lumen Version v5.5.2 ~ v5.6.0
* PHP Version 7.0.11, 7.2.21
* System centos 7.2,  arch linux 5.2.13

hello guys，i found there is a possible memory leak issue in lumen, but laravel does not exist when using queue:work.

The job is very simple, just make a http request to server and get the response. 
And i find that when the request is using in stream will not leak, but using in curl, the memory will leak.

I don't know what's different between laravel and lumen 's queue:work. But it is real exist.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
