### ISSUE TITLE
Method Illuminate\Translation\Translator::trans does not exist.

### ISSUE THREAD

**Issue by s-mezencev** [laravel/lumen-framework#974]
- Lumen Version: 6.0.2
- PHP Version: 7.2.10

### Description:
Hi,
It looks like helper trans() in vendor/laravel/lumen-framework/src/helpers.php still using method "trans" (renamed to "get" in lumen 6) and any call of trans() return "Method Illuminate\Translation\Translator::trans does not exist" exception.

### Steps To Reproduce:
use somewhere dump(trans('')); for example

**Comment by s-mezencev** [comment]
Thank you for reaction.

**Comment by marcmascort** [comment]
Hi!
This issue is solved in https://github.com/laravel/lumen-framework/pull/975 but is not tagged and now to work with `6.x` version and use translations is necessary use the `6.x` branch instead of `^6.0` release.
@driesvints Please can you tag new release to solve this? Thanks!

**Comment by driesvints** [comment]
@marcmascort today is release day so it'll be tagged today.

**Comment by marcmascort** [comment]
Thank you so much!
