### ISSUE TITLE
Method default on luman 6 migrations generate an SQL error

### ISSUE THREAD

**Issue by nnadhif** [laravel/lumen-framework#977]
- Lumen Version: 6.0.2
- PHP Version: 7.3.9
- Database Driver & Version: 5.7.26

### Description:
When we made upgrade our project from Lumen version 5.8 to version 6.0, all migrations has stopped working as expected.
An SQL error was generated with the following message:
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('0'), `uuid` varchar(255) null, `provider` varchar(255) null, at line `

### Fix:
This bug is already signaled and fixed there [laravel/ideas/issues/1832](https://github.com/laravel/ideas/issues/1832).

### Suggestion:
Could you publish please a new release with the fix? Our production pipeline is blocked due to this bug.

Thank you.

**Comment by driesvints** [comment]
@nnadhif this should be fixed in v6.0.3 of Laravel (illuminate components). Can you verify that you're using v6.0.3 of the Laravel components in your composer.lock file?

**Comment by nnadhif** [comment]
in our composer.lock, illuminate components are on v6.0.2.

**Comment by nnadhif** [comment]
I just updated the dependencies, the migrations are working again.

Thank you for your help @driesvints.
