### ISSUE TITLE
route() returns invalid URL for named route with two optional parameters

### ISSUE THREAD

**Issue by zkelo** [laravel/lumen-framework#982]
- Lumen Version: 6.0.2
- Laravel Version: 6.0
- PHP Version: 7.3.10

### Description:

`route()` returns invalid URL for named route with two optional params

### Steps To Reproduce:

I have two routes. First is main route for home page (url: `/`), second is for test and have two optional params - `id` and `name`. I want to make redirect from home page to named route "test", but `route()` helper returns invalid URL

This is my code:
```php
/**
 * @var Laravel\Lumen\Routing\Router $router
 */

$router->get('/', function () {
    return route('test');
    // return redirect()->route('test');
});

$router->get('/test[/{id}[/{name}]]', [
    'as' => 'test', function ($id = 0, $name = '') {
        if ($name) {
            return "Name: $name (ID: $id)";
        }
        if ($id) {
            return "ID: $id";
        }
        return 'Need an id or name!';
    }
]);
```

This is what returns `route()` helper for route test: `https://example.com/test[/{id}[/{name}]]`

**Comment by driesvints** [comment]
Looks like Taylor closed the pr so I guess this is a no-fix for now, sorry.
