### ISSUE TITLE
NotFoundHttpException 

### ISSUE THREAD

**Issue by sahdev0** [laravel/lumen-framework#983]
- Lumen Version: 6.0.3
- PHP Version: 7.3.0
- Database Driver & Version: MySQL

### Description:
I am creating API for my application in lumen as backend. But after test with postman i am not able to get response expect getting **NotFoundHttpException**.

This is my routes
```
$router->get('/', function () use ($router) {
    return $router->app->version();
});

// public routes
$router->group(['prefix' => 'api/v1'], function () use ($router) {
    
    $router->post('register', 'UsersController@register');
    $router->post('login', ['uses'=>'AuthController@authenticate']);

});

// auth routes
$router->group(['prefix' => 'api/v1/auth', 'middleware'=>'jwt'], function () use ($router) {
    
    $router->post('create-course', 'CourseController@create_course');

});
```
# Error:

NotFoundHttpException
--
in RoutesRequests.php line 229
at Application->handleDispatcherResponse(array(0))in RoutesRequests.php line 169
at Application->Laravel\Lumen\Concerns\{closure}(object(Request))in RoutesRequests.php line 416
at Application->sendThroughPipeline(array(), object(Closure))in RoutesRequests.php line 171
at Application->dispatch(null)in RoutesRequests.php line 108
at Application->run()in index.php line 28

if i am doing anything wrong please guide, how i could resolve this.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
