### ISSUE TITLE
Validation - required_without - Not functioning correctly.

### ISSUE THREAD

**Issue by christhomas** [laravel/lumen-framework#987]
- Lumen Version: 5.8.13
- PHP Version: 7.3

### Description:

A simple validation of an array with required_without rules does not give the expected result

```
$request = new Request([
    'field_1' => 1,
    'field_2' => 2,
    'access' => true,
    'admin' => true,
]);
$data = $this->validate($request, [
    'field_1' => 'required|integer|min:1',
    'field_2' => 'required|integer|min:1',
    'access' => 'required_without:admin|boolean',
    'admin' => 'boolean',
]);
```

I expect this validation to fail because access + admin fields are both specified. However it doesn't fail and I get the valid data back, including both fields.

### Steps To Reproduce:

I have given PHP code in the description, this appears to be sufficient. I've copied it into multiple projects and they all fail in the same way.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by christhomas** [comment]
Yes, it's still a problem with the latest 6.1.0

```
$data = $this->validate($request, $rules=[
    'user_id' => 'required|integer|min:1',
    'package_group_id' => 'required|integer|min:1',
    'access' => 'required_without:admin|boolean',
    'admin' => 'required_without:access|boolean',
]);

return ['data' => $data, 'rules' => $rules];
```

It's not failing when I post both access + admin fields together

**Comment by christhomas** [comment]
I don't see the point in closing an issue immediately then having to immediately reopen it, but ok :)

**Comment by driesvints** [comment]
@christhomas we like to keep open issues to a bare minimum. This works the best for us as maintainers.
