### ISSUE TITLE
Validation - required_without - Not functioning correctly.

### ISSUE THREAD

**Issue by christhomas** [laravel/lumen-framework#988]
Lumen Version: 6.1.0
PHP Version: 7.3
Description:
A simple validation of an array with required_without rules does not give the expected result

```
$request = new Request([
    'field_1' => 1,
    'field_2' => 2,
    'access' => true,
    'admin' => true,
]);
$data = $this->validate($request, [
    'field_1' => 'required|integer|min:1',
    'field_2' => 'required|integer|min:1',
    'access' => 'required_without:admin|boolean',
    'admin' => 'boolean',
]);
```

I expect this validation to fail because access + admin fields are both specified. However it doesn't fail and I get the valid data back, including both fields.

Steps To Reproduce:
I have given PHP code in the description, this appears to be sufficient. I've copied it into multiple projects and they all fail in the same way.

**Comment by driesvints** [comment]
Hey @christhomas. The above seems correct. The `required_without` doesn't fails if the target field *is* present. It just denotes that the field should be provided when the admin field isn't present.

The following correctly passes:

```
    dd(Validator::make([
        'access' => true,
        'admin' => true,
    ], [
        'access' => 'required_without:admin|boolean',
        'admin' => 'boolean',
    ])->passes());
```

And the following will not:

```
    dd(Validator::make([], [
        'access' => 'required_without:admin|boolean',
        'admin' => 'boolean',
    ])->passes());
```

Also: validation errors don't specifically have to do anything with Lumen so you can report these on the framework repo. However, always try to use a support channel first before reporting an issue. Usually there's a lot that can be solved/caught before an issue should be opened:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
