### ISSUE TITLE
faker_locale option is not working

### ISSUE THREAD

**Issue by Lin07ux** [laravel/lumen-framework#989]
- Lumen Version: 5.8.* | 6.2.0
- PHP Version: 7.2.3
- Database Driver & Version: PostgreSQL 9.6

### Description:

The `faker_locale` option in `config/app.php` is not working when i use `factory()` method to generate data in Lumen 5.8 or 6.2.

### Steps To Reproduce:

Firt, I set the `faker_locale` option in `config/app.php`: 

```php
'faker_locale' => 'zh_CN'
```

Then, I define a factory like this:

```php
$factory->define(Subject::class, function (Faker $faker) {
    return [
        'name' => $faker->name,
    ];
});
```
I used this factory in a seeder. When I run the seeder, I got a Subject whose name attribute is in English, eg. `Alexane Hirthe`, not the Chinese name I excepted.

However, when I modify part code in the `Illuminate\Database\DatabaseServiceProvider::registerEloquentFactory()`, I get the correct result:

```php
$this->app->singleton(FakerGenerator::class, function ($app) {
    // new code
    $this->app->configure('app');

    return FakerFactory::create($app['config']->get('app.faker_locale', 'en_US'));
});
```

**Comment by driesvints** [comment]
This is currently not implemented in Lumen but you can send in a PR if you want.

Here's the Laravel implementation: https://github.com/laravel/framework/blob/ffdc4e590f1a45190984a9770051281b7ee28d8d/src/Illuminate/Database/DatabaseServiceProvider.php#L77-L79
