### ISSUE TITLE
please let route support sub-domain

### ISSUE THREAD

**Issue by wutong** [laravel/lumen-framework#99]
wish u let route group support  sub-domain
plz

**Comment by lukasgeiter** [comment]
You can run Lumen on a subdomain. However if you're looking for something like subdomain wildcards like in Laravel you should just use Laravel. Lumen is for microservices. Not big applications that use multiple subdomains.

**Comment by wutong** [comment]
@lukasgeiter 
so u mean I should run 2 project use lumen in different domain?
I don't think so. I know lumen is for micro-services.
but in my idea it should support multiple sub-domains.

**Comment by taiyaei** [comment]
I disagree with Lumen supporting subdomains, personally. Lumen is for microcomponents or quick websites. If you absolutely need subdomains, you should either split your project into two microservices (Lumen installs) or use Laravel as it's for that type of thing. Otherwise, eventually, Lumen would just become another Laravel.

I suppose this is up to debate though, but that's my 2¢

**Comment by Andreyco** [comment]
I think that possible response is already stated in docs.

"In addition, Lumen does not use Symfony's Routing component. Instead, nikic/fast-route is used for greater performance. If you need Symfony Routing features such as sub-domain routing or optional parameters, you should use the full Laravel framework."

Lumen is for micro services. I would either switch to Laravel or create another services (on subdomain in your case)

**Comment by catalinux** [comment]
In the docs page http://lumen.laravel.com/docs/routing there is a "subtitle" for "Sub-Domain Routing", unfortunately the anchor is missing.

Anyone knows what was the intention?

**Comment by assertchris** [comment]
In case someone else stumbles across this, like I did; you can use this: https://gist.github.com/assertchris/a1b8df1476467b0eb29d7d6815b39d81

**Comment by lucasjkr** [comment]
I didn't come here because of subdomains, I was googling optional route parameters for Lumen, and apparently that's also not supported? Just leaving this comment here while I keep looking.

**Comment by vaptu** [comment]
[https://ozdemirburak.com/a/subdomain-routing-in-lumen](https://ozdemirburak.com/a/subdomain-routing-in-lumen)

**Comment by macropay-solutions** [comment]
If anyone is interested, this is a solution for multiple urls https://github.com/laravel/framework/discussions/54149#discussioncomment-11802662
