### ISSUE TITLE
Dispatching the Symfony\Component\HttpFoundation\Request during Unit Tests is not working correctly when compared to using Postman

### ISSUE THREAD

**Issue by Hell4Ge** [laravel/lumen-framework#990]
- Lumen Version: Laravel Framework Lumen (6.2.0) (Laravel Components ^6.0)
- PHP Version: php:7.3-fpm-stretch (docker image)
- Database Driver & Version: none

### Description:
Dispatching the object of Request::create(...) works as expected using Postman, but not during unit tests.

### Steps To Reproduce:
Ensure the port 8080 is free or change it in docker-compose.yml file

`git clone https://github.com/Hell4Ge/lumenbug-1.git`
`cd lumenbug-1/.docker/ && docker-compose -p lumenbug-1 up -d --build`
`docker exec lumenbug-1_php_1 cp .env.example .env`
`docker exec lumenbug-1 composer update`
`docker exec lumenbug-1_php_1 vendor/bin/phpunit`

The failure of unit test is expected as it is a proof, the result is different from executing a POST request to http://localhost:8080/anotherExampleRoute using Postman.

### Use Case
I am designing the API that needs to call other routes from single route as its easier to rollback the database and storage if something fails. As long as this bug persists I am not able to test if efficiently

### Side notes
Happened also on 5.* version of Lumen, I noticed that once the unit test has been run then some of the things stays the same, like the providers seems to do not run again with every next request (ie. you cannot change user by sending different token in future requests, instead you HAVE TO use actingAs method which was not in my favor as it was quite custom login method).

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by Hell4Ge** [comment]
> Hey there,
> 
> Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> Thanks!

I don't understand, are you trying to make me believe its not a bug, but a feature? Where can I find somebody to help me "identify this as a bug" if not here

**Comment by driesvints** [comment]
@Hell4Ge on the channels I listed above
