### ISSUE TITLE
use str_random() in model

### ISSUE THREAD

**Issue by snip77** [laravel/lumen-framework#991]
- Lumen Version: 6.x
- PHP Version: 7.3.9

### Description:
when i use `str_random()` in some `Model `, i have error like this:

`Call to undefined function App\str_random()`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by snip77** [comment]
I know.
but i think `str_random()` is php function. and it should not know as `App\str_random()` and when i migrate from 5.8 to 6.x i have this error!

**Comment by crynobone** [comment]
> but i think `str_random()` is php function.

Are you sure? https://github.com/laravel/helpers/blob/master/src/helpers.php#L482-L485

**Comment by snip77** [comment]
Yes it is php function.but when i use in laravel model : laravel think its models function!

**Comment by crynobone** [comment]
https://laravel.com/docs/6.x/upgrade#helpers

![Screenshot_20191019-065536](https://user-images.githubusercontent.com/172966/67133015-892f0e00-f23d-11e9-8dd0-2da8232aa911.png)

**Comment by jimoheokoh** [comment]
`use Illuminate\Support\Str;
$var = Str::random(32);`

**Comment by freelancerwadud** [comment]
Thanks @jimoheokoh

**Comment by m01127673780** [comment]
> `$var = Str::random(32);`

**Comment by m01127673780** [comment]
Thanks <3@jimoheokoh

**Comment by tobiasthaden** [comment]
> but i think `str_random()` is php function.

https://www.php.net/manual-lookup.php?pattern=str_random
