### ISSUE TITLE
Allow us to reconfigure / reload the in-memory app config()

### ISSUE THREAD

**Issue by Hell4Ge** [laravel/lumen-framework#992]
Hello

I am in need to switch the .env file at runtime which is actually pretty easy using DotEnv, but there is a problem with config files since the `Application` `loadedConfigurations` private array cannot be cleared solely

Currently workroud hack is to make a Closure::call

```
    public static function reloadConfig() {
        $configClear = function() {
            eval('$this->loadedConfigurations = [];'); # eval is not needed, but I want to avoid confusing my IDE
        };
        $configClear->call(app());

        collect(scandir(app()->basePath('config')))->each(function ($item, $key) {
            app()->configure(basename($item, '.php'));
        });
        $configRepository = app('config');

        $items = self::accessProtected($configRepository, 'items');
        dd($items);
    }

    private static function accessProtected($obj, $prop) {
        $reflection = new ReflectionClass($obj);
        $property = $reflection->getProperty($prop);
        $property->setAccessible(true);
        return $property->getValue($obj);
    }
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
