### ISSUE TITLE
timezone issus

### ISSUE THREAD

**Issue by mowangjuanzi** [laravel/lumen-framework#997]
If I set `timezone=Asia/Shanghai` in `config/app.php`, it not work.

i found set timezone only set `TIMEZONE=Asia/Shanghai`, it work.

so I suggest update `src/Application.php`:

```php
    /**
     * Create a new Lumen application instance.
     *
     * @param  string|null  $basePath
     * @return void
     */
    public function __construct($basePath = null)
    {
        $this->basePath = $basePath;

        $this->bootstrapContainer();
        
        $this->configure("app");

        $timezone = config("app.timezone", env('APP_TIMEZONE'));
        if (! empty($timezone)) {
            date_default_timezone_set($timezone);
        }

        $this->registerErrorHandling();
        $this->bootstrapRouter();
    }
```

This gives priority to reading the configuration file

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
