### ISSUE TITLE
Eloquent model field names become uppercased if include underscores

### ISSUE THREAD

**Issue by chimit** [laravel/lumen-framework#998]
- Lumen Version: 6.2.0
- PHP Version: 7.3.12
- Database Driver & Version: MySQL 5.7 (Homestead)

### Description:
Just noticed a very strange problem. One of my models has a column with an underscore. Now when I retrieve an object from the database this column name is changed so the next letter after the underscore becomes capitalized.

### Steps To Reproduce:
```php
$user = new User(['facebook_id' => 123]);
$user->save();

$user_retrieved = User::where(['facebook_id' => 123])->first();

var_dump($user_retrieved->facebook_id); // null
var_dump($user_retrieved->facebookId); // null
var_dump($user_retrieved->facebook_Id); // string '123' (length=3)
```
It doesn't look like intentionally camelCased... Another strange thing is that I'm getting this problem only on my local machine (macOS Catalina) and not on the server (Ubuntu).

**Comment by driesvints** [comment]
Does the same thing happens for Laravel?

**Comment by chimit** [comment]
Just checked on Laravel 6.5.2. No, there is no such problem.

**Comment by driesvints** [comment]
I get the proper result for `$user_retrieved->facebook_id` and `null` for the other examples (which I'd expect.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by chimit** [comment]
Finally, I found the problem. My database column has this incorrect name `facebook_Id`. Have no idea how it may happen because in my migrations everything is correct 🤔
